import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Sugar Supreme Powernudge | 最新スロットレビュー",
  hero: {
    title: "Sugar Supreme Powernudge",
    subheading: "シュガー・シュプリーム・パワーナッジ",
    score: 4.1,
    scoreMax: 5,
    rtp: "96.09%",
    maxMultiplier: "x5,000",
    provider: "Pragmatic Play",
    releaseDate: "2023-11-02",
    volatility: "High",
    reels: "6",
    paylines: "Cluster Pays",
    minBet: "$0.2",
    maxBet: "$240",
    slotImageSrc: "/slots/sugar-supreme-powernudge.jpg",
    highlights: [
      "特徴的な「パワーナッジ機能」",
      "フリースピン中は確定発動＆マルチプライヤー蓄積",
      "クラスターペイシステム",
      "最大配当5,000倍",
    ],
    watchouts: [
      "ハイボラティリティのため、資金管理に注意が必要",
      "RTPはカジノによって変動する可能性がある",
    ],
  },
  featuredCasino: {
    name: "2up",
    logo: "/assets/casino/2up.png",
    href: "/2up",
    ctaText: "今すぐプレイ",
    ctaHref: "/2up",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30x",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/golden-panda",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/betgoat",
    },
    {
      name: "2up",
      logo: "/assets/casino/2up.png",
      href: "/reviews/2up",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "[仮想通貨](https://casinotsu.com/crypto) でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/2up",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "/reviews/cybet",
      bonus: "$500",
      freeSpins: "50",
      wagering: "35x",
      rating: 3.5,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/cybet",
    },
    {
      name: "1win",
      logo: "/images/casino/1win_375x375-2.png",
      href: "/reviews/1win",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/1win",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/miki",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/WSM_375x375-2.png",
      href: "/reviews/wsm-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "/reviews/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitz",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "/reviews/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20x",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wikibet",
    },
    {
      name: "Katsuwin",
      logo: "/images/casino/katsuwin_375x375-2.png",
      href: "/reviews/katsuwin",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/katsuwin",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/sushi-casino",
    },
    {
      name: "Betpanda",
      logo: "/images/casino/Betpanda_375x375-2.png",
      href: "/reviews/betpanda",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/betpanda",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "/reviews/parimatch",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/parimatch",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io_375x375-2.png",
      href: "/reviews/bets-io",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bets-io",
    },
    {
      name: "Duelbits",
      logo: "/images/casino/duelbits_375x375-2.png",
      href: "/reviews/duelbits",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: undefined,
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/sportsbet-io",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "/reviews/shuffle",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40x",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/shuffle",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: undefined,
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/winz-io",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "/reviews/dafabet",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/dafabet",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/lucky-block",
    },
    {
      name: "Ramenbet",
      logo: "/images/casino/ramenbet_375x375-2.png",
      href: "/reviews/ramenbet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/ramenbet",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/Flush_375x375-2.png",
      href: "/reviews/flush",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/flush",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "/reviews/queen-casino",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30x",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/queen-casino",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/roobet",
    },
    {
      name: "Stake",
      logo: "/images/casino/stake_375x375-2.png",
      href: "/reviews/stake",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/stake",
    },
    {
      name: "Wonder Casino",
      logo: "/images/casino/wonder-casino_375x375-2.png",
      href: "/reviews/wonder-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wonder-casino",
    },
    {
      name: "Yuugado",
      logo: "/images/casino/yuugado_375x375-2.png",
      href: "/reviews/yuugado",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/yuugado",
    },
    {
      name: "Konibet",
      logo: "/images/casino/konibet_375x375-2.png",
      href: "/reviews/konibet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/konibet",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-me",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "/reviews/kakeyo",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: "10x",
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/kakeyo",
    },
    {
      name: "Mystino",
      logo: "/images/casino/mystino_375x375-2.png",
      href: "/reviews/mystino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/mystino",
    },
    {
      name: "InterCasino",
      logo: "/images/casino/Inter-Casino_375x375-2.png",
      href: "/reviews/inter-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/inter-casino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "/reviews/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/empire777",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      wagering: undefined,
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/pinnacle",
    },
    {
      name: "Vera&John",
      logo: "/images/casino/VeraJohn_375x375-2.png",
      href: "/reviews/vera-john",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/vera-john",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "/reviews/live-casino-house",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-2.png",
      href: "/reviews/casino-x",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casitabi",
    },
  ],
  gameInfo: {
    intro: "Pragmatic Play 社より、お菓子をテーマにした「Sugar Supreme Powernudge（シュガー・シュプリーム・パワーナッジ）」が登場いたしました。まるでキャンディの国に迷い込んだかのような、カラフルで甘い世界観が魅力のスロットです。今回は、この「Sugar Supreme Powernudge」のゲーム概要、注目の「パワーナッジ機能」やフリースピン、さらに RTP やボラティリティなどの基本情報まで、CasinoTsu が詳しくレビューいたします。",
    basicInfo: {
      rtp: "96.09%",
      volatility: "High",
      reels: "6",
      paylines: "Cluster Pays",
      minBet: "$0.2",
      maxBet: "$240",
      provider: "Pragmatic Play",
      releaseDate: "2023-11-02",
    },
  },
  payoutTable: {
    title: "配当／ペイアウト",
    symbols: [
      {
        name: "ケーキ",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "キャンディ（複数種類）",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "キャンディ（複数種類）",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
    ],
    maxPayout: "x5,000",
    notes: [
      "クラスターペイシステムにより、5つ以上の同シンボルが隣接すると配当が成立します。",
      "ベット額が2ドルの場合の配当例がこちらです。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "パワーナッジ機能",
        description: "配当成立時にランダムで発動（基本ゲーム）。勝利シンボルを含むリールが1段下に移動し、マルチプライヤー（ビスケット）を獲得・上昇させます。配当が途切れるまで継続し、フリースピン中は確定発動＆マルチプライヤーがリセットされません。",
        icon: "/images/sugarsupreme-feature1.jpg",
      },
      {
        name: "フリースピン",
        description: "スキャッターシンボルが3つ以上出現すると獲得。フリースピン中はパワーナッジ機能が強化され、獲得したマルチプライヤーはスピンごとにリセットされずに蓄積されます。",
        icon: "/images/sugarsupreme-fs1.jpg",
      },
      {
        name: "ボーナスフィーチャー購入機能",
        description: "ベット額の100倍を支払うことで、すぐにフリースピンラウンドを開始できます。",
        icon: "/images/sugarsupreme-bonusbuy.jpg",
      },
    ],
  },
  sections: [
    {
      heading: "1. 導入・概要",
      paragraphs: [
        "Pragmatic Play 社より、お菓子をテーマにした「Sugar Supreme Powernudge（シュガー・シュプリーム・パワーナッジ）」が登場いたしました。まるでキャンディの国に迷い込んだかのような、カラフルで甘い世界観が魅力のスロットです。今回は、この「Sugar Supreme Powernudge」のゲーム概要、注目の「パワーナッジ機能」やフリースピン、さらに RTP やボラティリティなどの基本情報まで、CasinoTsu が詳しくレビューいたします。",
      ],
    },
    {
      heading: "2. ゲーム基本情報",
      table: {
        columns: ["概要", "詳細"],
        rows: [
          ["名称", "Sugar Supreme Powernudge"],
          ["プロバイダー", "[Pragmatic Play](https://casinotsu.com/providers/pragmatic-play)"],
          ["リリース日", "2023-11-02"],
          ["RTP (基本ゲーム)", "96.09% (カジノによって変動する場合があります)"],
          ["RTP (フリースピン購入時)", "96.8%"],
          ["ボラティリティ", "High (高)"],
          ["最大配当倍率", "x5,000"],
          ["最大ベット額", "$240"],
          ["最小ベット額", "$0.2"],
          ["リール数", "6"],
          ["行数", "6"],
          ["ペイライン", "Cluster Pays (クラスターペイ) ※5つ以上の同シンボルが隣接"],
          ["ヒット頻度", "約 3.69回転に1回"],
          ["フリースピン突入頻度", "約 260回転に1回"],
        ],
      },
      paragraphs: [
        " RTP（還元率）について ",
        "RTP は、プレイヤーに還元されると期待される金額の割合を示します。『Sugar Supreme Powernudge』の基本ゲームの RTP は 96.09% ですが、フリースピン購入時には 96.8% と、やや高くなります。CasinoTsu としては、RTP はあくまで理論値であり、実際のプレイ結果を保証するものではないことにご留意ください。また、カジノによって RTP が異なる場合があるため、プレイ前に CasinoTsu チェックをおすすめいたします。",
        "** ボラティリティについて **",
        "このスロットは「High（高）」ボラティリティに分類されます。これは、勝利の頻度は比較的低いものの、一度勝利すると大きな配当が得られる可能性があることを意味します。ハイリスク・ハイリターンを求めるプレイヤーや、高額賞金を狙いたいプレイヤーに適していると、CasinoTsu は判断しております。",
        "** Cluster Pays (クラスターペイ) について **",
        "『Sugar Supreme Powernudge』は、従来のペイラインではなく、「クラスターペイ」システムを採用しています。これは、5 つ以上の同じシンボルが縦または横に隣接することで配当が成立する仕組みです。シンボルがリール上に集まるほど、配当の可能性が高まります。",
      ],
    },
    {
      heading: "4. ゲーム特徴・フィーチャー",
      items: [
        {
          name: "パワーナッジ機能",
          description: "このスロットの最大の特徴は、その名の通り「パワーナッジ機能」です。配当が成立するたびにランダムで発動し、勝利に貢献したシンボルに「ビスケット」が出現します。このビスケットはマルチプライヤー（倍率）となっており、最初は x1（1倍）からスタートします。\n\n配当成立後、勝利シンボルを含むリール全体が1段下に移動します。この時、ビスケットは元の位置に固定され、新しいシンボルが上から補充されます。移動後も勝利シンボルが隣接していれば、新たな配当が成立します。\n\nさらに、配当成立があった場所に新しいビスケットが出現したり、既にビスケットがある場合はマルチプライヤーが +1 ずつ加算されていきます。複数のマルチプライヤーを獲得した場合、それらは合算されて配当に適用されます。\n\nこのパワーナッジ機能は、新たな配当が成立しなくなるまで繰り返されます。配当が途切れるたびにマルチプライヤーが上昇していくため、連続して配当を獲得できるチャンスが生まれます。\n\n**基本ゲームでのパワーナッジ**\n基本ゲーム中では、パワーナッジ機能は配当成立時にランダムで発動します。勝利シンボルがリールを下方向に1段移動し、そのシンボルに紐づいたマルチプライヤーが獲得できます。\n\n**フリースピン中のパワーナッジ**\nフリースピン中は、パワーナッジ機能がさらに強力になります。配当成立時に勝利シンボルを含むリールが1段下に移動し、そのシンボルに紐づいたマルチプライヤーが獲得できます。さらに、配当成立があった場所に新しいビスケットが出現したり、既にビスケットがある場合はマルチプライヤーが +1 ずつ加算されていきます。複数のマルチプライヤーを獲得した場合、それらは合算されて配当に適用されます。\n\n**パワーナッジ機能のポイント**\n*   配当成立時にランダムで発動（基本ゲーム）\n*   勝利シンボルを含むリールが1段下に移動\n*   マルチプライヤー（ビスケット）を獲得・上昇\n*   配当が途切れるまで継続\n*   フリースピン中は確定発動＆マルチプライヤーがリセットされない",
          icon: "/images/sugarsupreme-feature1.jpg",
        },
        {
          name: "フリースピン",
          description: "スキャッターシンボルが3つ以上出現すると、フリースピンを獲得できます。獲得できるフリースピン数は、出現したスキャッターの数によって変動します。\n\n| **スキャッター数** | **フリースピン数** |\n| --- | --- |\n| 3つ | 10スピン |\n| 4つ | 12スピン |\n| 5つ | 15スピン |\n| 6つ | 20スピン |\n\nフリースピン中にさらにスキャッターシンボルが出現した場合、追加のフリースピンを獲得できます（スキャッター3つ以上で10スピン追加）。\n\n**フリースピン中のパワーアップ**\nフリースピン中は、パワーナッジ機能が強化されます。\n*   配当成立時は必ずパワーナッジが発動します。\n*   獲得したマルチプライヤーは、スピンごとにリセットされずに蓄積されていきます。\n\nこれにより、フリースピン中はマルチプライヤーがどんどん大きくなり、高額配当を狙いやすくなります。数十倍、数百倍ものマルチプライヤーが期待できるため、非常にエキサイティングなフィーチャーです。 CasinoTsu は、このフリースピンが本機最大の魅力の一つであると評価いたします。",
          icon: "/images/sugarsupreme-fs1.jpg",
        },
        {
          name: "ボーナスフィーチャー購入機能",
          description: "ベット額の100倍を支払うことで、すぐにフリースピンラウンドを開始できる「ボーナスフィーチャー購入機能」も搭載されています。この機能は、より早くボーナスラウンドを楽しみたいプレイヤーにとって非常に便利です。ただし、CasinoTsu としては、この機能が利用できないカジノや地域もあるため、ご注意ください。\n\n**🔑フリースピン購入が勝利のカギ！？** [ボーナス購入機能がついたスロットで勝率爆上がり](https://casinotsu.com/slots/bonus-buy)！",
          icon: "/images/sugarsupreme-bonusbuy.jpg",
        },
      ],
    },
    {
      heading: "5. プロバイダー情報",
      paragraphs: [
        "**Pragmatic Play（プラグマティックプレイ）** は、世界中のオンラインカジノで人気のスロットプロバイダーです。革新的なゲーム性と高品質なグラフィック、そして魅力的なボーナス機能で多くのプレイヤーを魅了しています。 CasinoTsu も、その安定した品質とエンターテイメント性から、常に注視しているプロバイダーの一つです。",
        "*   **ライセンス:** マルタ、イギリス、ギリシャ、ルーマニア、イタリア、デンマーク、スウェーデン、南アフリカ、コロンビア、アルゼンチン（ブエノスアイレス州、メンドーサ州、ロサリオ州）、ギリシャ、ジブラルタル、カナダ（オンタリオ州）など、多数の管轄区域でライセンスを取得しています。",
        "*   **リリース日:** Sugar Supreme Powernudge は 2023年11月2日にリリースされました。",
        "*   **他の人気作品:**",
        "    *   [Sweet Bonanza](https://casinotsu.com/slots/sweet-bonanza) (スイート・ボナンザ)",
        "    *   [Sugar Rush](https://casinotsu.com/slots/sugar-rush) (シュガー・ラッシュ)",
        "    *   [Gems Bonanza](https://casinotsu.com/slots/gems-bonanza) (ジェムズ・ボナンザ)",
        "    *   [The Dog House Megaways](https://casinotsu.com/slots/the-dog-house-megaways) (ザ・ドッグ・ハウス・メガウェイズ)",
        "Pragmatic Play 社のスロットは、高ペイアウト率や「Drops & Wins」といったトーナメントイベントも充実しており、多くのプレイヤーに支持されています。",
      ],
    },
    {
      heading: "6. グラフィック・サウンド",
      table: {
        columns: ["項目", "詳細"],
        rows: [
          [
            "グラフィック",
            "キャンディーやケーキなどの甘いお菓子がモチーフ。カラフルでポップなデザインは、まるで「お菓子の国」にいるかのような気分にさせてくれます。Sugar Rushよりもさらに甘く、鮮やかなビジュアルが特徴です。",
          ],
          [
            "サウンド・音響効果",
            "ポップでキャッチーなBGMは、ゲームプレイを楽しく盛り上げます。勝利時やフィーチャー発動時には、軽快な効果音が加わり、さらにゲームをエキサイティングにします。サウンドは簡単にオフにすることも可能です。",
          ],
        ],
      },
    },
    {
      heading: "7. ペイアウト・配当表",
      paragraphs: [
        "### ・絵柄／シンボル",
        "このスロットには、以下のようなシンボルが登場します。",
        "*   **高配当シンボル:** ケーキ、キャンディ（複数種類）",
        "*   **低配当シンボル:** キャンディ（複数種類）",
        "ベット額が2ドルの場合の配当例がこちらです。 CasinoTsu では、このシンボルの組み合わせが勝利の鍵を握ると考えております。",
      ],
      table: {
        title: "・配当／ペイアウト",
        columns: ["シンボル", "5つ", "4つ", "3つ"],
        rows: [
          ["ケーキ", "", "", ""],
          ["キャンディ（複数種類）", "", "", ""],
          ["キャンディ（複数種類）", "", "", ""],
        ],
      },
      notes: [
        "『Sugar Supreme Powernudge』は、6リール x 6行のグリッドレイアウトを採用しており、合計36個のシンボルが表示されます。",
        "**クラスターペイ** システムにより、同じシンボルが5つ以上隣接（縦または横）すると配当を獲得できます。",
        "**最大配当倍率**",
        "このスロットの最大配当倍率は **x5,000** です。 CasinoTsu は、このポテンシャルに期待を寄せています。",
      ],
    },
    {
      heading: "8. モバイル対応",
      paragraphs: [
        "『Sugar Supreme Powernudge』は、HTML5技術に基づいて開発されているため、デスクトップPC、タブレット、スマートフォンなど、あらゆるデバイスで快適にプレイできます。特別なアプリのダウンロードは不要で、お使いのデバイスのブラウザから直接アクセスして楽しむことができます。",
        "パワーナッジ機能のダイナミックな動きや、カラフルなグラフィックは、小さな画面でもしっかりと再現されており、モバイルデバイスでのプレイ体験も損なわれません。どこにいても、この甘くて刺激的なスロットを存分に楽しむことができます。 CasinoTsu は、このモバイル対応の柔軟性を高く評価しています。",
        "**📱カジノアプリで気軽にオンカジで遊ぼう♪** [カジノアプリ](https://casinotsu.com/casino-apps) 対応のメリットやカジノを分かりやすく解説！",
      ],
    },
    {
      heading: "9. 戦略・攻略法",
      paragraphs: [
        "### ・ハイボラティリティを理解する",
        "『Sugar Supreme Powernudge』はハイボラティリティのスロットです。これは、勝利の頻度は低いものの、一度大きな配当が出るとその金額も大きくなる可能性があることを意味します。そのため、CasinoTsu としては、[資金管理](https://casinotsu.com/tools/bankroll-app) には十分注意が必要です。",
        "*   **長期的視点:** 短期間での結果に一喜一憂せず、長期的な視点でプレイすることが大切です。",
        "*   **ベット額調整:** 資金が尽きないように、ベット額は慎重に設定しましょう。ハイボラティリティのスロットでは、最低ベット額から始めるのがおすすめです。",
        "### ・パワーナッジ機能の活用",
        "パワーナッジ機能は、このスロットの醍醐味です。配当成立後にリールが移動し、マルチプライヤーが蓄積される仕組みを理解することで、より戦略的にプレイできます。 CasinoTsu では、この機能を最大限に活用することが勝利への近道だと考えております。",
        "*   **フリースピンでの爆発力:** フリースピン中はパワーナッジが確定発動し、マルチプライヤーもリセットされないため、最も大きな配当が期待できるタイミングです。",
        "*   **ボーナス購入の検討:** もし、より早くフリースピンの興奮を味わいたいのであれば、ボーナス購入機能（ベット額の100倍）の利用も検討できます。ただし、必ずしも有利になるとは限らないため、リスクも理解した上で利用しましょう。",
        "### ・フリースピン獲得の頻度",
        "フリースピンは、平均して約260回転に1回程度出現するとされています。この頻度を念頭に置いて、資金配分やプレイ時間を調整すると良いでしょう。 CasinoTsu は、この統計データを参考に、計画的なプレイをおすすめします。",
      ],
    },
    {
      heading: "10. 類似ゲーム",
      table: {
        columns: ["スロット名", "詳細"],
        rows: [
          [
            "[**スイート・ボナンザ**](https://casinotsu.com/slots/sweet-bonanza)",
            "Pragmatic Play 社の中でも特に人気の高い、スイーツがテーマのスロットです。ペイシンボルがリール上にランダムに配置され、配当が成立する「ペイ・エニウェア」システムと、マルチプライヤー機能が特徴です。",
          ],
          [
            "[**シュガーラッシュ**](https://casinotsu.com/slots/sugar-rush)",
            "『Sugar Supreme Powernudge』の姉妹機とも言えるスロットです。こちらもキャンディやスイーツがテーマで、マルチプライヤー機能が搭載されています。",
          ],
          [
            "[シュガーラッシュ1000](https://casinotsu.com/slots/sugar-rush-1000)",
            "『シュガーラッシュ』シリーズの最新作で、最大配当25,000倍、最大マルチプライヤー1,024倍と、さらにハイボラティリティにパワーアップしています。",
          ],
        ],
      },
      paragraphs: [
        "これらのスロットも、『Sugar Supreme Powernudge』と同様に、カラフルなビジュアルとエキサイティングなフィーチャーを楽しめるため、ぜひ CasinoTsu チェックしてみてください。特に、クラスターペイの仕組みや、マルチプライヤーによる連鎖的な配当獲得に魅力を感じる方にはおすすめです。",
        "**🌟リリースされたてホヤホヤの新作スロットで遊んじゃおう！** [日本で遊べる新着ベストスロット](https://casinotsu.com/slots/new-slots) はこれ★",
      ],
    },
    {
      heading: "11. まとめ",
      paragraphs: [
        "『Sugar Supreme Powernudge』は、可愛らしいお菓子の世界観とは裏腹に、刺激的な「パワーナッジ機能」とハイボラティリティが融合した、非常にエキサイティングなスロットです。CasinoTsu は、そのゲーム性の高さを高く評価しています。",
        "配当成立ごとにマルチプライヤーが上昇し、リールが移動していく様子は、プレイヤーを飽きさせません。特にフリースピン中は、パワーナッジ機能が確定発動し、マルチプライヤーも蓄積されていくため、一撃で高額配当を獲得できる可能性を秘めています。",
        "最大配当5,000倍というポテンシャルも魅力的で、見た目の可愛らしさだけでなく、ゲーム性でもプレイヤーを熱くさせてくれるでしょう。甘いものが苦手な方でも、その中毒性の高いゲームプレイにハマってしまうかもしれません。",
        "**こんなプレイヤーにおすすめ:**",
        "*   ハイボラティリティの [スロット](https://casinotsu.com/slots) で高額賞金を狙いたい方",
        "*   Pragmatic Play 社のスロットが好きな方",
        "*   可愛らしいだけでなく、刺激的なゲーム性を求める方",
        "*   クラスターペイシステムに興味がある方",
        "ぜひこの甘くて危険なスロット、「Sugar Supreme Powernudge」で、CasinoTsu と共に大きな勝利を掴み取ってください！正確さが第一。興奮はその次。",
      ],
    },
  ],
  faq: [
    {
      q: "シュガー・シュプリーム・パワーナッジのRTPは？",
      a: "基本ゲームの RTP は 96.09% ですが、カジノやフリースピン購入時など、状況によって変動する場合があります。プレイするカジノの情報を CasinoTsu チェックすることをおすすめいたします。",
    },
    {
      q: "パワーナッジ機能とは？",
      a: "配当が成立した際にランダムで発動する機能です。勝利シンボルを含むリールが1段下に移動し、そのシンボルに紐づいたマルチプライヤー（ビスケット）を獲得できます。配当が途切れるまで継続し、フリースピン中はさらに強力になります。",
    },
    {
      q: "このスロットのボラティリティは？",
      a: "「High（高）」ボラティリティです。勝利頻度は低いですが、一回の勝利で得られる配当は大きくなる傾向があります。",
    },
    {
      q: "フリースピンはどうやったら獲得できますか？",
      a: "リール上にスキャッターシンボルが3つ以上出現すると、フリースピンを獲得できます。出現数に応じて、10～20回のフリースピンが付与されます。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Sugar supreme powernudge", href: "https://casinotsu.com/slots/sugar-supreme-powernudge" },
  ],
  tableOfContents: [
    { label: "1. 導入・概要", href: "#" },
    { label: "2. ゲーム基本情報", href: "#" },
    { label: "4. ゲーム特徴・フィーチャー", href: "#" },
    { label: "5. プロバイダー情報", href: "#" },
    { label: "6. グラフィック・サウンド", href: "#" },
    { label: "7. ペイアウト・配当表", href: "#" },
    { label: "8. モバイル対応", href: "#" },
    { label: "9. 戦略・攻略法", href: "#" },
    { label: "10. 類似ゲーム", href: "#" },
    { label: "11. まとめ", href: "#" },
    { label: "12. よくある質問", href: "#" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "/2up",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/sugar-supreme-powernudge" />;
}
