import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "トワイライト・プリンセス | Pragmatic Playの人気スロットを徹底解説！",
  hero: {
    title: "トワイライト・プリンセス",
    subheading: "美少女プリンセスと薄明かりの冒険へ！最大7,500倍を狙うクラスターペイ型スロット",
    description: "Pragmatic Play社からリリースされた「トワイライト・プリンセス」は、魅力的なプリンセスが主人公のクラスターウィンスロットです。隣接するシンボルが5つ以上集まることで配当が発生するクラスターペイシステムを採用し、最大7,500倍もの高配当が期待できます。美しいグラフィックとサウンド、そしてエキサイティングなフリースピン機能で、プレイヤーを幻想的な世界へと誘います。",
    score: 4.1,
    scoreMax: 5,
    rtp: "96.08%",
    maxMultiplier: "x7,500",
    provider: "Pragmatic Play",
    releaseDate: "2023-10-02",
    volatility: "High",
    reels: "5x5",
    paylines: "クラスターペイ",
    minBet: "$0.2",
    maxBet: "$240",
    slotImageSrc: "/slots/twilight-princess.jpg",
    highlights: [
      "クラスターペイシステムで最大7,500倍の配当を狙える",
      "マルチプライヤーワイルドで配当を最大10倍に！",
      "フリースピン中はマルチプライヤーワイルドがホールドされ、一撃必殺のチャンス！",
      "美しいプリンセスと幻想的な薄明かりの世界観",
      "Pragmatic Playの人気スロット「スターライト・プリンセス」の姉妹機",
    ],
    watchouts: [
      "ハイボラティリティのため、資金管理が重要",
      "ボーナス購入機能は一部地域で利用不可",
    ],
  },
  featuredCasino: {
    name: "2up Casino",
    logo: "/images/casinos/2up_logo.png",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwilight-princess",
    ctaText: "今すぐプレイ！",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwilight-princess",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
  },
  casinos: [
    {
      name: "ゴールデンパンダ",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30x",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "ベットゴート",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "2アップカジノ",
      logo: "/images/casinos/2up_375x375.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$500",
      freeSpins: "50",
      wagering: "35x",
      rating: 3.5,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "1win",
      logo: "/images/casinos/1win_375x375.png",
      href: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "WSM Casino",
      logo: "/images/casinos/WSM_375x375.png",
      href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20x",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Betpanda",
      logo: "/images/casinos/Betpanda_375x375.png",
      href: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Bets.io",
      logo: "/images/casinos/bets-io_375x375.png",
      href: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: undefined,
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40x",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: undefined,
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Ramenbet",
      logo: "/images/casinos/ramenbet_375x375-1.png",
      href: "https://go.casinotsu.com/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Flush Casino",
      logo: "/images/casinos/Flush_375x375-1.png",
      href: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30x",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$0",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Stake",
      logo: "/images/casinos/stake_375x375-1.png",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Yuugado",
      logo: "/images/casinos/yuugado_375x375-1.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Konibet",
      logo: "/images/casinos/konibet_375x375.png",
      href: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: "10x",
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$0",
      freeSpins: "-",
      wagering: undefined,
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Casino-X",
      logo: "/images/casinos/casino-x_375x375-1.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Ftwilight-princess",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Ftwilight-princess",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Ftwilight-princess",
    },
  ],
  gameInfo: {
    intro: "トワイライト・プリンセスは、Pragmatic Play社が開発した、美少女プリンセスがテーマのクラスターペイ型スロットゲームです。5x5のリールグリッドで展開され、隣接する同じシンボルが5つ以上集まることで配当が発生します。",
    basicInfo: {
      rtp: "96.08%",
      volatility: "High",
      reels: "5",
      paylines: "クラスターペイシステムのため、ペイラインはありません。",
      minBet: "$0.2",
      maxBet: "$240",
      provider: "Pragmatic Play",
      releaseDate: "2023-10-02",
    },
  },
  payoutTable: {
    title: "トワイライト・プリンセス 配当表 (ベット額2ドル時)",
    symbols: [
      {
        name: "クラウン",
        payout5: "10.00",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "ベル",
        payout5: "7.50",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "フラワー",
        payout5: "5.00",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "バッジ",
        payout5: "4.00",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "ハート",
        payout5: "3.00",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "ヘキサゴン",
        payout5: "2.50",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "ダイヤモンド",
        payout5: "2.00",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "トライアングル",
        payout5: "1.50",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "サークル",
        payout5: "1.00",
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "マルチプライヤーワイルド",
        description: "2倍から10倍のマルチプライヤーを付与。ワイルドとしても機能。",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: true,
      },
    ],
    maxPayout: "7,500x",
    notes: [
      "上記はベット額2ドル時の配当例です。",
      "クラスターペイシステムのため、隣接する同じシンボルが5つ以上揃うと配当が発生します。",
      "複数のマルチプライヤーワイルドが出現した場合、その値は加算されます。",
    ],
  },
  features: {
    title: "トワイライト・プリンセスのゲーム特徴・フィーチャー",
    items: [
      {
        name: "クラスターペイ",
        description: "伝統的なペイラインに代わり、隣接する同じシンボルが5つ以上集まることで配当が発生するシステム。",
        icon: undefined,
      },
      {
        name: "マルチプライヤーワイルド",
        description: "ピンク色の魔法のスティックシンボル。配当成立を助けるだけでなく、2倍から10倍までのランダムなマルチプライヤーを付与します。",
        icon: undefined,
      },
      {
        name: "プリンセスフィーチャー",
        description: "通常ゲーム中、プリンセスがランダムに発動。追加のスティッキーワイルドやマルチプライヤーワイルドが出現し、配当クラスターの形成やマルチプライヤーの増加をサポートします。",
        icon: undefined,
      },
      {
        name: "フリースピン",
        description: "金色のオーブシンボルが3つ以上出現すると10回のフリースピンが開始。フリースピン中はマルチプライヤーワイルドがホールドされ、配当クラスターが形成しやすくなります。",
        icon: undefined,
      },
      {
        name: "追加スピン（リスピン）",
        description: "フリースピン中に、左上にスキャッターが付いたシンボルが2つ以上同時に出現すると、追加スピンを獲得できます。",
        icon: undefined,
      },
      {
        name: "ボーナスフィーチャー購入機能",
        description: "ベット額の100倍を支払うことで、直接フリースピンラウンドを購入できる機能（一部地域を除く）。",
        icon: undefined,
      },
    ],
  },
  sections: [
    {
      heading: "トワイライト・プリンセスをプレイできるカジノ",
      paragraphs: [
        "CasinoTsu が厳選した、トワイライト・プリンセスをプレイできるおすすめのオンラインカジノをご紹介いたします。各カジノでは、魅力的なボーナスや特典をご用意しておりますので、ぜひチェックしてみてください。",
      ],
    },
    {
      heading: "ゲーム基本情報",
      paragraphs: [
        "トワイライト・プリンセスは、Pragmatic Play 社が開発した、美少女プリンセスがテーマのクラスターペイ型スロットゲームです。5x5のリールグリッドで展開され、隣接する同じシンボルが5つ以上集まることで配当が発生します。",
      ],
      table: {
        title: "ゲーム基本情報",
        columns: ["概要", "詳細"],
        rows: [
          ["名称", "Twilight Princess"],
          ["リリース日", "2023-10-02"],
          ["プロバイダー", "Pragmatic Play"],
          ["最大配当倍率", "x7,500"],
          ["ボラティリティ", "High"],
          ["最大ベット額", "$240 (Pragmatic Play公式では$100ですが、一部カジノでは$240まで対応)"],
          ["ゲーム形式", "クラスターペイ (隣接する同じシンボルが5つ以上で配当成立)"],
          ["UK特定制限", "英国プレイヤーの場合、25歳未満は1スピンあたり£2、25歳以上は£5までのベット制限あり。"],
        ],
      },
    },
    {
      heading: "トワイライト・プリンセスのゲーム特徴・フィーチャー",
      paragraphs: [
        "このスロットの魅力は、なんといってもそのユニークなゲーム機能にあります。CasinoTsu が注目のポイントを解説いたします。",
      ],
      bullets: [
        "**シンボルとクラスターペイ**: 伝統的なペイラインに代わり、クラスターペイ システムが採用されています。これにより、シンボルが密集するほど大きな配当が期待できます。",
        "**マルチプライヤーワイルド**: ピンク色の魔法のスティックシンボルは、マルチプライヤーワイルドです。配当成立を助けるだけでなく、2倍から10倍までのランダムなマルチプライヤーを付与します。",
        "**プリンセスフィーチャー**: 通常ゲーム中、プリンセスがランダムに「プリンセスフィーチャー」を発動させることがあります。これにより、追加のスティッキーワイルド（固定されて消えないワイルド）やマルチプライヤーワイルドが出現し、配当クラスターの形成やマルチプライヤーの増加をサポートします。",
        "**フリースピン**: 金色のオーブ シンボルが3つ以上出現すると、10回のフリースピンが開始されます。",
        "**フリースピン中の特徴**: 背景が夕暮れ時のような「トワイライト」仕様に変化し、雰囲気が一層盛り上がります。プリンセスが、マルチプライヤーワイルドを出現させることがあります。一度出現したマルチプライヤーワイルドは、フリースピンが終了するまでリール上にホールド（固定）されます。",
        "**追加スピン（リスピン）**: フリースピン中に、左上にスキャッターが付いたシンボルが2つ以上同時に出現すると、追加スピンを獲得できます。",
        "**ボーナスフィーチャー購入機能**: ベット額の100倍を支払うことで、直接フリースピンラウンドを購入できる機能も搭載されています。",
      ],
    },
    {
      heading: "トワイライト・プリンセスのプロバイダー情報",
      table: {
        title: "プロバイダー情報",
        columns: ["概要", "詳細"],
        rows: [
          ["プロバイダー名", "Pragmatic Play"],
          ["ライセンス", "マルタ、英国、ジブラルタル、ルーマニア、ギリシャ、イタリア、デンマーク、スウェーデン、南アフリカ、コロンビア、カナダ（オンタリオ州）、バハマ、ベルギー、チェコ、ポルトガル、スペイン、フィリピン、スイス、ナイジェリア、オランダ、インドなど、多数の国際ライセンスを取得。"],
          ["リリース日", "2023年10月2日"],
          ["他の人気作品", "『スイートボナンザ』、『ギャラクティック・トレジャーズ』、『ビッグ・バス・ボナンザ』、『ゲート・オブ・オリンポス』、『スターライト・プリンセス』（トワイライト・プリンセスの姉妹機にあたる人気スロット）など。"],
          ["特徴", "高品質なグラフィックとサウンド、多様なテーマ、革新的なゲームメカニクス、そして高いペイアウト率で知られる大手プロバイダー。特に「ドロップ＆ウィン」キャンペーンは多くのプレイヤーに支持されています。HTML5技術を駆使し、モバイルデバイスでのプレイも快適に提供しています。"],
        ],
      },
    },
    {
      heading: "トワイライト・プリンセスのグラフィックとサウンド",
      paragraphs: [
        "トワイライト・プリンセスは、その名の通り「薄明かり」のロマンチックな雰囲気をテーマにしており、美しいビジュアルとサウンドがプレイヤーを魅了します。CasinoTsu は、ゲームの没入感を高めるこれらの要素も重視しております。",
      ],
      bullets: [
        "**グラフィック**: テーマは美少女戦士、ファンタジー、ロマンチック。背景には夕暮れ時の空のような幻想的な青空が広がり、ゲーム進行で深みのあるトーンに変化。プリンセスは洗練された優雅なデザイン。",
        "**シンボル**: 各シンボルも美しくデザインされており、読みやすく、すっきりとしたデザインが採用されています。",
        "**サウンド・音響効果**: アップテンポで爽やかなサウンドトラックが流れ、ゲームプレイを盛り上げます。スピン音や配当成立時の効果音も、ゲームの雰囲気を損なうことなく、プレイヤーの体験を向上させるように工夫されています。",
      ],
    },
    {
      heading: "トワイライト・プリンセスのペイアウト・配当表",
      paragraphs: [
        "トワイライト・プリンセスでは、クラスターペイシステムにより、ペイラインの概念はありません。配当は、隣接する同じシンボルが5つ以上揃うことで成立します。CasinoTsu は、皆様に正確な情報を提供するため、配当表を精査しました。",
      ],
    },
    {
      heading: "トワイライト・プリンセスのモバイル対応",
      paragraphs: [
        "トワイライト・プリンセスは、現代のプレイヤーのニーズに合わせて、HTML5技術を使用して開発されています。CasinoTsu は、いつでもどこでも快適にプレイできる環境を提供することが重要だと考えております。",
      ],
      bullets: [
        "**対応デバイス**: スマートフォン（iOS、Android）、タブレット、デスクトップPC",
        "**プレイ方法**: ウェブブラウザを通じて直接プレイ可能。カジノアプリのインストールは不要な場合が多いですが、カジノアプリがあるカジノもあります。",
        "**操作性**: タッチスクリーンに最適化されており、直感的な操作で快適にプレイできます。画面サイズに合わせてインターフェースが自動調整されます。",
        "**ゲーム体験**: モバイルでも、PC版と変わらない高品質なグラフィック、スムーズなアニメーション、そしてサウンドを楽しむことができます。",
      ],
    },
    {
      heading: "トワイライト・プリンセス｜戦略・攻略法",
      paragraphs: [
        "トワイライト・プリンセスはハイボラティリティのスロットであるため、一撃の大きな配当を狙うことが醍醐味ですが、CasinoTsu としては、資金管理と戦略的なプレイを推奨しております。",
      ],
      bullets: [
        "**ベット戦略**: 資金管理の徹底、ベット額の調整（低ベットから開始、徐々に増減）、UKプレイヤーの年齢制限の確認。",
        "**フィーチャー活用法**: マルチプライヤーワイルドの重要性、プリンセスフィーチャーを待つ、フリースピン中の追加スピン獲得の活用。",
        "**注意点**: ゲーム中の誤作動時の対応、RTPの変動確認。",
      ],
    },
    {
      heading: "トワイライト・プリンセス類似ゲーム",
      table: {
        title: "類似ゲーム",
        columns: ["スロット名", "詳細"],
        rows: [
          ["スターライト・プリンセス", "トワイライト・プリンセスと同じ世界観ですが、グラフィックは日本アニメ風。Tumble（連鎖）機能やマルチプライヤーなど、共通する魅力があります。"],
          ["ムーンプリンセス・トリニティ", "Play'n GO社の人気シリーズ。可愛らしいプリンセスたちが登場し、トリニティ機能によるワイルドやマルチプライヤーが特徴です。"],
          ["ゲート・オブ・オリンポス", "Pragmatic Play社からリリースされており、こちらもクラスターペイシステムと強力なマルチプライヤーが魅力です。テーマはギリシャ神話。"],
        ],
      },
    },
    {
      heading: "トワイライト・プリンセス｜まとめ",
      paragraphs: [
        "トワイライト・プリンセスは、Pragmatic Play 社が贈る、美少女プリンセスがテーマのクラスターペイ型スロットです。スターライト・プリンセスの姉妹機として登場し、より洗練された洋風のキャラクターデザインと、ロマンチックなトワイライト（薄明）の雰囲気が特徴です。",
        "ハイボラティリティ ながらも、RTP 96.08% を誇り、最大7,500倍 の高配当を狙えるポテンシャルを秘めています。CasinoTsu は、正確さが第一。興奮はその次。の精神で、このゲームの魅力を皆様にお届けします。",
      ],
      bullets: [
        "ユニークなクラスターペイシステム",
        "マルチプライヤーワイルドで配当を最大10倍に！",
        "フリースピン中はマルチプライヤーワイルドがホールドされ、一撃の破壊力が高い",
        "プリンセスフィーチャーで通常ゲームも楽しめる",
        "ボーナス購入機能で即フリースピン（一部地域を除く）",
        "美しいグラフィックとサウンド",
        "モバイル対応でいつでもどこでもプレイ可能",
      ],
      prosCons: {
        pros: [
          "クラスターペイシステムで最大7,500倍の配当を狙える",
          "マルチプライヤーワイルドで配当を最大10倍に！",
          "フリースピン中はマルチプライヤーワイルドがホールドされ、一撃必殺のチャンス！",
          "美しいプリンセスと幻想的な薄明かりの世界観",
          "Pragmatic Playの人気スロット「スターライト・プリンセス」の姉妹機",
        ],
        cons: [
          "ハイボラティリティのため、資金管理が重要",
          "フィーチャーの種類は比較的少なめ",
          "ボーナス購入機能は一部地域で利用不可",
        ],
      },
    },
  ],
  similarGames: [
    {
      name: "スターライト・プリンセス",
      href: "/slots/starlight-princess",
      provider: "Pragmatic Play",
      description: "トワイライト・プリンセスと同じ世界観ですが、グラフィックは日本アニメ風。Tumble（連鎖）機能やマルチプライヤーなど、共通する魅力があります。",
    },
    {
      name: "ムーンプリンセス・トリニティ",
      href: "/slots/moon-princess-trinity",
      provider: "Play'n GO",
      description: "Play'n GO社の人気シリーズ。可愛らしいプリンセスたちが登場し、トリニティ機能によるワイルドやマルチプライヤーが特徴です。",
    },
    {
      name: "ゲート・オブ・オリンポス",
      href: "/slots/gates-of-olympus",
      provider: "Pragmatic Play",
      description: "Pragmatic Play社からリリースされており、こちらもクラスターペイシステムと強力なマルチプライヤーが魅力です。テーマはギリシャ神話。",
    },
  ],
  prosCons: {
    pros: [
      "クラスターペイシステムで最大7,500倍の配当を狙える",
      "マルチプライヤーワイルドで配当を最大10倍に！",
      "フリースピン中はマルチプライヤーワイルドがホールドされ、一撃必殺のチャンス！",
      "美しいプリンセスと幻想的な薄明かりの世界観",
      "Pragmatic Playの人気スロット「スターライト・プリンセス」の姉妹機",
    ],
    cons: [
      "ハイボラティリティのため、資金管理が重要",
      "フィーチャーの種類は比較的少なめ",
      "ボーナス購入機能は一部地域で利用不可",
    ],
  },
  faq: [
    {
      q: "トワイライト・プリンセスの最大配当倍率は？",
      a: "最大でベット額の 7,500倍 です。コイン単位では最大12,000コインとなります。",
    },
    {
      q: "トワイライト・プリンセスのRTP（還元率）は？",
      a: "公式のRTPは 96.08% です。ただし、オンラインカジノによっては、この数値が若干異なる場合があります。CasinoTsu は、プレイする前にゲーム画面で正確なRTPを確認することをおすすめします。",
    },
    {
      q: "このスロットはどのように配当が発生しますか？",
      a: "クラスターペイシステム を採用しており、同じシンボルが5つ以上、水平または垂直に隣接して配置されることで配当が発生します。ペイラインはありません。",
    },
    {
      q: "マルチプライヤーワイルドはどのように機能しますか？",
      a: "マルチプライヤーワイルドには2倍から10倍までのランダムなマルチプライヤーが付与され、配当成立時に適用されます。複数のマルチプライヤーワイルドが出現した場合は、その値が合算されます。",
    },
    {
      q: "フリースピンはどのように獲得できますか？",
      a: "金色のオーブシンボルが3つ以上出現すると、10回のフリースピンを獲得できます。また、フリースピン中に特定のスキャッターシンボルが出現すると、追加スピンを獲得することも可能です。",
    },
  ],
  breadcrumbs: [
    { label: "ホーム", href: "https://casinotsu.com/" },
    { label: "スロット", href: "https://casinotsu.com/slots" },
    { label: "トワイライト・プリンセス", href: "https://casinotsu.com/slots/twilight-princess" },
  ],
  tableOfContents: [
    { label: "トワイライト・プリンセス｜評価・基本情報", href: "#hero" },
    { label: "トワイライト・プリンセスをプレイできるカジノ", href: "#casinos" },
    { label: "ゲーム基本情報", href: "#game-info" },
    { label: "トワイライト・プリンセスのゲーム特徴・フィーチャー", href: "#features" },
    { label: "トワイライト・プリンセスのプロバイダー情報", href: "#provider-info" },
    { label: "トワイライト・プリンセスのグラフィックとサウンド", href: "#graphics-sound" },
    { label: "トワイライト・プリンセスのペイアウト・配当表", href: "#payout-table" },
    { label: "トワイライト・プリンセスのモバイル対応", href: "#mobile" },
    { label: "トワイライト・プリンセス｜戦略・攻略法", href: "#strategy" },
    { label: "トワイライト・プリンセス類似ゲーム", href: "#similar-games" },
    { label: "トワイライト・プリンセス｜まとめ", href: "#summary" },
    { label: "よくある質問 (FAQ)", href: "#faq" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwilight-princess",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/twilight-princess" />;
}
