import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Twin Spin Deluxe / ツインスピン・デラックス - スロットレビュー",
  hero: {
    title: "Twin Spin Deluxe",
    subheading: "ツインスピン・デラックス",
    description: "ネットエント社の大人気クラッシックスロット、「Twin Spin」のデラックス版が登場しました！Twin Spin Deluxeの特長や、初期版との違いについて、CasinoTsuが徹底レビューいたします。👀✨",
    score: 4.4,
    scoreMax: 5,
    rtp: "96.61%",
    maxMultiplier: "x100,000",
    provider: "NetEnt",
    releaseDate: "2017年9月7日",
    volatility: "Medium",
    reels: "6",
    paylines: "なし。9つ以上同じシンボルがクラスター状に隣接して揃えば配当成立（クラスターペイ方式）",
    minBet: "$0.10",
    maxBet: "$100.00",
    slotImageSrc: "/slots/twin-spin-deluxe.png",
    highlights: [
      "ツインリール機能の拡大（最大6リール連動）",
      "クラスターペイ方式による新しい勝利の可能性",
      "クラシックなデザインと現代的なゲームプレイの融合",
      "Mediumボラティリティによるバランスの取れたゲーム性",
    ],
    watchouts: [
      "独立したフリースピンやボーナスラウンドは搭載されていない",
      "クラスターペイ方式のため、勝利の頻度や配当額はシンボルのクラスターサイズに依存する",
      "最大配当倍率100,000倍は理論上の数値であり、達成は非常に稀",
    ],
  },
  featuredCasino: {
    name: "2up",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/reviews/2up",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
  },
  casinos: [
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://casinotsu.com/reviews/betgoat",
      bonus: "独自コインも利用可能！",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "2up",
      logo: "/assets/casino/2up.png",
      href: "https://casinotsu.com/reviews/2up",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "https://casinotsu.com/reviews/cybet",
      bonus: "$500",
      freeSpins: "50",
      wagering: undefined,
      rating: 3.5,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      href: "https://casinotsu.com/reviews/1win",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://casinotsu.com/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: undefined,
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "$1,000",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://casinotsu.com/reviews/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: undefined,
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: undefined,
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.png",
      href: "https://casinotsu.com/reviews/parimatch",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io.png",
      href: "https://casinotsu.com/reviews/bets-io",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "https://casinotsu.com/reviews/duelbits",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "$2,020",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: undefined,
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "$500",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: undefined,
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Flush Casino",
      logo: "/assets/casino/flush-casino.png",
      href: "https://casinotsu.com/reviews/flush",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: undefined,
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Casino Sky",
      logo: "/assets/casino/casino-sky.png",
      href: "https://casinotsu.com/reviews/casino-sky",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: undefined,
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Fresh Casino",
      logo: "/assets/casino/fresh-casino.png",
      href: "https://casinotsu.com/reviews/fresh-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: undefined,
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Empire.io",
      logo: "/assets/casino/empireio.jpg",
      href: "https://casinotsu.com/reviews/empire-io",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "賭け条件ナシのキャシュバック＆VIP特典がスゴイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire-io:empire-io?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      href: "https://casinotsu.com/reviews/stake",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casino/wonder-casino.png",
      href: "https://casinotsu.com/reviews/wonder-casino",
      bonus: "$917",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: undefined,
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ohmyspins:ohmyspins?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      href: "https://casinotsu.com/reviews/yuugado",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Tedbet",
      logo: "/assets/casino/tedbet.png",
      href: "https://casinotsu.com/reviews/tedbet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/tedbet:tedbet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "BetRebels",
      logo: "/assets/casino/betrebels.png",
      href: "https://casinotsu.com/reviews/betrebels",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betrebels:betrebels?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Conquestador",
      logo: "/assets/casino/conquestador.png",
      href: "https://casinotsu.com/reviews/conquestador",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/conquestador:conquestador?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.jpg",
      href: "https://casinotsu.com/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cloudbet:cloudbet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Lilibet",
      logo: "/assets/casino/lilibet.png",
      href: "https://casinotsu.com/reviews/lilibet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lilibet:lilibet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Livecasino.io",
      logo: "/images/casino/livecasinoio.jpg",
      href: "https://casinotsu.com/reviews/livecasino-io",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/livecasino-io:livecasino-io?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.jpg",
      href: "https://casinotsu.com/reviews/lucky-bull",
      bonus: "$917",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-bull:lucky-bull?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.jpg",
      href: "https://casinotsu.com/reviews/gamdom",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/gamdom:gamdom?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Energy Casino",
      logo: "/assets/casino/energy-casino.png",
      href: "https://casinotsu.com/reviews/energy-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/energy-casino:energy-casino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Konibet",
      logo: "/assets/casino/konibet.png",
      href: "https://casinotsu.com/reviews/konibet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Vulkan Vegas",
      logo: "/assets/casino/vulkan-vegas.jpg",
      href: "https://casinotsu.com/reviews/vulkanvegas",
      bonus: "¥100,000",
      freeSpins: "125",
      wagering: undefined,
      rating: 4,
      tagline: "アメコミの世界観に入り込んじゃえ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vulkan-vegas:vulkanvegas?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: undefined,
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://casinotsu.com/reviews/kakeyo",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: undefined,
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Bons.com",
      logo: "/images/casino/bons.png",
      href: "https://casinotsu.com/reviews/bons",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "マインクラフトチックでも中身はモダン",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bons-com:bons?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      href: "https://casinotsu.com/reviews/mystino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "InterCasino",
      logo: "/images/casino/inter-casino.png",
      href: "https://casinotsu.com/reviews/inter-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "$1,600",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "BitStarz",
      logo: "/assets/casino/bitstarz.png",
      href: "https://casinotsu.com/reviews/bitstarz",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitstarz:bitstarz?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino.png",
      href: "https://casinotsu.com/reviews/joycasino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/joy-casino:joycasino?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casino/casino-secret.png",
      href: "https://casinotsu.com/reviews/casino-secret",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-secret:casino-secret?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Vera&John",
      logo: "/images/casino/VeraJohn.png",
      href: "https://casinotsu.com/reviews/vera-john",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      href: "https://casinotsu.com/reviews/casino-x",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: undefined,
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "William Hill",
      logo: "/assets/casino/william-hill.jpg",
      href: "https://casinotsu.com/reviews/william-hill",
      bonus: "$300",
      freeSpins: undefined,
      wagering: undefined,
      rating: 3.5,
      tagline: "世界三大の超老舗ブックメーカー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/william-hill-casino:william-hill?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
    {
      name: "Eldoah Casino",
      logo: "/images/casino/eldoah.png",
      href: "https://casinotsu.com/reviews/eldoah",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
    },
  ],
  gameInfo: {
    intro: "Twin Spin Deluxeは、クラシックなカジノの雰囲気を持ちつつ、現代的なゲームプレイを融合させたスロットです。CasinoTsuでは、正確さが第一。興奮はその次。の精神で、基本情報をまとめました。",
    basicInfo: {
      rtp: "96.61%",
      volatility: "Medium",
      reels: "6",
      paylines: "なし。9つ以上同じシンボルがクラスター状に隣接して揃えば配当成立（クラスターペイ方式）",
      minBet: "$0.10",
      maxBet: "$100.00",
      provider: "NetEnt",
      releaseDate: "2017年9月7日",
    },
  },
  payoutTable: {
    title: "シンボルのデザイン",
    symbols: [
      {
        name: "Wild",
        description: "通常のシンボルの代わりとなり、配当成立を助けます。ただし、ワイルドシンボル自体は配当を生み出しません。",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
      },
      {
        name: "ダイヤモンド",
        description: "最高配当シンボル",
        payout5: "x10,000",
        payout4: "x5,000",
        payout3: "x2,000",
      },
      {
        name: "7",
        description: "高配当シンボル",
        payout5: "x5,000",
        payout4: "x2,500",
        payout3: "x1,000",
      },
      {
        name: "ベル",
        description: "高配当シンボル",
        payout5: "x3,000",
        payout4: "x1,500",
        payout3: "x600",
      },
      {
        name: "バー",
        description: "高配当シンボル",
        payout5: "x2,000",
        payout4: "x1,000",
        payout3: "x400",
      },
      {
        name: "チェリー",
        description: "高配当シンボル",
        payout5: "x1,000",
        payout4: "x500",
        payout3: "x200",
      },
      {
        name: "A",
        description: "低配当シンボル",
        payout5: "x500",
        payout4: "x250",
        payout3: "x100",
      },
      {
        name: "K",
        description: "低配当シンボル",
        payout5: "x400",
        payout4: "x200",
        payout3: "x80",
      },
      {
        name: "Q",
        description: "低配当シンボル",
        payout5: "x300",
        payout4: "x150",
        payout3: "x60",
      },
      {
        name: "J",
        description: "低配当シンボル",
        payout5: "x200",
        payout4: "x100",
        payout3: "x50",
      },
      {
        name: "10",
        description: "低配当シンボル",
        payout5: "x100",
        payout4: "x50",
        payout3: "x20",
      },
    ],
    maxPayout: "100,000x",
    notes: [
      "クラスターペイ方式：同じシンボルが9つ以上隣接して揃うと配当成立。",
      "ワイルドシンボルは、配当成立を補助しますが、それ自体で配当を生み出すことはありません。",
    ],
  },
  features: {
    title: "ゲームの魅力",
    items: [
      {
        name: "ツインリールフィーチャー",
        description: "各スピンの開始時に、隣接する2つのリールが常に同じシンボルで表示されるように連動します。この連動は最大6つのリール全てに拡大する可能性があり、高配当獲得のチャンスを大きく広げます。",
        icon: "/images/icon-twin-reel.png",
      },
      {
        name: "クラスターペイ",
        description: "従来のペイライン方式ではなく、同じシンボルが9つ以上隣接して集まる（クラスターを形成する）と配当が発生する仕組みです。これにより、画面上のどこにシンボルが集まっても配当が得られ、よりダイナミックなゲーム展開が楽しめます。",
        icon: "/images/icon-cluster-pay.png",
      },
      {
        name: "クラシックなデザイン",
        description: "鮮やかなネオンカラーと、夜の街を思わせるようなクールでスタイリッシュなデザインが特徴です。オリジナルのTwin Spinの雰囲気を引き継ぎつつ、洗練されたビジュアルを提供します。",
        icon: "/images/icon-design.png",
      },
      {
        name: "サウンドデザイン",
        description: "軽快でリズミカルなBGMは、ゲームプレイをさらに盛り上げます。夜のドライブを連想させるような、クールなサウンドが特徴です。",
        icon: "/images/icon-sound.png",
      },
    ],
  },
  sections: [
    {
      heading: "Twin Spin Deluxe の基本情報",
      paragraphs: [
        "Twin Spin Deluxeは、クラシックなカジノの雰囲気を持ちつつ、現代的なゲームプレイを融合させたスロットです。CasinoTsuでは、正確さが第一。興奮はその次。の精神で、基本情報をまとめました。",
      ],
      table: {
        title: "基本情報",
        columns: ["項目", "内容"],
        rows: [
          ["コインバリュー ($)", "$0.01 – $1.00"],
          ["リール数", "6"],
          ["行数", "5"],
          ["ペイライン", "なし。9つ以上同じシンボルがクラスター状に隣接して揃えば配当成立（クラスターペイ方式）"],
          ["ベット幅", "$0.10 – $100.00"],
          ["RTP（還元率）", "96.61%"],
          ["ボラティリティ", "Medium"],
          ["最大ベット額", "$100"],
          ["最大配当倍率", "x100,000"],
          ["リリース日", "2017年9月7日"],
          ["プロバイダー", "NetEnt"],
        ],
      },
      bullets: [
        "**RTP (Return To Player):** この数値は、理論上、プレイヤーに還元される金額の割合を示します。96.61%は、平均よりもやや高めで、プレイヤーにとって有利な設定と言えます。",
        "**ボラティリティ:** Medium（中程度）のボラティリティは、頻繁に勝利が発生するわけではありませんが、一度の勝利で比較的大きな配当が期待できるバランスの取れたゲーム性を示唆しています。",
        "**クラスターペイ:** 従来のペイライン方式とは異なり、隣接する同じシンボルが9つ以上集まることで配当が発生します。これにより、画面上にシンボルが密集するほど大きな勝利のチャンスが生まれます。",
      ],
    },
    {
      heading: "ツインスピン・デラックスの概要",
      paragraphs: [
        "Twin Spin Deluxeは、NetEnt（ネットエント）社が開発した、オンラインスロットの中でも特に人気が高い「Twin Spin」のデラックスバージョンです。オリジナルのTwin Spinは、「Win All Ways」という原則に基づき、243通りのペイラインでプレイできましたが、Twin Spin Deluxeではゲームの構造がさらに進化しています。",
        "オリジナルのTwin Spinが5リール・3行の構成だったのに対し、Twin Spin Deluxeは **6リール・5行** という、より広大なグリッドを採用しています。これにより、シンボルの配置や勝利の可能性が大きく変化しました。また、ペイアウトシステムも従来のペイライン方式から、 **クラスターペイ方式** へと変更されています。",
        "Twin Spin Deluxeは、その名の通り「デラックス」な体験を提供します。クラシックなスロットの持つシンプルさと、最新のスロットが持つ興奮を兼ね備えています。特に、スピンごとにリールが連動する「ツインリール機能」は健在で、これが複数リールに拡大すると、高配当獲得のチャンスが大きく広がります。",
      ],
      bullets: [
        "NetEntの人気スロット「Twin Spin」のデラックス版",
        "6リール・5行のグリッド構成",
        "クラスターペイ方式を採用",
        "ツインリール機能が健在で、最大6リールまで拡大可能",
      ],
    },
    {
      heading: "ツインスピン・デラックスのゲームメカニクス",
      paragraphs: [
        "Twin Spin Deluxeの最大の特徴であり、ゲーム名の由来でもあるのがこの「ツインリールフィーチャー」です。CasinoTsuは、この機能の綿密な分析を重視しています。",
        "各スピンの開始時に、隣接する2つのリールが常に同じシンボルで表示されるように連動します。これにより、同じシンボルが揃いやすくなります。",
        "この連動機能は、単なる2つのリールに留まりません。スピンが進むにつれて、この「双子リール」は3つ、4つ、さらにはデラックス版では **最大6つ全てのリールにまで拡大** する可能性があります！リールが6つ全て同じシンボルで埋まった場合、クラスターペイ方式との相乗効果で、まさに爆発的な配当が期待できます。この機能が、ゲームに常に高い期待感と興奮をもたらします。 🤩",
        "オリジナルのTwin Spinが「Win All Ways」方式を採用していたのに対し、Twin Spin Deluxeではペイアウトの仕組みが大きく変更されています。CasinoTsuは、この新しいメカニクスの理解を深めることが重要だと考えています。",
        "従来のペイライン（左から右へ絵柄が揃う）に依存するのではなく、**クラスターペイ方式** を採用しています。これは、**同じシンボルが9つ以上、リール上のどこかに隣接して集まる（クラスターを形成する）と配当が発生する** という仕組みです。",
        "この方式により、ペイアウトのチャンスが大幅に増加します。リール1から始まる必要はなく、画面の中央でシンボルが集まっても配当が得られます。縦横、あるいは斜めに隣接するシンボルが対象となるため、より直感的で、かつ勝利の機会が多いと感じられるでしょう。この新しいペイアウトシステムが、ゲームに新鮮な魅力を加えています。",
      ],
      bullets: [
        "**ツインリールフィーチャー:** 隣接するリールが同じシンボルで連動し、最大6リールまで拡大する可能性があります。",
        "**クラスターペイ:** 9つ以上の隣接するシンボルでクラスターを形成すると配当が発生します。",
      ],
    },
    {
      heading: "ツインスピン・デラックスのシンボルとペイアウト",
      paragraphs: [
        "Twin Spin Deluxeのシンボルは、オリジナルのTwin Spinから引き継がれており、クラシックなカジノゲームの雰囲気を色濃く反映しています。鮮やかなネオンカラーで描かれたシンボルは、夜の街を思わせるような、クールでスタイリッシュな印象を与えます。",
        "Twin Spin Deluxeはクラスターペイ方式を採用しているため、ペイアウトはリール上のシンボルの数と配置によって決まります。例えば、ダイヤモンドのシンボルが9つ以上隣接して画面上に現れた場合、配当が発生します。シンボルの数が増えれば増えるほど、配当も大きくなります。CasinoTsuは、このシンボルクラスターの形成を注意深く観察します。",
      ],
      bullets: [
        "**高配当シンボル:** ダイヤモンド、7、ベル、バー、チェリー",
        "**低配当シンボル:** トランプカード（A, K, Q, J, 10）",
        "**Wildシンボル:** 通常シンボルの代わりとなり、配当成立を助けます。",
        "クラスターペイ方式のため、ペイアウトはシンボルの数と隣接度によって決まります。",
      ],
    },
    {
      heading: "Twin Spin Deluxe をプレイできるカジノ",
      paragraphs: [
        "Twin Spin Deluxeをプレイできるオンラインカジノは多数ありますが、CasinoTsuでは特におすすめのサイトをいくつかご紹介いたします。これらのカジノでは、新規登録者向けの[ボーナス](https://casinotsu.com/bonuses)や、頻繁に開催されるプロモーションなど、お得な特典が用意されている場合があります。",
      ],
      table: {
        title: "おすすめカジノ",
        columns: ["カジノ名", "CasinoTsu 推薦ボーナス", "特徴"],
        rows: [
          ["エルドアカジノ", "ジャパカジ登録で入金不要ボーナス2,000円", "少額から高額まで対応、VIPプログラムが充実"],
          ["インターカジノ", "ジャパカジ登録で登録フリースピン150回分（30ドル相当）", "老舗カジノ、豊富なボーナスとプロモーション"],
          ["ジョイカジノ", "ジャパカジ登録で4,500円の入金不要ボーナス", "多彩なゲーム、魅力的なウェルカムオファー"],
          ["ボンズカジノ", "ジャパカジ限定5,000円入金不要ボーナス＋フリースピン20回分", "幅広いゲーム、お得なボーナス多数"],
        ],
      },
      notes: [
        "ボーナス内容や賭け条件は変更される可能性があります。最新の情報は各カジノの公式サイトでご確認ください。CasinoTsuでは、常に正確な情報提供を心がけております。",
      ],
    },
    {
      heading: "Twin Spin Deluxe をプレイしてみた感想",
      paragraphs: [
        "オリジナルのTwin Spinは、そのシンプルさとユニークなツインリール機能で、多くのプレイヤーに愛されてきました。Twin Spin Deluxeも、そのDNAを受け継ぎつつ、より現代的なゲーム体験を提供してくれます。CasinoTsuのプレイヤー視点での感想をお伝えします。",
        "まず、やはり「ツインリール機能」の存在が大きいです。スピンが始まるたびに、2つのリールが同じ絵柄で揃う保証があるため、常に「何か起こるかも」という期待感があります。この連動リールが3つ、4つと拡大していく瞬間は、まさに興奮の連続！特に、6リール全てが連動した際には、クラスターペイと相まって、驚くような配当が生まれることもあります。",
        "クラスターペイ方式は、従来のペイライン方式とは異なる勝利の感覚を与えてくれます。画面上のどこにシンボルが集まっても配当になるため、よりダイナミックなゲーム展開を楽しめます。正直、最初は慣れが必要かもしれませんが、一度コツを掴めば、この新しいペイアウトシステムの面白さにハマるはずです。",
        "Twin Spin Deluxeのデザインは、オリジナルの持つ「ネオ・クラシック」な雰囲気を踏襲しています。鮮やかなネオンカラーと、都会的で洗練されたサウンドデザインは、プレイヤーを飽きさせません。夜の街を疾走するような、軽快でリズミカルなBGMは、ゲームプレイをさらに盛り上げてくれます。 CasinoTsuは、この美学を高く評価しています。",
        "オリジナルのTwin Spinは、そのシンプルさゆえに、経験豊富なプレイヤーにとってはやや物足りなさを感じることもあったかもしれません。しかし、Twin Spin Deluxeは、6リール構成とクラスターペイという新しい要素を取り入れることで、より戦略的で、かつ大きな勝利の可能性を秘めたゲームへと進化しました。",
        "オリジナルの持つ「シンプルさ」と、デラックス版の持つ「進化」のバランスが絶妙です。どちらのバージョンが好きかは、プレイヤーの好みによるところが大きいでしょう。しかし、Twin Spin Deluxeは、オリジナルのファンはもちろん、新しいタイプのスロットを求めているプレイヤーにも、ぜひ試してみてほしい作品です。 CasinoTsuのチェック、ダブルチェック、そしてCasinoTsuチェックを経て、この評価に至りました。",
        "Twin Spin Deluxeは、まず海外のオンラインカジノで先行リリースされ、その斬新なゲーム性で注目を集めました。その後、日本のオンラインカジノサイトにも登場し、多くのプレイヤーに楽しまれています。NetEnt社の人気機種であることも、その信頼性と魅力を裏付けています。",
      ],
      bullets: [
        "ツインリール機能による常に期待感のあるゲームプレイ。",
        "クラスターペイ方式によるダイナミックな勝利の可能性。",
        "クラシックとモダンが融合した洗練されたデザインとサウンド。",
        "オリジナルのファンにも、新しいゲーム性を求めるプレイヤーにもおすすめ。",
      ],
    },
    {
      heading: "ツインスピン・デラックスを勝手に評価！",
      paragraphs: [
        "CasinoTsuでは、プレイヤーの皆様がより深くゲームを理解できるよう、独自の評価基準で採点を行っております。正確さが第一。興奮はその次。をモットーに、各項目をチェックしました。",
      ],
      table: {
        title: "評価",
        columns: ["項目", "評価"],
        rows: [
          ["グラフィック", "★★★★☆　ー　ネオンが輝く都会的なデザインは、シンプルながらも魅力的。夜の街の雰囲気をうまく表現しています。"],
          ["サウンド", "★★★★★　ー　軽快でリズミカルなBGMは、プレイ中の気分をさらに高めてくれます。夜のドライブを連想させるような、クールなサウンドです。"],
          ["面白さ", "★★★★★　ー　ツインリール機能の拡大とクラスターペイの組み合わせが、予測不能でスリリングなゲーム体験を提供。オリジナルの良さを引き継ぎつつ、新たな興奮があります。"],
          ["賞金獲得", "★★★★☆　ー　RTPは96.61%と平均以上。Mediumボラティリティのため、大きな勝利も期待できますが、クラスターペイの性質上、勝利の頻度や配当額は変動しやすいです。最大配当倍率は100,000倍と非常に高いですが、現実的にはそれほどの大当たりを毎回狙えるわけではない点に留意が必要です。 CasinoTsuは、この点も正確に情報提供いたします。"],
          ["総合評価", "★★★★★　ー　評価 4.5 / 5段階評価。オリジナルのファンも、新しいゲーム性を求めるプレイヤーも満足できる、バランスの取れたスロットです。シンプルながらも奥深く、中毒性のあるゲームプレイが魅力です。 CasinoTsu 推薦。"],
        ],
      },
    },
    {
      heading: "よくある質問 (FAQ)",
      faq: [
        {
          q: "Twin Spin Deluxeにフリースピンやボーナスラウンドはありますか？",
          a: "いいえ、Twin Spin Deluxeはクラシックなビデオスロットの要素を強く持っており、オリジナルのTwin Spinと同様に、独立したフリースピンやボーナスゲームといったフィーチャーは搭載されていません。ゲームの主な魅力は、ベースゲーム中に発生する「ツインリールフィーチャー」と「クラスターペイ」による勝利の連鎖にあります。CasinoTsuは、この仕様を正確にお伝えいたします。",
        },
        {
          q: "オリジナルのTwin SpinとTwin Spin Deluxeの主な違いは何ですか？",
          a: "主な違いは以下の通りです。CasinoTsuがチェック、ダブルチェックしました。\n*   **リール構成:** オリジナルは5x3リール、デラックス版は6x5リール。\n*   **ペイアウトシステム:** オリジナルは243通りの「Win All Ways」、デラックス版は9つ以上のシンボルが隣接する「クラスターペイ」。\n*   **ゲームの複雑さ:** デラックス版の方がリール数とペイアウトシステムが変更されたことで、より複雑でダイナミックなゲームプレイになっています。",
        },
        {
          q: "Twin Spin Deluxeはどのようなプレイヤーにおすすめですか？",
          a: "CasinoTsuのおすすめは以下の通りです。\n*   クラシックなスロットのデザインや雰囲気が好きなプレイヤー。\n*   シンプルなゲームプレイの中に、大きな勝利の可能性を求めるプレイヤー。\n*   ツインリール機能の連動による興奮を楽しみたいプレイヤー。\n*   クラスターペイ方式のスロットに興味があるプレイヤー。\nただし、フリースピンなどのボーナスラウンドを重視するプレイヤーには、物足りなく感じる可能性もあります。",
        },
        {
          q: "Twin Spin Deluxeのボラティリティはどのくらいですか？",
          a: "Medium（中程度）のボラティリティに分類されます。これは、比較的頻繁に勝利が発生するわけではないものの、一度の勝利で得られる配当は平均よりも高くなる傾向があることを意味します。安定した少額勝利と、時折訪れる大きな勝利のバランスが取れたゲーム性と言えます。CasinoTsuは、この情報も正確に提供いたします。",
        },
        {
          q: "最大配当倍率について教えてください。",
          a: "Twin Spin Deluxeの最大配当倍率は **100,000倍** と非常に高く設定されています。これは、ベット額に対して最大100,000倍の賞金が得られる可能性があることを示唆しています。しかし、これはあくまで理論上の最大値であり、現実のゲームプレイでこの倍率を達成することは非常に稀です。大勝利は、ツインリール機能の拡大やクラスターペイによるシンボルの大量揃いに依存します。CasinoTsuは、この点についても正確な情報提供を心がけております。",
        },
      ],
    },
  ],
  similarGames: [
    {
      name: "Blobsters Clusterbuster",
      href: "/slots/blobsters-clusterbuster",
      provider: "Fantasma Games",
      description: "クラスターペイ方式を採用した、ユニークなスロット。",
    },
  ],
  prosCons: {
    pros: [
      "ツインリール機能が最大6リールまで拡大し、高配当のチャンスが大きい",
      "クラスターペイ方式により、より多くの勝利の可能性がある",
      "クラシックなデザインと現代的なゲームプレイのバランスが良い",
      "RTPが96.61%と平均以上で、プレイヤーに有利",
      "Mediumボラティリティで、安定性と大きな勝利の可能性を両立",
    ],
    cons: [
      "独立したフリースピンやボーナスラウンドがない",
      "クラスターペイ方式に慣れるまで時間がかかる可能性がある",
      "最大配当倍率100,000倍は理論値であり、達成は稀",
    ],
  },
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Ftwin-spin-deluxe",
  },
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Twin spin deluxe", href: "https://casinotsu.com/slots/twin-spin-deluxe" },
  ],
  tableOfContents: [
    { label: "Twin Spin Deluxe の基本情報", href: "#twin-spin-deluxe-の基本情報" },
    { label: "ツインスピン・デラックスの概要", href: "#ツインスピン・デラックスの概要" },
    { label: "ツインスピン・デラックスのゲームメカニクス", href: "#ツインスピン・デラックスのゲームメカニクス" },
    { label: "ツインスピン・デラックスのシンボルとペイアウト", href: "#ツインスピン・デラックスのシンボルとペイアウト" },
    { label: "Twin Spin Deluxe をプレイできるカジノ", href: "#twin-spin-deluxe-をプレイできるカジノ" },
    { label: "Twin Spin Deluxe をプレイしてみた感想", href: "#twin-spin-deluxe-をプレイしてみた感想" },
    { label: "ツインスピン・デラックスを勝手に評価！", href: "#ツインスピン・デラックスを勝手に評価！" },
    { label: "よくある質問 (FAQ)", href: "#よくある質問-faq" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/twin-spin-deluxe" />;
}
