import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Moon Princess",
  hero: {
    title: "Moon Princess",
    subheading: "ムーンプリンセス",
    description: "日本人プレイヤーの皆様に大変ご好評いただいております、Play'n GO社よりリリースの「ムーンプリンセス（Moon Princess）」をご紹介いたします。CasinoTsuでも数々のカジノのボーナス対象として推薦させていただいており、その人気は折り紙付きです。カスケード式スロットならではの連鎖による爽快感と、まるで人気アニメのような魅力的な世界観が、日本のプレイヤーの皆様を惹きつけています。今回は、この「ムーンプリンセス」をCasinoTsuが詳しく解説いたします！✨",
    score: 4.3,
    scoreMax: 5,
    rtp: "96.5%",
    maxMultiplier: "x5,000",
    provider: "Play'n GO",
    releaseDate: "2016-06-30",
    volatility: "High",
    reels: "5",
    paylines: "クラスターペイ",
    minBet: "$0.20",
    maxBet: "$100",
    slotImageSrc: "/slots/moon-princess.png",
    highlights: [
      "クラスターペイ（Cluster Pays）",
      "3人のプリンセスによるガールパワー機能",
      "メーターフィーチャー（Resonance）によるフリースピン突入",
      "フリースピン中のマルチプライヤー機能",
    ],
    watchouts: [
      "ハイボラティリティのため、資金管理に注意が必要",
      "RTPはカジノによって異なる場合がある",
    ],
  },
  featuredCasino: {
    name: "2up Casino",
    logo: "/assets/casino/2up.png",
    href: "/reviews/2up",
    ctaText: "今すぐプレイ",
    ctaHref: "/reviews/2up",
    tagline: "2アップカジノ 2up",
  },
  casinos: [
    {
      name: "ReSpin",
      logo: "/assets/casino/respin.jpg",
      href: "/reviews/respin",
      bonus: "300USDT",
      freeSpins: "200",
      wagering: "35x (ボーナス), 5x (フリースピン)",
      rating: 4,
      tagline: "10種類のメジャーな仮想通貨が使えるクリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/respin",
    },
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30x (ボーナス), 30x (フリースピン)",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/golden-panda",
    },
    {
      name: "2up",
      logo: "/images/casino/2up_375x375-1.png",
      href: "/reviews/2up",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/2up",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x (ボーナス), 20x (フリースピン)",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/miki",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/wsm-casino_375x375-1.png",
      href: "/reviews/wsm-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "/reviews/bitz",
      bonus: "$1,000",
      freeSpins: undefined,
      wagering: "29x (ボーナス)",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitz",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "/reviews/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20x (ボーナス), 20x (フリースピン)",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wikibet",
    },
    {
      name: "Katsuwin",
      logo: "/images/casino/katsuwin_375x375-1.png",
      href: "/reviews/katsuwin",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/katsuwin",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x (ボーナス), 40x (フリースピン)",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/sushi-casino",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "/reviews/parimatch",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/parimatch",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "/reviews/duelbits",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/sportsbet-io",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "/reviews/shuffle",
      bonus: "$2,020",
      freeSpins: undefined,
      wagering: "40x (ボーナス)",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/shuffle",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: undefined,
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/winz-io",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "/reviews/dafabet",
      bonus: "$500",
      freeSpins: undefined,
      wagering: "20x (ボーナス)",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/dafabet",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35x (フリースピン)",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/lucky-block",
    },
    {
      name: "Ramenbet",
      logo: "/images/casino/ramenbet_375x375-1.png",
      href: "/reviews/ramenbet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/ramenbet",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/flush_375x375-1.png",
      href: "/reviews/flush",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/flush",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "/reviews/queen-casino",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30x (ボーナス), 20x (フリースピン)",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/queen-casino",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "/reviews/roobet",
      bonus: "$0",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/roobet",
    },
    {
      name: "Casino Sky",
      logo: "/images/casino/casinosky_375x375.png",
      href: "/reviews/casino-sky",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-sky",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35x (ボーナス), 40x (フリースピン)",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/mega-dice",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "/reviews/cosmoswin",
      bonus: "$10,000",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/cosmoswin",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45x (ボーナス), 60x (フリースピン)",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bc-game",
    },
    {
      name: "Stake",
      logo: "/images/casino/stake_375x375-1.png",
      href: "/reviews/stake",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/stake",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "/reviews/wonder-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wonder-casino",
    },
    {
      name: "K8",
      logo: "/assets/casino/k8.jpg",
      href: "/reviews/k8",
      bonus: "$1,840",
      freeSpins: "288",
      wagering: "25x (ボーナス), 25x (フリースピン)",
      rating: 4.5,
      tagline: "日本で人気の実機を打つならK8のパチンコで決まりっ！昔懐かしの台を打ちまくろう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/k8",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35x (ボーナス), 40x (フリースピン)",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/ohmyspins",
    },
    {
      name: "Yuugado",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "/reviews/yuugado",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/yuugado",
    },
    {
      name: "Tedbet",
      logo: "/images/casino/tedbet_375x375.png",
      href: "/reviews/tedbet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/tedbet",
    },
    {
      name: "BetRebels",
      logo: "/images/casino/betrebels_375x375.png",
      href: "/reviews/betrebels",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/betrebels",
    },
    {
      name: "Conquestador",
      logo: "/images/casino/Conquestador_375x375.png",
      href: "/reviews/conquestador",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/conquestador",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.jpg",
      href: "/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/cloudbet",
    },
    {
      name: "Livecasino.io",
      logo: "/images/casino/livecasinoio.jpg",
      href: "/reviews/livecasino-io",
      bonus: "$0",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/livecasino-io",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.jpg",
      href: "/reviews/lucky-bull",
      bonus: "$917",
      freeSpins: undefined,
      wagering: "30x (ボーナス)",
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/lucky-bull",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.jpg",
      href: "/reviews/gamdom",
      bonus: "$0",
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/gamdom",
    },
    {
      name: "Energy Casino",
      logo: "/images/casino/energy-casino_375x375.png",
      href: "/reviews/energy-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/energy-casino",
    },
    {
      name: "Konibet",
      logo: "/images/casino/konibet_375x375.png",
      href: "/reviews/konibet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/konibet",
    },
    {
      name: "Vulkan Vegas",
      logo: "/assets/casino/vulkan-vegas.jpg",
      href: "/reviews/vulkanvegas",
      bonus: "¥100,000",
      freeSpins: "125",
      wagering: "40x (ボーナス), 30x (フリースピン)",
      rating: 4,
      tagline: "アメコミの世界観に入り込んじゃえ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/vulkanvegas",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x (ボーナス), 20x (フリースピン)",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-me",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "/reviews/mystino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/mystino",
    },
    {
      name: "Trustdice",
      logo: "/images/casino/Trustdice_375x375.png",
      href: "/reviews/trustdice",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/trustdice",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "/reviews/inter-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/inter-casino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "/reviews/empire777",
      bonus: "$1,600",
      freeSpins: undefined,
      wagering: "20x (ボーナス)",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/empire777",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "/reviews/pinnacle",
      bonus: "$0",
      freeSpins: undefined,
      wagering: undefined,
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/pinnacle",
    },
    {
      name: "Justspin",
      logo: "/assets/casino/justspin.jpg",
      href: "/reviews/just-spin",
      bonus: "$500",
      freeSpins: "600",
      wagering: "50x (ボーナス), 50x (フリースピン)",
      rating: 4,
      tagline: "シンプルなデザインで見やすいプラットフォーム",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/just-spin",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "/reviews/winunique",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30x (ボーナス), 30x (フリースピン)",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/winunique",
    },
    {
      name: "21.com",
      logo: "/assets/casino/21com.jpg",
      href: "/reviews/21-com",
      bonus: "$1,000",
      freeSpins: "1000",
      wagering: "50x (ボーナス), 50x (フリースピン)",
      rating: 4,
      tagline: "構造もシンプルで検索機能も使いやすい",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/21-com",
    },
    {
      name: "BitStarz",
      logo: "/images/casino/bitstarz_375x375.png",
      href: "/reviews/bitstarz",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitstarz",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino_375x375.png",
      href: "/reviews/joycasino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/joycasino",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casinos/casino-secret_375x375.png",
      href: "/reviews/casino-secret",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-secret",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "/reviews/vera-john",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/vera-john",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "/reviews/live-casino-house",
      bonus: "¥50,000",
      freeSpins: undefined,
      wagering: "20x (ボーナス)",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: undefined,
      wagering: "40x (ボーナス)",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "/reviews/casino-x",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x (ボーナス), 20x (フリースピン)",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casitabi",
    },
    {
      name: "William Hill",
      logo: "/assets/casino/william-hill.jpg",
      href: "/reviews/william-hill",
      bonus: "$300",
      freeSpins: undefined,
      wagering: "25x (ボーナス)",
      rating: 3.5,
      tagline: "世界三大の超老舗ブックメーカー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/william-hill",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "/reviews/eldoah",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/eldoah",
    },
  ],
  gameInfo: {
    intro: "日本人プレイヤーの皆様に大変ご好評いただいております、Play'n GO社よりリリースの「ムーンプリンセス（Moon Princess）」をご紹介いたします。CasinoTsuでも数々のカジノのボーナス対象として推薦させていただいており、その人気は折り紙付きです。カスケード式スロットならではの連鎖による爽快感と、まるで人気アニメのような魅力的な世界観が、日本のプレイヤーの皆様を惹きつけています。今回は、この「ムーンプリンセス」をCasinoTsuが詳しく解説いたします！✨",
    basicInfo: {
      rtp: "96.50% (※複数バージョンあり)",
      volatility: "High (ハイ)",
      reels: "5",
      paylines: "クラスターペイ（Cluster Pays）",
      minBet: "$0.20",
      maxBet: "$100",
      provider: "Play'n GO",
      releaseDate: "2016-06-30",
    },
  },
  payoutTable: {
    title: "ムーンプリンセス のシンボル・配当",
    symbols: [
      {
        name: "プリンセス顔 (3種)",
        description: "3つ以上揃えば配当発生",
        payout5: "x5,000",
        payout4: "x1,000",
        payout3: "x500",
      },
      {
        name: "宝石 (3種)",
        description: "3つ以上揃えば配当発生",
        payout5: "x1,000",
        payout4: "x300",
        payout3: "x100",
      },
      {
        name: "宝石 (3種)",
        description: "3つ以上揃えば配当発生",
        payout5: "x300",
        payout4: "x100",
        payout3: "x30",
      },
    ],
    maxPayout: "5,000x",
    notes: [
      "$1ベット時のペイアウト例",
      "プリンセスたちの顔のシンボルが3つ以上揃えば配当が発生します。",
    ],
  },
  features: {
    title: "ムーンプリンセス｜ゲーム機能",
    items: [
      {
        name: "ガールパワー（Girl Power）",
        description: "ペイラインが成立しない場合でも、プリンセスたちがランダムにリール上のシンボルを変化させ、勝利のチャンスを生み出します。",
        icon: undefined,
      },
      {
        name: "メーターフィーチャー (Resonance)",
        description: "勝利シンボルが消えるとメーターがチャージされ、満タンになると「レゾナンススピン」または「トリニティ」が発動します。3人のプリンセス全員のガールパワーが同時に発動し、高い勝利の可能性を秘めています。",
        icon: "/images/Moon-princess-meter.jpg",
      },
      {
        name: "ボーナスゲーム（フリースピン）",
        description: "フィールド内の全てのシンボルが消滅すると、ボーナスゲーム（フリースピン）に突入するチャンスがあります。プレイヤーは3人のプリンセスの中から1人を選択し、フリースピンの回数やガールパワーの特性が異なります。",
        icon: "/images/Moon-princess-free-spins.jpg",
      },
      {
        name: "マルチプライヤー機能",
        description: "勝利ごとに倍率が上昇するマルチプライヤー機能が搭載されています。フリースピン中はこのマルチプライヤーがリセットされず、継続して適用されるため、爆発的な配当を生み出す可能性があります。",
        icon: undefined,
      },
    ],
  },
  sections: [
    {
      heading: "Moon Princess の基本情報",
      paragraphs: [
        "「ムーンプリンセス」は、従来のペイライン方式ではなく、**クラスターペイ**というメカニクスを採用しております。5x5のグリッド上で、**3つ以上の同一シンボルが縦または横に隣接して揃う**ことで勝利となります。勝利したシンボルは消滅し、上から新しいシンボルが落下してくる**カスケード（連鎖）**が発生します。この連鎖により、1回のスピンで複数回の勝利が期待できる点が、このスロットの大きな魅力です。",
      ],
      bullets: [
        "3人のプリンセスが登場し、それぞれ異なる特別な能力を持ちます。",
        "ラブ (Love) - ピンク: 1セットのシンボルを別のシンボルに変化させる能力。",
        "スター (Star) - ブルー: 最高2つのワイルドシンボルを出現させる能力。",
        "ストーム (Storm) - グリーン: ランダムに選ばれた2セットのシンボルを消去する能力。",
      ],
      table: {
        title: "基本情報",
        columns: ["項目", "詳細"],
        rows: [
          ["リール数", "5リール×5行"],
          ["ゲームメカニクス", "クラスターペイ（Cluster Pays）"],
          ["ペイライン", "なし"],
          ["コインバリュー", "$0.20〜$100.00"],
          ["最高獲得コイン数", "500,000"],
          ["RTP（返還率）", "96.50% (※複数バージョンあり)"],
          ["ボラティリティ", "High (ハイ)"],
          ["最大ベット額", "$100"],
          ["最小ベット額", "$0.20"],
        ],
      },
    },
    {
      heading: "ムーンプリンセス を遊ぶならこのカジノ！",
      paragraphs: [
        "CasinoTsuが、ボーナスやお得な特典をご用意しているカジノを厳選いたしました。",
      ],
      table: {
        title: "おすすめカジノ",
        columns: ["カジノ名", "登録ボーナス"],
        rows: [
          ["[**遊雅堂**](/reviews/yuugado)", "ジャパカジ限定！ 遊雅堂の入金不要ボーナス3,000円🎁<br>👉 [遊雅堂 のオファー](/offers/yuugado-exclusive) へ"],
          ["[**エルドアカジノ**](/reviews/eldoah)", "エルドアカジノ（eldoah casino）では、ジャパカジから登録で今なら入金不要ボーナス2,000円分を進呈中っ🤞🎁<br>👉 [エルドアカジノ のオファー](/offers/eldoah-exclusive) へ"],
          ["[**インターカジノ**](/reviews/inter-casino)", "ジャパカジからの登録で、今なら3倍の150回分（30ドル相当）登録フリースピンが貰えちゃうんですっ(/≧▽≦)/<br>👉 [インターカジノ のオファー](/offers/shinqueen-no-deposit-bonus) へ"],
          ["[**ジョイカジノ**](/reviews/joycasino)", "入金不要でジョイカジノに登録するだけなのに、4,500円！<br>👉 [ジョイカジノ のオファー](/offers/joycasino-exclusive) へ"],
          ["[**ステークカジノ**](/reviews/stake)", "ジャパカジから登録&カスタマーサポートに連絡するともらえる、入金不要ボーナス2,500円を進呈中～ヾ(≧▽≦\*)o<br>👉 [ステークのオファー](/offers/stake-exclusive) へ"],
        ],
      },
    },
    {
      heading: "プレイしてみた感想",
      paragraphs: [
        "美少女戦士のファンとしては、どうしてもプレイしてみたくなる魅力がありました。",
        "BGMも、プリンセスたちが戦っているかのような高揚感があり、フィーチャーやボーナスモードに突入すると、さらに音楽が変化するため、勝利金が加算された時には「悪党をやっつけた！」という気分になります。",
        "フィーチャーやボーナスが始まるまでは、時に忍耐が必要となることもありますが、フィールド内にペイアウトがない場合でも、ランダムにプリンセスたちが助けてくれる**ガールパワー**があるため、退屈することはありません。感謝！🙏",
        "当選するかどうかは運次第ではありますが、十分に楽しめるゲームであることは間違いありません。特に、かつてこのようなプリンセス戦隊もののアニメをご覧になっていた女性プレイヤーの皆様には、強くお勧めいたします！もちろん、可愛いキャラクターを眺めるのがお好きな男性プレイヤーの皆様にも、きっとお楽しみいただけることでしょう。",
      ],
    },
    {
      heading: "類似ゲームと続編",
      paragraphs: [
        "「ムーンプリンセス」は、そのユニークなゲーム性やテーマから多くのプレイヤーに愛されており、Play'n GO社からは数多くの続編や派生機種がリリースされています。",
      ],
      bullets: [
        "[Moon Princess 100](/slots/moon-princess-100)（ムーンプリンセス100）: 最大配当倍率が10,000倍にアップグレードされ、さらなる興奮を提供します。",
        "[Moon Princess Christmas Kingdom](/slots/moon-princess-christmas-kingdom)（ムーンプリンセス・クリスマスキングダム）: クリスマスの季節にぴったりの、特別なバージョンです。",
        "[Moon Princess Trinity](/slots/moon-princess-trinity)（ムーンプリンセス・トリニティ）: 3人のプリンセスが同時にフィーチャーを発動する「トリニティ」機能が強化されています。",
        "[Moon Princess Power of Love](/slots/moon-princess-power-of-love)（ムーンプリンセス・パワーオブラブ）: 最新作の一つとして、さらなる進化を遂げています。",
        "[Moon Princess Stargazing](/slots/moon-princess-stargazing): 新たな機能と、高い最大配当倍率（10,000倍）が特徴です。",
        "[Moon Princess Origins](/slots/moon-princess-origins): シリーズの中でも特に高い最大配当倍率（20,000倍）を誇ります。",
      ],
      paragraphs: [
        "これらの続編では、グラフィックの向上、さらにエキサイティングなフィーチャー、そしてより高い勝利の可能性が追求されています。",
      ],
    },
    {
      heading: "勝手に評価！",
      paragraphs: [
        "CasinoTsu 評価 4.9 / 5段階評価",
      ],
      bullets: [
        "グラフィック: ★★★★☆ ー 近年の3Dスロットのような立体感はありませんが、Play'n GO社らしい、しっかりと作り込まれたアニメ調のグラフィックは健在であり、テーマ性を豊かにしています。",
        "サウンド: ★★★★☆ ー 戦隊ヒーローもののBGMのような、プレイヤーの心を躍らせるサウンドは素晴らしいです。一点だけ！途中で聞こえる「LOVE!」や「ナイス！」というボイスが男性なのが少し残念。ここはぜひ、プリンセスたちの声で統一してほしかったところです。",
        "面白さ: ★★★★★ ー テーマ性がしっかりと表現されており、ランダムに何が起こるかわからないワクワク感、ゲーム内の機能を存分に楽しめる点が、このスロットの大きな魅力です。",
        "賞金獲得: ★★★★★ ー RTP96.5%は平均的な数値ですが、実際にプレイしてみた感触では、粘り強くプレイすることで期待できるでしょう。特に、ボーナスラウンドの爆発力は驚異的です！🎯",
      ],
    },
    {
      heading: "その他おススメ神様スロット",
      paragraphs: [
        "Spinomenal社人気シリーズの初作！ [『ブック・オブ・デミゴッズ（Book of Demi Gods）』2](/slots/book-of-demi-gods-2) をチェック♪",
      ],
    },
  ],
  similarGames: [
    {
      name: "Moon Princess 100",
      href: "/slots/moon-princess-100",
      provider: "Play'n GO",
      description: "最大配当倍率が10,000倍にアップグレードされ、さらなる興奮を提供します。",
    },
    {
      name: "Moon Princess Christmas Kingdom",
      href: "/slots/moon-princess-christmas-kingdom",
      provider: "Play'n GO",
      description: "クリスマスの季節にぴったりの、特別なバージョンです。",
    },
    {
      name: "Moon Princess Trinity",
      href: "/slots/moon-princess-trinity",
      provider: "Play'n GO",
      description: "3人のプリンセスが同時にフィーチャーを発動する「トリニティ」機能が強化されています。",
    },
    {
      name: "Moon Princess Power of Love",
      href: "/slots/moon-princess-power-of-love",
      provider: "Play'n GO",
      description: "最新作の一つとして、さらなる進化を遂げています。",
    },
    ],
  prosCons: {
    pros: [
      "アニメ調の魅力的な世界観とキャラクター",
      "クラスターペイとカスケード連鎖による爽快感",
      "ガールパワー機能によるランダムな勝利チャンス",
      "メーターフィーチャーからの高配当トリニティ機能",
      "フリースピン中のマルチプライヤー機能による爆発力",
      "続編や派生機種が多数リリースされており、飽きさせない",
    ],
    cons: [
      "ハイボラティリティのため、資金管理が重要",
      "フリースピン突入条件が厳しい場合がある",
      "RTPはカジノによって異なる場合がある",
      "サウンドの一部（ボイス）に改善の余地あり",
    ],
  },
  faq: [
    {
      q: "ムーンプリンセスのボーナスモードは何種類ありますか？",
      a: "フリースピンモードは、プレイヤーが選択するプリンセスによって3種類（ラブ、スター、ストーム）に分岐します。それぞれフリースピンの回数やガールパワーの特性が異なります。",
    },
    {
      q: "ムーンプリンセスに続編はありますか？",
      a: "はい、「Moon Princess 100」、「Moon Princess Christmas Kingdom」、「Moon Princess Trinity」、「Moon Princess Stargazing」、「Moon Princess Origins」など、多数の続編や派生機種があります。",
    },
    {
      q: "ムーンプリンセスはどのようなプレイヤーにおすすめですか？",
      a: "アニメやマンガ（特に魔法少女もの）が好きなプレイヤー、クラスターペイのスロットが好きなプレイヤー、そしてハイボラティリティ（高リスク・高リターン）なゲーム性で一攫千金を狙いたいプレイヤーにおすすめです。",
    },
    {
      q: "ムーンプリンセスは無料でプレイできますか？",
      a: "はい、多くのオンラインカジノでは、リアルマネーでプレイする前に、ゲームの雰囲気を試せる無料デモ版を提供しております。",
    },
    {
      q: "ハイボラティリティのスロットをプレイする際の注意点は？",
      a: "ハイボラティリティのスロットは、勝利頻度が低い代わりに一度の勝利で大きな配当を得られる可能性があります。そのため、資金管理（バンクロールマネジメント）をしっかり行い、余裕を持ったベット額でプレイすることが重要です。また、フィーチャーやボーナスがなかなか発動しなくても、冷静にプレイを続ける忍耐力も求められます。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "Slots", href: "/slots" },
    { label: "Moon princess", href: "/slots/moon-princess" },
  ],
  tableOfContents: [
    { label: "Moon Princess の基本情報", href: "#moon-princess-no-kihon-jōhō" },
    { label: "ムーンプリンセス を遊ぶならこのカジノ！", href: "#muunpurinsesu-o-asobu-narawakono-kajino" },
    { label: "プレイしてみた感想", href: "#purei-shite-mita-kansō" },
    { label: "類似ゲームと続編", href: "#ruiji-gēmu-to-zokuhen" },
    { label: "勝手に評価！", href: "#katte-ni-hyōka" },
    { label: "その他おススメ神様スロット", href: "#sonota-osusume-kamisama-supurotto" },
    { label: "よくある質問 (FAQ)", href: "#yoku-aru-shitsumon-faq" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "/reviews/2up",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/moon-princess" />;
}
