import ProvidersTemplate, { ProvidersPageData } from "@/components/templates/ProvidersTemplate";

const data: ProvidersPageData = {
  title: "YOLTED（ヨールテッド）ゲームプロバイダーレビュー｜2025最新",
  banner: {
    title: "YOLTED",
    subheading: "革新的なゲーム性と魅力的なグラフィックで注目を集める新進気鋭のプロバイダー",
    description: "2020年に設立されたYOLTEDは、斬新な「スワイプ」ジャンルや日本市場を意識したテーマ性の高いスロットで、多くのプレイヤーを魅了しています。西海岸の自由で創造性あふれる雰囲気を反映したユニークなゲームで、今後の活躍が期待されています。",
    avatarSrc: "/assets/provider/yolted.png",
    avatarAlt: "YOLTEDロゴ",
  },
  hero: {
    highlights: [
      "斬新な「スワイプ」ゲームジャンル",
      "日本市場を意識したテーマ性の高いスロット",
      "高品質なグラフィックとサウンド",
      "HTML5とJavaScriptによる最新技術",
    ],
    watchouts: [
      "ゲーム数はまだ少ない",
      "ジャックポット機能は提供されていない",
    ],
  },
  intro: "CasinoTsu は、プレイヤーの皆様に信頼できる情報をお届けするため、日々最新の情報を収集・分析しております。この度、革新的なゲーム性と魅力的なグラフィックで注目を集めるゲームプロバイダー、YOLTED（ヨールテッド）について、詳細なレビューをお届けいたします。",
  authorCommentary: {
    author: "CasinoTsu編集部",
    commentary: "YOLTEDは、そのユニークなゲーム性と魅力的なグラフィックで、多くのプレイヤーを魅了しています。特に「スワイプ彼女」シリーズや「ノート・オブ・デス」は、斬新なゲームプレイと日本市場を意識したテーマで人気を集めています。CasinoTsu では、以下のゲームを特におすすめいたします。",
    avatarSrc: "/assets/authors/casinotsu-editor.png",
    role: "カジノゲームレビュー担当",
    hook: "YOLTEDのゲームは、さすが2020年誕生の新鋭プロバイダーだけあり、グラフィックが美しく、アクションもなめらかです。",
    theGoodStuff: "特に注目すべきは、ブリッツフィーチャーでスロットを回せるところ！通常の「スピン」の6倍速でスロットを回せる、いわば高速スピン機能です。時間がないけれど、100スピンくらいサクッと回したいという願いを叶えてくれます。",
    theHeadsUp: "サウンドにもこだわっており、特に『スロット彼女』や『スワイプ彼女』では声優を起用しており、リアルな女の子の声が楽しめます。彼女テーマで癒されるスロットは、日本のメーカーが参入していないオンカジ業界ではかなりレアな存在です。",
    finalThought: "まだまだゲーム数は少ないものの、その独自性と日本市場へのアプローチの巧みさから、今後の成長が非常に期待されるゲームプロバイダーです。斬新なゲーム体験を求めるプレイヤーや、日本のポップカルチャーが好きなプレイヤーに特におすすめできます。",
  },
  featured: {
    title: "CasinoTsu 推薦！ YOLTEDのおすすめ／人気ゲーム",
    items: [
      {
        name: "Vampires Gone Wild",
        founded: "2020",
        hq: "USA",
        licenses: ["Malta", "Sweden", "Denmark", "Curacao"],
        gameTypes: ["Slot"],
        tagline: "ヴァンパイア・ゴーン・ワイルド",
        topGames: [
          { name: "Vampires Gone Wild", href: "https://casinotsu.com/slots/vampires-gone-wild" },
          { name: "Note of Death", href: "https://casinotsu.com/slots/note-of-death" },
          { name: "Swipe gf", href: "https://casinotsu.com/slots/swipe-gf" },
          { name: "Slot Gf Amane", href: "https://casinotsu.com/slots/slot-gf-amane" },
          { name: "Robo Ultra", href: "https://casinotsu.com/slots/robo-ultra" },
          { name: "Coin Swipe", href: "https://casinotsu.com/slots/coin-swipe" },
          { name: "Crystal Swipe", href: "https://casinotsu.com/slots/crystal-swipe" },
          { name: "Section VIII: Rise of the Damned", href: "https://casinotsu.com/slots/section-viii-rise-of-the-damned" },
        ],
      },
      {
        name: "Note of Death",
        founded: "2020",
        hq: "USA",
        licenses: ["Malta", "Sweden", "Denmark", "Curacao"],
        gameTypes: ["Slot"],
        tagline: "ノート・オブ・デス",
        topGames: [
          { name: "Vampires Gone Wild", href: "https://casinotsu.com/slots/vampires-gone-wild" },
          { name: "Note of Death", href: "https://casinotsu.com/slots/note-of-death" },
          { name: "Swipe gf", href: "https://casinotsu.com/slots/swipe-gf" },
          { name: "Slot Gf Amane", href: "https://casinotsu.com/slots/slot-gf-amane" },
          { name: "Robo Ultra", href: "https://casinotsu.com/slots/robo-ultra" },
          { name: "Coin Swipe", href: "https://casinotsu.com/slots/coin-swipe" },
          { name: "Crystal Swipe", href: "https://casinotsu.com/slots/crystal-swipe" },
          { name: "Section VIII: Rise of the Damned", href: "https://casinotsu.com/slots/section-viii-rise-of-the-damned" },
        ],
      },
      {
        name: "Swipe gf",
        founded: "2020",
        hq: "USA",
        licenses: ["Malta", "Sweden", "Denmark", "Curacao"],
        gameTypes: ["Swipe Game", "Slot"],
        tagline: "スワイプ彼女",
        topGames: [
          { name: "Vampires Gone Wild", href: "https://casinotsu.com/slots/vampires-gone-wild" },
          { name: "Note of Death", href: "https://casinotsu.com/slots/note-of-death" },
          { name: "Swipe gf", href: "https://casinotsu.com/slots/swipe-gf" },
          { name: "Slot Gf Amane", href: "https://casinotsu.com/slots/slot-gf-amane" },
          { name: "Robo Ultra", href: "https://casinotsu.com/slots/robo-ultra" },
          { name: "Coin Swipe", href: "https://casinotsu.com/slots/coin-swipe" },
          { name: "Crystal Swipe", href: "https://casinotsu.com/slots/crystal-swipe" },
          { name: "Section VIII: Rise of the Damned", href: "https://casinotsu.com/slots/section-viii-rise-of-the-damned" },
        ],
      },
    ],
  },
  sections: [
    {
      heading: "YOLTED（ヨールテッド）とは？",
      paragraphs: [
        "YOLTEDは、2020年にアメリカ西海岸カリフォルニアで設立された、比較的新しいゲームデベロッパーです。設立から間もないながらも、特に「スワイプ」という斬新なゲームジャンルや、日本市場を意識したテーマ性の高いスロットゲームで、多くのプレイヤーの心を掴んでいます。西海岸の自由で創造性あふれる雰囲気を反映したような、ユニークなゲームを次々とリリースしており、今後の活躍が期待されています。",
      ],
    },
    {
      heading: "どこで遊べるか：YOLTEDが遊べる人気のカジノ",
      paragraphs: [
        "YOLTEDのゲームは、そのユニークさから多くのオンラインカジノで取り扱われています。ここでは、特に日本人プレイヤーに人気があり、YOLTEDのゲームをプレイできるおすすめのカジノをいくつかご紹介します。",
      ],
      bullets: [
        "Mystino: ボーナス ¥154,500、賭け条件 25x。",
        "Bitcasino.io: ボーナス ¥200,000、賭け条件 40x。",
        "Casitabi: ボーナス $500、賭け条件 20x、フリースピン 250回。",
        "Casino Me: ボーナス $777、賭け条件 20x、フリースピン 77回。",
        "Lilibet: ボーナス ¥130,000、賭け条件 50x、フリースピン 50回。",
        "Casino Sky: ボーナス ￥57,777、賭け条件 40x。",
        "WSM Casino: ボーナス $25,000、賭け条件 60x、フリースピン 50回。",
      ],
    },
    {
      heading: "ゲーム一覧・技術情報",
      paragraphs: [
        "YOLTEDは、現在約17種類のスロットゲームと1種類のカードゲーム（SwipeGF）を開発しており、そのゲームはJavaScriptとHTML5という最新技術を用いて制作されています。これにより、PCはもちろん、スマートフォンやタブレットといった様々なデバイスで、高品質なゲーム体験を提供しています。",
      ],
      table: {
        title: "YOLTED提供ゲーム一覧",
        columns: ["名称", "総合評価", "RTP", "最大配当倍率", "ボラティリティ", "リール構成", "ペイライン数"],
        rows: [
          ["Vampires Gone Wild", "84", "96%", "x50,000", "High", "-", "-"],
          ["Note of Death", "66", "96%", "x5,000", "High", "3", "10"],
          ["Swipe gf", "66", "96%", "x1,000", "Medium", "-", "-"],
          ["Slot Gf Amane", "72", "96%", "x1,000", "Medium", "3", "5"],
          ["Robo Ultra", "85", "96%", "x20,000", "High", "5", "-"],
          ["Coin Swipe", "84", "95.1%", "x5,000", "Medium", "-", "-"],
          ["Crystal Swipe", "62", "94%", "x1,000", "Low", "1", "1"],
          ["Section VIII: Rise of the Damned", "81", "94%", "x50,000", "High", "3", "10"],
          ["Lady's Blessing", "-", "96%", "-", "Medium", "-", "-"],
          ["Texas Wild Justice", "-", "-", "-", "-", "-", "-"],
          ["Bubble Trouble", "-", "-", "-", "-", "-", "-"],
          ["King of the Woods", "-", "-", "-", "-", "-", "-"],
          ["SlotGF Alice", "-", "94%", "-", "Medium", "5x3", "10"],
          ["Sutter's Mill", "-", "-", "-", "-", "-", "-"],
          ["Home Run 777", "-", "-", "-", "-", "-", "-"],
          ["Book of Imhotep", "-", "-", "-", "-", "-", "-"],
          ["Legacy of Imhotep", "-", "-", "-", "-", "-", "-"],
          ["Sweet Reels", "-", "-", "-", "-", "-", "-"],
        ],
      },
    },
    {
      heading: "SlotGF Alice 詳細情報",
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["RTP", "94%"],
          ["リスク", "Medium (中程度)"],
          ["最小ベット額", "0.1"],
          ["最大ベット額", "200"],
          ["ボーナス機能", "Wild、フリースピン、ボーナスゲーム、ボーナスシンボル、シンボル収集（エネルギー）、追加フリースピン"],
          ["テーマ", "アニメ、オリエンタル、美容、漫画、日本、花"],
          ["リール構成", "5×3"],
          ["ペイライン数", "10本"],
        ],
      },
    },
    {
      heading: "プロバイダー情報： YOLTED",
      paragraphs: [
        "ゲーム数は少ないながらも、キラリと光るスロットと、変わり種スワイプゲームを揃えた YOLTED（ヨールテッド） の魅力を徹底解剖いたします。",
        "YOLTEDは、2020年設立の新しいゲームデベロッパーながらも、珍しいスワイプゲームで 日本人プレイヤーの心をグッとつかむ ニクイゲームプロバイダーです。",
        "アメリカのカリフォルニア州に拠点を置き、 西海岸の自由で創造性あふれる土地柄が伝わってくるようなゲーム をどしどしリリースしています。🏝",
        "知る人ぞ知るYOLTED（というか知らない人がほとんどかも…(￣▽￣)）そんな、クリエイティブさ全開のゲームプロバイダーの魅力に迫っていきましょう！",
      ],
      table: {
        title: "YOLTED 一般情報",
        columns: ["項目", "詳細"],
        rows: [
          ["ライセンス", "SGA（スウェーデン）、DGA（デンマーク）、eMoore（キュラソー）、MGA（マルタ）"],
          ["カジノゲームタイプ", "スロット、スワイプ"],
          ["採用カジノ", "Bitcasino.io, Casitabi, Casino Me など"],
          ["モバイル対応", "ブラウザ版、スマホ版どちらも対応"],
          ["ゲームフィーチャー", "フリースピン、選択式ボーナス、ワイルドマルチプライヤー、リスピンなど"],
          ["設立", "アメリカ西海岸カリフォルニアで2020年に設立"],
          ["公平性", "RNG（ランダムナンバージェネレーター＝乱数生成器）によるランダムなゲーム結果であることを書くライセンス旗艦が認証済"],
          ["開発技術", "JavaScriptとHTML5"],
        ],
      },
    },
    {
      heading: "YOLTED 提供ゲーム一覧",
      paragraphs: [
        "ゲーム数は比較的少なめなものの、ひとつひとつのゲームのクオリティはかなり高めです！日本人プレイヤーの好みも的確に研究されているであろうテーマや空気感にも注目です♪",
      ],
      bullets: [
        "リールズ・オブ・アイオン（REELS of AION）",
        "レディーズ・ブレスィング（Lady’s Blessing）",
        "ナイツ・ファイト（Knights Fight）",
        "ノート・オブ・デス（Note of Death）",
        "ヴァンパイアーズ・ゴーン・ワイルド（Vampires Gone Wild）",
        "スロット彼女（SlotGF Amane）",
        "スワイプ彼女（SwipeGF）",
        "コイン・スワイプ（Coin Swipe）",
        "クリスタル・スワイプ（Crystal Swipe）",
        "ロボ・ウルトラ（Robo Ultra）",
        "セクション・エイト（Section VIII）",
        "Texas Wild Justice",
        "Bubble Trouble",
        "King of the Woods",
        "SlotGF Alice",
        "Sutter's Mill",
        "Home Run 777",
        "Book of Imhotep",
        "Legacy of Imhotep",
        "Sweet Reels",
      ],
    },
    {
      heading: "YOLTEDの安全性",
      paragraphs: [
        "YOLTEDは、プレイヤーが安心してゲームを楽しめるよう、高い安全基準を設けています。",
      ],
      subheading: "ライセンス",
      paragraphs: [
        "YOLTEDは、ゲームを提供しているオンラインカジノが運営されるキュラソー、スウェーデン、デンマーク、マルタなど、各国のライセンス認証機関から、ゲームの公平性・プラットフォームにおいて認証を受けています。これにより、YOLTEDのゲームは厳格な規制基準を満たしていることが保証されています。",
      ],
      subheading: "セキュリティ",
      paragraphs: [
        "ホームページに記載のプライバシーポリシー、利用規約でユーザーの情報保護を明記しています。実際にプレイするに当たり個人情報がディベロッパーに伝わることはありませんが、特殊なケースでAPIを利用する際などの個人情報保護も万全です。プレイの公平性は、乱数生成器（RNG）によって保証されています。",
      ],
      subheading: "ゲームの公平性",
      paragraphs: [
        "RTP（還元率）について: YOLTEDのゲームのRTPは、公開されているもので94%～96%程度です。業界標準が96.5%と言われる中、平均前後の数値を保っていると言えます。スワイプゲームはヒット率が高い（ボラティリティが低い）物が多いように見受けられます。",
        "YOLTEDの公平性を認証している第三者機関: デンマークのギャンブルを管轄するデンマーク・ギャンブル・オーソリティ（DMA）、同じくスウェーデンのSGA、マルタのMGA、そしてゲーミング（オンラインカジノ）のメッカ、キュラソーのゲーミングトラストであるeMooreの認証を取得しています。",
        "これだけ大御所のお墨付きがあって、ハズレなワケはありませんね🌟",
      ],
    },
    {
      heading: "ゲーム体験：ゲーム内フィーチャー",
      paragraphs: [
        "YOLTEDで楽しめる機能は下記の通りです。ジャックポット機能はないものの、一般的なスロットフィーチャーと言えるでしょう。",
      ],
      bullets: [
        "スキャッターフリースピン",
        "無限フリースピン",
        "ワイルドマルチプライヤー",
        "フィーチャー選択式ボーナススピン",
        "拡大ワイルド",
        "スティッキーワイルド",
        "フリースピン中に他のシンボルをワイルドに変えるワイルド",
        "リスピン",
      ],
    },
    {
      heading: "YOLTEDの傑作！人気ゲーム",
      subheading: "スロット彼女（SlotGF Amane)",
      paragraphs: [
        "萌え系キャラクターが全面にフィーチャーされた、彼女テーマのスロットゲームです。",
        "可愛らしい女の子（彼女の天音ちゃん）が一緒にはしゃいでくれたり、一緒に残念がったりする瞬間はまさにキュンキュン🥺 フリースピンに突入するとランジェリー姿になり、セクシー度もMAXに🙈 💕",
        "「彼女」と書かれたハートのワイルドが勝利の鍵を握ります。",
      ],
      subheading: "ノート・オブ・デス（Note of Death）",
      paragraphs: [
        "来ました！これまた日本市場に適応した「デスノート」ではなく、ノート・オブ・デスです！",
        "スキャッター3つでフリースピンに突入すると、選択式ボーナスが選べます。拡大ワイルドかスティッキーワイルドから選んで、勝利の確率を倍増させましょう！",
      ],
      subheading: "スワイプ彼女（Swipe GF)",
      paragraphs: [
        "こちらは物珍しい、スワイプ式のゲームです。グラフィックがとても可愛い〜！🎀 👒",
        "スワイプする方向が関係あるのでしょうか？いいえ、おそらく関係ないでしょう。😄",
        "とにかく、画面に現れるキャラクターをスワイプしていき、うさぎが出るとハズレ、女の子が出ると当たりです。ランダムに現れるキャラクターをひたすらスワイプしていきましょう。バッチリ声優が録音したサウンドエフェクトが心に響きます。",
        "Tinderやマッチングアプリをイメージしたのかもしれません。ボーナスモードではデートに行けることも♪",
      ],
    },
    {
      heading: "YOLTEDのゲームの特徴",
      paragraphs: [
        "YOLTEDのゲームは、さすが2020年誕生の新鋭プロバイダーだけあり、グラフィックが美しく、アクションもなめらかです。",
        "そして注目すべきは、ブリッツフィーチャーでスロットを回せるところ！それぞれ説明していきますね★",
      ],
      subheading: "なめらかなグラフィックアクション",
      paragraphs: [
        "HTML5を元に構築されたゲームはブラウザでのプレイに最適化されており、PCゲームをプレイしているかのようななめらかなアクションが楽しめます。",
        "スマホ版にももちろん対応しており、「スワイプ彼女」ではまるでマッチングアプリを使っているような臨場感も味わえます♪",
      ],
      subheading: "一通り揃ったフィーチャー",
      paragraphs: [
        "ジャックポットこそありませんが、スロットで定番のボーナススピンやスキャッターといったフィーチャーが揃っています。",
        "「無限フリースピン」とは、フリースピン中に指定シンボルが停止しさえすれば、永遠にフリースピンが継続するというものです。もちろん、勝利確率も高くなります。",
        "ボラティリティが低い＆ヒット率の高いイケイケ系、ボラティリティが高い＆当たると爆発力が高い系のスロットに分かれているようです。",
      ],
      subheading: "サウンド",
      paragraphs: [
        "サウンドにもこだわっており、特に『スロット彼女』や『スワイプ彼女』では声優を起用しており、リアルな女の子の声が楽しめます(￣▽￣)♡",
        "彼女テーマで癒されるスロットは、日本のメーカーが参入していないオンカジ業界ではかなりレアな存在です♪",
      ],
      subheading: "ブリッツフィーチャー",
      paragraphs: [
        "通常の「スピン」の6倍速でスロットを回せる、いわば高速スピン機能です。100スピンも数分で完了します💨",
        "「あー、時間がないけれど、100スピンくらいサクッと回したいなー」というマニアックな願いを叶えてくれます！スロットの立ち食い、といったところでしょうか🍜",
      ],
    },
    {
      heading: "YOLTEDのゲームを提供しているカジノ",
      paragraphs: [
        "2020年に生まれた新生メーカーだけあって、知名度はまだ低めです。というのも、実はリリース当初は、カジ旅とカジノミー限定のゲームプロバイダーだったんですよね。",
        "それにも関わらず、「スロット彼女」などの人気ぶりは目覚ましいものがあります…。",
        "現在では、ビットカジノ・アイオーもYOLTEDを取り入れ始めているので、今後さらに広まっていくことを期待しています★",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "YOLTEDのゲームは、スマートフォンからでもPC同等のクオリティで遊べます。「スワイプ彼女」など、ゲームに没入したい方はヘッドフォンの着用をおすすめします♡ HTML5技術を活用したゲームは、あらゆるデバイスに最適化されており、場所を選ばずに快適なプレイが可能です。",
      ],
    },
    {
      heading: "安全性・公平性・KYC",
      paragraphs: [
        "YOLTEDは、プレイヤーが安心してゲームを楽しめるよう、安全性と公平性を重視しています。",
      ],
      subheading: "ライセンス",
      paragraphs: [
        "キュラソー、スウェーデン、デンマーク、マルタなどの主要なライセンス機関から認可を受けており、ゲームの公平性とプラットフォームの安全性が保証されています。",
      ],
      subheading: "RNG認証",
      paragraphs: [
        "RNG（乱数生成器）による公平なゲーム結果が保証されており、第三者機関による監査も受けています。",
      ],
      subheading: "KYC（本人確認）",
      paragraphs: [
        "YOLTED自体はゲームプロバイダーであり、KYC手続きはゲームをプレイするオンラインカジノ側で実施されます。通常、アカウント登録時や出金時に、身分証明書（パスポート、運転免許証など）や住所確認書類（公共料金の請求書、住民票など）の提出が求められます。これにより、不正利用やマネーロンダリングを防ぎ、未成年者のギャンブル参加を防止しています。",
      ],
    },
    {
      heading: "ハイライト・強み",
      paragraphs: [
        "YOLTEDの最大の強みは、その独自性と革新性にあります。",
      ],
      bullets: [
        "斬新なゲーム性: 特に「スワイプ彼女」のようなスワイプ操作を取り入れたゲームは、従来のオンラインカジノゲームにはない新鮮な体験を提供します。",
        "日本市場への適応: 『スロット彼女』や『ノート・オブ・デス』など、日本のアニメや漫画文化を意識したテーマは、日本人プレイヤーの好みに合致しており、高い人気を得ています。",
        "高品質なグラフィックとサウンド: 最新技術を用いた美しいグラフィックと、声優を起用したリアルなサウンドは、プレイヤーをゲームの世界に深く引き込みます。",
        "デモ版の提供: 全てのゲームで無料デモ版を提供しており、プレイヤーはリアルマネーを賭ける前にゲームのルールや面白さを十分に試すことができます。これは、特に初めてYOLTEDのゲームをプレイする日本人プレイヤーにとって大きなメリットとなります。",
        "グローバルな人気: 世界中のプレイヤーから人気があり、多くのオンラインカジノがYOLTEDをトッププロバイダーの一つとして採用しています。Gamblers Connectなどのレビューサイトでも高く評価され、フリースピンやボーナスといった特典が注目されています。",
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "YOLTEDのゲームは、そのグラフィックを見れば、一味違った感覚を覚えることでしょう。",
        "多くのスロットゲームがヨーロッパの企業によって開発されている中、このメーカーはアメリカ西海岸を拠点としています。",
        "カリフォルニアの風に吹かれながら掻き立てられたインスピレーションが炸裂しています🎉",
        "まだまだゲーム数は少ないものの、その独自性と日本市場へのアプローチの巧みさから、今後の成長が非常に期待されるゲームプロバイダーです。斬新なゲーム体験を求めるプレイヤーや、日本のポップカルチャーが好きなプレイヤーに特におすすめできます。",
        "CasinoTsu は、皆様に安全で楽しいカジノ体験を提供するため、常に最新の情報をお届けしてまいります。",
      ],
    },
  ],
  comparison: {
    title: "YOLTED 提供ゲーム一覧",
    caption: "CasinoTsu では、プレイヤーの皆様が安心して遊べるカジノ体験を提供するため、常に正確な情報提供を心がけております。",
    columns: ["ゲーム名", "総合評価", "RTP", "最大配当倍率", "ボラティリティ"],
    rows: [
      ["Vampires Gone Wild (ヴァンパイア・ゴーン・ワイルド)", "4/5", "96%", "x50,000", "High"],
      ["Note of Death (ノート・オブ・デス)", "3.5/5", "96%", "x5,000", "High"],
      ["Swipe gf (スワイプ彼女)", "3.5/5", "96%", "x1,000", "Medium"],
      ["Slot Gf Amane (スロット彼女 天音)", "3.5/5", "96%", "x1,000", "Medium"],
      ["Robo Ultra (ロボ・ウルトラ)", "4.5/5", "96%", "x20,000", "High"],
      ["Coin Swipe (コインスワイプ)", "4/5", "95%", "x5,000", "Medium"],
      ["Crystal Swipe (クリスタルスワイプ)", "3/5", "94%", "x1,000", "Low"],
      ["Section VIII: Rise of the Damned (セクション・エイト｜地獄の亡者・ライジング)", "4/5", "94%", "x50,000", "High"],
    ],
  },
  faq: [
    {
      q: "YOLTED、何が有名ですか？",
      a: "アメリカ西海岸の雰囲気が感じられるゲームテーマ、グラフィック、そしてゲームの演出は、日本人プレイヤーとの親和性が高いと言えるでしょう。特に「スワイプ彼女」や「スロット彼女」シリーズが人気です。",
    },
    {
      q: "YOLTEDのゲームはどこでプレイできますか？",
      a: "Bitcasino.io、Casitabi、Casino Meなどで提供されています。今後、さらに多くのカジノで取り扱われることが期待されます。",
    },
    {
      q: "ゲームは公平に遊べますか？",
      a: "はい、YOLTEDのゲームは乱数生成器（RNG）の認証を欧州各国およびキュラソーの認証機関から受けており、完全に恣意性のない結果が得られる公平なゲームとなっています。チェック、ダブルチェック、そして CasinoTsu チェック済みです。",
    },
    {
      q: "YOLTEDのゲームにはどのような種類がありますか？",
      a: "現在は主にスロットと、ユニークなスワイプゲームが中心です。インスピレーションに優れたメーカーなので、今後、さらに面白いフィーチャーを備えたタイトルが登場することに期待が持てます。",
    },
    {
      q: "YOLTEDはスロットも制作していますか？",
      a: "もちろんです！YOLTEDのスロットには、神話系、バンパイア系、妖精系、アニメ系など、様々なテーマのものが揃っています。特に日本市場を意識したテーマは人気が高いです。",
    },
    {
      q: "YOLTEDのゲームは無料で試せますか？",
      a: "はい、YOLTEDは全てのゲームで無料デモ版を提供しています。リアルマネーを賭ける前に、ゲームの雰囲気を掴んだり、戦略を試したりするのに最適です。",
    },
  ],
  cta: {
    text: "YOLTEDのゲームをプレイできるカジノはこちら",
    href: "/reviews",
  },
  games: [
    "Vampires Gone Wild",
    "Note of Death",
    "Swipe gf",
    "Slot Gf Amane",
    "Robo Ultra",
    "Coin Swipe",
    "Crystal Swipe",
    "Section VIII: Rise of the Damned",
    "Lady's Blessing",
    "Texas Wild Justice",
    "Bubble Trouble",
    "King of the Woods",
    "SlotGF Alice",
    "Sutter's Mill",
    "Home Run 777",
    "Book of Imhotep",
    "Legacy of Imhotep",
    "Sweet Reels",
  ],
  features: [
    "フリースピン",
    "選択式ボーナス",
    "ワイルドマルチプライヤー",
    "リスピン",
    "無限フリースピン",
    "拡大ワイルド",
    "スティッキーワイルド",
    "ブリッツフィーチャー",
  ],
  security: [
    "キュラソーライセンス",
    "スウェーデンライセンス",
    "デンマークライセンス",
    "マルタライセンス",
    "RNG認証",
    "第三者機関による監査",
  ],
};

export default function Page() {
  return <ProvidersTemplate data={data} canonicalPath="/providers/yolted" />;
}
