import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Mermaid's Diamond",
  hero: {
    title: "Mermaid's Diamond",
    subheading: "マーメイド・ダイヤモンド",
    description: "マーメイド・ダイヤモンド（Mermaid’s Diamond）は、Play’n GO社が提供する、神秘的な人魚の世界をテーマにしたスロットゲームです。ユニークな6角形変形リールを採用し、海底に眠るダイヤモンドを探す冒険へとプレイヤーを誘います。CasinoTsuが、この魅力溢れるスロットの秘密を詳しくご紹介いたします。",
    score: 3.4,
    scoreMax: 5,
    rtp: "96.5%",
    maxMultiplier: "x5,000",
    provider: "Play’n GO",
    releaseDate: "2017-09-19",
    volatility: "Medium",
    reels: "6角形変形リール (3-4-5-4-3)",
    paylines: "720通り (左右両方向からのペイアウトに対応)",
    minBet: "$0.20",
    maxBet: "$100",
    slotImageSrc: "/slots/mermaids-diamond.jpg",
    highlights: [
      "ユニークな6角形変形リール",
      "720通りのペイライン",
      "左右両方向からのペイアウト",
      "フリースピン機能",
      "ワイルドシンボル",
      "スキャッターシンボル",
      "トライデントワイルド機能",
      "ディバイン機能",
      "ダイヤモンド収集機能",
      "追加フリースピン機能",
    ],
    watchouts: [
      "フリースピン突入までに時間がかかる場合がある",
      "一部カジノではRTPが低い場合がある",
    ],
  },
  featuredCasino: {
    name: "2upカジノ",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/reviews/2up",
    ctaText: "今すぐプレイ！",
    ctaHref: "https://casinotsu.com/reviews/2up",
    tagline: "仮想通貨でも日本円でもプレイ可能な、最新オンラインカジノです。",
  },
  casinos: [
    {
      name: "ReSpin（リスピン）",
      logo: "/assets/casino/respin.jpg",
      href: "https://casinotsu.com/reviews/respin",
      bonus: "300USDT",
      freeSpins: "200",
      wagering: "35倍",
      rating: 4,
      tagline: "10種類の主要な仮想通貨が利用可能なクリプトカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/respin",
    },
    {
      name: "Golden Panda（ゴールデンパンダ）",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30倍",
      rating: 4,
      tagline: "出金は原則として即時反映され、ストレスフリーなプレイが可能です♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/golden-panda",
    },
    {
      name: "2up（2アップ）",
      logo: "/images/casino/2up_375x375.png",
      href: "https://casinotsu.com/reviews/2up",
      rating: 4,
      tagline: "仮想通貨でも日本円でもプレイ可能な、最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/2up",
    },
    {
      name: "Miki（ミキ）",
      logo: "/assets/casino/miki.jpg",
      href: "https://casinotsu.com/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30倍",
      rating: 4,
      tagline: "充実したゲームラインナップと、お得なボーナスでプレイをお楽しみください！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/miki",
    },
    {
      name: "WSM Casino（WSMカジノ）",
      logo: "/images/casino/wsm-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wsm-casino",
      rating: 4,
      tagline: "「ミームコイン」と「オンラインカジノ」の融合、時代の最先端を体験！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wsm-casino",
    },
    {
      name: "Bitz（ビッツ）",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29倍",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性も高い最新仮想通貨カジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitz",
    },
    {
      name: "Wikibet（ウィキベット）",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://casinotsu.com/reviews/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20倍",
      rating: 4,
      tagline: "シンプルで可愛らしいデザインが特徴！厳選されたゲームをお楽しみください★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wikibet",
    },
    {
      name: "Katsuwin（カツウィン）",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://casinotsu.com/reviews/katsuwin",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新進気鋭のカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/katsuwin",
    },
    {
      name: "Sushi Casino（スシカジノ）",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35倍",
      rating: 4,
      tagline: "豊富なオファーとVIPプログラムが魅力の最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/sushi-casino",
    },
    {
      name: "Parimatch（パリマッチ）",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://casinotsu.com/reviews/parimatch",
      rating: 4,
      tagline: "2024年11月オープン！注目の最新オンラインカジノを徹底レビューしました。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/parimatch",
    },
    {
      name: "Duelbits（デュエルビッツ）",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://casinotsu.com/reviews/duelbits",
      rating: 4,
      tagline: "500フリースピンがお得なクリプトカジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/duelbits",
    },
    {
      name: "Sportsbet.io（スポーツベットアイオー）",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      rating: 4.5,
      tagline: "スポーツベットだけではありません！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/sportsbet-io",
    },
    {
      name: "Shuffle（シャッフル）",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4,
      tagline: "独自のトークンによる資産運用も可能な仮想通貨カジノです★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/shuffle",
    },
    {
      name: "Winz（ウィンズ）",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件がありません♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/winz-io",
    },
    {
      name: "Dafabet（ダファベット）",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "セルティックFCのスポンサーを務めるカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/dafabet",
    },
    {
      name: "Lucky Block（ラッキーブロック）",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "50",
      freeSpins: "50",
      wagering: "35倍",
      rating: 4,
      tagline: "独自トークンも提供する仮想通貨カジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/lucky-block",
    },
    {
      name: "Ramenbet（ラーメンベット）",
      logo: "/images/casino/ramenbet_375x375-1.png",
      href: "https://casinotsu.com/reviews/ramenbet",
      rating: 4,
      tagline: "スロット、ライブカジノ、スポーツベットまで、全てが充実しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/ramenbet",
    },
    {
      name: "Flush Casino（フラッシュカジノ）",
      logo: "/images/casino/Flush_375x375-1.png",
      href: "https://casinotsu.com/reviews/flush",
      rating: 4,
      tagline: "今年、特に注目されているクリプトカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/flush",
    },
    {
      name: "Queen Casino（クイーンカジノ）",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30倍",
      rating: 4.5,
      tagline: "アジア市場で最も知名度の高いオンラインカジノとして君臨しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/queen-casino",
    },
    {
      name: "Roobet（ルーベット）",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "世界的な有名人がアンバサダーを務めるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/roobet",
    },
    {
      name: "Casino Sky（カジノスカイ）",
      logo: "/images/casino/casinosky_375x375.png",
      href: "https://casinotsu.com/reviews/casino-sky",
      rating: 4,
      tagline: "日本のオンラインカジノ業界プロフェッショナルが運営する、期待のカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-sky",
    },
    {
      name: "Mega Dice（メガダイス）",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35倍",
      rating: 3.5,
      tagline: "ボーナス最大1BTC！仮想通貨カジノをお楽しみください。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/mega-dice",
    },
    {
      name: "Cosmoswin（コスモスウィン）",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "https://casinotsu.com/reviews/cosmoswin",
      bonus: "$10,000",
      freeSpins: "-",
      rating: 4,
      tagline: "可愛いキャラクターがお出迎え！ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/cosmoswin",
    },
    {
      name: "BC.Game（ビーシーゲーム）",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45倍",
      rating: 4,
      tagline: "圧巻のゲーム数と、最大1,600ドルの初回入金ボーナスが魅力です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bc-game",
    },
    {
      name: "Stake（ステーク）",
      logo: "/images/casino/stake_375x375-1.png",
      href: "https://casinotsu.com/reviews/stake",
      rating: 4,
      tagline: "ハウスエッジ5%のレーキバックとVIP特典は非常にお得です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/stake",
    },
    {
      name: "Wonder Casino（ワンダーカジノ）",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wonder-casino",
      rating: 4.5,
      tagline: "業界最速の出金スピードと、仮想通貨に特化したボーナスが魅力です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wonder-casino",
    },
    {
      name: "K8（ケイスロット）",
      logo: "/assets/casino/k8.jpg",
      href: "https://casinotsu.com/reviews/k8",
      bonus: "$1,840",
      freeSpins: "288",
      wagering: "25倍",
      rating: 4.5,
      tagline: "日本で人気の実機をプレイするなら、K8のカジノで決まり！懐かしい台で熱くなりましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/k8",
    },
    {
      name: "OhMySpins（オーマイ スピンズ）",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35倍",
      rating: 4,
      tagline: "マニアックなプロバイダーもお探しなら、ぜひこちらで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/ohmyspins",
    },
    {
      name: "Yuugado（ユーガド）",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "https://casinotsu.com/reviews/yuugado",
      rating: 4.5,
      tagline: "「和」をテーマにしたオンラインカジノ。パチンコからスポーツベットまで幅広く楽しめます！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/yuugado",
    },
    {
      name: "Tedbet（テドベット）",
      logo: "/images/casino/tedbet_375x375.png",
      href: "https://casinotsu.com/reviews/tedbet",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいカジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/tedbet",
    },
    {
      name: "BetRebels（ベットレベルス）",
      logo: "/images/casino/betrebels_375x375.png",
      href: "https://casinotsu.com/reviews/betrebels",
      rating: 4,
      tagline: "スポーツファン必見！カジノゲームも続々充実中です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/betrebels",
    },
    {
      name: "Conquestador（コンクエストアドアー）",
      logo: "/images/casino/Conquestador_375x375.png",
      href: "https://casinotsu.com/reviews/conquestador",
      rating: 4,
      tagline: "検索機能が優秀！お好みのゲームを素早く見つけることができます。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/conquestador",
    },
    {
      name: "Cloudbet（クラウドベット）",
      logo: "/assets/casino/cloudbet.jpg",
      href: "https://casinotsu.com/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: "-",
      rating: 4,
      tagline: "入出金額の上限なし！仮想通貨ハイローラーの皆様必見です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/cloudbet",
    },
    {
      name: "Livecasino.io（ライブカジノアイオー）",
      logo: "/images/casino/livecasinoio.jpg",
      href: "https://casinotsu.com/reviews/livecasino-io",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "ライブカジノと仮想通貨、モダンな体験はいかがでしょうか？",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/livecasino-io",
    },
    {
      name: "Lucky Bull（ラッキーブル）",
      logo: "/assets/casino/lucky-bull.jpg",
      href: "https://casinotsu.com/reviews/lucky-bull",
      bonus: "$917",
      freeSpins: "-",
      wagering: "30倍",
      rating: 4,
      tagline: "キャラクターと共にラッキーブルの世界でクエストを攻略しましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/lucky-bull",
    },
    {
      name: "Gamdom（ガンダムカジノ）",
      logo: "/assets/casino/gamdom.jpg",
      href: "https://casinotsu.com/reviews/gamdom",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "ハイローラープレイヤーに最適な、最強のレーキバックカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/gamdom",
    },
    {
      name: "Energy Casino（エナジースカジノ）",
      logo: "/images/casino/energy-casino_375x375.png",
      href: "https://casinotsu.com/reviews/energy-casino",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/energy-casino",
    },
    {
      name: "Konibet（コニベット）",
      logo: "/images/casino/konibet_375x375.png",
      href: "https://casinotsu.com/reviews/konibet",
      rating: 4.5,
      tagline: "パチンコ・パチスロも楽しめるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/konibet",
    },
    {
      name: "Vulkan Vegas（バルカンベガス）",
      logo: "/assets/casino/vulkan-vegas.jpg",
      href: "https://casinotsu.com/reviews/vulkanvegas",
      bonus: "¥100,000",
      freeSpins: "125",
      wagering: "40倍",
      rating: 4,
      tagline: "アメコミの世界観に没頭しましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/vulkanvegas",
    },
    {
      name: "Casino Me（カジノミー）",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20倍",
      rating: 4,
      tagline: "独自のシステムによるお得なキャッシュバックをご用意しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-me",
    },
    {
      name: "Mystino（ミスティーノ）",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://casinotsu.com/reviews/mystino",
      rating: 4.5,
      tagline: "日本人プレイヤーの心を掴むカジノといえば、やはりミスティーノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/mystino",
    },
    {
      name: "Trustdice（トラストダイス）",
      logo: "/images/casino/Trustdice_375x375.png",
      href: "https://casinotsu.com/reviews/trustdice",
      rating: 4,
      tagline: "賭けて遊んで、さらに資産運用もできるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/trustdice",
    },
    {
      name: "InterCasino（インターカジノ）",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://casinotsu.com/reviews/inter-casino",
      rating: 4.5,
      tagline: "20年以上の歴史を持つ、信頼と実績のカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/inter-casino",
    },
    {
      name: "Empire777（エンパイア777）",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "アジアNo.1を誇るオンラインカジノはここです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/empire777",
    },
    {
      name: "Pinnacle（ピナクル）",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://casinotsu.com/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      rating: 3.5,
      tagline: "カジノゲームもスポーツベットも楽しめるハイブリッドカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/pinnacle",
    },
    {
      name: "Justspin（ジャストスピン）",
      logo: "/assets/casino/justspin.jpg",
      href: "https://casinotsu.com/reviews/just-spin",
      bonus: "$500",
      freeSpins: "600",
      wagering: "50倍",
      rating: 4,
      tagline: "シンプルで分かりやすいプラットフォームが魅力です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/just-spin",
    },
    {
      name: "WinUnique（ウィンユニーク）",
      logo: "/assets/casino/winunique.jpg",
      href: "https://casinotsu.com/reviews/winunique",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30倍",
      rating: 4,
      tagline: "キラキラ輝く金色招き猫が勝利を運んでくれるかもしれません？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/winunique",
    },
    {
      name: "21.com（トゥエンティワン・ドットコム）",
      logo: "/assets/casino/21com.jpg",
      href: "https://casinotsu.com/reviews/21-com",
      bonus: "$1,000",
      freeSpins: "1000",
      wagering: "50倍",
      rating: 4,
      tagline: "シンプルな構造と使いやすい検索機能が特徴です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/21-com",
    },
    {
      name: "BitStarz（ビットスターズ）",
      logo: "/images/casino/bitstarz_375x375.png",
      href: "https://casinotsu.com/reviews/bitstarz",
      rating: 4.5,
      tagline: "複数通貨に対応したマルチウォレットが便利です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitstarz",
    },
    {
      name: "Joy Casino（ジョイカジノ）",
      logo: "/images/casino/joycasino_375x375.png",
      href: "https://casinotsu.com/reviews/joycasino",
      rating: 4.5,
      tagline: "ジョイカジノの豪華なボーナスをぜひゲットしてください！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/joycasino",
    },
    {
      name: "Casino Secret（カジノシークレット）",
      logo: "/assets/casinos/casino-secret_375x375.png",
      href: "https://casinotsu.com/reviews/casino-secret",
      rating: 4.5,
      tagline: "キャッシュバックといえば、カジノシークレットで決まりです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-secret",
    },
    {
      name: "Vera&John（ベラジョン）",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://casinotsu.com/reviews/vera-john",
      rating: 4.5,
      tagline: "オンラインカジノといえば、やはりベラジョンが外せません！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/vera-john",
    },
    {
      name: "Live Casino House（ライブカジノハウス）",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://casinotsu.com/reviews/live-casino-house",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "ライブカジノをはじめ、多様なゲームが楽しめるお馴染みのカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io（ビットカジノアイオー）",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノとして、長年の信頼を誇ります！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitcasino-io",
    },
    {
      name: "Casino-X（カジノエックス）",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://casinotsu.com/reviews/casino-x",
      rating: 4.5,
      tagline: "豪華なボーナスが満載のカジノエックスで、お得にプレイしましょう♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-x",
    },
    {
      name: "Casitabi（カシタビ）",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20倍",
      rating: 4.5,
      tagline: "RPG型カジノで、旅をしながらボスを倒してお得にプレイできます！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casitabi",
    },
    {
      name: "Eldoah Casino（エルドアカジノ）",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://casinotsu.com/reviews/eldoah",
      rating: 4.5,
      tagline: "ライブカジノの利用満足度において、6年連続ナンバー1を誇るオンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/eldoah",
    },
    {
      name: "ReSpin（リスピン）",
      logo: "/assets/casino/respin.jpg",
      href: "https://casinotsu.com/reviews/respin",
      bonus: "300USDT",
      freeSpins: "200",
      wagering: "35倍",
      rating: 4,
      tagline: "10種類の主要な仮想通貨が利用可能なクリプトカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/respin",
    },
    {
      name: "Golden Panda（ゴールデンパンダ）",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30倍",
      rating: 4,
      tagline: "出金は原則として即時反映され、ストレスフリーなプレイが可能です♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/golden-panda",
    },
    {
      name: "2up（2アップ）",
      logo: "/images/casino/2up_375x375.png",
      href: "https://casinotsu.com/reviews/2up",
      rating: 4,
      tagline: "仮想通貨でも日本円でもプレイ可能な、最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/2up",
    },
    {
      name: "Miki（ミキ）",
      logo: "/assets/casino/miki.jpg",
      href: "https://casinotsu.com/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30倍",
      rating: 4,
      tagline: "充実したゲームラインナップと、お得なボーナスでプレイをお楽しみください！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/miki",
    },
    {
      name: "WSM Casino（WSMカジノ）",
      logo: "/images/casino/wsm-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wsm-casino",
      rating: 4,
      tagline: "「ミームコイン」と「オンラインカジノ」の融合、時代の最先端を体験！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wsm-casino",
    },
    {
      name: "Bitz（ビッツ）",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29倍",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性も高い最新仮想通貨カジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitz",
    },
    {
      name: "Wikibet（ウィキベット）",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://casinotsu.com/reviews/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20倍",
      rating: 4,
      tagline: "シンプルで可愛らしいデザインが特徴！厳選されたゲームをお楽しみください★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wikibet",
    },
    {
      name: "Katsuwin（カツウィン）",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://casinotsu.com/reviews/katsuwin",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新進気鋭のカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/katsuwin",
    },
    {
      name: "Sushi Casino（スシカジノ）",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35倍",
      rating: 4,
      tagline: "豊富なオファーとVIPプログラムが魅力の最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/sushi-casino",
    },
    {
      name: "Parimatch（パリマッチ）",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://casinotsu.com/reviews/parimatch",
      rating: 4,
      tagline: "2024年11月オープン！注目の最新オンラインカジノを徹底レビューしました。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/parimatch",
    },
    {
      name: "Duelbits（デュエルビッツ）",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://casinotsu.com/reviews/duelbits",
      rating: 4,
      tagline: "500フリースピンがお得なクリプトカジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/duelbits",
    },
    {
      name: "Sportsbet.io（スポーツベットアイオー）",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      rating: 4.5,
      tagline: "スポーツベットだけではありません！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/sportsbet-io",
    },
    {
      name: "Shuffle（シャッフル）",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4,
      tagline: "独自のトークンによる資産運用も可能な仮想通貨カジノです★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/shuffle",
    },
    {
      name: "Winz（ウィンズ）",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件がありません♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/winz-io",
    },
    {
      name: "Dafabet（ダファベット）",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "セルティックFCのスポンサーを務めるカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/dafabet",
    },
    {
      name: "Lucky Block（ラッキーブロック）",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "50",
      freeSpins: "50",
      wagering: "35倍",
      rating: 4,
      tagline: "独自トークンも提供する仮想通貨カジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/lucky-block",
    },
    {
      name: "Ramenbet（ラーメンベット）",
      logo: "/images/casino/ramenbet_375x375-1.png",
      href: "https://casinotsu.com/reviews/ramenbet",
      rating: 4,
      tagline: "スロット、ライブカジノ、スポーツベットまで、全てが充実しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/ramenbet",
    },
    {
      name: "Flush Casino（フラッシュカジノ）",
      logo: "/images/casino/Flush_375x375-1.png",
      href: "https://casinotsu.com/reviews/flush",
      rating: 4,
      tagline: "今年、特に注目されているクリプトカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/flush",
    },
    {
      name: "Queen Casino（クイーンカジノ）",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30倍",
      rating: 4.5,
      tagline: "アジア市場で最も知名度の高いオンラインカジノとして君臨しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/queen-casino",
    },
    {
      name: "Roobet（ルーベット）",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "世界的な有名人がアンバサダーを務めるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/roobet",
    },
    {
      name: "Casino Sky（カジノスカイ）",
      logo: "/images/casino/casinosky_375x375.png",
      href: "https://casinotsu.com/reviews/casino-sky",
      rating: 4,
      tagline: "日本のオンラインカジノ業界プロフェッショナルが運営する、期待のカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-sky",
    },
    {
      name: "Mega Dice（メガダイス）",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35倍",
      rating: 3.5,
      tagline: "ボーナス最大1BTC！仮想通貨カジノをお楽しみください。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/mega-dice",
    },
    {
      name: "Cosmoswin（コスモスウィン）",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "https://casinotsu.com/reviews/cosmoswin",
      bonus: "$10,000",
      freeSpins: "-",
      rating: 4,
      tagline: "可愛いキャラクターがお出迎え！ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/cosmoswin",
    },
    {
      name: "BC.Game（ビーシーゲーム）",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45倍",
      rating: 4,
      tagline: "圧巻のゲーム数と、最大1,600ドルの初回入金ボーナスが魅力です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bc-game",
    },
    {
      name: "Stake（ステーク）",
      logo: "/images/casino/stake_375x375-1.png",
      href: "https://casinotsu.com/reviews/stake",
      rating: 4,
      tagline: "ハウスエッジ5%のレーキバックとVIP特典は非常にお得です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/stake",
    },
    {
      name: "Wonder Casino（ワンダーカジノ）",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wonder-casino",
      rating: 4.5,
      tagline: "業界最速の出金スピードと、仮想通貨に特化したボーナスが魅力です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wonder-casino",
    },
    {
      name: "K8（ケイスロット）",
      logo: "/assets/casino/k8.jpg",
      href: "https://casinotsu.com/reviews/k8",
      bonus: "$1,840",
      freeSpins: "288",
      wagering: "25倍",
      rating: 4.5,
      tagline: "日本で人気の実機をプレイするなら、K8のカジノで決まり！懐かしい台で熱くなりましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/k8",
    },
    {
      name: "OhMySpins（オーマイ スピンズ）",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35倍",
      rating: 4,
      tagline: "マニアックなプロバイダーもお探しなら、ぜひこちらで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/ohmyspins",
    },
    {
      name: "Yuugado（ユーガド）",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "https://casinotsu.com/reviews/yuugado",
      rating: 4.5,
      tagline: "「和」をテーマにしたオンラインカジノ。パチンコからスポーツベットまで幅広く楽しめます！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/yuugado",
    },
    {
      name: "Tedbet（テドベット）",
      logo: "/images/casino/tedbet_375x375.png",
      href: "https://casinotsu.com/reviews/tedbet",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいカジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/tedbet",
    },
    {
      name: "BetRebels（ベットレベルス）",
      logo: "/images/casino/betrebels_375x375.png",
      href: "https://casinotsu.com/reviews/betrebels",
      rating: 4,
      tagline: "スポーツファン必見！カジノゲームも続々充実中です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/betrebels",
    },
    {
      name: "Conquestador（コンクエストアドアー）",
      logo: "/images/casino/Conquestador_375x375.png",
      href: "https://casinotsu.com/reviews/conquestador",
      rating: 4,
      tagline: "検索機能が優秀！お好みのゲームを素早く見つけることができます。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/conquestador",
    },
    {
      name: "Cloudbet（クラウドベット）",
      logo: "/assets/casino/cloudbet.jpg",
      href: "https://casinotsu.com/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: "-",
      rating: 4,
      tagline: "入出金額の上限なし！仮想通貨ハイローラーの皆様必見です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/cloudbet",
    },
    {
      name: "Livecasino.io（ライブカジノアイオー）",
      logo: "/images/casino/livecasinoio.jpg",
      href: "https://casinotsu.com/reviews/livecasino-io",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "ライブカジノと仮想通貨、モダンな体験はいかがでしょうか？",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/livecasino-io",
    },
    {
      name: "Lucky Bull（ラッキーブル）",
      logo: "/assets/casino/lucky-bull.jpg",
      href: "https://casinotsu.com/reviews/lucky-bull",
      bonus: "$917",
      freeSpins: "-",
      wagering: "30倍",
      rating: 4,
      tagline: "キャラクターと共にラッキーブルの世界でクエストを攻略しましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/lucky-bull",
    },
    {
      name: "Gamdom（ガンダムカジノ）",
      logo: "/assets/casino/gamdom.jpg",
      href: "https://casinotsu.com/reviews/gamdom",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "ハイローラープレイヤーに最適な、最強のレーキバックカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/gamdom",
    },
    {
      name: "Energy Casino（エナジースカジノ）",
      logo: "/images/casino/energy-casino_375x375.png",
      href: "https://casinotsu.com/reviews/energy-casino",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/energy-casino",
    },
    {
      name: "Konibet（コニベット）",
      logo: "/images/casino/konibet_375x375.png",
      href: "https://casinotsu.com/reviews/konibet",
      rating: 4.5,
      tagline: "パチンコ・パチスロも楽しめるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/konibet",
    },
    {
      name: "Vulkan Vegas（バルカンベガス）",
      logo: "/assets/casino/vulkan-vegas.jpg",
      href: "https://casinotsu.com/reviews/vulkanvegas",
      bonus: "¥100,000",
      freeSpins: "125",
      wagering: "40倍",
      rating: 4,
      tagline: "アメコミの世界観に没頭しましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/vulkanvegas",
    },
    {
      name: "Casino Me（カジノミー）",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20倍",
      rating: 4,
      tagline: "独自のシステムによるお得なキャッシュバックをご用意しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-me",
    },
    {
      name: "Mystino（ミスティーノ）",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://casinotsu.com/reviews/mystino",
      rating: 4.5,
      tagline: "日本人プレイヤーの心を掴むカジノといえば、やはりミスティーノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/mystino",
    },
    {
      name: "Trustdice（トラストダイス）",
      logo: "/images/casino/Trustdice_375x375.png",
      href: "https://casinotsu.com/reviews/trustdice",
      rating: 4,
      tagline: "賭けて遊んで、さらに資産運用もできるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/trustdice",
    },
    {
      name: "InterCasino（インターカジノ）",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://casinotsu.com/reviews/inter-casino",
      rating: 4.5,
      tagline: "20年以上の歴史を持つ、信頼と実績のカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/inter-casino",
    },
    {
      name: "Empire777（エンパイア777）",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "アジアNo.1を誇るオンラインカジノはここです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/empire777",
    },
    {
      name: "Pinnacle（ピナクル）",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://casinotsu.com/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      rating: 3.5,
      tagline: "カジノゲームもスポーツベットも楽しめるハイブリッドカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/pinnacle",
    },
    {
      name: "Justspin（ジャストスピン）",
      logo: "/assets/casino/justspin.jpg",
      href: "https://casinotsu.com/reviews/just-spin",
      bonus: "$500",
      freeSpins: "600",
      wagering: "50倍",
      rating: 4,
      tagline: "シンプルで分かりやすいプラットフォームが魅力です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/just-spin",
    },
    {
      name: "WinUnique（ウィンユニーク）",
      logo: "/assets/casino/winunique.jpg",
      href: "https://casinotsu.com/reviews/winunique",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30倍",
      rating: 4,
      tagline: "キラキラ輝く金色招き猫が勝利を運んでくれるかもしれません？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/winunique",
    },
    {
      name: "21.com（トゥエンティワン・ドットコム）",
      logo: "/assets/casino/21com.jpg",
      href: "https://casinotsu.com/reviews/21-com",
      bonus: "$1,000",
      freeSpins: "1000",
      wagering: "50倍",
      rating: 4,
      tagline: "シンプルな構造と使いやすい検索機能が特徴です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/21-com",
    },
    {
      name: "BitStarz（ビットスターズ）",
      logo: "/images/casino/bitstarz_375x375.png",
      href: "https://casinotsu.com/reviews/bitstarz",
      rating: 4.5,
      tagline: "複数通貨に対応したマルチウォレットが便利です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitstarz",
    },
    {
      name: "Joy Casino（ジョイカジノ）",
      logo: "/images/casino/joycasino_375x375.png",
      href: "https://casinotsu.com/reviews/joycasino",
      rating: 4.5,
      tagline: "ジョイカジノの豪華なボーナスをぜひゲットしてください！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/joycasino",
    },
    {
      name: "Casino Secret（カジノシークレット）",
      logo: "/assets/casinos/casino-secret_375x375.png",
      href: "https://casinotsu.com/reviews/casino-secret",
      rating: 4.5,
      tagline: "キャッシュバックといえば、カジノシークレットで決まりです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-secret",
    },
    {
      name: "Vera&John（ベラジョン）",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://casinotsu.com/reviews/vera-john",
      rating: 4.5,
      tagline: "オンラインカジノといえば、やはりベラジョンが外せません！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/vera-john",
    },
    {
      name: "Live Casino House（ライブカジノハウス）",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://casinotsu.com/reviews/live-casino-house",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "ライブカジノをはじめ、多様なゲームが楽しめるお馴染みのカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io（ビットカジノアイオー）",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノとして、長年の信頼を誇ります！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitcasino-io",
    },
    {
      name: "Casino-X（カジノエックス）",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://casinotsu.com/reviews/casino-x",
      rating: 4.5,
      tagline: "豪華なボーナスが満載のカジノエックスで、お得にプレイしましょう♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-x",
    },
    {
      name: "Casitabi（カシタビ）",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20倍",
      rating: 4.5,
      tagline: "RPG型カジノで、旅をしながらボスを倒してお得にプレイできます！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casitabi",
    },
    {
      name: "Eldoah Casino（エルドアカジノ）",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://casinotsu.com/reviews/eldoah",
      rating: 4.5,
      tagline: "ライブカジノの利用満足度において、6年連続ナンバー1を誇るオンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/eldoah",
    },
  ],
  gameInfo: {
    intro: "美しいマーメイドが、プレイヤーを神秘的な海中世界へと誘います。カラフルな宝石や貝殻が散りばめられた水中には、ひときわ輝くダイヤモンドが隠されています。これはPlay’n GO社がお届けする、マーメイドテーマのスロットです。数あるマーメイドテーマのスロットの中でも、このゲームは近年人気を集めている6角形変形リールを採用しており、ペイラインはなんと720通り！Play’n GO社は爆発力のある機種が多いことで知られていますが、このスロットの実力は如何ほどでしょうか。CasinoTsuが詳細に検証いたします。",
    basicInfo: {
      rtp: "96.5%",
      volatility: "Medium",
      reels: "6角形変形リール (3-4-5-4-3)",
      paylines: "720通り (左右両方向からのペイアウトに対応)",
      minBet: "$0.20",
      maxBet: "$100",
      provider: "Play’n GO",
      releaseDate: "2017-09-19",
    },
  },
  payoutTable: {
    title: "シンボル別配当",
    symbols: [
      {
        name: "ダイヤモンド",
        description: "最高配当シンボル",
        payout5: "10.00",
        payout4: "2.00",
        payout3: "1.00",
        isSpecial: false,
      },
      {
        name: "ルビー",
        payout5: "2.50",
        payout4: "1.25",
        payout3: "0.50",
        isSpecial: false,
      },
      {
        name: "サファイヤ",
        payout5: "1.50",
        payout4: "0.75",
        payout3: "0.30",
        isSpecial: false,
      },
      {
        name: "エメラルド",
        payout5: "1.00",
        payout4: "0.50",
        payout3: "0.20",
        isSpecial: false,
      },
      {
        name: "エイ",
        payout5: "0.75",
        payout4: "0.40",
        payout3: "0.15",
        isSpecial: false,
      },
      {
        name: "ヒトデ",
        payout5: "0.75",
        payout4: "0.40",
        payout3: "0.15",
        isSpecial: false,
      },
      {
        name: "イカ",
        payout5: "0.50",
        payout4: "0.25",
        payout3: "0.10",
        isSpecial: false,
      },
      {
        name: "貝殻",
        payout5: "0.50",
        payout4: "0.25",
        payout3: "0.10",
        isSpecial: false,
      },
    ],
    maxPayout: "x5,000",
    notes: [
      "以下の配当表は、1ドルベット時のものです。",
      "マーメイドはワイルドシンボルとして機能し、スキャッター以外のすべてのシンボルの代わりになります。",
      "宝箱はスキャッターシンボルで、フリースピン機能をトリガーします。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "多様なペイライン",
        description: "この5リールビデオスロットは、720ものペイラインを備えています。さらに、ペイアウトは左から右だけでなく、右から左への両方向で計算されるため、勝利のチャンスが広がります。",
        icon: undefined,
      },
      {
        name: "ゲームプレイの特性",
        description: "特徴的な機能の出現には、ある程度の忍耐が必要となる場合があります。しかし、フリースピンラウンドでの「爆発力」は特筆すべきもので、高額配当の可能性を秘めています。",
        icon: undefined,
      },
      {
        name: "コイン持ち",
        description: "一般的に高ボラティリティのスロットはコイン持ちが悪い傾向がありますが、マーメイド・ダイヤモンドは「悪くない」と評価されており、比較的長くプレイを楽しめる可能性があります。",
        icon: undefined,
      },
      {
        name: "スキャッターシンボル",
        description: "宝箱がスキャッターシンボルです。リール上に5つの宝箱が出現すると、フリースピン機能に突入します。宝箱は5つあり、その中から1つを選ぶことで、10回、15回、または25回のフリースピン回数が決定されます。",
        icon: "/images/screen-shot-2017-09-08-at-13-39-46_182x163.jpg",
      },
      {
        name: "ワイルドシンボル",
        description: "マーメイドがワイルドシンボルです。スキャッターシンボルを除く、他のすべてのシンボルの代わりとなり、勝利の組み合わせを形成するのに役立ちます。",
        icon: "/images/screen-shot-2017-09-08-at-13-40-10_180x112.jpg",
      },
      {
        name: "トライデントワイルド機能",
        description: "この機能は、基本ゲーム中にランダムで発動します。リールが回転している間に、1つまたは2つのリールにワイルドシンボルが追加されることがあります。ただし、この機能が必ず勝利を保証するわけではありません。",
        icon: "/images/screen-shot-2017-09-08-at-13-40-35_121x351.jpg",
      },
      {
        name: "ディバイン機能（神の介入機能）",
        description: "基本ゲームで4つのスキャッターが出現し、かつ勝利とならなかった場合に、この機能が発動する可能性があります。これにより、フリースピン機能をトリガーするために必要な5つ目のスキャッターが出現するチャンスが生まれます。この機能は基本ゲームでのみ有効です。",
        icon: undefined,
      },
      {
        name: "フリースピン中の機能",
        description: "フリースピン機能が起動すると、輝くダイヤモンドのシンボルに注目しましょう！\n- ダイヤモンド収集: フリースピン中にダイヤモンドシンボルを5つ集めると、「トライデントワイルド機能」が発動し、勝利の組み合わせを形成しやすくなります。このダイヤモンド収集は、フリースピン中に複数回にわたって蓄積され、機能終了時にリセットされます。\n- 追加フリースピン: フリースピン中にスキャッターシンボルが3つ、4つ、または5つ出現すると、それぞれ3回、4回、または5回の追加フリースピンが付与されます。これにより、さらに大きな勝利のチャンスが生まれます。\n- トライデントワイルド機能の強化: フリースピン中にダイヤモンドを5つ集めると、「トライデントワイルド機能」が確実に発動し、勝利に貢献します。この機能は、1回のフリースピンセッション中に複数回トリガーされる可能性があります。",
        icon: undefined,
      },
    ],
  },
  sections: [
    {
      heading: "グラフィック・サウンド",
      paragraphs: ["Play’n GOの真骨頂ともいえる、鮮やかで美しいグラフィックが魅力です。マーメイドや宝石、貝殻などのシンボルは細部まで丁寧に描かれており、まるで美しい水中世界にいるかのような没入感を与えてくれます。特に、6角形変形リールというユニークな構成が、視覚的な面白さをさらに引き立てています。 CasinoTsuは、その美しさを高く評価いたします。"],
      bullets: ["★★★★★ (グラフィック)"],
    },
    {
      heading: "グラフィック",
      paragraphs: ["Play’n GOの真骨頂ともいえる、鮮やかで美しいグラフィックが魅力です。マーメイドや宝石、貝殻などのシンボルは細部まで丁寧に描かれており、まるで美しい水中世界にいるかのような没入感を与えてくれます。特に、6角形変形リールというユニークな構成が、視覚的な面白さをさらに引き立てています。 CasinoTsuは、その美しさを高く評価いたします。"],
      bullets: ["★★★★★"],
    },
    {
      heading: "サウンド",
      paragraphs: ["ゲームのテーマに合わせた、幻想的なサウンドが流れます。水中を思わせる心地よいBGMと、勝利時などに流れるダイナミックなオーケストラ調のサウンドが、ゲームプレイを一層盛り上げてくれます。効果音も適切に配置されており、プレイ体験を豊かにしています。"],
      bullets: ["★★★★★"],
    },
    {
      heading: "スペック詳細",
      table: {
        columns: ["", ""],
        rows: [
          ["リール数", "5"],
          ["ベットコイン数", "20 (固定)"],
          ["ペイライン", "720ライン (固定、左右両方向有効)"],
          ["コインバリュー", "0.01 ～ 5.00"],
          ["ベット幅", "$0.20 ～ $100.00"],
          ["RTP（返還率）", "96.50%"],
        ],
      },
      notes: ["CasinoTsuは、これらの情報を正確に確認しております。"],
    },
    {
      heading: "モバイル対応",
      paragraphs: ["マーメイド・ダイヤモンドはHTML5技術で開発されており、スマートフォンやタブレットなどのモバイルデバイスに完全対応しています。特別なアプリのダウンロードは不要で、お使いのカジノサイトにアクセスすれば、ブラウザ上で直接ゲームをプレイできます。外出先でも、PCと同じように美しいグラフィックとサウンド、そしてユニークなゲーム体験をお楽しみいただけます。"],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "フリースピンの選択",
        "フリースピン機能に突入したら、5つの宝箱から1つを選ぶことになります。選択肢は10回、15回、25回のフリースピンですが、それぞれの選択がゲーム展開に影響を与えます。\n*   少ないフリースピン（10回）: より高い倍率のシンボルが出現しやすい傾向があるかもしれません。短時間で大きな勝利を狙いたいプレイヤー向けです。\n*   多いフリースピン（15回または25回）: より多くのスピン機会を得られます。じっくりとプレイし、ダイヤモンド収集や追加フリースピンのトリガーを狙いたいプレイヤーに適しています。\nご自身のプレイスタイルに合わせて、最適な宝箱を選んでみてください。",
        "ダイヤモンド収集の活用",
        "フリースピン中は、ダイヤモンドシンボルを集めることが勝利への鍵となります。5つ集めるごとに「トライデントワイルド機能」が発動し、勝利の組み合わせを作りやすくなります。フリースピン回数に余裕がある場合は、積極的にダイヤモンド収集を狙いましょう。",
        "RTPとボラティリティの理解",
        "RTP（還元率）が96.5%と高めであり、ボラティリティも「中程度」であるため、極端に資金が減りやすいわけではありませんが、Play’n GOのスロットらしく、フリースピン機能での爆発力が期待できます。一回のスピンで大きな勝利が出るというよりは、ボーナスラウンドでの一撃に期待するゲーム性と言えます。 CasinoTsu は、[正確さが第一。興奮はその次。](https://casinotsu.com/about)をモットーに、これらの情報を提供しております。",
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "マーメイド・ダイヤモンドは、美しいグラフィックとサウンド、そしてユニークな6角形変形リール、720通りのペイラインが特徴のスロットです。Play’n GOらしい爆発力のあるフリースピン機能と、ダイヤモンド収集によるワイルドシンボルの追加、さらには追加フリースピンの可能性も秘めており、一度フリースピンが起動すれば大きな勝利が期待できます。",
        "RTPも96.5%と良好で、ボラティリティも「中程度」であることから、安定したプレイと爆発力の両方を楽しみたいプレイヤーにおすすめです。変形リールや独特のボーナス機能に魅力を感じる方、そして美しいマーメイドの世界に癒されたい方に、ぜひ一度プレイしてみていただきたいスロットです。 CasinoTsu 推薦です。",
      ],
    },
    {
      heading: "・勝手に評価！",
      paragraphs: [
        "★★★★★ ー 総合評価 5 / 5段階評価",
        "CasinoTsu は、常に正確な情報と、プレイヤーの皆様が安心できる環境を提供することを目指しております。",
      ],
      bullets: [
        "グラフィック: ★★★★★ ー 綺麗ですねー。Play’n GOの細かなグラフィックが冴えています。 CasinoTsu もこの点を高く評価いたします。",
        "サウンド: ★★★★★ ー 水中にいるかのようなサウンドですが、Play’n GOがよく使うオーケストラ調のサウンドがダイナミックさを醸し出しています！ CasinoTsu もこの臨場感を評価します。",
        "面白さ: ★★★★★ ー 一味違った変形リールが面白い。なかなか楽しめました。 CasinoTsu もユニークなゲーム性に魅力を感じています。",
        "賞金獲得: ★★★★★ ー コイン持ちは「悪くない」ですが、フリースピンで爆発する機種です。フリースピンボーナスは興奮します！ CasinoTsu では、興奮はその次。正確さが第一、を心がけておりますが、この機種の魅力は十分に伝わります。",
      ],
    },
  ],
  similarGames: [
    {
      name: "Mermaid Millions",
      provider: "Microgaming",
      description: "古典的なマーメイドテーマのスロット。",
    },
    {
      name: "Mystic Mermaid",
      provider: "Aristocrat",
      description: "幻想的な雰囲気を持つマーメイドスロット。",
    },
    {
      name: "Book of Dead",
      provider: "Play’n GO",
      href: "https://casinotsu.com/slots/book-of-dead",
      description: "エジプト冒険テーマの定番スロット。",
    },
    {
      name: "Moon Princess",
      provider: "Play’n GO",
      description: "美少女キャラクターが登場する人気のスロット。",
    },
    {
      name: "Reactoonz",
      provider: "Play’n GO",
      description: "ユニークな連鎖システムが特徴のエイリアンスロット。",
    },
  ],
  prosCons: {
    pros: [
      "美しいグラフィックとサウンド",
      "ユニークな6角形変形リール",
      "720通りのペイライン（左右両方向有効）",
      "Play’n GOらしい爆発力のあるフリースピン機能",
      "ダイヤモンド収集によるワイルドシンボル追加",
      "追加フリースピンの可能性",
      "RTP 96.5%と良好",
      "ボラティリティは中程度で比較的安定",
    ],
    cons: [
      "フリースピン突入までに時間がかかる場合がある",
      "一部カジノではRTPが低い場合がある",
    ],
  },
  faq: [
    {
      q: "Mermaid’s Diamondはどのプロバイダーからリリースされましたか？",
      a: "Play’n GO社です。 CasinoTsu は、このプロバイダーの信頼性を確認済みです。",
    },
    {
      q: "Mermaid’s Diamondの還元率は？",
      a: "96.50% です。ただし、一部のカジノでは94.45%のRTPが提供されている場合もありますので、プレイ前に CasinoTsu が提供する各カジノの情報をご確認いただくことを強く推奨いたします。正確さが第一です。",
    },
  ],
  breadcrumbs: [
    { label: "ホーム", href: "https://casinotsu.com/" },
    { label: "スロット", href: "https://casinotsu.com/slots" },
    { label: "マーメイド・ダイヤモンド", href: "https://casinotsu.com/slots/mermaids-diamond" },
  ],
  tableOfContents: [
    { label: "Mermaid's Diamond 基本情報", href: "#mermaids-diamond-基本情報" },
    { label: "ゲーム特徴・フィーチャー", href: "#ゲーム特徴・フィーチャー" },
    { label: "プロバイダー情報", href: "#プロバイダー情報" },
    { label: "グラフィック・サウンド", href: "#グラフィック・サウンド" },
    { label: "ペイアウト・配当表", href: "#ペイアウト・配当表" },
    { label: "モバイル対応", href: "#モバイル対応" },
    { label: "戦略・攻略法", href: "#戦略・攻略法" },
    { label: "類似ゲーム", href: "#類似ゲーム" },
    { label: "まとめ", href: "#まとめ" },
    { label: "・勝手に評価！", href: "#・勝手に評価！" },
    { label: "よくある質問", href: "#よくある質問" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/mermaids-diamond" />;
}
