import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Crystal Land",
  hero: {
    title: "Crystal Land",
    subheading: "クリスタルランド",
    description: "Playson社がリリースした、フィーチャー満載のスロット「クリスタルランド（Crystal Land）」をご紹介いたします。ボーナスを集めて新レベルに到達し、賞金を獲得していく、やりがいのあるゲームです。",
    score: 2.5,
    scoreMax: 5,
    rtp: "95.2%",
    maxMultiplier: "5,000x",
    provider: "Playson",
    releaseDate: "2018年1月",
    volatility: "中高～高",
    reels: "7",
    paylines: "クラスターペイ",
    minBet: "0.10",
    maxBet: "100",
    slotImageSrc: "/slots/crystal-land.jpg",
    highlights: ["クラスターペイシステム", "レベルシステム", "ブロック解除でボーナスラウンドへ"],
    watchouts: ["中高～高ボラティリティのため、大きな勝利には運と忍耐が必要"],
  },
  featuredCasino: {
    name: "1win",
    logo: "/assets/casino/1win.png",
    href: "/reviews/1win",
    ctaText: "今すぐプレイ",
    ctaHref: "/reviews/1win",
  },
  casinos: [
    {
      name: "ReSpin",
      logo: "/assets/casino/respin.jpg",
      href: "/reviews/respin",
      bonus: "300USDT",
      freeSpins: "200",
      wagering: "35x / 5x",
      rating: 4,
      tagline: "10種類のメジャーな仮想通貨が使えるクリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/respin",
    },
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30x / 30x",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/golden-panda",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/betgoat",
    },
    {
      name: "1win",
      logo: "/images/1win_375x375.png",
      href: "/reviews/1win",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/1win",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x / 20x",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/miki",
    },
    {
      name: "WSM Casino",
      logo: "/images/WSM_375x375.png",
      href: "/reviews/wsm-casino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "/reviews/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitz",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "/reviews/katsuwin",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/katsuwin",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x / 40x",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/sushi-casino",
    },
    {
      name: "Betpanda",
      logo: "/images/Betpanda_375x375.png",
      href: "/reviews/betpanda",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/betpanda",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "/reviews/parimatch",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/parimatch",
    },
    {
      name: "Bets.io",
      logo: "/images/bets-io_375x375-1.png",
      href: "/reviews/bets-io",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bets-io",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "/reviews/duelbits",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/sportsbet-io",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: "-",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/winz-io",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "/reviews/lucky-block",
      bonus: "50",
      freeSpins: "-",
      wagering: "35x",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/lucky-block",
    },
    {
      name: "Flush Casino",
      logo: "/images/Flush_375x375-1.png",
      href: "/reviews/flush",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/flush",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/roobet",
    },
    {
      name: "Casino Sky",
      logo: "/images/casinosky_375x375.png",
      href: "/reviews/casino-sky",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-sky",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35x / 40x",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/mega-dice",
    },
    {
      name: "Fresh Casino",
      logo: "/images/fresh_375x375.png",
      href: "/reviews/fresh-casino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/fresh-casino",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "/reviews/cosmoswin",
      bonus: "$10,000",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/cosmoswin",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45x / 60x",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bc-game",
    },
    {
      name: "Stake",
      logo: "/images/stake_375x375-1.png",
      href: "/reviews/stake",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/stake",
    },
    {
      name: "K8",
      logo: "/assets/casino/k8.jpg",
      href: "/reviews/k8",
      bonus: "$1,840",
      freeSpins: "288",
      wagering: "25x / 25x",
      rating: 4.5,
      tagline: "日本で人気の実機を打つならK8のカジノで決まりっ！昔懐かしの台を打ちまくろう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/k8",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35x / 40x",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/ohmyspins",
    },
    {
      name: "Tedbet",
      logo: "/images/tedbet_375x375.png",
      href: "/reviews/tedbet",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/tedbet",
    },
    {
      name: "BetRebels",
      logo: "/images/betrebels_375x375.png",
      href: "/reviews/betrebels",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/betrebels",
    },
    {
      name: "Conquestador",
      logo: "/images/Conquestador_375x375.png",
      href: "/reviews/conquestador",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/conquestador",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.jpg",
      href: "/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/cloudbet",
    },
    {
      name: "Livecasino.io",
      logo: "/images/casino/livecasinoio.jpg",
      href: "/reviews/livecasino-io",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/livecasino-io",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.jpg",
      href: "/reviews/lucky-bull",
      bonus: "$917",
      freeSpins: "-",
      wagering: "30x",
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/lucky-bull",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.jpg",
      href: "/reviews/gamdom",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/gamdom",
    },
    {
      name: "Energy Casino",
      logo: "/images/energy-casino_375x375.png",
      href: "/reviews/energy-casino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/energy-casino",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x / 20x",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-me",
    },
    {
      name: "Bons.com",
      logo: "/assets/casinos/bons_375x375-1.png",
      href: "/reviews/bons",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "マインクラフトチックでも中身はモダン",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bons",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "/reviews/mystino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/mystino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "/reviews/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/empire777",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/pinnacle",
    },
    {
      name: "Casinoin",
      logo: "/assets/casino/casinoin.jpg",
      href: "/reviews/casinoin",
      bonus: "￥25,000",
      freeSpins: "200",
      wagering: "25x / 15x",
      rating: 4,
      tagline: "13種類の仮想通貨が利用可能なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casinoin",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "/reviews/winunique",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30x / 30x",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/winunique",
    },
    {
      name: "BitStarz",
      logo: "/images/bitstarz_375x375.png",
      href: "/reviews/bitstarz",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitstarz",
    },
    {
      name: "Joy Casino",
      logo: "/images/joycasino_375x375.png",
      href: "/reviews/joycasino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/joycasino",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casinos/casino-secret_375x375.png",
      href: "/reviews/casino-secret",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-secret",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/images/casino-x_375x375-1.png",
      href: "/reviews/casino-x",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x / 20x",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/casitabi",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "/reviews/eldoah",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/reviews/eldoah",
    },
  ],
  gameInfo: {
    intro: "Playson/プレイソン社よりリリースされた、シンプルながらもユニークなゲーム性を持つスロット「Crystal Land（クリスタルランド）」をご紹介いたします。\n\nカラフルでシンプルな宝石が特徴的なこのゲームは、スマートフォンで人気のパズルゲーム「キャンディークラッシュ」に似たゲーム性を持っており、多くのプレイヤーに親しみやすいでしょう。CasinoTsuが、この実力派スロットゲームを詳しくご紹介いたします。",
    basicInfo: {
      rtp: "95.2%",
      volatility: "中高～高",
      reels: "7リール×7行",
      paylines: "5つ以上のシンボルが縦横に隣接して揃ったら配当ゲット（クラスターペイシステム）",
      minBet: "0.10ドル",
      maxBet: "100.00ドル",
      provider: "Playson",
      releaseDate: "2018年1月",
    },
  },
  payoutTable: {
    title: "配当表",
    symbols: [
      {
        name: "ワイルドシンボル",
        description: "すべてのシンボルの代わりとなり、配当成立をサポートします。",
        isSpecial: true,
      },
      {
        name: "ルビーワイルドシンボル",
        description: "ワイルドシンボルと同様に、あらゆるシンボルの代わりになります。6つ以上のシンボルが揃った際に、そのシンボルがワイルドシンボルに変化することで生成されます。ルビーワイルドシンボルが消滅すると、「爆弾シンボル」に変化します。",
        isSpecial: true,
      },
      {
        name: "爆弾シンボル",
        description: "新しいシンボルが落ちてきても勝利パターンが形成されない場合、爆弾シンボルが爆発し、周囲のシンボルを巻き込んで消滅させます。これにより、新たな勝利のチャンスを生み出します。",
        isSpecial: true,
      },
      {
        name: "宝石",
        payout5: "x1",
        payout4: "x0.8",
        payout3: "x0.5",
      },
      {
        name: "宝石",
        payout5: "x0.8",
        payout4: "x0.6",
        payout3: "x0.4",
      },
      {
        name: "宝石",
        payout5: "x0.6",
        payout4: "x0.4",
        payout3: "x0.3",
      },
      {
        name: "宝石",
        payout5: "x0.5",
        payout4: "x0.3",
        payout3: "x0.2",
      },
      {
        name: "宝石",
        payout5: "x0.4",
        payout4: "x0.2",
        payout3: "x0.1",
      },
      {
        name: "宝石",
        payout5: "x0.3",
        payout4: "x0.1",
        payout3: "x0.05",
      },
    ],
    maxPayout: "500,000枚",
    notes: ["$1ベットあたりのペイアウトです。"],
  },
  features: {
    title: "ゲームの特徴",
    items: [
      {
        name: "クラスターペイシステム",
        description: "5つ以上の同じシンボルが縦または横に隣接して揃うことで配当が発生するシステム。",
        icon: "/images/crystal-land-symbol.jpg",
      },
      {
        name: "カスケードウィン（連鎖）",
        description: "配当が発生して揃ったシンボルは消滅し、新しいシンボルが落ちてくることで、一度のスピンで複数回の勝利が発生する可能性がある。",
        icon: "/images/crystal-land-symbol.jpg",
      },
      {
        name: "ブロック解除とボーナスラウンド",
        description: "フィールドの一部は「ブロック」されており、シンボルを揃えて消すことで解除できる。すべてのブロックを解除すると、ボーナスラウンドへ突入。",
        icon: "/images/crystal-land-design.jpg",
      },
      {
        name: "ワイルドシンボル",
        description: "すべてのシンボルの代わりとなり、配当成立をサポートする。",
        icon: "/images/crystal-land-wild.jpg",
      },
      {
        name: "ルビーワイルドシンボル",
        description: "ワイルドシンボルと同様に機能し、消滅すると爆弾シンボルに変化する。",
        icon: "/images/crystal-land-wild.jpg",
      },
      {
        name: "爆弾シンボル",
        description: "配当が形成されない場合に爆発し、周囲のシンボルを消滅させる。",
        icon: "/images/crystal-land-wild.jpg",
      },
      {
        name: "ボーナスラウンド",
        description: "カラーリングポーションと全爆弾シンボルが登場。宝箱を開けてスターを獲得し、勝利金乗数を増加させる。",
        icon: "/images/crystal-land-top.jpg",
      },
      {
        name: "レベルシステム",
        description: "シンボルを消してゲージを満たすとレベルアップ。レベルごとに異なるボーナスフィーチャーがアンロックされる。",
        icon: "/images/crystal-land-top.jpg",
      },
    ],
  },
  sections: [
    {
      heading: "Crystal Land をプレイできるカジノ",
      paragraphs: ["CasinoTsuでは、プレイヤーの皆様が安心して楽しめるカジノを厳選しております。"],
    },
    {
      heading: "基本情報",
      table: {
        columns: ["", ""],
        rows: [
          ["リール数", "7リール×7行"],
          ["ペイライン", "5つ以上のシンボルが縦横に隣接して揃ったら配当ゲット（クラスターペイシステム）"],
          ["コインバリュー", "$0.10〜100.00"],
          ["最高獲得コイン数", "500,000枚"],
          ["RTP（返還率）", "95.2%"],
          ["ボラティリティ", "中高～高"],
        ],
      },
    },
    {
      heading: "どんなゲームなの？",
      paragraphs: [
        "シンプルかつエレガントを基調としたこのゲームは、田園風景を背景に、6種類の宝石で構成されたフィールドを崩していくという内容です。",
      ],
      bullets: [
        "**クラスターペイシステム**\nこのゲームは、従来のペイラインではなく、「クラスターペイ」システムを採用しています。これは、5つ以上の同じシンボルが縦または横に隣接して揃うことで配当が発生するというものです。",
        "**カスケードウィン（連鎖）**\n配当が発生して揃ったシンボルは消滅し、その空いたスペースに上から新しいシンボルが落ちてきます。これにより、一度のスピンで複数回の勝利が発生する可能性があります。",
        "**ブロック解除とボーナスラウンド**\nフィールドの一部は「ブロック」されており、最初はプレイできません。ブロックされていないシンボルを揃えて消すことで、徐々にブロックを解除していくことができます。フィールド上のすべてのブロックを解除すると、ボーナスラウンドへと突入します。",
      ],
    },
    {
      heading: "シンボル",
      paragraphs: [
        "ワイルドシンボル: すべてのシンボルの代わりとなり、配当成立をサポートします。",
        "ルビーワイルドシンボル: ワイルドシンボルと同様に、あらゆるシンボルの代わりになります。6つ以上のシンボルが揃った際に、そのシンボルがワイルドシンボルに変化することで生成されます。ルビーワイルドシンボルが消滅すると、「爆弾シンボル」に変化します。",
        "爆弾シンボル: 新しいシンボルが落ちてきても勝利パターンが形成されない場合、爆弾シンボルが爆発し、周囲のシンボルを巻き込んで消滅させます。これにより、新たな勝利のチャンスを生み出します。",
        "特定の列のブロックを解除すると、ランダムワイルドシンボルの追加といったボーナスが付与されることもございます。",
      ],
    },
    {
      heading: "ボーナスラウンド",
      paragraphs: [
        "フィールドのブロックがすべて解除されると、ボーナスラウンドが開始されます。このラウンドでは、新しいシンボルは落下しません。代わりに、「カラーリングポーション」と「全爆弾シンボル」が登場します。",
        "**カラーリングポーション:**\n3つ与えられるこのポーションは、配当が発生しない場合に、6種類のシンボルタイプのうち1つを、フィールド上の別のシンボルにランダムに変換します。これにより、勝利の組み合わせを作り出す手助けとなります。",
        "**全爆弾シンボル:**\nカラーリングポーションをすべて使い切ると、全爆弾シンボルが爆発し、フィールド上のシンボルを一掃します。",
        "これらのポーションは、ボーナスラウンド中に配置される「宝箱」を開けるために重要な役割を果たします。宝箱の前にある宝石（シンボル）をすべて消すと、隠れていた宝箱が出現し、その中にある「スター」を獲得できます。スターは、各スターにつき勝利金の乗数を1倍ずつ増加させます。最大で乗数×9倍まで勝利金が増額される可能性があり、非常に魅力的なフィーチャーです。",
      ],
    },
    {
      heading: "レベルシステム",
      paragraphs: [
        "ゲーム画面左上には「レベルメーター」が搭載されており、シンボルを消してゲージを満たすことでレベルが上がります。レベルごとに異なるボーナスフィーチャーがアンロックされます。",
      ],
      bullets: [
        "レベルアップで得られるボーナス:",
        "レベル①: ランダムに3つのワイルドシンボルが出現します。",
        "レベル②: ランダムに3つのルビーワイルドシンボルが出現します。",
        "レベル③: 6種類あるシンボルのうち1種類が、カラーリングポーションによってランダムに別のシンボルに変換されます。",
        "レベルが上がるごとに、キャッシュ（賞金）や乗数（マルチプライヤー）を獲得できるチャンスもございます。",
      ],
    },
    {
      heading: "Crystal Land を遊ぶならこのカジノ！",
      table: {
        columns: ["カジノ名", "登録ボーナス"],
        rows: [
          ["[**カジ旅**](/reviews/casitabi)", "カジ旅で初回入金をすると、最高$500と250回分のフリースピンさらにはフリーベットもGET可能！(ﾉ◕ヮ◕)ﾉ"],
          ["[**ビットカジノ**](/reviews/bitcasino-io)", "ビットカジノの初回入金ボーナス｜最大20万円\*:･ﾟ✧🎁"],
          ["[**K8カジノ**](/reviews/k8)", "ジャパカジからK8 Casinoに新規登録するとK8カジノから入金不要ボーナス40ドルを進呈中～🙌"],
          ["[**カジノエックス**](/reviews/casino-x)", "カジノエックスさんから、ジャパカジ限定の入金不要ボーナスを用意してもらいました〜🎉 入金不要なのに4,500円🔥<br>**👉 [**カジノエックス** のオファー](/offers/casino-x-exclusive) へ"],
          ["[**ボンズカジノ**](/reviews/bons)", "ジャパカジ限定で5,000円の入金不要ボーナスと大人気スロット「Moon Princess（ムーンプリンセス）」の入金不要フリースピン20回分がもらえる超お得なボーナス到来✨<br>👉 **[**ボンズカジノ** のオファー](/offers/bons-exclusive) へ"],
        ],
      },
    },
    {
      heading: "Crystal Land 2 について",
      paragraphs: [
        "2023年12月には、Crystal Landの続編である「Crystal Land 2」がリリースされました。Crystal Land 2では、前作の魅力的なゲーム性はそのままに、さらにパワーアップしたフィーチャーと、より高い最大配当倍率（10,000倍）が魅力となっています。RTPも95.50%と若干向上しており、よりエキサイティングなプレイ体験を提供いたします。",
      ],
    },
    {
      heading: "プレイしてみた感想",
      paragraphs: [
        "シンプルで分かりやすいゲームでありながら、コイン持ちも良く、初心者の方でも安心してプレイできるスロットです。シンボルを崩すだけでなく、ブロック解除やフィーチャーシンボルの活用など、ゲーム内には様々な仕掛けが用意されており、飽きることなくプレイに没頭できます。",
        "ボーナスラウンドは比較的頻繁に訪れるため、スターを獲得できなくても十分楽しめます。もちろん、宝箱からスターを獲得できた時の興奮は格別です！",
        "グラフィックは鮮明で美しく、シンプルなゲーム性とは裏腹にユニークな機能が満載で、時間を忘れてハマってしまう魅力的なスロットゲームと言えるでしょう。CasinoTsuは、常に正確な情報をお届けできるよう、チェック、ダブルチェック、そしてCasinoTsuチェックを怠りません。",
      ],
    },
    {
      heading: "勝手に評価！",
      bullets: [
        "**グラフィック**\n★★★★★　ー　Playson社の安定したクオリティ。鮮明で美しいグラフィックは健在です。",
        "**サウンド**\n★★★★☆　ー 　爽やかなBGMと可愛らしい効果音が、ゲームの進行状況を分かりやすく伝え、プレイを盛り上げてくれます。",
        "**面白さ**\n★★★☆☆　ー　シンプルで分かりやすいゲーム性は初心者向けですが、単調さを感じるプレイヤーもいるかもしれません。そのため、星3つといたしました。",
        "**賞金獲得**\n★★★★☆ 　ー　ボーナスゲームの出現頻度が高く、最大配当倍率5,000倍、RTP95.20%と、まずまずの賞金獲得が期待できます。ただし、中高～高ボラティリティのため、大きな勝利を得るにはある程度の運と忍耐が必要です。",
        "**総合評価**\n★★★★☆ 　ー　評価4.3/5段階評価",
      ],
    },
  ],
  faq: [
    {
      q: "Crystal Landのレベルはいくつまでありますか？",
      a: "レベルは6まであります。シンボルが消えていく度に、レベルがあがっていきます。レベルアップにより、キャッシュやマルチプライヤーなどのボーナスを獲得できます。",
    },
    {
      q: "Crystal Landで遊べるカジノはどこですか？",
      a: "ReSpin、Golden Panda、Betgoat、1win、Miki、WSM Casino、Bitz、Katsuwin、Sushi Casino、Betpanda、Parimatch、Bets.io、Duelbits、Sportsbet.io、Winz、Lucky Block、Flush Casino、Roobet、Casino Sky、Mega Dice、Fresh Casino、Cosmoswin、BC.Game、Stake、K8、OhMySpins、Tedbet、BetRebels、Conquestador、Cloudbet、Livecasino.io、Lucky Bull、Gamdom、Energy Casino、Casino Me、Bons.com、Mystino、Empire777、Pinnacle、Casinoin、WinUnique、BitStarz、Joy Casino、Casino Secret、Bitcasino.io、Casino-X、Casitabi、Eldoah Casinoなど、多くのオンラインカジノでプレイ可能です。CasinoTsuが推薦するカジノで、ぜひお楽しみください。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "Slots", href: "/slots" },
    { label: "Crystal land", href: "/slots/crystal-land" },
  ],
  tableOfContents: [
    { label: "Crystal Land をプレイできるカジノ", href: "#crystal-land-をプレイできるカジノ" },
    { label: "基本情報", href: "#基本情報" },
    { label: "どんなゲームなの？", href: "#どんなゲームなの？" },
    { label: "シンボル", href: "#シンボル" },
    { label: "ボーナスラウンド", href: "#ボーナスラウンド" },
    { label: "レベルシステム", href: "#レベルシステム" },
    { label: "Crystal Land を遊ぶならこのカジノ！", href: "#crystal-land-を遊ぶならこのカジノ！" },
    { label: "Crystal Land 2 について", href: "#crystal-land-2-について" },
    { label: "プレイしてみた感想", href: "#プレイしてみた感想" },
    { label: "勝手に評価！", href: "#勝手に評価！" },
    { label: "よくある質問", href: "#よくある質問" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/crystal-land" />;
}
