import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Ugga Bugga（ウッガ・ブッガ）スロット｜高RTP99.07%！ユニークなホールド機能で戦略的に遊ぼう",
  hero: {
    title: "Ugga Bugga（ウッガ・ブッガ）",
    subheading: "高RTP99.07%！ユニークなホールド機能で戦略的に遊ぼう",
    description: "CasinoTsu は、スロットゲーム「Ugga Bugga（ウッガ・ブッガ）」をご紹介いたします。このゲームは、非常に高いRTP（還元率）とシンプルなゲーム性ながら、プレイヤーの参加を促すユニークな機能が特徴のクラシックスロットです。",
    score: 3.6,
    scoreMax: 5,
    rtp: "99.07%",
    maxMultiplier: "x1,000",
    provider: "Playtech",
    releaseDate: "2006年",
    volatility: "Low",
    reels: "3",
    paylines: "10",
    minBet: "$0.02",
    maxBet: "$20",
    slotImageSrc: "/slots/ugga-bugga.jpg",
    highlights: [
      "非常に高いRTP (99.07%)",
      "ユニークなホールド機能",
      "シンプルなゲーム性",
      "低ボラティリティで資金が長持ちしやすい",
    ],
    watchouts: [
      "グラフィックやサウンドはやや時代遅れ",
      "オートプレイ機能なし",
      "一部カジノでは提供終了の可能性あり",
    ],
  },
  featuredCasino: {
    name: "Betgoat",
    logo: "/assets/casino/betgoat.jpg",
    href: "/reviews/betgoat",
    ctaText: "今すぐプレイ！",
    ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fugga-bugga",
    tagline: "独自コインも利用可能！ 最新クリプトカジノ",
  },
  casinos: [
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "/reviews/betgoat",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "2up",
      logo: "/images/2up_375x375.png",
      href: "/reviews/2up",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "1win",
      logo: "/images/1win_375x375.png",
      href: "/reviews/1win",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "/reviews/miki",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "WSM Casino",
      logo: "/images/WSM_375x375.png",
      href: "/reviews/wsm-casino",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "/reviews/sushi-casino",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Betpanda",
      logo: "/images/Betpanda_375x375.png",
      href: "/reviews/betpanda",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "/reviews/parimatch",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Bets.io",
      logo: "/images/bets-io_375x375.png",
      href: "/reviews/bets-io",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "/reviews/sportsbet-io",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "/reviews/winz-io",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "/reviews/dafabet",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Ramenbet",
      logo: "/images/ramenbet_375x375-1.png",
      href: "/reviews/ramenbet",
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Flush Casino",
      logo: "/images/Flush_375x375-1.png",
      href: "/reviews/flush",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Fresh Casino",
      logo: "/images/fresh_375x375.png",
      href: "/reviews/fresh-casino",
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "/reviews/bc-game",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "/reviews/wonder-casino",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "/reviews/ohmyspins",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ohmyspins:ohmyspins?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Yuugado",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "/reviews/yuugado",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Tedbet",
      logo: "/images/tedbet_375x375.png",
      href: "/reviews/tedbet",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/tedbet:tedbet?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.jpg",
      href: "/reviews/cloudbet",
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cloudbet:cloudbet?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Konibet",
      logo: "/images/konibet_375x375.png",
      href: "/reviews/konibet",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Bons.com",
      logo: "/assets/casinos/bons_375x375-1.png",
      href: "/reviews/bons",
      rating: 4.5,
      tagline: "マインクラフトチックでも中身はモダン",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bons-com:bons?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Trustdice",
      logo: "/images/Trustdice_375x375.png",
      href: "/reviews/trustdice",
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/trustdice:trustdice?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "/reviews/inter-casino",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "/reviews/winunique",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winunique:winunique?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Joy Casino",
      logo: "/images/joycasino_375x375.png",
      href: "/reviews/joycasino",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/joy-casino:joycasino?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "/reviews/vera-john",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "/reviews/bitcasino-io",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Casino-X",
      logo: "/images/casino-x_375x375-1.png",
      href: "/reviews/casino-x",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "William Hill",
      logo: "/assets/casino/william-hill.jpg",
      href: "/reviews/william-hill",
      rating: 3.5,
      tagline: "世界三大の超老舗ブックメーカー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/william-hill-casino:william-hill?referrer_path=%2Fslots%2Fugga-bugga",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "/reviews/eldoah",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fugga-bugga",
    },
  ],
  gameInfo: {
    intro: "CasinoTsu は、スロットゲーム「Ugga Bugga（ウッガ・ブッガ）」をご紹介いたします。このゲームは、非常に高いRTP（還元率）とシンプルなゲーム性ながら、プレイヤーの参加を促すユニークな機能が特徴のクラシックスロットです。",
    basicInfo: {
      rtp: "99.07%",
      volatility: "Low",
      reels: "3",
      paylines: "10",
      minBet: "$0.02",
      maxBet: "$20",
      provider: "Playtech",
      releaseDate: "2006年",
    },
  },
  payoutTable: {
    title: "Ugga Bugga のシンボルと配当",
    symbols: [
      {
        name: "ワイルドシンボル",
        description: "マルチプライヤーの解放を助け、配当の成立をサポートします。",
        payout5: "x1,000",
        isSpecial: true,
      },
      {
        name: "戦士シンボル",
        description: "スキャッターシンボルの役割を持ち、リールのどこに現れても配当の対象となります。",
        payout5: "x500",
        isSpecial: true,
      },
      {
        name: "ティキマスク",
        payout5: "x200",
      },
      {
        name: "フードボウル",
        payout5: "x150",
      },
      {
        name: "小屋",
        payout5: "x100",
      },
      {
        name: "ドラム",
        payout5: "x75",
      },
      {
        name: "低配当シンボル",
        payout5: "x50 〜 x20",
      },
    ],
    maxPayout: "x1,000",
    notes: [
      "上記は一例であり、実際の配当はベット額によって変動します。",
      "ベットサイズは同一であっても、1回のスピンあたりの合計ベット額によってペイアウトは変動します。",
    ],
  },
  features: {
    title: "Ugga Bugga のゲームフィーチャー",
    items: [
      {
        name: "シンボルの固定（ホールドフィーチャー）",
        description: "最初のスピンで出現したシンボルの中から、気に入ったものを1〜3つまで固定することができます。どのシンボルをホールドするかはプレイヤー自身が決定できるため、ゲームへの参加意識を高める嬉しい機能です。ホールドするシンボルを選択後、2回目のスピンをクリックし、残りのリールに配置されるシンボルによって配当が確定します。",
        icon: "/images/ugga-bugga-hold-feature.jpg",
      },
      {
        name: "シンボルの自動固定",
        description: "ワイルドシンボルや民族シンボルなど、確実に配当をもたらすシンボルが1回目のスピンで出現した場合、そのシンボルは自動的にホールドされ、各ラインに固定されます。もちろん、プレイヤーが希望しない場合はホールドを解除することも可能です。",
        icon: "/images/ugga-bugga-10-payline.jpg",
      },
      {
        name: "オートプレイ機能について",
        description: "ご注意点として、Ugga Bugga にはオートプレイ機能が搭載されておりません。プレイヤーは毎回、手動でスピンボタンを押す必要があります。1回のスピン（ホールド機能を含む）には、およそ10秒程度かかると言われています。",
      },
    ],
  },
  sections: [
    {
      heading: "Ugga Bugga をプレイしてみた感想",
      paragraphs: [
        "非常にシンプルで分かりやすいスロットゲームです。最近のフィーチャーやボーナス機能が満載の最新スロットと比較すると、機能面では「何もない！」と感じるかもしれません（笑）。そのため、モダンなビデオスロットがお好みな方には、すぐに飽きがきてしまう可能性もあります。",
        "しかし、このようなシンプルで当たりが分かりやすいスロットを好むプレイヤーも少なくありません。CasinoTsu の担当者も、最新スロットに慣れている方ではありますが、このスロットをプレイする際には、どのような状況でシンボルをホールドすべきか、自身で考えながらスピンを楽しみました。最近のスロットでは味わえない、戦略的に自分でホールドシンボルを決定するプレイは、高RTPに繋がる可能性を秘めたスロットだと感じます。ぜひ一度お試しください。♪",
      ],
    },
    {
      heading: "Ugga Bugga を勝手に評価！",
      paragraphs: [
        "CasinoTsu では、以下の観点から Ugga Bugga を評価いたしました。",
      ],
      table: {
        title: "評価項目",
        columns: ["項目", "評価"],
        rows: [
          ["グラフィック", "★★☆☆☆ ー 残念ながら、Playtech社にグラフィックの洗練されたイメージは期待できません。グラフィックはやや時代遅れに感じられるかもしれませんが、テーマはしっかりと表現されており、機能面で問題はありません。"],
          ["サウンド", "★★☆☆☆ ー 残念ながら、サウンド面も特筆すべき点はありません。スピン音や当たり時の音には、わずかに民族的な要素が感じられる程度です。サウンドはシンプルですが、ゲームプレイの邪魔になることはありません。"],
          ["面白さ", "★★★☆☆ ー ペイアウトは頻繁に発生し、単にスピンを回すだけでなく、プレイヤーが戦略を練ることができる点がこのスロットの面白さです。ホールド機能により、プレイヤーが主体的にゲームに参加できる点がユニークで、面白さを感じさせます。"],
          ["賞金獲得", "★★★★☆ ー 当たりは頻繁に訪れ、プレイヤー自身の判断でスピンすることで高配当を狙える可能性があります。低ボラティリティのため、小役が頻繁に当たり、資金を長持ちさせやすいという点も魅力です。"],
        ],
      },
      bullets: [
        "総合評価：★★★☆☆ ー 3.7 / 5段階評価",
        "グラフィックやサウンドの評価を考慮すると総合評価は控えめになりますが、シンプルなスロットを好むプレイヤーには強くおすすめいたします。高RTPと戦略的なホールド機能の組み合わせは、ユニークで魅力的なゲーム体験を提供します。",
      ],
    },
    {
      heading: "Ugga Bugga のターゲットプレイヤー",
      bullets: [
        "**初心者プレイヤー:** シンプルなルールと分かりやすいペイアウトシステムにより、スロット初心者の方でもすぐに楽しむことができます。",
        "**低予算プレイヤー:** 低ボラティリティと頻繁な当たりにより、少額ベットでも比較的長くゲームを楽しむことができます。",
        "**戦略を楽しみたいプレイヤー:** 自分でシンボルをホールドする機能があるため、単なる運任せではない、戦略的なプレイを好む方に最適です。",
      ],
    },
    {
      heading: "Ugga Bugga はこのようなプレイヤーには向いていません",
      bullets: [
        "**ジャックポットハンター:** 低ボラティリティのため、一撃で高額賞金を獲得するようなゲーム性ではありません。",
        "**ハイローラー:** 最大ベット額が比較的低めに設定されているため、高額ベットで一攫千金を狙うプレイヤーには物足りない可能性があります。",
      ],
    },
    {
      heading: "Ugga Bugga をプレイできるカジノ",
      paragraphs: [
        "Playtech社製のゲームを提供しているカジノとして、ワンダーカジノを CasinoTsu は推薦いたします。人気の入金不要ボーナスから、ジャパカジ限定のフリースピンまで、様々なボーナスを獲得しながら幅広いゲームをお楽しみいただけます。",
        "※ 上記以外にも、多くのオンラインカジノでPlaytech社のスロットが提供されています。最新の情報は各カジノサイトにてご確認ください。",
      ],
    },
    {
      heading: "Ugga Bugga を遊ぶならこのカジノ！",
      table: {
        columns: ["カジノ名", "登録ボーナス"],
        rows: [
          ["[ワンダーカジノ](https://casinotsu.com/reviews/wonder-casino)", "ワンダーカジノの期間限定入金不要ボーナス40ドル＆入金フリースピン150回分！【ジャパカジ限定】\n👉 **[ワンダーカジノ のオファー](https://casinotsu.com/offers/wonder-casino-exclusive)** へ"],
        ],
      },
    },
    {
      heading: "Ugga Bugga の戦略・攻略法",
      bullets: [
        "**デモモードで練習を重ねましょう！**\nUgga Bugga の最大の特徴は、プレイヤー自身がシンボルをホールドできる「ホールド機能」です。この機能は独特であり、習熟するまでに少々時間を要するかもしれません。そのため、まずはデモモードで実際にプレイし、ホールド機能の使い方や戦略を掴むことを強く推奨いたします。",
        "**低ボラティリティを最大限に活かす**\nこのスロットは低ボラティリティに分類されます。これは、頻繁に小役が当たり、大きな損失を被るリスクが低い反面、一撃で高額賞金を獲得する可能性は低いことを意味します。この特性を理解し、資金管理を徹底しながらじっくりとプレイすることで、より長くゲームを楽しむことが可能になります。",
        "**予算管理を徹底しましょう**\n低ボラティリティであっても、ギャンブルであることに変わりはありません。あらかじめプレイする予算を明確に定め、それを超えないように細心の注意を払いましょう。正確さが第一。興奮はその次です。",
      ],
    },
  ],
  similarGames: [
    {
      name: "Mega Joker",
      provider: "NetEnt",
      description: "クラシックスロットでありながら驚異のRTP 99%を誇ります。",
    },
    {
      name: "Blood Suckers",
      provider: "NetEnt",
      description: "RTP 89.99%とこちらも高還元率。スキャッターシンボルによるボーナスゲームも魅力的です。",
    },
    {
      name: "Starmania",
      provider: "NextGen Gaming",
      description: "RTP 97.87%。美しい宇宙をテーマにしたスロットで、スタックワイルドやボーナススピンが楽しめます。",
    },
    {
      name: "Ocean Princess",
      provider: "Playtech",
      description: "Ugga Bugga と同様に、ホールド機能を持つクラシックスロットです。",
    },
    {
      name: "Age of the Godsシリーズ",
      provider: "Playtech",
      description: "神話をテーマにした人気のジャックポットスロットシリーズ。",
    },
    {
      name: "Buffalo Blitz",
      provider: "Playtech",
      description: "高速リールと多数のペイウェイが特徴のパワフルなスロット。",
    },
  ],
  prosCons: {
    pros: [
      "非常に高いRTP (99.07%)",
      "ユニークなホールド機能で戦略的にプレイ可能",
      "シンプルなルールで初心者にも分かりやすい",
      "低ボラティリティで頻繁に当たりがあり、資金が長持ちしやすい",
      "最大配当倍率1,000倍",
    ],
    cons: [
      "グラフィックやサウンドはやや時代遅れ",
      "オートプレイ機能がない",
      "一部カジノでは提供が終了している可能性がある",
      "ジャックポット機能はない",
      "ハイローラーにはベット額が物足りない可能性",
    ],
  },
  faq: [
    {
      q: "ウッガ・ブッガにフリースピンはありますか？",
      a: "いいえ。Ugga Bugga はクラシックスロットですので、フリースピンやボーナスゲームは搭載されておりません。",
    },
    {
      q: "Ugga Bugga の RTP はいくつですか？",
      a: "Ugga Bugga の RTP は 99.07% と非常に高いです。",
    },
    {
      q: "Ugga Bugga のボラティリティは？",
      a: "Ugga Bugga は低ボラティリティ（Low）です。",
    },
    {
      q: "Ugga Bugga の最大配当倍率は？",
      a: "Ugga Bugga の最大配当倍率は x1,000 です。",
    },
    {
      q: "Ugga Bugga はどこでプレイできますか？",
      a: "Playtech社製ゲームを提供しているオンラインカジノでプレイできます。例えば、ワンダーカジノなどがおすすめです。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "Ugga Bugga", href: "/slots/ugga-bugga" },
  ],
  tableOfContents: [
    { label: "Ugga Bugga（ウッガ・ブッガ）とは？", href: "#intro" },
    { label: "Ugga Bugga の基本情報", href: "#basic-info" },
    { label: "Ugga Bugga のシンボルと配当", href: "#payout-table" },
    { label: "Ugga Bugga のゲームフィーチャー", href: "#features" },
    { label: "Ugga Bugga をプレイしてみた感想", href: "#review" },
    { label: "Ugga Bugga を勝手に評価！", href: "#evaluation" },
    { label: "Ugga Bugga のターゲットプレイヤー", href: "#target-players" },
    { label: "Ugga Bugga はこのようなプレイヤーには向いていません", href: "#not-for-players" },
    { label: "Ugga Bugga をプレイできるカジノ", href: "#playable-casinos" },
    { label: "Ugga Bugga を遊ぶならこのカジノ！", href: "#recommended-casino" },
    { label: "よくある質問", href: "#faq" },
    { label: "Ugga Bugga の戦略・攻略法", href: "#strategy" },
    { label: "類似ゲーム", href: "#similar-games" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fugga-bugga",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/ugga-bugga" />;
}
