import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "シュガーラッシュ（Sugar Rush）オンカジ・スロットレビュー",
  hero: {
    title: "シュガーラッシュ（Sugar Rush）",
    score: 4.6,
    scoreMax: 5,
    rtp: "95.5%",
    maxMultiplier: "x5,000",
    provider: "Pragmatic Play",
    releaseDate: "2022-06-16",
    volatility: "High",
    reels: "7",
    paylines: "クラスターペイ",
    minBet: "$0.2",
    maxBet: "$100",
    slotImageSrc: "/slots/sugar-rush.jpg",
    highlights: [
      "お菓子をテーマにしたカラフルで甘い世界観",
      "クラスターペイシステムによる爽快な連鎖",
      "マルチプライヤースポット機能による高配当の可能性",
      "フリースピン中はマルチプライヤーが固定され、爆発力がアップ",
      "ボーナスフィーチャー購入機能で直接フリースピンへ突入可能",
    ],
    watchouts: [
      "ハイボラティリティのため、配当がない時間が続く可能性がある",
      "RTPはカジノによって異なる場合があるため、プレイ前に確認が必要",
      "ボーナス購入機能は高額なため、資金管理に注意が必要",
    ],
  },
  featuredCasino: {
    name: "2アップカジノ",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/reviews/2up-casino",
    ctaText: "今すぐプレイ",
    ctaHref: "https://casinotsu.com/reviews/2up-casino",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
  },
  casinos: [
    {
      name: "Golden Panda",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "30倍賭け条件",
      freeSpins: "30倍賭け条件",
      wagering: "30倍賭け条件",
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/golden-panda",
    },
    {
      name: "Betgoat",
      href: "https://casinotsu.com/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      tagline: "独自コインも利用可能！最新クリプトカジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/betgoat",
    },
    {
      name: "2up",
      href: "https://casinotsu.com/reviews/2up-casino",
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/2up-casino",
    },
    {
      name: "Cybet",
      href: "https://casinotsu.com/reviews/cybet",
      bonus: "35倍賭け条件, $500",
      freeSpins: "35倍賭け条件, 50",
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/cybet",
    },
    {
      name: "1win",
      href: "https://casinotsu.com/reviews/1win",
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/1win",
    },
    {
      name: "Miki",
      href: "https://casinotsu.com/reviews/miki-casino",
      bonus: "30倍賭け条件, $4,000",
      freeSpins: "20倍賭け条件, 200",
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/miki-casino",
    },
    {
      name: "WSM Casino",
      href: "https://casinotsu.com/reviews/wsm-casino",
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "29倍賭け条件, $1,000",
      freeSpins: "-",
      tagline: "本人確認書類不要！？匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/bitz",
    },
    {
      name: "Wikibet",
      href: "https://casinotsu.com/reviews/wikibet",
      bonus: "20倍賭け条件, ¥50,000",
      freeSpins: "20倍賭け条件, 200",
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/wikibet",
    },
    {
      name: "Katsuwin",
      href: "https://casinotsu.com/reviews/katsuwin",
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/katsuwin",
    },
    {
      name: "Sushi Casino",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "35倍賭け条件, ¥200,000",
      freeSpins: "40倍賭け条件, 50",
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/sushi-casino",
    },
    {
      name: "Betpanda",
      href: "https://casinotsu.com/reviews/betpanda",
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/betpanda",
    },
    {
      name: "Parimatch",
      href: "https://casinotsu.com/reviews/parimatch",
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/parimatch",
    },
    {
      name: "Bets.io",
      href: "https://casinotsu.com/reviews/bets-io",
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/bets-io",
    },
    {
      name: "Duelbits",
      href: "https://casinotsu.com/reviews/duelbits",
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      tagline: "スポーツベットだけじゃない！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/sportsbet-io",
    },
    {
      name: "Shuffle",
      href: "https://casinotsu.com/reviews/shuffle-casino",
      bonus: "40倍賭け条件, $2,020",
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/shuffle-casino",
    },
    {
      name: "Winz",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/winz-io",
    },
    {
      name: "Dafabet",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "20倍賭け条件, $500",
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/dafabet",
    },
    {
      name: "Lucky Block",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "35倍賭け条件, 50",
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/lucky-block",
    },
    {
      name: "Ramenbet",
      href: "https://casinotsu.com/reviews/ramenbet",
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/ramenbet",
    },
    {
      name: "Flush Casino",
      href: "https://casinotsu.com/reviews/flush-casino",
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/flush-casino",
    },
    {
      name: "Queen Casino",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "30倍賭け条件, 1,800USDT",
      freeSpins: "20倍賭け条件, 288",
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/queen-casino",
    },
    {
      name: "Roobet",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: "$0",
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/roobet",
    },
    {
      name: "Casino Sky",
      href: "https://casinotsu.com/reviews/casino-sky",
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/casino-sky",
    },
    {
      name: "Mega Dice",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "35倍賭け条件, 1BTC",
      freeSpins: "40倍賭け条件, 50",
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/mega-dice",
    },
    {
      name: "Cosmoswin",
      href: "https://casinotsu.com/reviews/cosmoswin",
      bonus: "キャッシュバック 最大$10,000",
      tagline: "可愛い女の子のキャラが案内役♪ユニークなボーナスショップも必見です！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/cosmoswin",
    },
    {
      name: "BC.Game",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "45倍賭け条件, $1,600",
      freeSpins: "60倍賭け条件, 460",
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/bc-game",
    },
    {
      name: "Empire.io",
      href: "https://casinotsu.com/reviews/empire-io",
      bonus: "$0",
      tagline: "賭け条件ナシのキャシュバック＆VIP特典がスゴイ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/empire-io",
    },
    {
      name: "Stake",
      href: "https://casinotsu.com/reviews/stake",
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/stake",
    },
    {
      name: "Wonder Casino",
      href: "https://casinotsu.com/reviews/wonder-casino",
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/wonder-casino",
    },
    {
      name: "OhMySpins",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "35倍賭け条件, ¥65,000",
      freeSpins: "40倍賭け条件, 200",
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/ohmyspins",
    },
    {
      name: "Yuugado",
      href: "https://casinotsu.com/reviews/yuugado",
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/yuugado",
    },
    {
      name: "Lilibet",
      href: "https://casinotsu.com/reviews/lilibet",
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/lilibet",
    },
    {
      name: "Konibet",
      href: "https://casinotsu.com/reviews/konibet",
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/konibet",
    },
    {
      name: "Casino Me",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "20倍賭け条件, $777",
      freeSpins: "20倍賭け条件, 77",
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/casino-me",
    },
    {
      name: "Kakeyo",
      href: "https://casinotsu.com/reviews/kakeyo",
      bonus: "10倍賭け条件, ¥100,000",
      freeSpins: "10倍賭け条件, 50",
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/kakeyo",
    },
    {
      name: "Mystino",
      href: "https://casinotsu.com/reviews/mystino",
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/mystino",
    },
    {
      name: "Trustdice",
      href: "https://casinotsu.com/reviews/trustdice",
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/trustdice",
    },
    {
      name: "InterCasino",
      href: "https://casinotsu.com/reviews/intercasino",
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/intercasino",
    },
    {
      name: "Empire777",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "20倍賭け条件, $1,600",
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/empire777",
    },
    {
      name: "Pinnacle",
      href: "https://casinotsu.com/reviews/pinnacle",
      bonus: "$0",
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/pinnacle",
    },
    {
      name: "WinUnique",
      href: "https://casinotsu.com/reviews/winunique",
      bonus: "30倍賭け条件, $330",
      freeSpins: "30倍賭け条件, 20",
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/winunique",
    },
    {
      name: "Joy Casino",
      href: "https://casinotsu.com/reviews/joycasino",
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/joycasino",
    },
    {
      name: "Vera&John",
      href: "https://casinotsu.com/reviews/vera-john",
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/vera-john",
    },
    {
      name: "Live Casino House",
      href: "https://casinotsu.com/reviews/live-casino-house",
      bonus: "20倍賭け条件, ¥50,000",
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "40倍賭け条件, ¥200,000",
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      href: "https://casinotsu.com/reviews/casino-x",
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/casino-x",
    },
    {
      name: "Casitabi",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "20倍賭け条件, $500",
      freeSpins: "20倍賭け条件, 250",
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/casitabi",
    },
    {
      name: "Eldoah Casino",
      href: "https://casinotsu.com/reviews/eldoah-casino",
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "カジノへ行く",
      ctaHref: "https://casinotsu.com/reviews/eldoah-casino",
    },
  ],
  gameInfo: {
    intro: "シュガーラッシュ（Sugar Rush）は、Pragmatic Play（プラグマティックプレイ）社がお届けする、お菓子をテーマにしたスロットゲームでございます。🍬 カラフルで甘い世界観がプレイヤーの皆様を夢のようなお菓子の国へと誘います。見た目の愛らしさとは裏腹に、高い爆発力を持つゲーム性も兼ね備えており、多くのプレイヤーに愛されております。",
    basicInfo: {
      rtp: "95.5% (※カジノによって異なる場合がございます。一般的には96.50%, 95.50%, 94.50%のいずれかが設定されています。プレイするカジノのゲーム画面でご確認ください。)",
      volatility: "High",
      reels: "7",
      paylines: "クラスターペイ",
      minBet: "$0.2",
      maxBet: "$100",
      provider: "Pragmatic Play",
      releaseDate: "2022-06-16",
    },
  },
  payoutTable: {
    title: "ペイアウト・配当表",
    symbols: [
      {
        name: "キャンディ（赤）",
        payout5: "x0.5",
        payout4: "",
        payout3: "",
        description: "一番配当が高いシンボル。",
      },
      {
        name: "キャンディ（オレンジ）",
        payout5: "x0.4",
        payout4: "",
        payout3: "",
      },
      {
        name: "キャンディ（紫）",
        payout5: "x0.3",
        payout4: "",
        payout3: "",
      },
      {
        name: "グミ（ピンク）",
        payout5: "x0.25",
        payout4: "",
        payout3: "",
      },
      {
        name: "グミ（青）",
        payout5: "x0.2",
        payout4: "",
        payout3: "",
      },
      {
        name: "グミ（緑）",
        payout5: "x0.15",
        payout4: "",
        payout3: "",
      },
      {
        name: "クマ（オレンジ）",
        payout5: "x0.1",
        payout4: "",
        payout3: "",
        description: "低配当ながらも出現頻度が高いシンボル。",
      },
    ],
    maxPayout: "x5,000",
    notes: [
      "上記は7x7グリッドでクラスターサイズが最大（またはそれに近い場合）の配当例です。",
      "実際の配当はゲーム内のペイテーブルでご確認ください。",
      "スキャッターシンボル（ロリポップ）は3つ以上出現でフリースピン獲得。",
      "マルチプライヤーは配当成立スポットに付与され、連鎖で倍増します（最大128倍、フリースピン中は固定）。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "クラスターペイ",
        description: "縦または横に5つ以上同じシンボルが隣接して出現すると配当成立となるシステム。連鎖してシンボルが消えていく爽快感が特徴。",
        icon: "",
      },
      {
        name: "タンブル（カスケード）機能",
        description: "配当成立シンボルは消滅し、新しいシンボルが落ちてくる。これにより1回のスピンで連続配当が発生する可能性がある。",
        icon: "",
      },
      {
        name: "マルチプライヤースポット",
        description: "配当成立シンボルがあった場所がマルチプライヤースポットとなり、再び配当が成立すると倍率が2倍になる。最大128倍まで増加し、フリースピン中は固定される。",
        icon: "",
      },
      {
        name: "フリースピン",
        description: "スキャッターシンボル（ロリポップ）が3つ以上出現すると獲得。出現数に応じて10〜30回のフリースピンが付与される。フリースピン中はマルチプライヤースポットが固定される。",
        icon: "",
      },
      {
        name: "ボーナスフィーチャー購入機能",
        description: "ベット額の100倍で直接フリースピンラウンドを開始できる機能。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "導入・概要",
      paragraphs: [
        "シュガーラッシュ（Sugar Rush）は、Pragmatic Play（プラグマティックプレイ）社がお届けする、お菓子をテーマにしたスロットゲームでございます。🍬 カラフルで甘い世界観がプレイヤーの皆様を夢のようなお菓子の国へと誘います。見た目の愛らしさとは裏腹に、高い爆発力を持つゲーム性も兼ね備えており、多くのプレイヤーに愛されております。",
      ],
    },
    {
      heading: "どこで遊べるか",
      paragraphs: [
        "シュガーラッシュは、様々なオンラインカジノでプレイ可能でございます。ここでは、 CasinoTsu が特におすすめするカジノと、そこで提供されているボーナス情報をご紹介いたします。",
      ],
    },
    {
      heading: "ゲーム基本情報",
      table: {
        title: "シュガーラッシュの基本情報",
        columns: ["概要", ""],
        rows: [
          ["名称", "Sugar Rush"],
          ["リリース日", "2022-06-16"],
          ["プロバイダー", "Pragmatic Play"],
          ["最大配当倍率", "x5,000 (※「シュガーラッシュ1000」では25,000倍)"],
          ["ボラティリティ", "High"],
          ["最大ベット額", "$100 (※「シュガーラッシュ1000」では240ドル)"],
          ["ゲームグリッド", "7x7"],
        ],
      },
    },
    {
      heading: "ゲーム特徴・フィーチャー",
      items: [
        {
          name: "絵柄／シンボル",
          description: "シュガーラッシュの通常シンボルは全部で7種類。キャンディやグミなど、カラフルで可愛らしいデザインでございます。特にクマの形をしたグミシンボルは、低配当ながらも出現頻度が高く、ゲームを盛り上げます。一番配当が高いのは、シンプルな飴玉シンボルです。",
          icon: "/images/sugar-rush-symbol.jpg",
        },
        {
          name: "ペイライン（クラスターペイ）",
          description: "シュガーラッシュでは、従来のペイライン方式ではなく、「クラスターペイ」システムを採用しております。これは、縦または横に5つ以上同じシンボルが隣接して出現すると配当成立となる仕組みでございます。まるで「ぷよ◯よ」のように、シンボルが連鎖して消えていく爽快感が楽しめます。",
        },
        {
          name: "最小／最大ベット額とオートプレイオプション",
          description: "シュガーラッシュは、最小$0.2から最大$100までベット可能です。 (※「シュガーラッシュ1000」では最大240ドルまでプレイできます)。オートプレイ機能も搭載されており、10回から1,000回までのスピン数を設定できます。さらに、スピンの速さも「通常」「クイックスピン」「ターボスピン」の3段階で調整可能で、プレイヤーの皆様の好みに合わせた快適なプレイが可能です。",
          icon: "/images/sugar-rush-autoplayoption.jpg",
        },
        {
          name: "RTP（還元率）",
          description: "シュガーラッシュのRTPは、一般的に96.50%、95.50%、94.50%のいずれかに設定されています。これは、カジノオペレーターによって異なる場合があるため、プレイする前に必ずゲーム画面でご確認ください。RTP（還元率）が高いほど、プレイヤーの皆様にとって有利になる傾向があります。",
        },
        {
          name: "ボラティリティ",
          description: "シュガーラッシュは、ボラティリティが「高」でございます。これは、見た目の可愛らしいデザインとは異なり、一撃で高額配当を獲得できる爆発力を持っていることを意味します。一方で、頻繁な小当たりは少なく、しばらく配当がない「カラ回し」が続く可能性もあります。ハイローラーや、一攫千金を狙いたいプレイヤーに向いております。",
        },
        {
          name: "最大可能配当倍率",
          description: "シュガーラッシュの最大可能配当倍率は5,000倍でございます。これは、ベット額の5,000倍までの賞金を獲得できる可能性があることを示しています。なお、後述する「シュガーラッシュ1000」では、最大配当倍率が25,000倍に大幅アップしております。",
        },
        {
          name: "タンブル（カスケード）機能",
          description: "シュガーラッシュは「タンブル（カスケード）機能」を搭載しております。配当が成立したシンボルは消滅し、その場に新しいシンボルが落ちてきます。これにより、1回のスピンで連続して配当が発生する可能性があります。この連鎖が続くと、マルチプライヤーがさらに増加し、大きな勝利へと繋がることもあります。",
        },
        {
          name: "マルチプライヤースポット",
          description: "このスロットの最大の特徴の一つが、「マルチプライヤースポット」機能でございます。スピン中に配当が成立したシンボルがあった場所は、マルチプライヤースポットとなり、その場所で再び配当が成立すると、マルチプライヤーが2倍になります。このマルチプライヤーは、連続して配当が成立するたびに倍増し、最大で128倍 にまで到達します。さらに、複数のマルチプライヤースポットが配当に関与する場合、その倍率は合算されます。フリースピン中は、このマルチプライヤースポットが固定されるため、より高倍率のマルチプライヤーを狙いやすくなります。",
          icon: "/images/sugar-rush-multiplier.jpg",
        },
        {
          name: "フリースピン",
          description: "スキャッターシンボル（ロリポップ）が3つ以上出現すると、フリースピンを獲得できます。フリースピンの回数は、出現したスキャッターの数によって変動いたします。",
          icon: "/images/sugar-rush-scatter.jpg",
        },
        {
          name: "ボーナスフィーチャー購入機能",
          description: "シュガーラッシュでは、フリースピンに突入するのを待つだけでなく、「ボーナスフィーチャー購入機能」を利用して、直接フリースピンラウンドを開始することができます。この機能は、ベット額の100倍 で利用可能であり、購入時には稀に4つ以上のスキャッターが出現し、より多くのフリースピンを獲得できる可能性もあります。一部のバージョン（例：「シュガーラッシュ1000」）では、さらに高額な「スーパーフリースピン」を購入するオプションも用意されており、より強力なボーナスラウンドを体験できます。",
          icon: "/images/sugar-rush-freespin.jpg",
        },
      ],
    },
    {
      heading: "プロバイダー情報",
      paragraphs: [
        "シュガーラッシュは、数々の人気スロットを生み出している Pragmatic Play（プラグマティックプレイ） 社によって開発されました。同社は、革新的なゲーム性と魅力的なテーマで、世界中のオンラインカジノプレイヤーから高い評価を得ております。",
      ],
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["会社名", "Pragmatic Play"],
          ["ライセンス", "マルタ、イギリス、ジブラルタルなど、多数の規制当局からライセンスを取得。"],
          ["リリース日", "2022年6月16日"],
          ["他の人気作品", "『スウィート・ボナンザ（Sweet Bonanza）』、『ゲート・オブ・オリンポス（Gates of Olympus）』、『スターライト・プリンセス（Starlight Princess）』など。"],
        ],
      },
    },
    {
      heading: "グラフィック・サウンド",
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["グラフィック", "2Dグラフィックで描かれる、カラフルで甘いお菓子の世界。キャンディやグミなどのシンボルは、見ているだけで楽しくなります。可愛らしさを重視したデザインは、多くのプレイヤーに受け入れられやすいでしょう。"],
          ["モバイル対応", "スマートフォンやタブレットでのプレイも快適に楽しめます。特に、モバイルデバイスでのプレイを考慮し、ポートレートモードに最適化されています。"],
          ["サウンド", "明るく軽快なBGMと、スピンや配当成立時に鳴る効果音が、ゲームの楽しさを一層引き立てます。甘すぎず、心地よいサウンドデザインは、長時間プレイしても飽きさせません。"],
        ],
      },
      paragraphs: [
        "『スウィート・ボナンザ』など、お菓子をテーマにしたスロットは数多く存在しますが、シュガーラッシュはその中でも特に親しみやすいデザインとサウンドを持っております。",
      ],
    },
    {
      heading: "ペイアウト・配当表",
      paragraphs: [
        "シュガーラッシュのシンボルごとの配当は、クラスターサイズによって変動します。以下に、7x7グリッドでクラスターサイズが最大（またはそれに近い場合）になった際の、各シンボルの配当倍率の例を示します。",
      ],
      table: {
        title: "シンボルごとの配当倍率（例）",
        columns: ["シンボル", "最小クラスターサイズ (5つ以上)", "最大クラスターサイズ (15個以上)"],
        rows: [
          ["キャンディ（赤）", "x0.5", "x150"],
          ["キャンディ（オレンジ）", "x0.4", "x120"],
          ["キャンディ（紫）", "x0.3", "x100"],
          ["グミ（ピンク）", "x0.25", "x90"],
          ["グミ（青）", "x0.2", "x80"],
          ["グミ（緑）", "x0.15", "x70"],
          ["クマ（オレンジ）", "x0.1", "x60"],
        ],
      },
      bullets: [
        "上記はあくまで例であり、実際の配当はゲーム内のペイテーブルでご確認ください。",
        "特別シンボル:",
        "スキャッターシンボル（ロリポップ）: 3つ以上出現するとフリースピンを獲得できます。",
        "マルチプライヤー: 配当成立スポットに付与され、連鎖で倍増します（最大128倍、フリースピン中は固定）。",
      ],
      notes: ["最大配当倍率: シュガーラッシュの最大配当倍率は5,000倍 でございます。これは、ベット額の5,000倍までの一括配当を獲得できる可能性があることを意味します。"],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "シュガーラッシュは、スマートフォンやタブレットなどのモバイルデバイスに完全対応しております。タッチ操作に最適化されたインターフェースにより、外出先でも自宅と同じように快適にプレイできます。特に、ポートレートモードでのプレイ体験が向上しており、片手で気軽に遊ぶことができます。",
      ],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "シュガーラッシュはハイボラティリティスロットであるため、戦略的なプレイが重要でございます。",
      ],
      bullets: [
        "バンクロール管理: ハイボラティリティのスロットでは、大きな配当を得るまでに時間がかかることがあります。そのため、十分な資金（バンクロール）を用意し、一度のベット額を抑えて、プレイ時間を長く保つことが大切です。急いでベット額を上げすぎると、すぐに資金が底をついてしまう可能性があります。",
        "マルチプライヤーの活用: マルチプライヤースポットは、シュガーラッシュの醍醐味でございます。フリースピン中はマルチプライヤーが固定されるため、フリースピン獲得時には、どこにマルチプライヤーが配置されるかが重要になります。高倍率のマルチプライヤーが複数箇所に蓄積されることを期待して、冷静にプレイしましょう。",
        "ボーナス購入機能の利用: フリースピンに突入しにくいと感じる場合は、ボーナスフィーチャー購入機能の利用も検討できます。ただし、購入にはベット額の100倍が必要となるため、資金管理には十分注意が必要です。また、購入したからといって必ずしも大きな勝利が得られるとは限らない点も理解しておきましょう。",
        "バージョンによる違いを理解する: シュガーラッシュには、「シュガーラッシュ1000」のような、より強化されたバージョンも存在します。これらのバージョンでは、最大配当倍率や最大マルチプライヤー、ベット可能額などが異なります。プレイする前に、どのバージョンで遊んでいるのかを確認し、それぞれの特徴を理解しておくと良いでしょう。",
      ],
    },
    {
      heading: "類似ゲーム",
      paragraphs: [
        "シュガーラッシュがお好きな方には、以下のスロットもおすすめでございます。",
      ],
      similarGames: [
        {
          name: "スウィート・ボナンナ（Sweet Bonanza）",
          href: "https://casinotsu.com/slots/sweet-bonanza",
          provider: "Pragmatic Play",
          description: "同じPragmatic Play社による、お菓子テーマの代表的な人気スロット。こちらもタンブル機能やフリースピンが特徴です。",
        },
        {
          name: "シュガーラッシュ2015（Sugar Rush 2015）",
          provider: "Pragmatic Play",
          description: "2015年にリリースされた、Pragmatic Play社の初期のシュガーラッシュ。現在のバージョンとはグラフィックやゲーム性が異なります。",
        },
        {
          name: "テイスティー・トリーツ（Tasty Treats）",
          provider: "Hacksaw Gaming",
          description: "Hacksaw Gaming社開発のスイーツテーマスロット。配当成立の仕組みがシュガーラッシュに似ています。",
        },
        {
          name: "シュガーラッシュ・クリスマス（Sugar Rush Xmas）",
          href: "https://casinotsu.com/slots/sugar-rush-xmas",
          provider: "Pragmatic Play",
          description: "シュガーラッシュのクリスマスバージョン。季節感あふれる演出が楽しめます。",
        },
        {
          name: "シュガーラッシュ1000（Sugar Rush 1000）",
          href: "https://casinotsu.com/slots/sugar-rush-1000",
          provider: "Pragmatic Play",
          description: "最大配当25,000倍、最大マルチプライヤー1,024倍へとパワーアップした最新作。より高いリスクとリターンを求めるプレイヤー向けです。",
        },
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "シュガーラッシュは、可愛らしいお菓子の世界観と、ハイボラティリティによる高い爆発力を兼ね備えた魅力的なスロットでございます。クラスターペイ、タンブル機能、そして特徴的なマルチプライヤースポットといったゲーム性は、一度プレイすると病みつきになること間違いなしです。",
        "こんなプレイヤーにおすすめ！",
        "可愛らしいデザインやテーマが好きなプレイヤー",
        "一撃の大きな配当を狙いたいハイローラー",
        "連鎖による爽快感を味わいたいプレイヤー",
        "初心者から経験者まで、幅広い層におすすめ",
        "ただし、ハイボラティリティであるため、大勝するには運も必要です。甘い見た目に惑わされず、冷静なバンクロール管理をしながら、お菓子の国での冒険を楽しんでください！ 🚀",
      ],
    },
    {
      heading: "よくある質問",
      faq: [
        {
          q: "Sugar Rushの最大配当倍率は？",
          a: "オリジナルの「シュガーラッシュ」の最大配当倍率は5,000倍です。ただし、「シュガーラッシュ1000」のようなバージョンでは、最大25,000倍まで可能です。",
        },
        {
          q: "Pragmatic Play社の他の人気スロットは？",
          a: "『スウィート・ボナンザ』、『ゲート・オブ・オリンポス』、『スターライト・プリンセス』などが人気です。",
        },
        {
          q: "シュガーラッシュでエラーが発生した場合、どうなりますか？",
          a: "ゲームの公式情報によると、「誤動作が起きると、配当とプレイは全て無効になります。」とのことです。カジノ側でエラーが発生した場合は、スクリーンショットを撮り、カジノサポートに問い合わせてください。",
        },
        {
          q: "シュガーラッシュは無料でプレイできますか？",
          a: "多くのオンラインカジノでは、デモプレイ（無料プレイ）モードを提供しています。実際の資金を使う前に、ゲームの雰囲気を掴むためにデモプレイを利用することをおすすめします。",
        },
        {
          q: "「シュガーラッシュ1000」とは何ですか？",
          a: "「シュガーラッシュ1000」は、オリジナルのシュガーラッシュをベースにした、より高機能・高配当を目指せるバージョンです。最大配当倍率が25,000倍、最大マルチプライヤーが1,024倍に向上し、ベット可能額も増加しています。",
        },
      ],
    },
  ],
  cta: {
    text: "今すぐシュガーラッシュをプレイ！",
    href: "https://casinotsu.com/reviews/2up-casino",
  },
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Sugar rush", href: "https://casinotsu.com/slots/sugar-rush" },
  ],
  tableOfContents: [
    { label: "導入・概要", href: "#導入・概要" },
    { label: "どこで遊べるか", href: "#どこで遊べるか" },
    { label: "ゲーム基本情報", href: "#ゲーム基本情報" },
    { label: "ゲーム特徴・フィーチャー", href: "#ゲーム特徴・フィーチャー" },
    { label: "プロバイダー情報", href: "#プロバイダー情報" },
    { label: "グラフィック・サウンド", href: "#グラフィック・サウンド" },
    { label: "ペイアウト・配当表", href: "#ペイアウト・配当表" },
    { label: "モバイル対応", href: "#モバイル対応" },
    { label: "戦略・攻略法", href: "#戦略・攻略法" },
    { label: "類似ゲーム", href: "#類似ゲーム" },
    { label: "まとめ", href: "#まとめ" },
    { label: "よくある質問", href: "#よくある質問" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/sugar-rush" />;
}
