import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "ドキドキ夏祭り (Doki Doki Fireworks) スロットレビュー | CasinoTsu",
  hero: {
    title: "ドキドキ夏祭り (Doki Doki Fireworks)",
    subheading: "かき氷ボーナスやカードボーナスで目指せDokiDoki高額賞金！",
    description: "ドキドキ夏祭り（Doki Doki Fireworks）は、日本のお祭りをイメージしたパチスロ風スロット。かき氷ボーナスなど萌えるフィーチャーを楽しんじゃおう！ ✨",
    score: 3.4,
    scoreMax: 5,
    rtp: "96.34% / 96.5%",
    maxMultiplier: "x100,000",
    provider: "Microgaming (Games Global)",
    releaseDate: "2022年8月1日",
    volatility: "高",
    reels: "3",
    paylines: "5",
    minBet: "¥50 / $0.50",
    maxBet: "¥10,000 / $100",
    slotImageSrc: "/slots/doki-doki-fireworks.jpg",
    highlights: [
      "日本の夏祭りをテーマにしたユニークなスロット",
      "最大100,000倍の驚異的な最大配当ポテンシャル",
      "かき氷ボーナス、カードボーナス、フリースピンなどの多彩なボーナス機能",
      "パチスロ風のレイアウトと萌え要素が融合",
      "高ボラティリティで一攫千金を狙える",
      "モバイルデバイスに完全対応",
    ],
    watchouts: [
      "高ボラティリティのため、勝利頻度は低い傾向にある",
      "初心者の方は、デモモードでの練習を推奨",
    ],
  },
  featuredCasino: {
    name: "2アップカジノ 2up",
    logo: "/assets/casino/2up.png",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdoki-doki-fireworks",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdoki-doki-fireworks",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
  },
  casinos: [
    {
      name: "Vera & John（ベラジョン）",
      logo: "/images/casino/vera_john.png",
      href: "https://go.casinotsu.com/go/vera-john",
      bonus: "ジャパカジ限定！フリースピン150回（入金不要ボーナス）",
      freeSpins: "150",
      wagering: "賭け条件なし",
      rating: 5,
      tagline: "オンカジの代名詞！初心者から上級者まで満足できるゲーム数と使いやすさ。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/vera-john",
    },
    {
      name: "InterCasino（インターカジノ）",
      logo: "/assets/casino/intercasino.png",
      href: "https://go.casinotsu.com/go/intercasino",
      bonus: "ジャパカジ限定！$30（入金不要ボーナス）",
      freeSpins: "-",
      wagering: "賭け条件なし",
      rating: 4.5,
      tagline: "20年以上の歴史を持つ老舗カジノ。信頼性が高く、豊富なプロモーションが魅力。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/intercasino",
    },
    {
      name: "遊雅堂（無料版も対応）",
      logo: "/assets/casino/yuugado.png",
      href: "https://go.casinotsu.com/go/yuugado",
      bonus: "ジャパカジ限定！¥3,000（入金不要ボーナス）",
      freeSpins: "-",
      wagering: "賭け条件なし",
      rating: 4.5,
      tagline: "和風テイストが特徴。パチンコ・パチスロ機種も豊富で、日本円でプレイ可能。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/yuugado",
    },
    {
      name: "Golden Panda",
      logo: "/images/casino/golden_panda.png",
      href: "https://go.casinotsu.com/go/golden-panda",
      bonus: "ボーナス賭け条件30倍、フリースピン賭け条件30倍",
      freeSpins: "-",
      wagering: "30倍",
      rating: 4,
      tagline: "出金が基本的に即時反映でストレスフリー。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/golden-panda",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.png",
      href: "https://go.casinotsu.com/go/betgoat",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "独自コインも利用可能！最新クリプトカジノ。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/betgoat",
    },
    {
      name: "2up",
      logo: "/assets/casino/2up.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdoki-doki-fireworks",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdoki-doki-fireworks",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      href: "https://go.casinotsu.com/go/1win",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/1win",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.png",
      href: "https://go.casinotsu.com/go/miki",
      bonus: "ボーナス賭け条件30倍、フリースピン賭け条件20倍",
      freeSpins: "-",
      wagering: "20-30倍",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/miki",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/wsm_casino.png",
      href: "https://go.casinotsu.com/go/wsm-casino",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino",
    },
    {
      name: "Betpanda",
      logo: "/assets/casino/betpanda.png",
      href: "https://go.casinotsu.com/go/betpanda",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/betpanda",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "https://go.casinotsu.com/go/duelbits",
      bonus: "ボーナスなし",
      freeSpins: "500",
      wagering: "-",
      rating: 4.5,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/duelbits",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.png",
      href: "https://go.casinotsu.com/go/dafabet",
      bonus: "ボーナス賭け条件20倍",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/dafabet",
    },
    {
      name: "Lucky Block",
      logo: "/images/casino/lucky_block.png",
      href: "https://go.casinotsu.com/go/lucky-block",
      bonus: "ボーナス€25,000、フリースピン賭け条件35倍",
      freeSpins: "-",
      wagering: "35倍",
      rating: 4.5,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/lucky-block",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.png",
      href: "https://go.casinotsu.com/go/roobet",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/roobet",
    },
    {
      name: "BC.Game",
      logo: "/images/casino/bc_game.png",
      href: "https://go.casinotsu.com/go/bc-game",
      bonus: "ボーナス賭け条件45倍、フリースピン賭け条件60倍",
      freeSpins: "-",
      wagering: "45-60倍",
      rating: 4.5,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/bc-game",
    },
    {
      name: "Wonder Casino",
      logo: "/images/casino/wonder_casino.png",
      href: "https://go.casinotsu.com/go/wonder-casino",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.png",
      href: "https://go.casinotsu.com/go/ohmyspins",
      bonus: "ボーナス賭け条件35倍、フリースピン賭け条件40倍",
      freeSpins: "-",
      wagering: "35-40倍",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/ohmyspins",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      href: "https://go.casinotsu.com/go/yuugado",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/yuugado",
    },
    {
      name: "Lilibet",
      logo: "/assets/casino/lilibet.png",
      href: "https://go.casinotsu.com/go/lilibet",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/lilibet",
    },
    {
      name: "Konibet",
      logo: "/assets/casino/konibet.png",
      href: "https://go.casinotsu.com/go/konibet",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/konibet",
    },
    {
      name: "Casino Me",
      logo: "/images/casino/casino_me.png",
      href: "https://go.casinotsu.com/go/casino-me",
      bonus: "ボーナス賭け条件20倍、フリースピン賭け条件20倍",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/casino-me",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      href: "https://go.casinotsu.com/go/mystino",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/mystino",
    },
    {
      name: "InterCasino",
      logo: "/assets/casino/intercasino.png",
      href: "https://go.casinotsu.com/go/intercasino",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/intercasino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.png",
      href: "https://go.casinotsu.com/go/empire777",
      bonus: "ボーナス賭け条件20倍",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/empire777",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joy_casino.png",
      href: "https://go.casinotsu.com/go/joy-casino",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/joy-casino",
    },
    {
      name: "Vera&John",
      logo: "/images/casino/vera_john.png",
      href: "https://go.casinotsu.com/go/vera-john",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/vera-john",
    },
    {
      name: "Bitcasino.io",
      logo: "/images/casino/bitcasino.png",
      href: "https://go.casinotsu.com/go/bitcasino",
      bonus: "ボーナス賭け条件40倍",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/bitcasino",
    },
    {
      name: "Eldoah Casino",
      logo: "/images/casino/eldoah_casino.png",
      href: "https://go.casinotsu.com/go/eldoah-casino",
      bonus: "ボーナスなし",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ。",
      ctaText: "詳細を見る",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino",
    },
  ],
  gameInfo: {
    intro: "ドキドキ夏祭り（Doki Doki Fireworks）は、Microgaming（Games Global）によって開発された、日本の夏祭りをテーマにしたユニークなオンラインスロットです。浴衣を着た可愛らしい3人の女の子が登場し、プレイヤーは彼女たちと一緒に夏祭りの雰囲気を楽しむことができます。パチスロ風のレイアウトと演出が特徴で、萌え要素と祭りの賑やかさが融合した、日本人プレイヤーにとって特に魅力的なゲームとなっています。このスロットは、最大で賭け金の100,000倍という非常に高いポテンシャルを秘めており、高ボラティリティを好むプレイヤーに最適です。カードボーナスや、選んだキャラクターによって特典が変わるフリースピン、そしてかき氷ボーナスなど、多彩なボーナス機能が搭載されており、ゲームを一層盛り上げます。",
    basicInfo: {
      rtp: "96.34% / 96.5%",
      volatility: "高",
      reels: "3",
      paylines: "5",
      minBet: "¥50 / $0.50",
      maxBet: "¥10,000 / $100",
      provider: "Microgaming (Games Global)",
      releaseDate: "2022年8月1日",
    },
  },
  payoutTable: {
    title: "ペイアウト・配当表",
    symbols: [
      {
        name: "イチゴ🍓",
        description: "高配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "20倍",
        isSpecial: false,
      },
      {
        name: "パイナップル🍍",
        description: "高配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "10倍",
        isSpecial: false,
      },
      {
        name: "スイカ🍉",
        description: "高配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "5倍",
        isSpecial: false,
      },
      {
        name: "プラム",
        description: "高配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "3倍",
        isSpecial: false,
      },
      {
        name: "オレンジ🍊",
        description: "低配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "1倍",
        isSpecial: false,
      },
      {
        name: "ブドウ🍇",
        description: "低配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "0.7倍",
        isSpecial: false,
      },
      {
        name: "バナナ🍌",
        description: "低配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "0.4倍",
        isSpecial: false,
      },
      {
        name: "チェリー🍒",
        description: "低配当シンボル",
        payout5: "-",
        payout4: "-",
        payout3: "0.2倍",
        isSpecial: false,
      },
      {
        name: "RESPIN",
        description: "リール上に3つ停止でリスピン獲得",
        payout5: "-",
        payout4: "-",
        payout3: "-",
        isSpecial: true,
      },
      {
        name: "カードボーナス",
        description: "出現でカードボーナスラウンド発動",
        payout5: "-",
        payout4: "-",
        payout3: "-",
        isSpecial: true,
      },
      {
        name: "7 (スキャッター)",
        description: "3つ揃いでフリースピンラウンド開始",
        payout5: "-",
        payout4: "-",
        payout3: "-",
        isSpecial: true,
      },
      {
        name: "かき氷",
        description: "フリースピン中に獲得でかき氷ボーナス発動",
        payout5: "-",
        payout4: "-",
        payout3: "-",
        isSpecial: true,
      },
    ],
    maxPayout: "x100,000",
    notes: [
      "上記配当は賭け額¥100の場合の例です。",
      "個々のシンボルの配当自体はそれほど高くありませんが、ボーナス機能やフリースピン中のマルチプライヤーと組み合わせることで、大きな勝利につながる可能性があります。",
      "ペイラインは左から右へ、同一シンボルが3つ揃うと配当が成立します。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "リスピン",
        description: "リール上にハート型の「RESPIN」シンボルが3つ停止すると、追加で1回のスピンが得られます。",
        icon: "💖",
      },
      {
        name: "カードボーナス",
        description: "「カードボーナス」シンボルが出現すると発動。5枚のカードから1枚を選び、配当（5倍～50倍）またはフリースピンを獲得。7が出るとフリースピンへ直接突入。",
        icon: "🃏",
      },
      {
        name: "フリースピン",
        description: "「7」スキャッターシンボル3つで発動。3人のキャラクターから1人を選択し、それぞれ異なるスピン回数とマルチプライヤーでプレイ。購入も可能（賭け金の50倍）。",
        icon: " spins",
      },
      {
        name: "かき氷ボーナス",
        description: "フリースピン中に「かき氷」シンボルが出現すると発動。選んだキャラクターに対応した色のかき氷が登場し、その大きさに応じた配当が得られます。複数回出現の可能性あり。",
        icon: "🍧",
      },
      {
        name: "シングルリール停止機能",
        description: "ベースゲーム中、個々のリールを個別に停止させることが可能（クイックスピンモードでは不可）。",
        icon: "✋",
      },
    ],
  },
  sections: [
    {
      heading: "1. 導入・概要",
      paragraphs: [
        "ドキドキ夏祭り（Doki Doki Fireworks）は、Microgaming（Games Global）によって開発された、日本の夏祭りをテーマにしたユニークなオンラインスロットです。浴衣を着た可愛らしい3人の女の子が登場し、プレイヤーは彼女たちと一緒に夏祭りの雰囲気を楽しむことができます。パチスロ風のレイアウトと演出が特徴で、萌え要素と祭りの賑やかさが融合した、日本人プレイヤーにとって特に魅力的なゲームとなっています。",
        "このスロットは、最大で賭け金の100,000倍という非常に高いポテンシャルを秘めており、高ボラティリティを好むプレイヤーに最適です。カードボーナスや、選んだキャラクターによって特典が変わるフリースピン、そしてかき氷ボーナスなど、多彩なボーナス機能が搭載されており、ゲームを一層盛り上げます。",
      ],
    },
    {
      heading: "2. ゲーム基本情報",
      paragraphs: [
        "ドキドキ夏祭りの基本情報について、CasinoTsu がチェック、ダブルチェック、そして CasinoTsu チェック を経てまとめました。",
      ],
      table: {
        title: "基本情報",
        columns: ["項目", "詳細"],
        rows: [
          ["名称", "Doki Doki Fireworks"],
          ["リリース日", "2022年8月1日"],
          ["プロバイダー", "Microgaming (Games Global)"],
          ["RTP（還元率）", "96.34% / 96.5%"],
          ["ボラティリティ", "高（High Volatility）"],
          ["リール数", "3"],
          ["ペイライン数", "5"],
          ["行数", "3"],
          ["最小ベット額", "¥50 / $0.50"],
          ["最大ベット額", "¥10,000 / $100"],
          ["最大配当倍率", "x100,000"],
        ],
      },
      bullets: [
        "**RTP（還元率）について:** ドキドキ夏祭りのRTPは、情報源によって96.34%と96.5%の2つの値が確認されています。どちらの値も業界平均を上回っており、プレイヤーにとって有利な還元率と言えるでしょう。",
        "**ボラティリティ（変動率）について:** このスロットは「高ボラティリティ」に分類されます。これは、勝利が発生する頻度は比較的低いものの、一度勝利が発生すると高額な配当が得られる可能性があることを意味します。そのため、じっくりと腰を据えてプレイしたいプレイヤーや、大きな勝利を狙いたいプレイヤーに適しています。",
        "**ベット額について:** 最小ベット額は日本円で50円（約$0.50）、最大ベット額は10,000円（約$100）となっています。この範囲は、低予算のプレイヤーからハイローラーまで、幅広い層のプレイヤーが自分のプレイスタイルに合わせて調整できるようになっています。",
      ],
    },
    {
      heading: "3. どこで遊べるか",
      paragraphs: [
        "ドキドキ夏祭りは、Microgaming（Games Global）のゲームを取り扱っているオンラインカジノでプレイできます。CasinoTsu 推薦の以下のカジノでは、お得なボーナスと共にこのスロットを楽しむことが可能です。",
      ],
      table: {
        title: "おすすめカジノ",
        columns: ["カジノ名", "ボーナス内容", "特徴"],
        rows: [
          ["Vera & John（ベラジョン）", "ジャパカジ限定！フリースピン150回（入金不要ボーナス）", "オンカジの代名詞！初心者から上級者まで満足できるゲーム数と使いやすさ。"],
          ["InterCasino（インターカジノ）", "ジャパカジ限定！$30（入金不要ボーナス）", "20年以上の歴史を持つ老舗カジノ。信頼性が高く、豊富なプロモーションが魅力。"],
          ["遊雅堂（無料版も対応）", "ジャパカジ限定！¥3,000（入金不要ボーナス）", "和風テイストが特徴。パチンコ・パチスロ機種も豊富で、日本円でプレイ可能。"],
          ["Golden Panda", "ボーナス賭け条件30倍、フリースピン賭け条件30倍", "出金が基本的に即時反映でストレスフリー。"],
          ["Betgoat", "ボーナスなし", "独自コインも利用可能！最新クリプトカジノ。"],
          ["2up", "ボーナスなし", "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。"],
          ["1win", "ボーナスなし", "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ。"],
          ["Miki", "ボーナス賭け条件30倍、フリースピン賭け条件20倍", "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！"],
          ["WSM Casino", "ボーナスなし", "時代の最先端？！「ミームコイン」×「オンラインカジノ」。"],
          ["Betpanda", "ボーナスなし", "匿名で安全に遊べるクリプトオンラインカジノ！"],
          ["Duelbits", "ボーナスなし", "500フリースピンが嬉しいクリプトカジノ♪"],
          ["Dafabet", "ボーナス賭け条件20倍", "セルティックFCのスポンサーカジノ。"],
          ["Lucky Block", "ボーナス€25,000、フリースピン賭け条件35倍", "独自トークンもある仮想通貨カジノ♪"],
          ["Roobet", "ボーナスなし", "世界的有名人がアンバサダーを務めるオンラインカジノ！"],
          ["BC.Game", "ボーナス賭け条件45倍、フリースピン賭け条件60倍", "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！"],
          ["Wonder Casino", "ボーナスなし", "業界最速の出金スピードと仮想通貨特化ボーナス！"],
          ["OhMySpins", "ボーナス賭け条件35倍、フリースピン賭け条件40倍", "マニアックなプロバイダーもココなら見つかる！"],
          ["Yuugado", "ボーナスなし", "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！"],
          ["Lilibet", "ボーナスなし", "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！"],
          ["Konibet", "ボーナスなし", "パチンコ・パチスロが遊べるオンラインカジノ！"],
          ["Casino Me", "ボーナス賭け条件20倍、フリースピン賭け条件20倍", "独自システムのお得なキャッシュバックあり！"],
          ["Mystino", "ボーナスなし", "日本人プレイヤーの心をグッと掴むカジノといえば…！"],
          ["InterCasino", "ボーナスなし", "実は20年以上歴史のあるカジノはココ！"],
          ["Empire777", "ボーナス賭け条件20倍", "アジアNo.1を豪語するオンカジはここだ！"],
          ["Joy Casino", "ボーナスなし", "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！"],
          ["Vera&John", "ボーナスなし", "オンカジといえば、やっぱりベラジョン！"],
          ["Bitcasino.io", "ボーナス賭け条件40倍", "元祖仮想通貨カジノ！"],
          ["Eldoah Casino", "ボーナスなし", "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ。"],
        ],
      },
      paragraphs: [
        "**デモプレイについて:** ドキドキ夏祭りは、多くのオンラインカジノで無料のデモモードでプレイすることが可能です。実際の資金を使わずにゲームのルールやフィーチャーを体験できるため、初心者の方でも安心して試すことができます。",
      ],
    },
    {
      heading: "4. ゲーム特徴・フィーチャー",
      paragraphs: [
        "ドキドキ夏祭りは、日本の夏祭りをテーマにしたユニークなボーナス機能が満載です。",
      ],
      bullets: [
        "**リスピン:** リール上にハート型の「RESPIN」シンボルが3つ停止すると、追加で1回のスピンが得られます。これは、配当成立やボーナスへの期待感を高めるシンプルな機能です。",
        "**カードボーナス:** 「カードボーナス」シンボルがリールに出現すると、このボーナスラウンドが発動します。プレイヤーは5枚のカードから1枚を選び、その結果に応じて配当またはフリースピンを獲得できます。配当は賭け金の5倍から最大50倍までと、通常モードでもコツコツと賞金を積み上げられるチャンスがあります。また、カードボーナスで「7」のシンボルが出現した場合、フリースピンラウンドへ直接突入することもあります。",
        "**フリースピン:** 「7」と描かれたスキャッターシンボル（フリースピンシンボル）が3つ揃うと、フリースピンラウンドが開始されます。",
        "**フリースピンの選択肢:** フリースピンラウンドでは、3人の可愛らしい女の子（黄色、ピンク、青）から1人を選びます。それぞれ異なるスピン回数と、ランダムに出現するマルチプライヤーの組み合わせを持っています。",
        "**フリースピン中のフィーチャー:** フリースピン中にリール上にハート型のマルチプライヤーシンボルがランダムに出現し、勝利金に掛けられます。さらに、フリースピン中に「7」のシンボルが3つ揃うと、フリースピンの回数が7回追加されます。",
        "**かき氷ボーナス:** フリースピンラウンド中に「かき氷」シンボルが出現すると、かき氷ボーナスが発動します。選んだキャラクターに対応した色のかき氷が登場し、その大きさに応じた配当が得られます。一番大きいかき氷が最も高額な配当となります。プレイヤーはキャラクターの応援に合わせて、ひたすらクリックしてかき氷を食べ進めます。",
        "**シングルリール停止機能:** ベースゲーム中、プレイヤーは個々のリールを個別に停止させることが可能です（クイックスピンモードでは利用できません）。これにより、より戦略的にシンボルを配置し、勝利の可能性を高めることが可能です。",
      ],
      table: {
        title: "フリースピンの選択肢",
        columns: ["キャラクター", "フリースピン回数", "マルチプライヤー（選択肢）"],
        rows: [
          ["黄色い女の子", "7回", "4倍、7倍、10倍、20倍"],
          ["ピンク色の女の子", "10回", "3倍、5倍、7倍、10倍"],
          ["青色の女の子", "13回", "2倍、3倍、5倍、7倍"],
        ],
      },
    },
    {
      heading: "5. プロバイダー情報",
      paragraphs: [
        "ドキドキ夏祭りは、オンラインカジノ業界で長年の実績を持つ Microgaming（マイクロゲーミング）によって開発されました。近年、Microgamingは Games Global（ゲームズグローバル）というブランド名でも知られており、両方の名称で言及されることがあります。",
      ],
      table: {
        title: "プロバイダー情報",
        columns: ["項目", "詳細"],
        rows: [
          ["リリース日", "2022年8月1日"],
          ["ライセンス", "マルタ、UKギャンブリングコミッションなど多数"],
          ["他の人気作品", "Mega Moolah, Immortal Romance, Thunderstruck II"],
        ],
      },
    },
    {
      heading: "6. グラフィック・サウンド",
      paragraphs: [
        "ドキドキ夏祭りは、日本の夏祭りの雰囲気を忠実に再現した、鮮やかで可愛らしいグラフィックが特徴です。",
      ],
      bullets: [
        "**グラフィック:** 浴衣を着た3人の美少女キャラクターが、花火や屋台といった夏祭りの情景の中でプレイヤーを楽しませてくれます。パチスロ風のシンプルなレイアウトながらも、キャラクターの表情や祭りの小道具などが丁寧に描かれており、視覚的に楽しいゲームとなっています。",
        "**サウンド:** 夏祭りを連想させるお囃子や賑やかなBGMが流れ、ゲームの雰囲気を盛り上げます。キャラクターが登場する際には、可愛らしいアニメボイスも加わり、没入感を高めています。",
      ],
    },
    {
      heading: "7. ペイアウト・配当表",
      paragraphs: [
        "ドキドキ夏祭りのペイアウトは、シンボルの組み合わせとベット額によって決まります。ここでは、賭け額が¥100の場合の配当例を示します。",
      ],
      table: {
        title: "シンボル別配当（賭け額¥100の場合）",
        columns: ["シンボル", "配当倍率"],
        rows: [
          ["イチゴ🍓", "20倍"],
          ["パイナップル🍍", "10倍"],
          ["スイカ🍉", "5倍"],
          ["プラム", "3倍"],
          ["オレンジ🍊", "1倍"],
          ["ブドウ🍇", "0.7倍"],
          ["バナナ🍌", "0.4倍"],
          ["チェリー🍒", "0.2倍"],
        ],
      },
      bullets: [
        "**ペイライン:** ゲームは3リール3列のレイアウトで、5通りのペイラインが用意されています。左端のリールから右方向へ、同一シンボルが3つ揃うと配当が成立します。",
        "**最大配当倍率:** ドキドキ夏祭りの最大配当倍率は、なんと100,000倍です。",
      ],
    },
    {
      heading: "8. モバイル対応",
      paragraphs: [
        "ドキドキ夏祭りは、スマートフォンやタブレットなどのモバイルデバイスに完全対応しています。Microgaming（Games Global）はモバイルゲーム開発にも力を入れており、このスロットも例外ではありません。",
      ],
      bullets: [
        "**マルチデバイス対応:** iOS、Android、Windowsなど、主要なオペレーティングシステムを搭載したデバイスで快適にプレイできます。",
        "**レスポンシブデザイン:** デバイスの画面サイズに合わせてレイアウトが自動調整されるため、どのデバイスからでも見やすく、操作しやすいインターフェースを提供します。",
        "**スムーズなプレイ:** シンプルな3x3のリール構成と直感的な操作性により、外出先でもストレスなくゲームを楽しむことができます。",
      ],
    },
    {
      heading: "9. 戦略・攻略法",
      paragraphs: [
        "ドキドキ夏祭りは高ボラティリティのスロットであるため、戦略的なアプローチが勝利への鍵となります。",
      ],
      bullets: [
        "**ベット戦略:** 高ボラティリティを理解し、資金管理をしっかり行い、一度の大きな勝利を待つ心構えが必要です。ベット額は、ゲームの展開を見ながら徐々に調整するのがおすすめです。資金が十分にある場合は、最大ベット額でプレイすることで、最大配当のポテンシャルを最大限に引き出すことができます。",
        "**フィーチャー活用法:** 大当たりを狙うなら、マルチプライヤーが高い「黄色い女の子」を選択するのがおすすめです。ただし、スピン回数が少ないため、運の要素も大きくなります。より安定した勝利を目指すなら、「ピンク色の女の子」や「青色の女の子」も良い選択肢となります。カードボーナスは、フリースピンに繋がる可能性も秘めているため、侮れません。ベースゲームで、配当成立にあと一歩という状況では、シングルリール停止機能を活用して、勝利の可能性を探ってみましょう。",
        "**注意点:** ゲームの機能が多く、高ボラティリティであるため、オンラインスロット初心者の方には、最初はデモモードで十分に練習することをおすすめします。感情的にならず、冷静にプレイを続けることが重要です。",
      ],
    },
    {
      heading: "関連ゲーム",
      relatedGames: [
        {
          name: "ムーンプリンセス (Play'n GO)",
          href: "/slots/moon-princess",
          provider: "Play'n GO",
          description: "セーラー戦士風のキャラクターが登場する、高ボラティリティで人気のスロット。",
        },
        {
          name: "ハワイアンドリーム (JTG)",
          href: "/slots/hawaiian-dream",
          provider: "JTG",
          description: "ビキニ姿の女性が登場する、日本のパチスロファンにも人気のスロット。",
        },
      ],
    },
    {
      heading: "11. まとめ",
      paragraphs: [
        "ドキドキ夏祭りは、日本の夏祭りと萌え要素を融合させた、ユニークで魅力的なオンラインスロットです。Microgaming（Games Global）らしい高品質なグラフィックとサウンド、そしてパチスロ風の演出が、日本人プレイヤーの心を掴むことでしょう。 CasinoTsu は、このゲームの持つポテンシャルと魅力を、自信を持ってお勧めいたします。",
        "最大100,000倍という驚異的な最大配当ポテンシャルと、高ボラティリティは、一攫千金を狙うプレイヤーにとってたまらない魅力です。カードボーナス、フリースピン、かき氷ボーナスなど、多彩なフィーチャーがゲームを飽きさせず、常にドキドキする展開を提供してくれます。",
      ],
      bullets: [
        "こんなプレイヤーにおすすめ:",
        "日本の夏祭りの雰囲気が好きな方",
        "萌え系のキャラクターが登場するスロットが好きな方",
        "高ボラティリティで大きな勝利を狙いたい方",
        "パチスロ風のゲーム性を楽しみたい方",
        "ユニークなボーナス機能を体験したい方",
      ],
      paragraphs: [
        "初心者の方でも、デモモードで十分に練習を積めば、このエキサイティングな夏祭りを楽しむことができるはずです。 CasinoTsu は、皆様のオンラインカジノ体験を最大限にサポートいたします。",
      ],
    },
    {
      heading: "12. よくある質問",
      faq: [
        {
          q: "ドキドキ夏祭りはどのカジノで遊べますか？",
          a: "Microgaming（Games Global）のゲームを提供しているオンラインカジノでプレイできます。特に、ベラジョン、インターカジノ、遊雅堂などの人気カジノでも取り扱われています。CasinoTsu では、おすすめのカジノリストをご用意しておりますので、そちらもご参照ください。",
        },
        {
          q: "フリースピンの購入額はいくらですか？",
          a: "フリースピンの購入額は、現在の賭け額の50倍です。",
        },
        {
          q: "ジャックポット機能は搭載されていますか？",
          a: "いいえ、ドキドキ夏祭りにはジャックポット機能は搭載されていません。しかし、最大100,000倍という非常に高い最大配当ポテンシャルを持っています。",
        },
        {
          q: "ゲーム中に問題が発生した場合、どうすればいいですか？",
          a: "ゲーム中に問題が発生した場合は、まずはオンラインカジノのカスタマーサポートに連絡してください。状況を説明し、指示に従ってください。",
        },
        {
          q: "ドキドキ夏祭りにはピンク色、黄色、青色の女の子がいますが、何か特徴があるのですか？",
          a: "はい、フリースピンラウンドで選択できる3人の女の子は、それぞれスピンの回数とマルチプライヤーの選択肢が異なります。黄色い女の子は最も高いマルチプライヤー（最大20倍）を持っていますが、スピン回数は少なくなります。プレイヤーは自分のプレイスタイルに合わせてキャラクターを選ぶことができます。",
        },
        {
          q: "このスロットはモバイルでプレイできますか？",
          a: "はい、ドキドキ夏祭りはスマートフォンやタブレットなどのモバイルデバイスに完全対応しており、いつでもどこでも快適にプレイできます。",
        },
        {
          q: "RTP（還元率）とボラティリティについて教えてください。",
          a: "RTPは96.34%または96.5%で、ボラティリティは「高」です。これは、勝利頻度は低いものの、一度の勝利で高額な配当が得られる可能性があることを意味します。",
        },
      ],
    },
  ],
  similarGames: [
    {
      name: "ムーンプリンセス",
      href: "/slots/moon-princess",
      provider: "Play'n GO",
      description: "セーラー戦士風のキャラクターが登場する、高ボラティリティで人気のスロット。",
    },
    {
      name: "ハワイアンドリーム",
      href: "/slots/hawaiian-dream",
      provider: "JTG",
      description: "ビキニ姿の女性が登場する、日本のパチスロファンにも人気のスロット。",
    },
    ],
  prosCons: {
    pros: [
      "日本の夏祭りをテーマにしたユニークなデザインと萌え要素",
      "最大100,000倍という非常に高い最大配当ポテンシャル",
      "多彩なボーナス機能（カードボーナス、フリースピン、かき氷ボーナス）",
      "高ボラティリティで大きな勝利を狙える",
      "パチスロ風のゲーム性が楽しめる",
      "モバイルデバイスに完全対応",
      "シングルリール停止機能で戦略的なプレイが可能",
    ],
    cons: [
      "高ボラティリティのため、勝利頻度が低い場合がある",
      "初心者にはやや複雑に感じられる可能性がある",
      "ジャックポット機能は搭載されていない",
    ],
  },
  faq: [
    {
      q: "ドキドキ夏祭りはどのカジノで遊べますか？",
      a: "Microgaming（Games Global）のゲームを提供しているオンラインカジノでプレイできます。特に、ベラジョン、インターカジノ、遊雅堂などの人気カジノでも取り扱われています。CasinoTsu では、おすすめのカジノリストをご用意しておりますので、そちらもご参照ください。",
    },
    {
      q: "フリースピンの購入額はいくらですか？",
      a: "フリースピンの購入額は、現在の賭け額の50倍です。",
    },
    {
      q: "ジャックポット機能は搭載されていますか？",
      a: "いいえ、ドキドキ夏祭りにはジャックポット機能は搭載されていません。しかし、最大100,000倍という非常に高い最大配当ポテンシャルを持っています。",
    },
    {
      q: "ゲーム中に問題が発生した場合、どうすればいいですか？",
      a: "ゲーム中に問題が発生した場合は、まずはオンラインカジノのカスタマーサポートに連絡してください。状況を説明し、指示に従ってください。",
    },
    {
      q: "ドキドキ夏祭りにはピンク色、黄色、青色の女の子がいますが、何か特徴があるのですか？",
      a: "はい、フリースピンラウンドで選択できる3人の女の子は、それぞれスピンの回数とマルチプライヤーの選択肢が異なります。黄色い女の子は最も高いマルチプライヤー（最大20倍）を持っていますが、スピン回数は少なくなります。プレイヤーは自分のプレイスタイルに合わせてキャラクターを選ぶことができます。",
    },
    {
      q: "このスロットはモバイルでプレイできますか？",
      a: "はい、ドキドキ夏祭りはスマートフォンやタブレットなどのモバイルデバイスに完全対応しており、いつでもどこでも快適にプレイできます。",
    },
    {
      q: "RTP（還元率）とボラティリティについて教えてください。",
      a: "RTPは96.34%または96.5%で、ボラティリティは「高」です。これは、勝利頻度は低いものの、一度の勝利で高額な配当が得られる可能性があることを意味します。",
    },
  ],
  cta: {
    text: "今すぐプレイ",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdoki-doki-fireworks",
  },
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Doki doki fireworks", href: "https://casinotsu.com/slots/doki-doki-fireworks" },
  ],
  tableOfContents: [
    { label: "1. 導入・概要", href: "#1-導入・概要" },
    { label: "2. ゲーム基本情報", href: "#2-ゲーム基本情報" },
    { label: "3. どこで遊べるか", href: "#3-どこで遊べるか" },
    { label: "4. ゲーム特徴・フィーチャー", href: "#4-ゲーム特徴・フィーチャー" },
    { label: "5. プロバイダー情報", href: "#5-プロバイダー情報" },
    { label: "6. グラフィック・サウンド", href: "#6-グラフィック・サウンド" },
    { label: "7. ペイアウト・配当表", href: "#7-ペイアウト・配当表" },
    { label: "8. モバイル対応", href: "#8-モバイル対応" },
    { label: "9. 戦略・攻略法", href: "#9-戦略・攻略法" },
    { label: "10. 類似ゲーム", href: "#10-類似ゲーム" },
    { label: "11. まとめ", href: "#11-まとめ" },
    { label: "12. よくある質問", href: "#12-よくある質問" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/doki-doki-fireworks" />;
}
