import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Dragon Reborn スロットレビュー | 特徴・ボーナス・評価・おすすめカジノ",
  hero: {
    title: "Dragon Reborn",
    subheading: "ドラゴンリボーン",
    description: "2000年代のパチスロのような、学園、バトル、美少女といった要素が融合したパチスロ風スロットゲーム「Dragon Reborn」をご紹介します。頻繁に訪れる大当たりと、中毒性の高いゲーム演出、そして魅力的なスペックについて、CasinoTsuが詳しく解説いたします😉",
    score: 4.7,
    scoreMax: 5,
    rtp: "97%",
    maxMultiplier: "x1,500",
    provider: "Manna Play",
    releaseDate: "2021-09-30",
    volatility: "中",
    reels: "5",
    paylines: "5",
    minBet: "$0.2",
    maxBet: "$100",
    slotImageSrc: "/slots/dragon-reborn.jpg",
    highlights: [
      "パチスロ風の懐かしい演出",
      "学園・バトル・美少女テーマ",
      "頻繁に訪れる大当たり",
      "中毒性の高いゲーム演出",
      "アニメのようなストーリー展開",
      "最大配当倍率 x1,500",
      "RTP 97%",
    ],
    watchouts: [
      "通常モードのゲーム性はややシビアな場合がある",
    ],
  },
  featuredCasino: {
    name: "WSM Casino",
    logo: "/assets/casino/wsm-casino.png",
    href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fdragon-reborn",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fdragon-reborn",
    tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
  },
  casinos: [
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "30x 賭け条件, $4,000",
      freeSpins: "20x 賭け条件, 200",
      wagering: "30x",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/wsm-casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Betpanda",
      logo: "/images/casino/betpanda_375x375-1.png",
      href: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Wonder Casino",
      logo: "/images/casino/wonder-casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Yuugado",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "20x 賭け条件, $1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Vera&John",
      logo: "/images/casino/vera-john_375x375-1.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "40x 賭け条件, ¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fdragon-reborn",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fdragon-reborn",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fdragon-reborn",
    },
  ],
  gameInfo: {
    intro: "「ドラゴンリボーン（Dragon Reborn）〜竜魂転生〜」は、2000年代のパチスロを彷彿とさせる懐かしい雰囲気に、学園、バトル、美少女といった魅力的なテーマを組み合わせた、パチスロ風スロットゲームです。アニメのようなストーリー展開と、頻繁に訪れる大当たりにより、時間を忘れて没頭してしまうことでしょう。CasinoTsuでは、その詳細なゲーム演出とスペックを徹底的にご紹介いたします😉",
    basicInfo: {
      rtp: "97%",
      volatility: "中",
      reels: "5",
      paylines: "5",
      minBet: "$0.2",
      maxBet: "$100",
      provider: "Manna Play",
      releaseDate: "2021-09-30",
    },
  },
  payoutTable: {
    title: "シンボルと配当表",
    symbols: [
      {
        name: "7 (赤)",
        description: "フリースピンまたは連続フリースピン",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "7 (青)",
        description: "フリースピンまたは連続フリースピン",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "7 (紫)",
        description: "フリースピンまたは連続フリースピン",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "邪龍",
        description: "ボーナスラウンド突入のトリガー",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "魂",
        description: "リスピンのトリガー（4連続でボーナススピンへ）",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "主人公",
        payout5: "x8",
        payout4: "",
        payout3: "x1.6",
      },
      {
        name: "ヒロインA",
        payout5: "x6",
        payout4: "",
        payout3: "x1.2",
      },
      {
        name: "ヒロインB",
        payout5: "x5",
        payout4: "",
        payout3: "x1",
      },
      {
        name: "ヒロインC",
        payout5: "x4",
        payout4: "",
        payout3: "x0.8",
      },
      {
        name: "ヒロインD",
        payout5: "x3",
        payout4: "",
        payout3: "x0.6",
      },
      {
        name: "ヒロインE",
        payout5: "x2",
        payout4: "",
        payout3: "x0.4",
      },
    ],
    maxPayout: "x1,500",
    notes: [
      "6種類のノーマルシンボルは、3つ揃った場合にベット額の0.4倍から8倍までの配当が得られます。",
      "フリースピンボーナスをトリガーするのは、画面右上にある水色の「魂」シンボルです。これを3つ揃え、かつ4連続で引き当てるとボーナスステージ「FREE GAME MODE」に突入します。",
      "「7」のシンボルは赤、青、紫の3種類があり、それぞれフリースピンや連続フリースピンといった特典が付与されます。",
      "ボーナスラウンド突入のトリガーとなる左上の「邪龍」シンボルも重要です。",
      "「Special Bonus」という、突発的にボーナスステージに突入する「生入り」のパターンも存在します。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "リスピン",
        description: "「魂」シンボルが4連続で揃うとリスピンに突入。疾走感あふれるBGMと共に期待感が高まります。発生頻度は約10回に1回程度。",
        icon: "",
      },
      {
        name: "ボーナススピン",
        description: "リスピンからさらに3〜4回に1度の頻度でボーナススピンに突入。赤竜モード（双竜乱舞）と青竜モード（邪竜モード）の2種類があります。",
        icon: "",
      },
      {
        name: "BIG WIN",
        description: "ボーナススピン中のバトルに勝利すると獲得。最大賞金額は1,500倍まで膨れ上がります。",
        icon: "",
      },
      {
        name: "アニメ風演出",
        description: "キャラクターのボイスやストーリー展開など、アニメを見ているかのような体験が楽しめます。",
        icon: "",
      },
      {
        name: "懐かしのパチスロ風",
        description: "2000年代のパチスロを彷彿とさせるグラフィック、BGM、演出が特徴です。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "1. 導入・概要（Introduction & Overview）",
      paragraphs: [
        "「ドラゴンリボーン（Dragon Reborn）〜竜魂転生〜」は、2000年代のパチスロを彷彿とさせる懐かしい雰囲気に、学園、バトル、美少女といった魅力的なテーマを組み合わせた、パチスロ風スロットゲームです。アニメのようなストーリー展開と、頻繁に訪れる大当たりにより、時間を忘れて没頭してしまうことでしょう。CasinoTsuでは、その詳細なゲーム演出とスペックを徹底的にご紹介いたします😉",
      ],
    },
    {
      heading: "2. ゲーム基本情報（Basic Game Info）",
      paragraphs: [
        "「僕のヒーローアカデミア」や「呪術廻戦」を彷彿とさせる、まるでアニメのような世界観を持つこのスロットは、一体どのようなゲームなのでしょうか？🤣 CasinoTsuが、ストーリー展開も楽しめる新感覚スロット「ドラゴンリボーン（Dragon Reborn）〜竜魂転生〜」の魅力を紐解いてまいります！",
        "懐かしさを感じるパチスロのようなグラフィック、BGM、そしてアニメーションは、細部までこだわり抜かれております✌️",
      ],
      table: {
        title: "概要",
        columns: ["概要", "詳細"],
        rows: [
          ["名称", "Dragon Reborn"],
          ["リリース日", "2021-09-30"],
          ["プロバイダー", "Manna Play"],
          ["最大配当倍率", "x1,500"],
          ["最大ベット額", "$100"],
          ["RTP", "97%"],
          ["ボラティリティ", "中"],
          ["リール数", "5"],
          ["ペイライン数", "5"],
          ["行数", "3"],
          ["最小ベット額", "$0.2"],
        ],
      },
    },
    {
      heading: "3. どこで遊べるか（Where to Play）",
      paragraphs: [
        "「ドラゴンリボーン」は、当初 [ベラジョン（Vera & John）](https://casinotsu.com/reviews/vera-john) で限定リリースされましたが、現在では多くのオンラインカジノでプレイ可能となっております。以下に、このスロットが遊べるCasinoTsu厳選のおすすめカジノと、それぞれのボーナス情報をご紹介いたします。",
      ],
    },
    {
      heading: "4. ゲーム特徴・フィーチャー（Game Features）",
      paragraphs: [
        "### ・リスピンの頻度",
        "ゲームを開始するとすぐに、リスピンの頻度の高さに気づかれることでしょう。CasinoTsuの調査では、約10回に1回の割合で「魂」シンボルが4連続で揃い、リスピンに突入しました。最も頻繁に発生した場合は5回に1度、最も間隔が空いた場合は18回に1度でした。",
        "リスピンが発生すると、疾走感あふれるBGMが流れ、ゲームの雰囲気が一層盛り上がり、期待感が掻き立てられます😆😆",
        "### ・フィーチャー",
        "リスピンからさらに、3〜4回に1度の頻度でボーナススピンに突入しました🔥🔥",
        "ボーナススピンには、『赤龍ボーナス』と『青竜ボーナス』の2種類があり、以下のようにモードが切り替わります。（まるで『僕のヒーローアカデミア』のキャラクターのような、魅力的なヒロインが登場します！）",
        "- **赤竜モード** 👉 「双竜乱舞」が発動します。",
        "- **青竜モード** 👉 「邪竜モード」が発動します。",
        "「双竜モード」では、双竜と主人公の3人が対戦する演出が楽しめます。",
        "フィーチャーの発生間隔が非常に短いのが印象的です。100回のスピンで2〜3回フィーチャーが発動するのは、プレイヤーにとって有難いことです。一方で、非常に賑やかなゲーム展開となるため、常にエキサイティングなプレイを求める方には最適と言えるでしょう👍",
        "✅ **CasinoTsu からのアドバイス：**<br>通常モードのゲーム中は、リターンの獲得が厳しい場面もございます。損失が大きくなりそうな場合は、深追いせず冷静な判断を心がけることが重要です。",
      ],
    },
    {
      heading: "5. プロバイダー情報（Developer Info）",
      paragraphs: [
        "「ドラゴンリボーン」は、マルタを拠点とするゲームプロバイダー、**Manna Play** 社によって開発されました。Manna Play社は、忍者、侍、ムエタイ、龍といった日本やアジアの文化をモチーフにしたゲームを数多く手がけており、そのユニークなテーマとエンターテイメント性の高いゲームデザインで広く知られています。",
      ],
      bullets: [
        "**開発会社:** Manna Play",
        "**ライセンス:** （※具体的なライセンス情報は公開されておりませんが、オンラインカジノで提供されていることから、適切なライセンスを取得していると考えられます。）",
        "**リリース日:** 2021-09-30",
        "**他の人気作品:**",
        "    *   「大正ロマンス」（「鬼滅の刃」の無限列車編を彷彿とさせるテーマのスロット）",
        "    *   その他、日本やアジアの文化をモチーフにした多数のスロット",
      ],
    },
    {
      heading: "6. グラフィック・サウンド（Visual & Audio）",
      table: {
        columns: ["項目", "内容"],
        rows: [
          ["グラフィックス", "2D"],
          ["モバイル版対応", "👍"],
          ["BGM", "疾走感あるハードビート"],
          ["特殊効果", "声優によるボイス（サウンドエフェクト）あり"],
        ],
      },
      paragraphs: [
        "オープニングから流れる、疾走感あふれるリードギターのBGMは、プレイヤーの心を掴むこと間違いなしです。「これは格好良い！」と期待が高まります。😚",
        "まず、通常モードでは、主人公の日常や学校風景がゲームの背景として描かれます。（キャラクターの吹き出しに表示されるセリフの翻訳は、時にユーモラスで、逆に面白さを見出すことができます。）",
        "4連続で「魂」シンボルが3つ揃うと、クラスに悪霊が出現し、ヒロインたちに取り憑きます。「闇堕ち」したヒロインを救い出すために、ボーナスステージでのバトルが開始されます！",
        "**このリスピン演出時のBGMの盛り上がりは、熱心なパチスロファンをも魅了するほどの、強烈なワクワク感を演出してくれます💕**",
        "往年のスロット（2000年代頃）を思わせるBGMやグラフィック演出は、プレイヤーに心地よい懐かしさを提供します😆",
        "シンボルを揃えてバトルに勝利し、ヒロインを救出できれば「BIG WIN」獲得です！（おめでとうございます！🎉）🤑💰",
      ],
    },
    {
      heading: "7. ペイアウト・配当表（Payout Table）",
      paragraphs: [
        "### ・シンボルと配当表",
        "6種類のノーマルシンボルは、3つ揃った場合にベット額の0.4倍から8倍までの配当が得られます。フリースピンボーナスをトリガーするのは、画面右上にある水色の「魂」シンボルです。これを3つ揃え、かつ4連続で引き当てると **ボーナスステージ「FREE GAME MODE」に突入** します😆",
        "「7」のシンボルは赤、青、紫の3種類があり、それぞれフリースピンや連続フリースピンといった特典が付与されます。また、ボーナスラウンド突入のトリガーとなる左上の「邪龍」シンボルも重要です。",
        "さらに、「Special Bonus」という、突発的にボーナスステージに突入する「生入り」のパターンも存在します。平均して50回転につき16.66%の出現率とされていますが、CasinoTsuの実践では100回転以上一度も出ないこともあれば、50回転で2回出現することもありました😂",
        "### ・ペイライン",
        "リールレイアウトは、基本的な5リール3行の構成となっており、**5通りのペイライン**（横一列に上段・中段・下段、および斜めに2本）が設定されています。このシンプルな設計は、ペイライン上の結果と獲得賞金を把握しやすいという利点があります🤓",
        "### ・最大勝利金",
        "フリーゲーム中のイベントが連鎖することで、最大賞金額は1,500倍まで膨れ上がります。",
      ],
    },
    {
      heading: "8. モバイル対応（Mobile Compatibility）",
      paragraphs: [
        "「ドラゴンリボーン」は、HTML5技術を用いて開発されているため、スマートフォンやタブレットといったモバイルデバイスに完全対応しています。特別なアプリのダウンロードは不要で、お使いのデバイスのウェブブラウザから直接アクセスし、いつでもどこでも快適にプレイをお楽しみいただけます。グラフィックやサウンドも、モバイル環境に最適化されています。",
      ],
    },
    {
      heading: "9. 戦略・攻略法（Strategy & Tips）",
      paragraphs: [
        "### ・最低ベット、最大ベット",
        "ベット額の範囲は、最低$0.2から最大$100までとなっております。この幅広いベット範囲により、低予算のプレイヤーからハイローラーまで、ご自身のプレイスタイルに合わせて柔軟にベット額を調整することが可能です。",
        "### ・RTPとボラティリティ",
        "*   **RTP（還元率）:** ゲームプロバイダーである [Manna Play社](https://casinotsu.com/providers/manna-play) は、RTP値を97%と公表しています。これは市場平均と比較しても高い数値であり、 CasinoTsu は長期的にプレイヤーに有利な還元が期待できると考えております。",
        "*   **ボラティリティ:** 公式での発表はございませんが、CasinoTsu によるプレイ体験では「中ボラティリティ」であると体感いたしました。オートプレイで1時間試したところ、ベースゲーム時のリターンはやや渋い印象でしたが、ボーナスへの突入は頻繁で、$100前後の「BIG WIN」が何度か発生しました。これは、頻繁な小勝利は少ないものの、一度大きな勝利が発生するとまとまった金額を獲得できる可能性があることを示唆しています。",
        "### ・オートプレイ機能",
        "画面左下の「AUTO」ボタンをクリックすると、5、10、50、100、250、そして「∞（無制限）」の6段階でオートプレイを設定できます🙌 また、1スピンの速さは3段階で調整可能です。絵柄が揃う際のワクワク感を重視される方は、カスタムせずに「🐢」モードのままプレイすることをおすすめいたします。",
        "### ・プレイ中のエラーについて",
        "通信回線のトラブルやスマートフォンの電池切れなど、プレイ中に予期せぬ問題が発生する可能性もございます。ほとんどのオンラインカジノでは、**プレイ中にエラーが発生した場合、再ログインすることで問題発生時の画面からプレイを再開できます**。残高が失われることは通常ありませんが、万が一の場合は、速やかに[カスタマーサポート](https://casinotsu.com/about/contact) へお問い合わせください。",
      ],
    },
    {
      heading: "10. 類似ゲーム（Similar Games）",
      paragraphs: [
        "パチスロ風スロットとしては、Golden Hero社の『 [Dream of Gold（金蛙神）](https://casinotsu.com/slots/dreams-of-gold)』や『 [Hawaiian Dream](https://casinotsu.com/slots/hawaiian-dream)』などが有名ですが、「ドラゴンリボーン」と同様に、懐かしさと興奮を味わえるゲームは他にも存在します。",
        "「ドラゴンリボーン」と似た雰囲気のゲームをお探しであれば、大手ゲームプロバイダーGolden Hero社が提供する以下のタイトルもおすすめです。",
      ],
      bullets: [
        "[花魁ドリーム](https://casinotsu.com/slots/oiran-dream)",
        "[Hawaiian Dream](https://casinotsu.com/slots/hawaiian-dream)",
        "[Dreams of Gold （金蛙神）](https://casinotsu.com/slots/dreams-of-gold)",
      ],
    },
    {
      heading: "11. まとめ（Summary / Conclusion）",
      paragraphs: [
        "「ドラゴンリボーン」は、2000年代のパチスロを彷彿とさせる懐かしいグラフィックとサウンド、そして学園×バトル×美少女というユニークなテーマが融合した、非常に魅力的なスロットゲームです。頻繁に訪れるリスピンやボーナスステージ、そしてアニメのようなストーリー展開が、プレイヤーを飽きさせません。",
        "通常モードのゲーム性はややシビアな側面もありますが、ボーナスラウンドでの大きな勝利の可能性を秘めています。特に、実店舗のパチスロファンや、アニメのようなストーリー性を重視するプレイヤーにとっては、まさに「ドはまり」すること間違いなしのゲームと言えるでしょう。",
        "CasinoTsuとしては、通常モードのゲーム背景アニメーションやセリフのバリエーションがさらに豊富であれば、より一層楽しめるかと存じますが、全体として非常に満足度の高い体験を提供してくれるスロットです。",
      ],
    },
    {
      heading: "12. よくある質問（FAQ）",
      faq: [
        {
          q: "Dragon Rebornはどのプロバイダーのスロットですか？",
          a: "マルタを拠点とするManna Play社によってリリースされています。同社は、忍者、侍、ムエタイ、龍など、日本やアジアの文化をモチーフにしたゲームを多数開発しており、ユニークなテーマとエンターテイメント性の高いゲームデザインが特徴です。",
        },
        {
          q: "Dragon Rebornはどのようなスロットゲームですか？",
          a: "キャラクターが登場し、吹き出しでストーリーが展開されたり、アニメさながらの声優によるボイスが聞けたりと、単なるスロットプレイにとどまらず、アニメを視聴しているような感覚で楽しめるゲームです。パチスロ風の演出とバトル要素が融合し、懐かしさと新しさを兼ね備えた体験を提供します。",
        },
      ],
    },
  ],
  similarGames: [
    {
      name: "花魁ドリーム",
      href: "https://casinotsu.com/slots/oiran-dream",
      provider: "Golden Hero",
      description: "日本の文化をテーマにした、セクシーな演出が特徴のスロット。",
    },
    {
      name: "Hawaiian Dream",
      href: "https://casinotsu.com/slots/hawaiian-dream",
      provider: "Golden Hero",
      description: "リゾート感あふれるハワイをテーマにした、シンプルながらも熱い演出が魅力のスロット。",
    },
    {
      name: "Dreams of Gold （金蛙神）",
      href: "https://casinotsu.com/slots/dreams-of-gold",
      provider: "Golden Hero",
      description: "日本のパチスロを彷彿とさせる演出と、高配当が期待できる「ドキドキ」演出が特徴のスロット。",
    },
  ],
  prosCons: {
    pros: [
      "パチスロ風の懐かしい演出とサウンド",
      "学園・バトル・美少女といったユニークなテーマ",
      "頻繁に訪れるリスピンとボーナスステージ",
      "アニメのようなストーリー展開とボイス演出",
      "RTP 97%と高め",
      "最大配当倍率 x1,500",
      "モバイル対応でいつでもどこでもプレイ可能",
    ],
    cons: [
      "通常モードのゲーム性はややシビアな場合がある",
      "演出が賑やかなため、落ち着いたプレイを好む人には不向きな可能性",
    ],
  },
  faq: [
    {
      q: "Dragon Rebornはどのプロバイダーのスロットですか？",
      a: "マルタを拠点とするManna Play社によってリリースされています。同社は、忍者、侍、ムエタイ、龍など、日本やアジアの文化をモチーフにしたゲームを多数開発しており、ユニークなテーマとエンターテイメント性の高いゲームデザインが特徴です。",
    },
    {
      q: "Dragon Rebornはどのようなスロットゲームですか？",
      a: "キャラクターが登場し、吹き出しでストーリーが展開されたり、アニメさながらの声優によるボイスが聞けたりと、単なるスロットプレイにとどまらず、アニメを視聴しているような感覚で楽しめるゲームです。パチスロ風の演出とバトル要素が融合し、懐かしさと新しさを兼ね備えた体験を提供します。",
    },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fdragon-reborn",
  },
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Dragon reborn", href: "https://casinotsu.com/slots/dragon-reborn" },
  ],
  tableOfContents: [
    { label: "1. 導入・概要", href: "#introduction-overview" },
    { label: "2. ゲーム基本情報", href: "#basic-game-info" },
    { label: "3. どこで遊べるか", href: "#where-to-play" },
    { label: "4. ゲーム特徴・フィーチャー", href: "#game-features" },
    { label: "5. プロバイダー情報", href: "#developer-info" },
    { label: "6. グラフィック・サウンド", href: "#visual-audio" },
    { label: "7. ペイアウト・配当表", href: "#payout-table" },
    { label: "8. モバイル対応", href: "#mobile-compatibility" },
    { label: "9. 戦略・攻略法", href: "#strategy-tips" },
    { label: "10. 類似ゲーム", href: "#similar-games" },
    { label: "11. まとめ", href: "#summary-conclusion" },
    { label: "12. よくある質問", href: "#faq" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/dragon-reborn" />;
}
