import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "祭（Matsuri）- オンラインスロットレビュー",
  hero: {
    title: "祭（Matsuri）",
    subheading: "日本の「ノスタルジー」をリアルに感じることができるスロット",
    description: "ボーナスゲームは金魚すくい、シンボルにはかき氷と、夏祭り気分を存分に味わえる一作です。早速 CasinoTsu がレビューをお届けします！✨",
    score: 3.3,
    scoreMax: 5,
    rtp: "96.17%",
    maxMultiplier: "x3,000",
    provider: "Play’n GO",
    releaseDate: "2017年3月23日",
    volatility: "Medium to High",
    reels: "5",
    paylines: "25",
    minBet: "$0.25",
    maxBet: "$100",
    slotImageSrc: "/slots/matsuri.png",
    highlights: [
      "日本の夏祭りをテーマにしたユニークなデザイン",
      "金魚すくいボーナスゲームで最大ベット額の500倍を狙える",
      "フリースピン中に移動するワイルドシンボルが特徴",
      "コイン持ちが良く、比較的長くプレイできる",
    ],
    watchouts: [
      "中〜高ボラティリティのため、大きな勝利には時間がかかる場合がある",
      "ベースゲームでの小当たりが多いため、ボーナスフィーチャーを待つ忍耐力が必要",
    ],
  },
  featuredCasino: {
    name: "Golden Panda",
    logo: "/assets/casino/golden-panda.jpg",
    href: "https://casinotsu.com/reviews/golden-panda",
    ctaText: "詳細を見る",
    ctaHref: "https://casinotsu.com/reviews/golden-panda",
    tagline: "ゴールデンパンダ",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "30x 賭け条件",
      freeSpins: "30x 賭け条件",
      wagering: "¥850,000",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/golden-panda",
    },
    {
      name: "2up",
      logo: "/images/casino/2up_375x375.png",
      href: "https://casinotsu.com/reviews/2up",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、[最新オンラインカジノ](https://casinotsu.com/new-casinos)",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/2up",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      bonus: "30x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "$4,000",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんの[ボーナス](https://casinotsu.com/)でお得にプレイ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/miki",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/WSM_375x375-2.png",
      href: "https://casinotsu.com/reviews/wsm-casino",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "29x 賭け条件",
      wagering: "$1,000",
      freeSpins: "-",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新[仮想通貨カジノ](https://casinotsu.com/crypto)！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/bitz",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://casinotsu.com/reviews/wikibet",
      bonus: "20x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "¥50,000",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/wikibet",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://casinotsu.com/reviews/katsuwin",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/katsuwin",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "35x 賭け条件",
      freeSpins: "40x 賭け条件",
      wagering: "¥200,000",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/sushi-casino",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://casinotsu.com/reviews/parimatch",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/parimatch",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://casinotsu.com/reviews/duelbits",
      rating: 4,
      tagline: "500フリースピンが嬉しい[クリプトカジノ](https://casinotsu.com/crypto)♪",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/sportsbet-io",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "40x 賭け条件",
      wagering: "$2,020",
      freeSpins: "-",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/shuffle",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/winz-io",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "20x 賭け条件",
      wagering: "$500",
      freeSpins: "-",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/dafabet",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "35x 賭け条件",
      wagering: "50",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/lucky-block",
    },
    {
      name: "Ramenbet",
      logo: "/images/casino/ramenbet_375x375-1.png",
      href: "https://casinotsu.com/reviews/ramenbet",
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/ramenbet",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/Flush_375x375-1.png",
      href: "https://casinotsu.com/reviews/flush",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/flush",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "30x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "1,800USDT",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/queen-casino",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/roobet",
    },
    {
      name: "Casino Sky",
      logo: "/images/casino/casinosky_375x375.png",
      href: "https://casinotsu.com/reviews/casino-sky",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/casino-sky",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "35x 賭け条件",
      freeSpins: "40x 賭け条件",
      wagering: "1BTC",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/mega-dice",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "https://casinotsu.com/reviews/cosmoswin",
      bonus: "キャッシュバック 最大$10,000",
      freeSpins: "-",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/cosmoswin",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "45x 賭け条件",
      freeSpins: "60x 賭け条件",
      wagering: "$1,600",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/bc-game",
    },
    {
      name: "Stake",
      logo: "/images/casino/stake_375x375-1.png",
      href: "https://casinotsu.com/reviews/stake",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/stake",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wonder-casino",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/wonder-casino",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "35x 賭け条件",
      freeSpins: "40x 賭け条件",
      wagering: "¥65,000",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/ohmyspins",
    },
    {
      name: "Yuugado",
      logo: "/images/casino/yuugado_375x375-1.png",
      href: "https://casinotsu.com/reviews/yuugado",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/yuugado",
    },
    {
      name: "Tedbet",
      logo: "/images/casino/tedbet_375x375.png",
      href: "https://casinotsu.com/reviews/tedbet",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/tedbet",
    },
    {
      name: "BetRebels",
      logo: "/images/casino/betrebels_375x375.png",
      href: "https://casinotsu.com/reviews/betrebels",
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/betrebels",
    },
    {
      name: "Conquestador",
      logo: "/images/casino/Conquestador_375x375.png",
      href: "https://casinotsu.com/reviews/conquestador",
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/conquestador",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.jpg",
      href: "https://casinotsu.com/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: "-",
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/cloudbet",
    },
    {
      name: "Lilibet",
      logo: "/images/casino/lilibet_375x375.png",
      href: "https://casinotsu.com/reviews/lilibet",
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/lilibet",
    },
    {
      name: "Livecasino.io",
      logo: "/images/casino/livecasinoio.jpg",
      href: "https://casinotsu.com/reviews/livecasino-io",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/livecasino-io",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.jpg",
      href: "https://casinotsu.com/reviews/lucky-bull",
      bonus: "30x 賭け条件",
      wagering: "$917",
      freeSpins: "-",
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/lucky-bull",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.jpg",
      href: "https://casinotsu.com/reviews/gamdom",
      bonus: "$0",
      freeSpins: "-",
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/gamdom",
    },
    {
      name: "Energy Casino",
      logo: "/images/casino/energy-casino_375x375.png",
      href: "https://casinotsu.com/reviews/energy-casino",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/energy-casino",
    },
    {
      name: "Konibet",
      logo: "/images/casino/konibet_375x375.png",
      href: "https://casinotsu.com/reviews/konibet",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/konibet",
    },
    {
      name: "Vulkan Vegas",
      logo: "/assets/casino/vulkan-vegas.jpg",
      href: "https://casinotsu.com/reviews/vulkanvegas",
      bonus: "40x 賭け条件",
      freeSpins: "30x 賭け条件",
      wagering: "¥100,000",
      rating: 4,
      tagline: "アメコミの世界観に入り込んじゃえ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/vulkanvegas",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "20x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "$777",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/casino-me",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://casinotsu.com/reviews/mystino",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/mystino",
    },
    {
      name: "Trustdice",
      logo: "/images/casino/Trustdice_375x375.png",
      href: "https://casinotsu.com/reviews/trustdice",
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/trustdice",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://casinotsu.com/reviews/inter-casino",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/inter-casino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "20x 賭け条件",
      wagering: "$1,600",
      freeSpins: "-",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/empire777",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://casinotsu.com/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/pinnacle",
    },
    {
      name: "Justspin",
      logo: "/assets/casino/justspin.jpg",
      href: "https://casinotsu.com/reviews/just-spin",
      bonus: "50x 賭け条件",
      freeSpins: "50x 賭け条件",
      wagering: "$500",
      rating: 4,
      tagline: "シンプルなデザインで見やすいプラットフォーム",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/just-spin",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "https://casinotsu.com/reviews/winunique",
      bonus: "30x 賭け条件",
      freeSpins: "30x 賭け条件",
      wagering: "$330",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/winunique",
    },
    {
      name: "21.com",
      logo: "/assets/casino/21com.jpg",
      href: "https://casinotsu.com/reviews/21-com",
      bonus: "50x 賭け条件",
      freeSpins: "50x 賭け条件",
      wagering: "$1,000",
      rating: 4,
      tagline: "構造もシンプルで検索機能も使いやすい",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/21-com",
    },
    {
      name: "BitStarz",
      logo: "/images/casino/bitstarz_375x375.png",
      href: "https://casinotsu.com/reviews/bitstarz",
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/bitstarz",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino_375x375.png",
      href: "https://casinotsu.com/reviews/joycasino",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/joycasino",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casinos/casino-secret_375x375.png",
      href: "https://casinotsu.com/reviews/casino-secret",
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/casino-secret",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://casinotsu.com/reviews/vera-john",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/vera-john",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://casinotsu.com/reviews/live-casino-house",
      bonus: "20x 賭け条件",
      wagering: "¥50,000",
      freeSpins: "-",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "40x 賭け条件",
      wagering: "¥200,000",
      freeSpins: "-",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://casinotsu.com/reviews/casino-x",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "20x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "$500",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/casitabi",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://casinotsu.com/reviews/eldoah",
      rating: 4.5,
      tagline: "[ライブカジノ](https://casinotsu.com/live-casino)利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/eldoah",
    },
  ],
  gameInfo: {
    intro: "「MATSURI」は、PLAY’GO社が提供する5リール25ラインのお祭りをテーマにしたオンラインスロットです🎰 CasinoTsu では、このユニークなスロットの魅力に迫ります。",
    basicInfo: {
      rtp: "96.17% (一部情報源では94.15%と記載されている場合もありますが、一般的には96.17%とされています)",
      volatility: "Medium to High (中〜高)",
      reels: "5",
      paylines: "25",
      minBet: "$0.25",
      maxBet: "$100",
      provider: "Play’n GO",
      releaseDate: "2017年3月23日",
    },
  },
  payoutTable: {
    title: "ペイアウト・配当表",
    symbols: [
      {
        name: "着物の女性",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "提灯（ワイルド）",
        description: "スキャッターシンボルとボーナスシンボルを除く、他のどのシンボルの代わりにもなります。",
        payout5: "",
        payout4: "",
        payout3: "",
        isSpecial: true,
      },
      {
        name: "麺類（例：たこ焼き）",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "団子",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "扇子",
        payout5: "",
        payout4: "",
        payout3: "",
      },
      {
        name: "金魚（ボーナス）",
        description: "中央のリール（2, 3, 4リール）に出現すると、金魚ボーナスが発動します。",
        payout5: "",
        payout4: "",
        payout3: "",
        isSpecial: true,
      },
      {
        name: "仮面（スキャッター）",
        description: "リール1、3、5に3つ以上出現するとフリースピンに突入します。",
        payout5: "",
        payout4: "",
        payout3: "",
        isSpecial: true,
      },
    ],
    maxPayout: "x3,000 (ベット額の3,000倍、または75,000コイン)",
    notes: [
      "最高賞金金額は、ベット額と配当を掛けた値です。",
      "同じラインで2つの勝ちの組み合わせがそろうと、高額のほうの組み合わせに対する賞金が支払われます。",
      "2つ以上の有効なペイラインで勝ちの組み合わせがそろうと、勝利金額は合計されます。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "SCATTER(スキャッター)",
        description: "仮面の絵柄がスキャッターシンボルです。リール1、3、5に3つ以上出現するとフリースピンに突入します。フリースピンは8回からスタートし、最大20回まで再フリースピンが可能です。フリースピン中に出現したワイルドシンボルは、そのリール全体がワイルドに変化し、スピンごとに左方向へ移動していきます。",
        icon: "",
      },
      {
        name: "金魚ボーナス",
        description: "金魚絵柄のシンボルが中央のリール（2, 3, 4リール）に出現すると、金魚ボーナスが発動します✨ このミニゲームでは、金魚をすくってコインを獲得します。このボーナスラウンドでの最大配当は、ベット額の500倍となる可能性があります。",
        icon: "",
      },
      {
        name: "WILD(ワイルド)",
        description: "「祭」の絵柄がワイルドシンボルです。スキャッターシンボルとボーナスシンボルを除く、他のどのシンボルの代わりにもなり、配当を形成するのに役立ちます。フリースピン中には、ワイルドシンボルが出現したリール全体がワイルドに変化し、左方向へと移動していくユニークな動きを見せます。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "導入・概要",
      paragraphs: [
        "日本の「ノスタルジー」をリアルに感じることができるスロット、「祭（Matsuri）」。ボーナスゲームは金魚すくい、シンボルにはかき氷と、夏祭り気分を存分に味わえる一作です。早速 CasinoTsu がレビューをお届けします！✨",
      ],
    },
    {
      heading: "プロバイダー情報",
      paragraphs: [
        "Play’n GOは、モバイルゲーム開発で高い評価を得ているスウェーデンのゲームプロバイダーです。2005年の設立以来、革新的なゲームと高品質なグラフィックスで、世界中のオンラインカジノプレイヤーから支持されています。「Moon Princess（ムーンプリンセス）」や「Book of Dead（ブックオブデッド）」など、数々の人気タイトルをリリースしています。CasinoTsu は、Play’n GO社の正確で魅力的なゲーム体験を推薦いたします。",
      ],
    },
    {
      heading: "グラフィック・サウンド",
      paragraphs: [
        "★★★★☆　ー　 CasinoTsu の評価として、画面は大変美しく、お祭りの華やかさと、どこかノスタルジックな演出と雰囲気に魅了されます。アニメの影響を受けた繊細でパステルカラーの配色が特徴的です。",
        "★★★★☆　ー　世界観や雰囲気にあった音楽、お祭りという身近な環境、日本人にはなじみやすい感覚でプレイしていて楽しくなります。 CasinoTsu は、このサウンドデザインを高く評価しています。",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "「MATSURI」はPlay’n GO社によって開発されており、モバイルデバイスでのプレイに最適化されています。スマートフォンやタブレットで、いつでもどこでも快適にプレイを楽しむことができます。CasinoTsu は、この利便性を皆様に推奨いたします。",
      ],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "CasinoTsu は、[responsible gambling/responsible-gambling](https://casinotsu.com/responsible-gambling)を推奨しつつ、ゲームをより深く楽しむための戦略をお伝えします。",
        "**基本的なゲームプレイ**",
        "ベースゲームは、時にゆっくりとした展開になることもあり、忍耐力が必要な場合があります。しかし、頻繁にワイルドシンボルが出現するため、小当たりが多く、コイン持ちが良い傾向があります。CasinoTsu は、この安定したゲームフローを評価しています。",
        "ボーナスフィーチャー: フリースピンや金魚ボーナスといったフィーチャーが、このスロットの主な魅力と言えるでしょう。これらのボーナスラウンドで大きな勝利のチャンスがあります。",
        "**ベット戦略**",
        "最小ベットから: まずは最小ベット額の$0.25からプレイを開始し、ゲームの感覚を掴みましょう。",
        "最大ベットへ: ゲームに慣れてきたら、最大ベット額の$100まで段階的に上げていくことで、より大きな配当を狙うことができます。",
        "オートスピンの活用: オートスピン機能を使えば、ベット額を設定したまま自動でスピンを回すことができます。これにより、ゲーム展開に集中しやすくなります。 CasinoTsu は、この機能の効率的な活用を推奨します。",
        "**注意点**",
        "ボラティリティ: このスロットは中〜高ボラティリティに分類されます。つまり、頻繁に当たるわけではありませんが、当たるときは比較的大きな配当が期待できるということです。資金管理に注意しながらプレイしましょう。 CasinoTsu は、この点を強調して注意喚起いたします。",
        "ボーナスフィーチャーの頻度: ベースゲームでの勝利は比較的小さなものに留まることが多いですが、ボーナスフィーチャーのトリガーを待つことが、大きな勝利への鍵となります。 CasinoTsu は、このゲーム性を正確にお伝えします。",
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "「MATSURI」は、日本の夏祭りをテーマにした、ユニークで魅力的なオンラインスロットです。Play’n GOならではの高品質なグラフィックとサウンド、そして日本らしいノスタルジックな雰囲気が融合し、プレイヤーを飽きさせません。CasinoTsu は、このゲームの魅力を皆様にお届けいたします。",
        "**グラフィックとサウンド**",
        "★★★★☆　ー　お祭りの華やかさと、どこか懐かしさを感じるデザインが素晴らしいです。サウンドも世界観にマッチしており、没入感を高めてくれます。 CasinoTsu は、この点を高く評価しております。",
        "**ゲームプレイと面白さ**",
        "★★★★☆　ー　金魚すくいボーナスは特にユニークで、日本人プレイヤーならずとも楽しめるでしょう。ワイルドシンボルの頻繁な出現は、コイン持ちの良さにも繋がっており、ストレスなくプレイできます。フリースピン中のワイルドの動きもエキサイティングです。 CasinoTsu は、このゲームプレイの楽しさを保証いたします。",
        "**賞金獲得の可能性**",
        "★★★★☆　ー　ベースゲームでの小当たりが多い一方で、ワイルドが揃った時の破壊力は目を見張るものがあります。フリースピンや金魚ボーナスで大きな配当を狙える可能性も秘めています。 CasinoTsu は、この賞金獲得の可能性についても正確にお伝えいたします。",
        "**総合評価**",
        "★★★★☆　ー　評価4/5段階評価",
        "CasinoTsu は、この「MATSURI」スロットについて、その世界観、雰囲気、そして何よりも祭りの華やかさと楽しさの傍にある「ノスタルジック」な感情をうまく表現できている点を高く評価いたします。",
        "プレイしていて楽しかったし、ストレスもありませんでした。通常スピンでワイルドが頻繁に登場し、コイン持ちが良い印象でした。フリースピンでも同様にワイルドが出現することを考えると、一気にワイルドだらけになる場面も期待できます！皆様も提灯（ちょうちん）で画面がいっぱいになる体験を、ぜひお楽しみください。",
        "**こんなプレイヤーに CasinoTsu は「MATSURI」を推薦します:**",
        "日本の文化や夏祭りがお好きなプレイヤー",
        "ユニークなボーナスゲームやフィーチャーを楽しみたいプレイヤー",
        "ノスタルジックな雰囲気の[スロット](https://casinotsu.com/slots)を好むプレイヤー",
        "コイン持ちが良く、比較的長くプレイできるスロットを探しているプレイヤー",
      ],
    },
  ],
  similarGames: [
    {
      name: "Moon Princess",
      href: "",
      provider: "Play’n GO",
      description: "",
    },
    {
      name: "Book of Dead",
      href: "",
      provider: "Play’n GO",
      description: "",
    },
    {
      name: "Hanzo's Dojo",
      href: "",
      provider: "",
      description: "和風テーマ",
    },
    {
      name: "Sakura Fortune",
      href: "",
      provider: "",
      description: "和風テーマ",
    },
  ],
  prosCons: {
    pros: [
      "日本の夏祭りをテーマにしたユニークで魅力的なデザイン",
      "金魚すくいボーナスゲームはユニークで高配当の可能性あり",
      "フリースピン中の移動するワイルドシンボルがエキサイティング",
      "ベースゲームでのワイルドシンボルの出現頻度が高く、コイン持ちが良い",
      "サウンドデザインがお祭りの雰囲気にマッチしており没入感が高い",
      "モバイルデバイスに最適化されており、どこでもプレイ可能",
    ],
    cons: [
      "中〜高ボラティリティのため、大きな勝利には時間がかかる場合がある",
      "ベースゲームでの小当たりが多いため、ボーナスフィーチャーを待つ忍耐力が必要",
    ],
  },
  faq: [
    {
      q: "Matsuriはどのプロバイダーからリリースされましたか？",
      a: "ムーンプリンセスでおなじみのPlay’n GO社からリリースされました。",
    },
    {
      q: "Matsuriはどのカジノで遊ぶことができますか？",
      a: "VegasSlotsOnline、Casino Hipster、Slots Temple、AskGamblersなどのスロットレビューサイトでも紹介されており、CasinoTsu（カジノツウ）の提携カジノである、[ゴールデンパンダ](https://casinotsu.com/reviews/golden-panda)、[2アップカジノ](https://casinotsu.com/reviews/2up)、[ミキ](https://casinotsu.com/reviews/miki)などのオンラインカジノで遊ぶことができます。CasinoTsu は、これらのカジノでのプレイを推薦いたします。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "祭（Matsuri）", href: "" },
  ],
  tableOfContents: [
    { label: "導入・概要", href: "#導入・概要" },
    { label: "どこで遊べるか", href: "#どこで遊べるか" },
    { label: "CasinoTsu 推薦！「祭（Matsuri）」をプレイできるカジノ", href: "#CasinoTsu-推薦-祭（Matsuri）をプレイできるカジノ" },
    { label: "ゲーム基本情報", href: "#ゲーム基本情報" },
    { label: "ゲーム特徴・フィーチャー", href: "#ゲーム特徴・フィーチャー" },
    { label: "プロバイダー情報", href: "#プロバイダー情報" },
    { label: "グラフィック・サウンド", href: "#グラフィック・サウンド" },
    { label: "ペイアウト・配当表", href: "#ペイアウト・配当表" },
    { label: "モバイル対応", href: "#モバイル対応" },
    { label: "戦略・攻略法", href: "#戦略・攻略法" },
    { label: "類似ゲーム", href: "#類似ゲーム" },
    { label: "まとめ", href: "#まとめ" },
    { label: "よくある質問", href: "#よくある質問" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/matsuri" />;
}
