import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Fireworks Master（ファイアーワークス・マスター） | Playson | CasinoTsu",
  hero: {
    title: "Fireworks Master",
    subheading: "麻雀と花火の融合！ユニークなリールで勝利を掴む",
    description: "Playson（プレイソン）社が提供する「Fireworks Master」は、麻雀とオンラインスロットの要素を融合させた斬新なゲーム性、そして花火のように華やかなボーナスフィーチャーが特徴のスロットゲームです。最大で6,206倍の配当が期待でき、特別なボーナスゲームを体験できます。",
    score: 2.5,
    scoreMax: 5,
    rtp: "95.07%",
    maxMultiplier: "x6,206",
    provider: "Playson",
    releaseDate: "2017年9月19日",
    volatility: "中〜高",
    reels: "5",
    paylines: "通常時243通り、フリースピン中最大3125通り",
    minBet: "$0.50",
    maxBet: "$150",
    slotImageSrc: "/slots/firework-master.jpg",
    highlights: [
      "ユニークなマルチレイヤーリールと連鎖反応システム",
      "最大3125通りに広がるペイライン",
      "フリースピン中のフォーチュンホイールによる高配当の可能性",
      "高品質なグラフィックとサウンド",
      "モバイル最適化により、どこでもプレイ可能",
    ],
    watchouts: [
      "中〜高ボラティリティのため、勝利が安定しない場合がある",
      "RTPが平均的（95.07%）",
      "一部情報源では、配当が低いと感じるプレイヤーもいる可能性",
    ],
  },
  featuredCasino: {
    name: "1win",
    logo: "/assets/casino/1win.png",
    href: "#",
    ctaText: "今すぐプレイ！",
    tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.png",
      href: "/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "-",
      wagering: "30x",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.png",
      href: "/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      href: "/reviews/1win",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.png",
      href: "/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "WSM Casino",
      logo: "/assets/casino/wsm-casino.png",
      href: "/reviews/wsm-casino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.png",
      href: "/reviews/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casino/katsuwin.png",
      href: "/reviews/katsuwin",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.png",
      href: "/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Betpanda",
      logo: "/assets/casino/betpanda.png",
      href: "/reviews/betpanda",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.png",
      href: "/reviews/parimatch",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io.png",
      href: "/reviews/bets-io",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "/reviews/duelbits",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Sportsbet.io",
      logo: "/images/casino/sportsbet-io.png",
      href: "/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Winz",
      logo: "/images/casino/winz-io.png",
      href: "/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: "-",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.png",
      href: "/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/flush.png",
      href: "/reviews/flush",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.png",
      href: "/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Casino Sky",
      logo: "/assets/casino/casino-sky.png",
      href: "/reviews/casino-sky",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.png",
      href: "/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35x",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Fresh Casino",
      logo: "/assets/casino/fresh-casino.png",
      href: "/reviews/fresh-casino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.png",
      href: "/reviews/cosmoswin",
      bonus: "キャッシュバック 最大$10,000",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "BC.Game",
      logo: "/images/casino/bc-game.png",
      href: "/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45x",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      href: "/reviews/stake",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.png",
      href: "/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35x",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Tedbet",
      logo: "/assets/casino/tedbet.png",
      href: "/reviews/tedbet",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "BetRebels",
      logo: "/assets/casino/betrebels.png",
      href: "/reviews/betrebels",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Conquestador",
      logo: "/assets/casino/conquestador.png",
      href: "/reviews/conquestador",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.png",
      href: "/reviews/cloudbet",
      bonus: "5BTC",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Lilibet",
      logo: "/assets/casino/lilibet.png",
      href: "/reviews/lilibet",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Livecasino.io",
      logo: "/assets/jp/livecasino-io.png",
      href: "/reviews/livecasino-io",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.png",
      href: "/reviews/lucky-bull",
      bonus: "$917",
      freeSpins: "-",
      wagering: "30x",
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.png",
      href: "/reviews/gamdom",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Energy Casino",
      logo: "/assets/casino/energy-casino.png",
      href: "/reviews/energy-casino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.png",
      href: "/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Bons.com",
      logo: "/images/casino/bons.png",
      href: "/reviews/bons",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "マインクラフトチックでも中身はモダン",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      href: "/reviews/mystino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.png",
      href: "/reviews/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.png",
      href: "/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Casinoin",
      logo: "/assets/casino/casinoin.png",
      href: "/reviews/casinoin",
      bonus: "¥25,000",
      freeSpins: "200",
      wagering: "25x",
      rating: 4,
      tagline: "13種類の仮想通貨が利用可能なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.png",
      href: "/reviews/winunique",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30x",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "BitStarz",
      logo: "/assets/casino/bitstarz.png",
      href: "/reviews/bitstarz",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino.png",
      href: "/reviews/joycasino",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casino/casino-secret.png",
      href: "/reviews/casino-secret",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/jp/bitcasino-io.png",
      href: "/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      href: "/reviews/casino-x",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.png",
      href: "/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Eldoah Casino",
      logo: "/images/casino/eldoah.png",
      href: "/reviews/eldoah",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "#",
    },
    {
      name: "Slots.lv Casino",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
    {
      name: "Sloto'Cash Casino",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
    {
      name: "Jackpot Wheel Casino",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
    {
      name: "Casino Extreme",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
    {
      name: "Slotland",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
    {
      name: "Riobet Casino",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
    {
      name: "Stake Casino",
      href: "#",
      tagline: "その他のプレイ可能カジノ",
      ctaText: "詳細を見る",
      ctaHref: "#",
    },
  ],
  gameInfo: {
    intro: "「Fireworks Master」は、多層構造のリールと、画面を彩る花火のような演出がプレイヤーの没入感を高めるスロットゲームです。最大で6,206倍の配当が期待できるこのゲームで、特別なボーナスゲームを体験し、数多くの勝利を掴みましょう！",
    basicInfo: {
      rtp: "95.07%",
      volatility: "中〜高",
      reels: "5",
      paylines: "通常時243通り、フリースピンボーナス中は最大3125通りまで増加します。",
      minBet: "$0.50",
      maxBet: "$150",
      provider: "Playson",
      releaseDate: "2017年9月19日",
    },
  },
  payoutTable: {
    title: "ペイアウト・配当表",
    symbols: [
      {
        name: "龍（最高配当）",
        payout5: "x1000",
        payout4: "x200",
        payout3: "x50",
      },
      {
        name: "鳳凰",
        payout5: "x500",
        payout4: "x150",
        payout3: "x40",
      },
      {
        name: "獅子",
        payout5: "x400",
        payout4: "x120",
        payout3: "x30",
      },
      {
        name: "壺",
        payout5: "x300",
        payout4: "x100",
        payout3: "x25",
      },
      {
        name: "ランタン",
        payout5: "x200",
        payout4: "x80",
        payout3: "x20",
      },
      {
        name: "A",
        payout5: "x150",
        payout4: "x60",
        payout3: "x15",
      },
      {
        name: "K",
        payout5: "x120",
        payout4: "x50",
        payout3: "x12",
      },
      {
        name: "Q",
        payout5: "x100",
        payout4: "x40",
        payout3: "x10",
      },
      {
        name: "J",
        payout5: "x80",
        payout4: "x30",
        payout3: "x8",
      },
      {
        name: "10",
        payout5: "x60",
        payout4: "x20",
        payout3: "x6",
      },
      {
        name: "金色のパンダ(ワイルド)",
        description: "ボーナスシンボル（灯篭）以外の全てのシンボルに代用できます。",
        isSpecial: true,
      },
      {
        name: "ボーナスシンボル（灯篭）",
        description: "7つ以上でフリースピンが発動します。",
        isSpecial: true,
      },
    ],
    maxPayout: "x6,206",
    notes: [
      "上記は$1ベット時の配当例です。",
      "ワイルドシンボルはボーナスシンボル（灯篭）以外の全てのシンボルに代用できます。",
      "ボーナスシンボル（灯篭）は7つ以上でフリースピンボーナスに突入します。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "ユニークなマルチレイヤーリール",
        description: "リールが3つの層で構成され、勝利の組み合わせが成立すると下のレイヤーのシンボルが現れる連鎖反応が発生します。これにより、1回のスピンで複数の勝利が生まれる可能性があります。",
        icon: "✨",
      },
      {
        name: "ペイラインの増加",
        description: "通常スピン時には243通りのペイラインがありますが、連鎖反応が進むにつれて最大720通りまで増加する可能性があります。フリースピンボーナス中は最大3125通りまで拡張します。",
        icon: "📈",
      },
      {
        name: "ボーナスシンボルとフリースピン",
        description: "灯篭のシンボルがスキャッターとして機能し、7つ以上出現するとフリースピンボーナスがトリガーされます。獲得できるフリースピン回数は、出現数に応じて決定されます。",
        icon: "🎁",
      },
      {
        name: "フォーチュンホイール",
        description: "フリースピンボーナス中に特定の条件を満たすと、マルチプライヤー（最大50倍）やコインウィンを獲得できるフォーチュンホイールが回転します。",
        icon: "🎡",
      },
      {
        name: "ワイルドシンボル",
        description: "金色のパンダのシンボルはワイルドカードとして機能し、ボーナスシンボル以外のすべてのシンボルに代用でき、勝利の組み合わせを作りやすくします。",
        icon: "🐼",
      },
      {
        name: "オートプレイ機能",
        description: "連続してスピンを行うことができるオートプレイ機能が搭載されており、ゲームプレイに集中しやすくなります。",
        icon: "▶️",
      },
    ],
  },
  sections: [
    {
      heading: "グラフィック・サウンド",
      paragraphs: [
        "「Fireworks Master」は、花火と東洋（特に中国）のテーマを融合させたデザインが特徴です。リールには麻雀牌を思わせるシンボルが配置され、背景には美しい花火や中国風の装飾が描かれています。鮮やかで高品質なグラフィックは、プレイヤーをゲームの世界観に引き込みます。花火の演出は特に見事で、勝利時やボーナス獲得時には画面を彩り、お祝いムードを盛り上げます。",
        "ゲームのサウンドトラックは、軽快でリズミカルなチャイナ風の音楽が中心で、ゲームプレイを邪魔することなく、楽しげな雰囲気を演出します。シンボルの回転音、勝利時のサウンド、ボーナスフィーチャーの発動音などが、ゲームの進行に合わせて効果的に鳴り響き、プレイ体験を豊かにしています。",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "「Fireworks Master」は、現代のプレイヤーのニーズに合わせて、モバイルデバイスでのプレイに最適化されています。ブラウザを通じて直接プレイできるため、アプリのダウンロードは必要ありません。スマートフォン（iOS、Android）やタブレットなどの様々なデバイスで、快適にプレイすることが可能です。モバイルデバイスの画面サイズに合わせてインターフェースが調整されており、直感的な操作でゲームを楽しむことができます。",
      ],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "「Fireworks Master」は中〜高ボラティリティのスロットであるため、資金管理が重要になります。プレイ時間と目標勝利額を設定し、それに基づいてベット額を調整しましょう。連続して勝利が出にくい場合でも、資金が尽きないように、ベット額は慎重に設定することが推奨されます。",
        "ペイラインが増加する仕組みや、フォーチュンホイールの存在を考慮し、ベット額を微調整しながら、ゲームの展開に合わせて戦略を変えていくのも良いでしょう。勝利によるシンボルの消滅と下のレイヤーへの展開は、1回のスピンで複数回の勝利を生むチャンスです。フリースピンボーナス中はペイラインが増加し、さらにスピン回数も追加される可能性があるため、積極的に狙っていきましょう。",
      ],
      notes: [
        "中〜高ボラティリティのため、勝利が頻繁に出ないこともあります。一喜一憂せず、長期的な視点でプレイすることが大切です。",
        "RTPは95.07%と、平均的な数値ですが、突出して高いわけではありません。過度な期待はせず、ゲーム自体を楽しむことを重視しましょう。",
        "実際の資金を投入する前に、デモモードでゲームの仕組みやフィーチャーを十分に理解することをお勧めします。",
      ],
    },
    {
      heading: "プロバイダー情報",
      paragraphs: [
        "Playson（プレイソン）は、2012年に設立されたゲームプロバイダーで、マルタに拠点を置いています。比較的新しい会社でありながらも、革新的なゲーム開発で急速に頭角を現しています。彼らは、ユニークなゲームメカニクス、高品質なグラフィック、そして魅力的なボーナスフィーチャーを組み合わせたスロットを提供することに注力しています。マルタ、ルーマニア、ベラルーシなど、複数の国でライセンスを取得しており、信頼性の高い運営を行っています。",
      ],
      table: {
        title: "CasinoTsu 推薦 Playson 社の人気作品",
        columns: ["ゲーム名", "リンク"],
        rows: [
          ["Solar Temple", "/slots/solar-temple"],
          ["Buffalo Power: Hold and Win", "/slots/buffalo-power-hold-and-win"],
          ["Rome: Caesar's Glory", "/slots/rome-caesars-glory"],
          ["Legend of Cleopatra Megaways", "/slots/legend-of-cleopatra-megaways"],
        ],
      },
    },
  ],
  similarGames: [
    ],
  prosCons: {
    pros: [
      "ユニークなマルチレイヤーリールと連鎖反応システム",
      "最大3125通りに広がるペイライン",
      "フリースピン中のフォーチュンホイールによる高配当の可能性",
      "高品質なグラフィックとサウンド",
      "モバイル最適化により、どこでもプレイ可能",
    ],
    cons: [
      "中〜高ボラティリティのため、勝利が安定しない場合がある",
      "RTPが平均的（95.07%）",
      "一部情報源では、配当が低いと感じるプレイヤーもいる可能性",
    ],
  },
  faq: [
    {
      q: "Fireworks Masterはどのプロバイダーのスロットですか？",
      a: "Playson（プレイソン）というゲームプロバイダーによって開発・リリースされました。",
    },
    {
      q: "Fireworks Masterの特徴は何ですか？",
      a: "最大の特徴は、麻雀牌のような「マルチレイヤーリール」と、勝利時にシンボルが消えて下のレイヤーが開く「連鎖反応」システムです。また、フリースピンボーナス中に「フォーチュンホイール」が回転し、マルチプライヤーやコインウィンを獲得できるチャンスがある点もユニークです。",
    },
    {
      q: "このスロットは無料でプレイできますか？",
      a: "はい、多くのオンラインカジノでは、本物の資金でプレイする前にゲームの仕組みを試せる「デモモード（無料プレイ）」を提供しています。",
    },
    {
      q: "プログレッシブジャックポットはありますか？",
      a: "いいえ、「Fireworks Master」にはプログレッシブジャックポット機能は搭載されていません。ただし、最大でベット額の6,206倍の配当が得られる可能性があります。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "Slots", href: "/slots" },
    { label: "Firework master", href: "/slots/firework-master" },
  ],
  tableOfContents: [
    { label: "基本情報と概要", href: "#" },
    { label: "プレイ可能なカジノのご案内", href: "#" },
    { label: "ゲーム基本情報", href: "#" },
    { label: "ゲーム特徴・フィーチャー", href: "#" },
    { label: "プロバイダー情報", href: "#" },
    { label: "グラフィック・サウンド", href: "#" },
    { label: "ペイアウト・配当表", href: "#" },
    { label: "モバイル対応", href: "#" },
    { label: "戦略・攻略法", href: "#" },
    { label: "類似ゲーム", href: "#" },
    { label: "まとめ", href: "#" },
    { label: "よくある質問", href: "#" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/firework-master" />;
}
