import Link from "next/link";
import type { ReviewPageContent } from "@/components/templates/ReviewDetailTemplate";

export const review21Com: ReviewPageContent = {
  hero: {
    title: "21.com（21ドットコム）レビュー",
    subheading: "最大$1,000＋合計1,000回フリースピン",
    description: "スタイリッシュなサイトデザインと豊富なボーナスを備えた21.comをCasinoTsuが徹底検証。対応決済、サポート体制、注意点までまとめました。",
    score: 3.9,
    scoreMax: 5,
    scoreBreakdown: [
      {
        label: "人気指数",
        percent: 75,
        note: "デザイン性は高いが日本語表記や独自性に改善の余地あり。",
      },
      {
        label: "規約",
        percent: 74,
        note: "豪華なボーナスの一方で賭け条件50倍・MAXベット$3と厳しめ。",
      },
      {
        label: "操作性",
        percent: 81,
        note: "検索しやすく直感的だが決済ラインナップと翻訳品質に課題。",
      },
      {
        label: "サポート",
        percent: 77,
        note: "日本語サポートは丁寧だが対応時間が不定期。英語は24時間。",
      },
    ],
    highlights: [
      "登録後10日間毎日もらえる入金不要フリースピン",
      "入金4回目まで続くウェルカムボーナスで合計$1,000",
      "おしゃれで扱いやすいサイト構成",
      "豊富なゲーム数とライブカジノラインナップ",
    ],
    watchouts: [
      "日本語サポートは不定期対応",
      "賭け条件が50倍と厳しめ",
      "入出金時に手数料が発生する場合がある",
    ],
  },
  payments: {
    featured: [
      {
        name: "銀行振込",
        icon: "/assets/payments/bank-transfer.svg",
        href: "https://casinotsu.com/payment/bank-transfer",
        badge: "最小 $10",
        note: "主要銀行に対応し安心の定番ルート",
      },
      {
        name: "VISA",
        icon: "/assets/payments/visa.svg",
        href: "https://casinotsu.com/payment/visa",
        badge: "即時反映",
        note: "クレジット/デビットどちらも対応",
      },
      {
        name: "Mastercard",
        icon: "/assets/payments/mastercard.svg",
        href: "https://casinotsu.com/payment/mastercard",
        badge: "人気",
        note: "利用者の多い定番ブランド",
      },
      {
        name: "Payz",
        icon: "/assets/payments/payz.svg",
        href: "https://casinotsu.com/payment/payz",
        badge: "Eウォレット",
        note: "スピーディーな入出金と日本語UI",
      },
      {
        name: "Venus Point",
        icon: "/assets/payments/venus-point.svg",
        badge: "ポイント制",
        note: "換金性が高いポイントウォレット",
      },
    ],
    deposits: [
      { name: "VISAデビット / クレジットカード", icon: "/assets/payments/visa.svg" },
      { name: "Masterカード", icon: "/assets/payments/mastercard.svg" },
      { name: "Maestro" },
      { name: "iWallet", icon: "/assets/payments/iwallet.svg", href: "https://casinotsu.com/payment/iwallet" },
      { name: "Payz", icon: "/assets/payments/payz.svg", href: "https://casinotsu.com/payment/payz" },
      { name: "Venus Point", icon: "/assets/payments/venus-point.svg", href: "https://casinotsu.com/payment/venuspoint" },
      { name: "MuchBetter", icon: "/assets/payments/muchbetter.svg", href: "https://casinotsu.com/payment/muchbetter" },
      { name: "Jeton Wallet" },
      { name: "Vega Wallet", icon: "/assets/payments/vega-wallet.svg", href: "https://casinotsu.com/payment/vegawallet" },
      { name: "Mifinity" },
      { name: "Revolut" },
      { name: "Neteller" },
      { name: "Skrill" },
      { name: "EcoPayz", icon: "/assets/payments/ecopayz.svg" },
      { name: "Paysafecard" },
      { name: "Bank transfer", icon: "/assets/payments/bank-transfer.svg" },
      { name: "Sofort" },
      { name: "Trustly" },
      { name: "Zimpler" },
      { name: "Rapid Transfer" },
      { name: "Interac" },
      { name: "instaDebit" },
      { name: "POLi" },
      { name: "PhonePe" },
      { name: "UPI" },
    ],
    withdrawals: [
      { name: "iWallet", icon: "/assets/payments/iwallet.svg", href: "https://casinotsu.com/payment/iwallet" },
      { name: "Payz", icon: "/assets/payments/payz.svg", href: "https://casinotsu.com/payment/payz" },
      { name: "Venus Point", icon: "/assets/payments/venus-point.svg", href: "https://casinotsu.com/payment/venuspoint" },
      { name: "MuchBetter", icon: "/assets/payments/muchbetter.svg", href: "https://casinotsu.com/payment/muchbetter" },
      { name: "Jeton Wallet" },
      { name: "Vega Wallet", icon: "/assets/payments/vega-wallet.svg", href: "https://casinotsu.com/payment/vegawallet" },
      { name: "Mifinity" },
      { name: "Neteller" },
      { name: "Skrill" },
      { name: "EcoPayz", icon: "/assets/payments/ecopayz.svg" },
      { name: "Bank transfer", icon: "/assets/payments/bank-transfer.svg" },
      { name: "Sofort" },
      { name: "Trustly" },
      { name: "Zimpler" },
      { name: "Rapid Transfer" },
      { name: "Interac" },
      { name: "instaDebit" },
      { name: "POLi" },
    ],
    notes: [
      "主要決済手段を中心に対応。最低入金額は$10、最低出金額は$50。Payz入金時は$1、出金は一律$3の手数料が発生。",
      "出金処理時間の目安：電子ウォレット0〜5日（即時〜24時間が多数）、銀行送金/カード決済1〜5日、保留期間0〜72時間。",
    ],
  },
  bonuses: {
    overview:
      "21.comのプロモーションページには、常にお得なキャンペーン情報が盛りだくさん。CasinoTsuでも最新のオファー状況を継続的に確認し更新しています。",
    noDeposit:
      "新規登録者限定で、Pragmatic Play『Vampires vs Wolves』に使える100回のフリースピンが毎日10回ずつ10日間に分けて付与されます。入金不要でサイトの雰囲気を試せる絶好のチャンスです。",
    extraSpins: {
      summary:
        "入金を行うと追加で最大900回のフリースピンが付与されます。90日間、毎日10回ずつログイン時に受け取れる形式で長期的に楽しめる設計です。",
      schedule: [
        "登録後に携帯電話番号を認証すると最初の10回が即付与",
        "2日目は登録から24時間後に自動付与",
        "3日目から100日目までは毎日ログイン時に10回付与",
        "24時間以内に使用しないと失効するため毎日消化が必要",
      ],
      warning: "フリースピンで得た勝利金には50倍の賭け条件が設定され、24時間以内に消化する必要があります。",
    },
    welcomeRows: [
      { depositNumber: "初回", percent: "100%", cap: "$100", code: "BON1" },
      { depositNumber: "2回目", percent: "25%", cap: "$500", code: "BON2" },
      { depositNumber: "3回目", percent: "50%", cap: "$300", code: "BON3" },
      { depositNumber: "4回目", percent: "100%", cap: "$100", code: "BON4" },
    ],
    conditions: [
      "特に記載がない限り、ボーナスマネーの賭け条件は50倍。",
      "ボーナスマネーを使用した際の最高ベット額は$3。",
      "フリースピン購入機能など特殊ベットはボーナスマネーでは利用不可。",
      "禁止ゲーム以外での賭けは賭け条件に100%カウント。",
    ],
    prohibitedGames: [
      "100 Bit Dice",
      "1429 Uncharted Seas",
      "Aliens",
      "Big Bang",
      "Blood Suckers",
      "Champion of the Track",
      "Dead or Alive",
      "Dead or Alive 2",
      "EggOMatic",
      "Eye of the Kraken",
      "Jackpot Jester 50K",
      "Kings of Chicago",
      "Pearls of India",
      "Peek-a-Boo",
      "Robin Hood",
      "Scrooge",
      "Sea Hunter",
      "Secret of the Stones",
      "Secrets of Christmas",
      "Super Monopoly Money",
      "The Wish Master",
      "Tower Quest",
      "Wizard Shop",
      "Zombies",
      "The Dog House",
      "5 Lion",
      "Safari King",
      "Hercules & Pegasus",
      "Lady Godiva",
      "Greek Gods",
      "Egyptian Fortunes",
      "Jokers Jewels",
      "Marching Legions",
      "すべてのテーブルゲーム",
      "ライブカジノゲーム",
      "ビデオポーカー",
      "すべてのジャックポットゲーム",
    ],
  },
  offers: [
    {
      title: "月曜日に300フリースピンゲット！",
      description: "日曜日に$200入金すると、翌月曜日にPragmatic Play『JOHN HUNTER and the BOOK OF TUT』で使える300回のフリースピンを獲得。週明けから勢いを付けたい時に最適なキャンペーン。",
      highlight: "フリースピンは週明けにまとめて受け取れる常設オファー",
    },
    {
      title: "ウィークエンドスピン",
      description: "平日に$25以上入金すると、土曜と日曜それぞれにGreat Rhino Megawaysで使える21回のフリースピンが付与。常設オファーなので毎週活用できる。",
    },
  ],
  facts: [
    { label: "名称", value: "21.com" },
    {
      label: "ローンチ",
      value: "2018年（※記事初出時は2019年と記載がありましたが、最新情報では2018年とされています）",
    },
    { label: "運営会社", value: "BP Group Limited" },
    { label: "ライセンス", value: "Malta Gaming Authority" },
    { label: "VIPプログラム", value: "✅" },
    {
      label: "対応言語",
      value: "日本語、英語、フィンランド語、ノルウェー語、ドイツ語、フランス語、ポーランド語",
    },
    { label: "対応通貨", value: "CAD, EUR, NOK, NZD, USD" },
    {
      label: "ゲームタイプ",
      value:
        "バカラ、ブラックジャック、クラップス、ゲームショー、ライブカジノ、ポーカー、ルーレット、スロット、メガウェイスロット、ビデオポーカー、インスタントウィンゲーム（アビエーター、マイン、プラインコ）、ライブゲームショー（メガホイール、ファンキタイム）",
    },
    {
      label: "ゲームプロバイダー",
      value: (
        <span>
          <Link href="https://casinotsu.com/providers">BetSoft</Link>, <Link href="https://casinotsu.com/providers">Elk Studios</Link>, <Link href="https://casinotsu.com/providers">Microgaming</Link>, <Link href="https://casinotsu.com/providers">Play’n GO</Link>, <Link href="https://www.japanesecasino.com/reviews/21-com#pragmatic-play">Pragmatic Play</Link>, <Link href="https://casinotsu.com/providers">Quickspin</Link>, Games Global, 1x2Games, Booming Games, GreenTube, Nyx Interactive, Nolimit City, Push Gaming, Relax Gaming, Thunderkick, Red Tiger Gaming, NetEnt, Evolution Gaming, Just For The Win, Gamomat, Iron Dog Studios, Northern Lights Gaming, Foxium, Kalamba Games, Sthlm Gaming, Rabcat, iSoftBet, Pocket Games Soft, Lightning Box, Big Time Gaming, Light & Wonder, Playson, Fantasma Games, Hacksaw Gaming, Felt Gaming, Boomerang, 2 By 2 Gaming, Games Lab, Blueprint Gaming, ReelPlay, Leap, Yggdrasil Gaming, Snowborn Games, 4ThePlayer, Crazy Tooth Studio
        </span>
      ),
    },
    { label: "最小入金額", value: "$10 (€10 / NOK 250)" },
    { label: "最小出金額", value: "$50" },
    { label: "電話サポート", value: "❌" },
    { label: "メールサポート", value: "✅" },
    { label: "Eメール", value: <Link href="mailto:support@21.com">support@21.com</Link> },
    { label: "ライブチャット", value: "ライブチャットサポート (24時間英語対応)" },
    { label: "スカイプサポート", value: "❌" },
  ],
  intro: {
    paragraphs: [
      "21.com／21ドットコムは2018年にマルタライセンスを取得して誕生した、スタイリッシュなオンラインカジノです。",
      "21という数字はブラックジャックに由来し、ブランド名からも勝利へのこだわりが伝わります。独自のデザインで、一般的なカジノサイトとは一味違う世界観が魅力です。",
      "CasinoTsuでは、皆様の安全なカジノ体験のために細部までチェック。ここからは長所と注意点を順番に見ていきましょう。",
    ],
    ctas: [
      { text: "👉 21ドットコムで遊ぶ💖", href: "https://go.japanesecasino.com/go/21-com" },
      { text: "超カンタン解説！🔰オンラインカジノのはじめ方", href: "https://www.japanesecasino.com/guides" },
    ],
  },
  games: [
    "現在21.comでは、50社以上のプロバイダーが提供する1,000種類以上のゲームを取り扱っています。オープン当初よりも大幅にラインナップが拡充され、ジャンルの幅も豊富です。",
    "ELK、Pragmatic Play、Quickspin、Golden Heroなど人気スタジオのタイトルが揃っており、ライブカジノはEvolution GamingとPragmatic Playの両方を採用。ブラックジャックのテーブルも豊富で、テーブルゲーム好きでも満足できます。",
  ],
  features: [
    "白・ピンク・紫を基調としたポップなサイトデザインが印象的で、Netflix風にゲームが並ぶなど細部までこだわりが感じられます。",
    "おしゃれな見た目だけでなく、検索機能やカテゴリも整理されており、目的のゲームにすぐアクセスできる点も高評価です。",
  ],
  editorial: {
    author: "Rina Okabe",
    profileHref: "/authors/rina-okabe",
    hook: "ウェルカムボーナスはインパクトがある一方で、賭け条件50倍はしっかり把握しておきたいですね。",
    theGoodStuff: "最大$1,000の段階的ウェルカムボーナスと合計1,000回のフリースピンは、序盤の軍資金を後押ししてくれる魅力的な構成です。",
    theHeadsUp: "ただし賭け条件は50倍、さらに最高ベット$3という制限があるため、条件面の妥当性を重視したプレイが欠かせません。",
    finalThought: "ボーナスの魅力とリスクを天秤にかけ、自分のプレイスタイルに合うかを判断する視点を持って楽しみましょう。",
  },
  longform: {
    kicker: "CasinoTsuレビュー",
    title: "編集部による詳説",
    paragraphs: [
      "CasinoTsuではプレイヤーの皆様に信頼できる情報を届けるため日々リサーチを重ねており、21.comはその中でもスタイリッシュなデザインとスマートな導線で目を引くブランドです。ブランド名の「21」はブラックジャックに由来し、勝利へのこだわりが随所に感じられます。",
      "サイト全体はNetflix風のカード配置と軽快なアニメーションで統一され、ゲーム検索やカテゴリ分けも直感的に操作できます。一方で、一部のページでは直訳感のある日本語が残っており、デザインとのギャップをなくすための改善余地も見えました。",
      "ボーナスは入金不要フリースピン100回と、最大90日間継続する合計900回の追加フリースピンが目玉です。4回目の入金までカバーする最大$1,000のウェルカムボーナスも豪華ですが、賭け条件50倍や最高ベット$3などの制限は事前に把握しておきたいポイントです。",
      "決済手段は銀行振込や主要カード、PayzやVenus Pointといったウォレットに対応し、最低入金$10・最低出金$50と比較的利用しやすい設定です。出金手数料や保留時間は手段によって変動するため、毎回のトランザクションで最新情報を確認すると安心でしょう。",
      "サポートは日本語対応スタッフが在籍しているものの稼働時間が不定期で、基本は24時間対応の英語チャットが中心です。丁寧な応対が評判の一方で迅速さにムラがあるという声もあり、余裕を持った問い合わせ計画が推奨されます。",
      "総じて、21.comはデザイン性とフリースピン主体のプロモーションを重視するプレイヤーに向いたオンラインカジノです。条件に納得できればお得に遊べる構成なので、まずは登録特典を体験しつつ操作性や日本語サポートの感触を確かめてみてください。",
    ],
  },
  security: [
    "Comodo LimitedによるSSL暗号化で個人情報と財務情報を保護",
    "乱数生成器（RNG）による公平なゲーム結果",
    "iTech LabsやeCOGRAなど第三者機関による定期監査",
    "各決済プロバイダーの追加セキュリティレイヤーとファイアウォール保護",
  ],
  responsiblePlay: [
    "入金制限: 1日の入金額上限を設定",
    "賭け金制限: 1回/1日のベット総額に上限設定",
    "損失制限: 1日の損失額を管理",
    "時間/セッション制限: プレイ時間や休憩をコントロール",
    "クールオフ/タイムアウト: 一定期間アカウントを休止",
    "リアリティチェック: 勝敗・損失・経過時間の通知",
    "自己評価テスト: 依存リスクをセルフチェック",
    "出金ロック: 出金申請後のキャンセルを防止",
  ],
  complaintStats: [
    "AskGamblersに寄せられた苦情は17件中17件すべてが解決済み",
    "平均返信時間: 2日",
    "平均解決時間: 7日",
    "平均苦情額: $5,585",
  ],
  awards: [
    "2019年 AskGamblers Award 「Best New Casino」受賞",
    "Trustpilot: 2.4/5（29件、評価「Poor」）",
    "AskGamblers: CasinoRank 7.5/10、プレイヤー評価 5.8/10（59件）",
  ],
  restrictedCountries: [
    "オーストラリア",
    "アルゼンチン",
    "ボスニア・ヘルツェゴビナ",
    "オランダ",
    "キューバ",
    "デンマーク",
    "モロッコ",
    "アメリカ合衆国（一部地域）",
  ],
  userConcerns: [
    "出金処理の遅延: 明記された時間枠を超える報告あり",
    "本人確認プロセス（KYC）に時間がかかるとの声",
    "カスタマーサポート対応の品質にばらつきがあるとの意見",
  ],
  summary: [
    "サイトデザインは非常に斬新で、ゲームプロバイダーとタイトル数の充実度も高評価ポイント。主要決済方法への対応も進んでいます。",
    "賭け条件が厳しめ、出金時に手数料が発生する可能性がある点には注意が必要。フリースピン主体のキャンペーンが多いため、キャッシュバックなど別タイプの特典が増えるとさらに魅力的になるでしょう。",
    "豊富なゲームラインナップと4回目の入金まで続くウェルカムボーナスを考えると、一度試してみる価値は十分。コンプポイントやレベルシステムなどが導入されれば、継続プレイのモチベーションも高まりそうです。",
    "まずは登録ボーナスを活用してサイトの雰囲気をチェックしてみてください。",
  ],
  extraLinks: [
    { text: "🔰 賭け条件ってなに？わかりやすく解説！", href: "https://www.japanesecasino.com/guides/wagering-requirements" },
  ],
  faq: [
    {
      question: "21.comの入金不要ボーナスは何ですか？",
      answer: "Pragmatic Play社の人気スロット『Vampires vs Wolves』で利用できる100回のフリースピンです。登録後、毎日10回ずつ10日間にわたって付与されます。",
    },
    {
      question: "21.comでは銀行送金による入出金が可能ですか？",
      answer: "はい、可能です。ただし出金には$3の手数料がかかる場合があります。",
    },
    {
      question: "日本人サポートはいますか？",
      answer: "日本語担当者は在籍していますが対応は不定期です。担当者が不在の場合はメールで問い合わせると日本語で回答が受けられます。英語のライブチャットは24時間利用できます。",
    },
  ],
  cta: {
    text: "詳しいボーナス条件と最新キャンペーンを確認する",
    href: "https://www.japanesecasino.com/reviews/21-com",
  },
};
