import Link from "next/link";
import type { ReviewPageContent } from "@/components/templates/ReviewDetailTemplate";

export const reviewCloudbet: ReviewPageContent = {
  hero: {
    title: "クラウドベット（Cloudbet）レビュー",
    subheading: "最大5BTCのウェルカムボーナス",
    description: "入出金額上限なし！30種類以上の仮想通貨に対応し、ハイローラーから絶大な支持を受けるクラウドベットをCasinoTsuが徹底検証。安全性から独自のボーナスシステムまで解説します。",
    score: 4.0,
    scoreMax: 5,
    scoreBreakdown: [
      {
        label: "人気指数",
        percent: 78,
        note: "日本市場での認知度はまだ低いものの、豊富なゲームとキャンペーンで今後の発展に期待大。",
      },
      {
        label: "規約",
        percent: 74,
        note: "ボーナスがポイントを貯めて解放する独自システムのため、最初は理解に時間がかかる可能性あり。",
      },
      {
        label: "操作性",
        percent: 86,
        note: "PC・モバイル共に使いやすく、ライト・ダーク・クラシックの3モードに切り替え可能で快適。",
      },
      {
        label: "サポート",
        percent: 83,
        note: "丁寧な日本語サポートが24時間利用可能。ライブチャットは迅速だが、確認に時間がかかる場合も。",
      },
    ],
    highlights: [
      "30種類以上の豊富な仮想通貨決済に対応",
      "入出金額に上限がないためハイローラーに最適",
      "2,500種類以上の多彩なゲームラインナップ",
      "サイト上で直接クレジットカード等で仮想通貨を購入可能",
      "10年以上の運営実績と高い安全性評価",
    ],
    watchouts: [
      "法定通貨（日本円など）での直接入出金には未対応",
      "ボーナスシステムがポイント解放型で独特",
      "一部の日本語訳に不自然な箇所がある",
      "プレイヤーからの評判にばらつきが見られる",
    ],
  },
  payments: {
    featured: [
      {
        name: "Bitcoin",
        icon: "/assets/payments/bitcoin.svg",
        href: "https://www.casinotsu.com/payment/bitcoin",
        badge: "人気No.1",
        note: "最も代表的な仮想通貨",
      },
      {
        name: "Ethereum",
        icon: "/assets/payments/ethereum.svg",
        href: "https://www.casinotsu.com/payment/ethereum",
        badge: "高速",
        note: "スマートコントラクトで人気の通貨",
      },
      {
        name: "Tether",
        icon: "/assets/payments/tether.svg",
        href: "https://www.casinotsu.com/payment/usdt",
        badge: "安定",
        note: "米ドルに連動するステーブルコイン",
      },
      {
        name: "Ripple",
        icon: "/assets/payments/xrp.svg",
        badge: "送金",
        note: "国際送金に特化した決済システム",
      },
      {
        name: "Vega Wallet",
        icon: "/assets/payments/vega-wallet.svg",
        href: "https://www.casinotsu.com/payment/vega-wallet",
        badge: "Eウォレット",
        note: "ポイントでの管理が便利な決済手段",
      },
    ],
    deposits: [
      { name: "Bitcoin (BTC)", icon: "/assets/payments/bitcoin.svg" },
      { name: "Ethereum (ETH)", icon: "/assets/payments/ethereum.svg" },
      { name: "Tether (USDT)", icon: "/assets/payments/tether.svg" },
      { name: "Cardano (ADA)" },
      { name: "Avalanche (AVAX)" },
      { name: "Bitcoin Cash (BCH)", icon: "/assets/payments/bitcoin-cash.svg" },
      { name: "Binance Coin (BNB)" },
      { name: "Binance USD (BUSD)" },
      { name: "Dai (DAI)" },
      { name: "Dash (DASH)", icon: "/assets/payments/dash.svg" },
      { name: "Dogecoin (DOGE)" },
      { name: "Polkadot (DOT)" },
      { name: "Fantom (FTM)" },
      { name: "Chainlink (LINK)" },
      { name: "Litecoin (LTC)", icon: "/assets/payments/litecoin.svg" },
      { name: "Polygon (MATIC)" },
      { name: "PAX Gold (PAXG)" },
      { name: "Shiba Inu (SHIB)", icon: "/assets/payments/shiba-inu.svg" },
      { name: "Solana (SOL)" },
      { name: "Uniswap (UNI)" },
      { name: "USD Coin (USDC)" },
      { name: "Paxos Standard (USDP)" },
      { name: "TRON (TRX)" },
      { name: "EOS (EOS)" },
      { name: "Zcash (ZEC)" },
      { name: "Stellar (XLM)" },
      { name: "Ethena (ENA)" },
      { name: "Hedera (HBAR)" },
      { name: "Algorand (ALGO)" },
      { name: "J-Pay", icon: "/assets/payments/j-pay.svg" },
      { name: "Vega Wallet", icon: "/assets/payments/vega-wallet.svg" },
    ],
    withdrawals: [
        { name: "Bitcoin (BTC)", icon: "/assets/payments/bitcoin.svg" },
        { name: "Ethereum (ETH)", icon: "/assets/payments/ethereum.svg" },
        { name: "Tether (USDT)", icon: "/assets/payments/tether.svg" },
        { name: "Cardano (ADA)" },
        { name: "Avalanche (AVAX)" },
        { name: "Bitcoin Cash (BCH)", icon: "/assets/payments/bitcoin-cash.svg" },
        { name: "Binance Coin (BNB)" },
        { name: "Binance USD (BUSD)" },
        { name: "Dai (DAI)" },
        { name: "Dash (DASH)", icon: "/assets/payments/dash.svg" },
        { name: "Dogecoin (DOGE)" },
        { name: "Polkadot (DOT)" },
        { name: "Fantom (FTM)" },
        { name: "Chainlink (LINK)" },
        { name: "Litecoin (LTC)", icon: "/assets/payments/litecoin.svg" },
        { name: "Polygon (MATIC)" },
        { name: "PAX Gold (PAXG)" },
        { name: "Shiba Inu (SHIB)", icon: "/assets/payments/shiba-inu.svg" },
        { name: "Solana (SOL)" },
        { name: "Uniswap (UNI)" },
        { name: "USD Coin (USDC)" },
        { name: "Paxos Standard (USDP)" },
        { name: "TRON (TRX)" },
        { name: "EOS (EOS)" },
        { name: "Zcash (ZEC)" },
        { name: "Stellar (XLM)" },
        { name: "Ethena (ENA)" },
        { name: "Hedera (HBAR)" },
        { name: "Algorand (ALGO)" },
        { name: "J-Pay", icon: "/assets/payments/j-pay.svg" },
        { name: "Vega Wallet", icon: "/assets/payments/vega-wallet.svg" },
    ],
    notes: [
      "入出金額に上限はありません。入金手数料は無料です。",
      "各仮想通貨ごとに出金手数料が設定されています。(例: BTC 0.000077, ETH 0.003, USDT 40)",
      "出金は通常、数時間以内に処理されます。",
      "サイト上でクレジットカードやデビットカードを使い、直接仮想通貨を購入することができます。",
    ],
  },
  bonuses: {
    overview:
      "クラウドベットの初回入金ボーナスは、最大5BTCと高額ですが、一般的なマッチボーナスとは仕組みが異なります。リアルマネーでプレイしてポイントを貯めることで、ボーナスが段階的に現金としてアカウントに解放されていくユニークなシステムです。",
    noDeposit:
      "現在、クラウドベットでは入金不要ボーナスは提供されていません。",
    extraSpins: {
      summary: "ウェルカムボーナスにはフリースピンは含まれていませんが、後述のポイントクラブ（ロイヤリティクラブ）のマーケットプレイスでポイントを使ってフリースピンと交換することが可能です。",
      schedule: [],
      warning: "",
    },
    welcomeRows: [
      { depositNumber: "初回", percent: "ポイント解放型", cap: "5 BTC", code: "不要" },
    ],
    conditions: [
      "ボーナスは150ポイント貯めるごとに0.001 BTCずつ現金として解放されます。",
      "ポイントはリアルマネーでのプレイで貯まります。(スロット: 賭け金×0.008×(100-RTP), テーブルゲーム: 賭け金×0.008×(100-RTP)×10%)",
      "最低入金額は0.001 BTC（または相当額）です。",
      "ボーナス解放の有効期限は、初回入金から60日間です。",
      "ボーナス獲得のためには、登録から3ヶ月以内に初回入金を行う必要があります。",
    ],
    prohibitedGames: [
      "100 Bit Dice",
      "1000x Busta",
      "アーケードゲーム (Aviator, Mini Roulette, Plinko, Keno, Mines, Goal Mines, Dice, HiLO)",
    ],
  },
  offers: [
    {
      title: "ロイヤリティクラブ（ポイントクラブ）",
      description: "全プレイヤーが自動参加するロイヤリティプログラム。リアルマネーでプレイすると「雷ポイント」が貯まり、全6段階の会員ランクが上がります。ランクが上がるほど、限定特典がアンロックされます。",
      highlight: "貯まったポイントはボーナスやフリースピンと交換可能",
    },
    {
      title: "プロバイダー主催トーナメント",
      description: "Pragmatic Playなどの大手プロバイダーと提携し、高額賞金トーナメントを定期的に開催しています。賞金総額が$500,000に達することもあります。",
      highlight: "高額賞金を狙えるチャンス",
    },
  ],
  facts: [
    { label: "名称", value: "Cloudbet (クラウドベット)" },
    { label: "ローンチ", value: "2013年" },
    { label: "運営会社", value: "Halcyon Super Holdings B.V." },
    { label: "ライセンス", value: "Curaçao eGaming License" },
    { label: "VIPプログラム", value: "✅ (ロイヤリティクラブ)" },
    { label: "対応言語", value: "日本語、英語など15言語以上" },
    { label: "対応通貨", value: "BTC, ETH, USDTなど30種類以上の仮想通貨" },
    {
      label: "ゲームタイプ",
      value:
        "バカラ, ブラックジャック, クラップス, ゲームショー, ライブカジノ, ポーカー, ルーレット, スロット, スポーツベット, eスポーツ, オリジナルゲーム",
    },
    {
      label: "ゲームプロバイダー",
      value: (
        <span>
          <Link href="https://www.casinotsu.com/providers/betsoft">BetSoft</Link>, <Link href="https://www.casinotsu.com/providers/big-time-gaming">Big Time Gaming</Link>, <Link href="https://www.casinotsu.com/providers/elk-studios">Elk Studios</Link>, <Link href="https://www.casinotsu.com/providers/netent">NetEnt</Link>, <Link href="https://www.casinotsu.com/providers/nolimit-city">Nolimit City</Link>, <Link href="https://www.casinotsu.com/providers/playtech">Playtech</Link>, <Link href="https://www.casinotsu.com/providers/play-n-go">Play’n GO</Link> など80社以上
        </span>
      ),
    },
    { label: "最小入金額", value: "0.0001 BTCなど通貨による" },
    { label: "最小出金額", value: "通貨による" },
    { label: "電話サポート", value: "❌" },
    { label: "メールサポート", value: "✅" },
    { label: "Eメール", value: <Link href="mailto:support@cloudbet.com">support@cloudbet.com</Link> },
    { label: "ライブチャット", value: "24時間年中無休" },
    { label: "スカイプサポート", value: "❌" },
  ],
  intro: {
    paragraphs: [
      "クラウドベットは2013年に世界初の仮想通貨対応スポーツブックとして誕生し、10年以上の運営実績を持つ老舗オンラインカジノです。",
      "最大の特徴は、30種類以上の仮想通貨に対応し、入出金額に一切上限がないこと。これにより、特にハイローラーのプレイヤーから絶大な信頼を得ています。",
      "CasinoTsuでは、その独自のボーナスシステム、豊富なゲームラインナップ、そして業界トップクラスの安全性を徹底的に掘り下げ、プレイヤー目線でその実力を評価します。",
    ],
    ctas: [
      { text: "👉 クラウドベットで今すぐプレイ！", href: "https://go.casinotsu.com/go/cloudbet:cloudbet?referrer_path=%2Freviews%2Fcloudbet" },
      { text: "🔰 仮想通貨カジノの始め方", href: "https://www.casinotsu.com/bonuses/crypto" },
    ],
  },
  games: [
    "クラウドベットでは、2,500〜3,000種類以上の非常に豊富なゲームが楽しめます。2,000種類以上のスロットには定番から最新作まで揃っており、ライブカジノはEvolution社を含む5社のプロバイダーが参加し、250種類以上のテーブルを提供しています。",
    "元々がスポーツブックであるため、スポーツベットの種類も非常に充実。さらに、AviatorなどのクラッシュゲームやRTPが高いオリジナルゲームも多数プレイ可能です。",
  ],
  features: [
    "多くのゲームでデモプレイ（無料プレイ）が提供されており、リアルマネーを賭ける前にゲームを試すことができます。",
    "サイトのデザインはライトモード、ダークモード、クラシックモードの3種類から選択でき、プレイヤーの好みに合わせてカスタマイズできます。",
  ],
  editorial: {
    author: "CasinoTsu編集部",
    profileHref: "/authors",
    hook: "入出金上限なしの仮想通貨特化型カジノ。ハイローラーには天国だが、初心者には少し敷居が高いかも？",
    theGoodStuff: "30種類以上の仮想通貨に対応し、入出金上限がない点は他の追随を許しません。10年以上の運営実績と第三者機関からの高い評価が、その安全性を裏付けています。ゲーム数も豊富で飽きることがありません。",
    theHeadsUp: "ボーナスがポイントを貯めて解放する特殊なシステムであるため、即時反映を期待するプレイヤーには向いていません。また、法定通貨に未対応な点や、一部プレイヤーからサポート対応にばらつきがあるとの声も気になります。",
    finalThought: "仮想通貨でのプレイに慣れている、特に高額ベットを楽しみたいハイローラーにとっては、これ以上ない環境です。安全性と自由度の高さを両立した、ポテンシャルの高いカジノと言えるでしょう。",
  },
  longform: {
    kicker: "CasinoTsuレビュー",
    title: "編集部による詳説",
    paragraphs: [
      "CasinoTsuがクラウドベットをレビューするにあたり、最も注目したのはその揺るぎない信頼性と、仮想通貨プレイヤーへの完全なコミットメントです。2013年の設立以来、10年以上にわたりセキュリティ侵害ゼロという実績は、単なる謳い文句ではなく、高度なセキュリティ対策と堅実な運営の賜物です。Curaçaoライセンスはもちろん、Casino.Guruなどの独立機関から軒並み高評価を得ていることからも、その信頼性の高さが伺えます。",
      "このカジノの真価は、入出金額に上限がないという点に集約されています。これは、特に高額な資金を動かすハイローラーにとって、何物にも代えがたい魅力です。30種類を超える対応仮想通貨の豊富さも、市場の動向に敏感なクリプトユーザーのニーズを的確に捉えています。",
      "一方で、そのユニークなボーナスシステムは、評価が分かれるポイントかもしれません。ポイントを貯めて少しずつ現金化していく仕組みは、長期的にプレイするプレイヤーにとってはメリットがありますが、短期的な資金増強を期待する初心者には分かりにくい可能性があります。また、法定通貨に未対応である点は、仮想通貨に馴染みのない層にとっては明確な参入障壁となります（サイト内で購入できる機能はありますが）。",
      "総じて、クラウドベットは「仮想通貨プレイヤーによる、仮想通貨プレイヤーのためのカジノ」と言えます。その専門性と高い信頼性は、ターゲット層に深く刺さるものです。今後の課題は、決済方法の多様化やボーナスシステムの分かりやすさを通じて、より幅広い層のプレイヤーをいかに取り込んでいくかでしょう。そのポテンシャルは計り知れません。",
    ],
  },
  security: [
    "オランダ領キュラソー政府発行のCuraçao eGaming Licenseを取得",
    "10年以上の運営でセキュリティ侵害ゼロの実績",
    "SSL暗号化技術によりプレイヤーの個人情報と取引データを保護",
    "第三者監査機関によるRNG(乱数発生器)の定期的な監査",
    "機関グレードの顧客資産管理ソリューションと厳格なKYCポリシー",
  ],
  responsiblePlay: [
    "自己除外: 24時間から永久まで、期間を選択してプレイを停止",
    "制限ツール: 入金、賭け金、損失、セッション時間の上限を設定可能",
    "クールダウン/タイムアウト: 短期間のプレイ中断機能",
    "リアリティチェック: プレイ時間や収支を定期的に通知",
    "外部リソース: GambleAwareなど、ギャンブル依存症支援団体へのリンクを提供",
  ],
  complaintStats: [
    "Casino.Guruによる安全性指数: 8.7/10 (高評価)",
    "Casino.orgによる評価: 4.5/5",
    "PlayTodayによるスコア: 99.1/100 (Perfect Play)",
  ],
  awards: [],
  restrictedCountries: [],
  userConcerns: [
    "アカウント認証プロセスが複雑との報告",
    "一部のプレイヤーから出金遅延やサポート対応のばらつきが指摘されている",
    "アカウントの利用上限額の引き上げが難しいとの声がある",
  ],
  summary: [
    "2013年から続く老舗の仮想通貨特化型オンラインカジノ。",
    "最大の特徴は、30種類以上の仮想通貨に対応し、入出金限度額がないこと。",
    "2,500種類以上の豊富なゲーム、24時間日本語サポート、高い安全性を誇る。",
    "法定通貨には未対応だが、サイト内で直接仮想通貨を購入可能。仮想通貨に慣れたハイローラーに特におすすめ。",
  ],
  extraLinks: [
    { text: "🔰 カジノ用語辞典で分からない言葉をチェック", href: "https://www.casinotsu.com/guides/glossary" },
    { text: "✅ カジノライセンスの信頼性について", href: "https://www.casinotsu.com/info/casino-license" },
  ],
  faq: [
    {
      question: "クラウドベットでは法定通貨は使えますか？",
      answer: "いいえ、直接の法定通貨での入出金はできません。ただし、サイト上でクレジットカードなどを使って仮想通貨を直接購入し、それを使ってプレイすることは可能です。",
    },
    {
      question: "クラウドベットではどんなゲームで遊べますか？",
      answer: "スロット、ライブカジノのゲームをはじめ、スポーツ、eスポーツ、Aviatorを含むオリジナルゲーム、クラッシュゲーム、ミニゲーム、アーケードゲームなど、2,500〜3,000種類以上の豊富なゲームで遊ぶことができます。",
    },
    {
      question: "クラウドベットは安全ですか？",
      answer: "はい、クラウドベットはキュラソーライセンスを取得しており、10年以上の運営実績を持つ信頼性の高いオンラインカジノです。SSL暗号化技術や厳格なセキュリティ対策により、プレイヤーの安全を守っています。",
    },
    {
      question: "モバイルアプリはありますか？",
      answer: "いいえ、専用のモバイルアプリはありません。しかし、ウェブサイトはHTML5技術で最適化されており、スマートフォンやタブレットのブラウザから快適にアクセス・プレイできます。",
    },
    {
      question: "アカウント認証（KYC）は必要ですか？",
      answer: "登録時点では必須ではありませんが、一定額以上の出金やセキュリティ上の理由から、後日KYC（本人確認）が求められる場合があります。その際は、身分証明書や住所確認書類の提出が必要です。",
    },
  ],
  cta: {
    text: "クラウドベットでボーナスをゲットする！",
    href: "https://go.casinotsu.com/go/cloudbet:cloudbet?referrer_path=%2Freviews%2Fcloudbet",
  },
};