import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Sweet Cat Cafe Resort 遊び方・攻略法解説",
  hero: {
    title: "Sweet Cat Cafe Resort",
    subheading: "南国リゾートでネコ耳メイドさんと楽しむ、パチスロ風スロット！",
    description: "前作「スイート・キャット・カフェ」の続編。ビキニ姿のキャラクターや、フリースピン、マルチプライヤーといった豊富なフィーチャーが満載で、爆益を狙える可能性を秘めたスロットです。日本のゲームプロバイダーであるラクジン社が開発し、Golden Hero社からリリースされています。",
    score: 4.7,
    scoreMax: 5,
    rtp: "96.5%",
    maxMultiplier: "x59,800",
    provider: "Golden Hero (ラクジン社開発)",
    releaseDate: "2023年8月1日",
    volatility: "Med-High",
    reels: "3",
    paylines: "5",
    minBet: "$0.2",
    maxBet: "$15",
    slotImageSrc: "/slots/sweet-cat-cafe-resort.jpg",
    highlights: [
      "南国リゾートが舞台のかわいらしいスロット",
      "ネコ耳メイドさんがビキニ姿で登場",
      "フリースピン、マルチプライヤー、リスピンなど豊富なフィーチャー",
      "パチスロ風のゲーム性",
      "ボーナス購入機能搭載",
    ],
    watchouts: [
      "ワイルドシンボルが存在しない",
      "デスクトップでは背景がぼやけて見えることがある",
      "継続抽選フィーチャーへの突入率が低い場合がある",
    ],
  },
  featuredCasino: {
    name: "WSM Casino",
    logo: "/assets/casino/wsm-casino.png",
    href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
  },
  casinos: [
    {
      name: "WSM Casino",
      logo: "/assets/casino/wsm-casino.jpg",
      href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x (ボーナス), 40x (フリースピン)",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.jpg",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40x",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30x (ボーナス), 20x (フリースピン)",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Fresh Casino",
      logo: "/assets/casino/fresh-casino.jpg",
      href: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.jpg",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casino/wonder-casino.jpg",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Konibet",
      logo: "/assets/casino/konibet.jpg",
      href: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.jpg",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "InterCasino",
      logo: "/images/casino/inter-casino.jpg",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Vera&John",
      logo: "/assets/casino/vera-john.jpg",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
    },
  ],
  gameInfo: {
    intro: "南国リゾートを舞台にした、可愛らしいネコ耳メイドさんが登場する人気のパチスロ風スロットゲーム「スイート・キャット・カフェ・リゾート（Sweet Cat Cafe Resort）」をご紹介🏝️。前作「スイート・キャット・カフェ」の続編として、さらに魅力的な機能とデザインでプレイヤーを魅了します。ビキニ姿のキャラクターや、フリースピン、マルチプライヤーといった豊富なフィーチャーが満載で、爆益を狙える可能性を秘めたスロットです。日本のゲームプロバイダーであるラクジン社が開発し、Golden Hero社からリリースされています。",
    basicInfo: {
      rtp: "96.5%",
      volatility: "Med-High",
      reels: "3",
      paylines: "5",
      minBet: "$0.2",
      maxBet: "$15",
      provider: "Golden Hero (ラクジン社開発)",
      releaseDate: "2023年8月1日",
    },
  },
  payoutTable: {
    title: "スイート・キャット・カフェ・リゾート 役・配当",
    symbols: [
      {
        name: "カクテル (Mojito)",
        payout5: "x100",
        payout4: "x20",
        payout3: "x5",
      },
      {
        name: "カクテル (Blue Hawaii)",
        payout5: "x80",
        payout4: "x16",
        payout3: "x4",
      },
      {
        name: "カクテル (Mai Tai)",
        payout5: "x60",
        payout4: "x12",
        payout3: "x3",
      },
      {
        name: "カクテル (Chi-Chi)",
        payout5: "x40",
        payout4: "x8",
        payout3: "x2",
      },
      {
        name: "スイート",
        payout5: "x30",
        payout4: "x6",
        payout3: "x1.5",
      },
      {
        name: "キャット",
        payout5: "x20",
        payout4: "x4",
        payout3: "x1",
      },
      {
        name: "カフェ",
        payout5: "x10",
        payout4: "x3",
        payout3: "x0.5",
      },
      {
        name: "リゾート",
        payout5: "x5",
        payout4: "x2",
        payout3: "x0.2",
      },
    ],
    maxPayout: "x59,800",
    notes: [
      "配当はベット額に対する倍率で表示されています。",
      "カクテルシンボルは、フリースピン中のボーナスステージで出現し、それぞれ異なるフィーチャーに影響を与えます。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "リスピン",
        description: "スキャッターシンボルが1つ出現すると、1回のリスピンを獲得できます。スキャッターはリール上にホールドされ、追加のスキャッター出現に期待できます。合計3つのスキャッターが揃うと、フリースピン（スイートタイム）へと突入します。",
        icon: "",
      },
      {
        name: "フリースピン（スイートタイム）",
        description: "ベルシンボルから出現する数字の合計が、フリースピンの回数を決定します。フリースピンの回数が決まると、ボーナスステージ（スイートタイム）が開始されます。4種類のカクテルが登場し、それぞれ出やすいフィーチャーが決まっています。",
        icon: "",
      },
      {
        name: "エクストラチャレンジ",
        description: "フリースピンが終了する前に、全てのマスがカクテル絵柄で埋まった場合はエクストラチャレンジへ進みます。エクストラチャレンジでは、スノーコーンシンボルが出現し、マスにマルチプライヤーを加算していきます。マルチプライヤーは最大100倍まで上昇する可能性があります。",
        icon: "",
      },
      {
        name: "継続抽選フィーチャー（ボーナスチャンス）",
        description: "フリースピンが全て終了すると、継続抽選フィーチャーが発動します。このフィーチャーは、「Finish」と表示されるとフリースピンは終了となりますが、「Come on！」と表示されれば、追加スピンが獲得でき、フリースピンが継続されます。マスが全て埋まった状態で継続抽選フィーチャーが発動した場合、エクストラチャレンジも継続します。",
        icon: "",
      },
      {
        name: "ボーナス購入（ボーナスバイ）",
        description: "右上の「BUY」ボタンをクリックすることで、ボーナス購入機能を利用できます。購入額は選択するフィーチャーによって異なり、一般的にベット額の55.50倍から77.30倍の範囲となります。",
        icon: "",
      },
      {
        name: "オートプレイ機能",
        description: "自動でスピンを回すことができるオートプレイ機能が搭載されています。",
        icon: "",
      },
      {
        name: "ターボ機能",
        description: "スピンの速度を速めるターボ機能により、テンポよくゲームを進めることができます。",
        icon: "",
      },
      {
        name: "スラムストップ機能",
        description: "スピンボタンを再度押すことで、リールの回転を途中で止めることができるスラムストップ機能も搭載されています。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "導入・概要",
      paragraphs: [
        "CasinoTsu は、南国リゾートを舞台にした、可愛らしいネコ耳メイドさんが登場する人気のパチスロ風スロットゲーム「スイート・キャット・カフェ・リゾート（Sweet Cat Cafe Resort）」をご紹介🏝️。前作「スイート・キャット・カフェ」の続編として、さらに魅力的な機能とデザインでプレイヤーを魅了します。ビキニ姿のキャラクターや、フリースピン、マルチプライヤーといった豊富なフィーチャーが満載で、爆益を狙える可能性を秘めたスロットです。日本のゲームプロバイダーであるラクジン社が開発し、Golden Hero社からリリースされています。",
      ],
    },
    {
      heading: "どこで遊べるか",
      paragraphs: [
        "CasinoTsu が自信をもっておすすめする、この魅力的なスロットがプレイできるオンラインカジノはこちらです。各カジノでは、お得なボーナスやプロモーションが用意されている場合がありますので、ぜひチェックしてみてください。",
      ],
    },
    {
      heading: "ボーナスと賭け条件について",
      paragraphs: [
        "一部のカジノでは、新規プレイヤー向けのウェルカムボーナスや、このスロットで利用できるフリースピンを提供しています。例えば、Sushi Casinoではボーナスに35倍、フリースピンに40倍の賭け条件が設定されています。これらのボーナスを活用することで、より長く、そしてお得にゲームを楽しむことができます。CasinoTsu では、常に正確な情報を皆様にお届けできるよう、チェック、ダブルチェック、そして CasinoTsu チェックを徹底しております。",
      ],
    },
    {
      heading: "ゲーム基本情報",
      table: {
        title: "ゲーム基本情報",
        columns: ["概要", "詳細"],
        rows: [
          ["名称", "Sweet Cat Cafe Resort"],
          ["リリース日", "2023年8月1日 (※注: 別の情報源では2024年8月29日との記載もあり、正確なリリース日は変動する可能性があります)"],
          ["プロバイダー", "Golden Hero (※注: 日本のゲームプロバイダーであるラクジン社も開発に関与しています)"],
          ["最大配当倍率", "x59,800"],
          ["ボラティリティ", "Med-High (中〜高)"],
          ["RTP", "96.5% (※注: ボーナス購入機能使用時は96.43%～96.53%の範囲で変動する可能性があります)"],
          ["最小ベット額", "$0.2 (または €0.20)"],
          ["最大ベット額", "$15 (または €15)"],
          ["リール数", "3"],
          ["ペイライン数", "5"],
          ["行数", "3"],
          ["テクノロジー", "JS, HTML5"],
        ],
      },
      paragraphs: [
        "このスロットは、JS（JavaScript）とHTML5技術を用いて開発されており、現代的なウェブブラウザでスムーズに動作します。CasinoTsu では、最新かつ正確な技術情報を提供することをお約束いたします。",
      ],
    },
    {
      heading: "スイート・キャット・カフェ・リゾートのレビュー",
      paragraphs: [
        "スイート・キャット・カフェ・リゾート（Sweet Cat Cafe Resort） は、 CasinoTsu が自信をもってお届けする、南国リゾートを舞台にした パチスロ風スロット です🏝️",
        "前作 スイート・キャット・カフェ の人気を受け、今回は ネコ耳メイド さんがビキニで登場～👙😍 このゲームは、前作「スイート・キャット・カフェ」のリスキン版であり、前作で「ケーキ」として登場したボーナスシンボルが、今作では「カクテル」に置き換わっています。",
        "フリースピン やおすすめ フィーチャー が盛りだくさんで目が離せません👀 CasinoTsu は、皆様に最もエキサイティングなゲーム体験をお届けできるよう、常に最新情報を収集しております。",
        "日本の ゲームプロバイダー 、 ラクジン社 が開発し Golden Hero社 から絶賛リリース中の スイート・キャット・カフェ・リゾート をさっそく深掘りしちゃいましょう😽",
        "このスロットは、特に低予算のプレイヤーや限られた資金でプレイしたいプレイヤーに適しています。CasinoTsu では、責任あるギャンブル を推奨しており、皆様が健全にゲームを楽しめるよう、情報提供に努めております。",
      ],
    },
    {
      heading: "グラフィック・サウンド",
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["グラフィック", "パチスロ風スロット の可愛らしいグラフィック。ただし、デスクトップPCでのプレイでは背景が「かすんでいる」「ぼやけている」ように見える場合があり、モバイルでのプレイに最適化されている可能性があります。"],
          ["モバイル仕様", "モバイル 端末でのプレイに特化した設計で、スムーズな操作性を実現🎵"],
          ["サウンド", "ゲームボイスは可愛らしく、プレイヤーを癒してくれます😻 臨場感あふれる効果音も楽しめます。"],
          ["特別フィーチャー", "スピン後の継続抽選フィーチャーで、さらなる配当獲得のチャンスがあります💋"],
        ],
      },
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "スマホ仕様 に最適化されており、動作も非常にスムーズで、いつでもどこでも手軽にプレイできます。",
        "ちょっとした空き時間に、リゾート気分を満喫しながら稼ぐチャンスです！ CasinoTsu は、モバイルゲームの利便性を重視しており、このスロットがその最たる例であると考えております。",
      ],
    },
    {
      heading: "スイート・キャット・カフェ・リゾートのメリット・デメリット",
      table: {
        columns: ["おすすめポイント", "残念ポイント"],
        rows: [
          ["✓ スマホで手軽に遊べる", "✗ ワイルドシンボルが存在しない"],
          ["✓ 豊富なフィーチャー（リスピン、フリースピン、エクストラチャレンジ、継続抽選）", "✗ 継続抽選フィーチャーへの突入率が低い場合がある"],
          ["✓ 日本人好みの可愛らしいデザイン", "✗ デスクトップでは背景がぼやけて見えることがある"],
          ["✓ 低予算プレイヤーや初心者にも優しいベット額設定", "✗ スロットにワイルドシンボルを期待するプレイヤーには物足りない可能性"],
          ["✓ ボーナス購入機能で迅速にボーナスステージへ突入可能", ""],
          ["✓ スイートタイム（フリースピン）中のボーナスチャンスがエキサイティング", ""],
          ["✓ ボーナスチャンスリ機能で継続的な賞金獲得の可能性", ""],
        ],
      },
      paragraphs: [
        "CasinoTsu は、これらの点を皆様にお伝えし、より良いゲーム体験の一助となることを目指しております。",
      ],
    },
    {
      heading: "スイート・キャット・カフェ・リゾートで遊べるおすすめ日本語カジノ",
      table: {
        columns: ["オンラインカジノ", "ボーナス内容"],
        rows: [
          ["インターカジノ", "**[インターカジノの登録フリースピン](https://casinotsu.com/reviews/inter-casino) 150回**"],
          ["遊雅堂（yuugado）", "**[遊雅堂（yuugado）の入金不要ボーナス](https://casinotsu.com/reviews/yuugado) ¥3,000**"],
          ["ベラ＆ジョン", "**[ベラ＆ジョンの入金不要フリースピン](https://casinotsu.com/reviews/vera-john) 150回**"],
        ],
      },
      paragraphs: [
        "スイート・キャット・カフェ・リゾート は、ベラジョン系列のカジノをはじめ、多くのオンラインカジノで絶賛配信中です💗 CasinoTsu 推薦のカジノで、ぜひこのゲームをお楽しみください。",
      ],
    },
    {
      heading: "ゲーム中に問題が起こったときの解決法",
      paragraphs: [
        "ゲーム内の説明によると、プレイ中に技術的な不具合が発生した場合、そのゲームのプレイおよび賞金はすべて無効となることがあります。CasinoTsu は、皆様に常に安定したゲーム環境を提供するため、安定したインターネット環境と、最新のデバイスでのプレイを推奨いたします。正確さが第一。興奮はその次。",
      ],
    },
    {
      heading: "スイート・キャット・カフェ・リゾート｜総評・まとめ",
      paragraphs: [
        "フィーチャー満載で、常にプレイヤーを飽きさせない スイート・キャット・カフェ・リゾート😽 CasinoTsu は、このゲームが提供する体験を高く評価しています。",
        "中程度のボラティリティ を持ちながらも、 ボーナスステージの爆発力 にも期待が持てる、まさに「揺さぶりの少ない」スロットと言えるでしょう💣",
        "日本の 老舗 プロバイダー であるラクジン社が開発に携わり、Golden Hero社からリリースされているだけあり、グラフィックや演出の クオリティは非常に高い です✨ CasinoTsu は、こうした質の高いゲームを皆様にご紹介できることを誇りに思っております。",
        "特に、 低予算のプレイヤー や、 パチスロ風のスロット が好きなプレイヤー、そして可愛らしいキャラクターに癒されたいプレイヤーには、ぜひ一度試していただきたい一押しスロットです。手軽にコインを貯める感覚を味わいたいなら、このゲームがぴったりかもしれません！",
        "このスロットは、モバイル でのプレイに最適化されており、アジア風のスロットに興味があるプレイヤーにとって、素晴らしい入門機となるでしょう。CasinoTsu は、皆様のオンラインカジノ体験が、より豊かで楽しいものになるよう、常に最善の情報を提供してまいります。",
      ],
    },
  ],
  similarGames: [
    {
      name: "ハワイアンドリーム・ジャックポット",
      href: "https://casinotsu.com/slots/hawaiian-dream-jackpot",
      provider: "Golden Hero",
      description: "大人気 ハワイアンドリーム が ジャックポットスロット になってカムバック🌺",
    },
    {
      name: "パーリー・ショーズ",
      href: "https://casinotsu.com/slots/pearly-shores",
      provider: "Octoplay",
      description: " Octoplay社 のクラスターペイスロットは遊びやすい中ボラ台🌴",
    },
    {
      name: "ドキドキ夏祭り",
      href: "https://casinotsu.com/slots/doki-doki-fireworks",
      provider: "Golden Hero",
      description: "夏祭りデートがテーマの パチスロ風スロット 💖",
    },
  ],
  prosCons: {
    pros: [
      "スマホで手軽に遊べる",
      "豊富なフィーチャー（リスピン、フリースピン、エクストラチャレンジ、継続抽選）",
      "日本人好みの可愛らしいデザイン",
      "低予算プレイヤーや初心者にも優しいベット額設定",
      "ボーナス購入機能で迅速にボーナスステージへ突入可能",
      "スイートタイム（フリースピン）中のボーナスチャンスがエキサイティング",
      "ボーナスチャンスリ機能で継続的な賞金獲得の可能性",
    ],
    cons: [
      "ワイルドシンボルが存在しない",
      "継続抽選フィーチャーへの突入率が低い場合がある",
      "デスクトップでは背景がぼやけて見えることがある",
      "スロットにワイルドシンボルを期待するプレイヤーには物足りない可能性",
    ],
  },
  faq: [
    {
      q: "スイート・キャット・カフェ・リゾートのベット額は？",
      a: "カジノによって多少異なりますが、例えばベラジョンでプレイした場合、CasinoTsu が確認したところ、最小ベット額は0.2ドル（または0.20ユーロ）から、最大ベット額は15ドル（または15ユーロ）となっています。",
    },
    {
      q: "スイート・キャット・カフェ・リゾートの還元率（RTP）は？",
      a: "ベースゲームのRTPは96.50%です。CasinoTsu による確認では、ボーナスステージ（スイートタイム）中の還元率は、出現するシンボルやマルチプライヤーによって変動する可能性があります。ボーナス購入機能を使用した場合、RTPは96.43%から96.53%の範囲で変動することがあります。正確さが第一。興奮はその次。",
    },
    {
      q: "このスロットにワイルドシンボルはありますか？",
      a: "いいえ、このゲームにはワイルドシンボルは搭載されていません。これは、多くのスロットゲームとは異なる特徴の一つです。CasinoTsu では、こうしたゲームのユニークな特徴も詳細にお伝えしております。",
    },
    {
      q: "無料でプレイできるデモ版はありますか？",
      a: "はい、SlotCatalogなどのプラットフォームで無料デモ版が提供されている場合があります。CasinoTsu は、実際のお金でプレイする前に、ゲームの感触を試すのに最適な方法であると認識しております。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Sweet cat cafe resort", href: "https://casinotsu.com/slots/sweet-cat-cafe-resort" },
  ],
  tableOfContents: [
    { label: "導入・概要", href: "#導入・概要" },
    { label: "どこで遊べるか", href: "#どこで遊べるか" },
    { label: "ゲーム基本情報", href: "#ゲーム基本情報" },
    { label: "スイート・キャット・カフェ・リゾートのレビュー", href: "#スイート・キャット・カフェ・リゾートのレビュー" },
    { label: "ゲーム特徴・フィーチャー", href: "#ゲーム特徴・フィーチャー" },
    { label: "グラフィック・サウンド", href: "#グラフィック・サウンド" },
    { label: "モバイル対応", href: "#モバイル対応" },
    { label: "スイート・キャット・カフェ・リゾートのメリット・デメリット", href: "#スイート・キャット・カフェ・リゾートのメリット・デメリット" },
    { label: "スイート・キャット・カフェ・リゾートで遊べるおすすめ日本語カジノ", href: "#スイート・キャット・カフェ・リゾートで遊べるおすすめ日本語カジノ" },
    { label: "ゲーム中に問題が起こったときの解決法", href: "#ゲーム中に問題が起こったときの解決法" },
    { label: "スイート・キャット・カフェ・リゾート｜総評・まとめ", href: "#スイート・キャット・カフェ・リゾート｜総評・まとめ" },
    { label: "類似ゲーム", href: "#類似ゲーム" },
    { label: "よくある質問", href: "#よくある質問" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fsweet-cat-cafe-resort",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/sweet-cat-cafe-resort" />;
}
