import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "ザ・ドッグ・ハウス・ドッグ・オア・アライブ",
  hero: {
    title: "ザ・ドッグ・ハウス・ドッグ・オア・アライブ",
    subheading: "Pragmatic Play社の最新作！最大10,000倍のハイボラティリティスロット",
    description: "初代の魅力を引き継ぎつつ、最大10,000倍というハイボラティリティスロットとして登場。CasinoTsu は、このエキサイティングなスロットを詳しくご紹介します。",
    score: 4.2,
    scoreMax: 5,
    rtp: "96.52%",
    maxMultiplier: "x10,000",
    provider: "Pragmatic Play",
    releaseDate: "2024年3月28日",
    volatility: "High",
    reels: "5",
    paylines: "20",
    minBet: "$0.20",
    maxBet: "$240",
    slotImageSrc: "/slots/the-dog-house-dog-or-alive.jpg",
    highlights: [
      "最大10,000倍のハイボラティリティ",
      "可愛らしい犬のテーマ",
      "マルチプライヤーワイルド搭載",
      "フリースピン中のスティッキーワイルド",
      "ボーナス購入機能あり",
    ],
    watchouts: [
      "ハイボラティリティのため、資金管理に注意が必要",
      "カジノによってRTPが異なる場合がある",
    ],
  },
  featuredCasino: {
    name: "ReSpin",
    logo: "/assets/casino/respin.jpg",
    href: "https://go.casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    ctaText: "今すぐプレイ！",
    ctaHref: "https://go.casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    tagline: "10種類以上の主要仮想通貨が利用可能な、注目のクリプトカジノです。",
  },
  casinos: [
    {
      name: "ReSpin",
      logo: "/assets/casino/respin.jpg",
      href: "https://go.casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "300USDT",
      freeSpins: "200",
      wagering: "35x, 5x",
      rating: 4,
      tagline: "10種類以上の主要仮想通貨が利用可能な、注目のクリプトカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30x, 30x",
      rating: 4,
      tagline: "出金は迅速に対応され、ストレスフリーなプレイ体験を提供します。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "独自のコインシステムも利用可能！最新のクリプトカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "2up",
      logo: "/images/2up_375x375.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "仮想通貨と日本円の両方でプレイ可能な、注目の新しいオンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$500",
      freeSpins: "50",
      wagering: "35x, 35x",
      rating: 3.5,
      tagline: "愛らしいマスコットキャラクターが魅力の、最新クリプトカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "1win",
      logo: "/images/1win_375x375.png",
      href: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノです。★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x, 20x",
      rating: 4,
      tagline: "充実したゲームラインナップと、盛りだくさんのボーナスでお得にプレイできます。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "WSM Casino",
      logo: "/images/WSM_375x375.png",
      href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」と「オンラインカジノ」の融合をお楽しみください。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性も重視した、最新の仮想通貨カジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20x, 20x",
      rating: 4,
      tagline: "シンプルな操作性と可愛らしいデザインが特徴！厳選されたゲームをお楽しみください。★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ設置台数を誇る、新進気鋭のカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x, 40x",
      rating: 4,
      tagline: "豊富なオファーやVIPプログラムが魅力的な、最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Betpanda",
      logo: "/images/Betpanda_375x375.png",
      href: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 3.5,
      tagline: "匿名で安全にプレイできる、クリプトオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Bets.io",
      logo: "/images/bets-io_375x375.png",
      href: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノです。♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "500フリースピンが魅力のクリプトカジノです。♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "1,000USDT",
      freeSpins: "-",
      rating: 4.5,
      tagline: "スポーツベットだけにとどまらない、充実したサービスを提供します。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40x",
      rating: 4,
      tagline: "独自のトークンによる資産運用も可能な、仮想通貨カジノです。★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務める、注目のオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Stake",
      logo: "/images/stake_375x375-1.png",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4,
      tagline: "ハウスエッジ5%のレーキバックと、VIP特典が大変お得です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "業界最速の出金スピードと、仮想通貨特化ボーナスが魅力です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "K8",
      logo: "/assets/casino/k8.jpg",
      href: "https://go.casinotsu.com/go/k8:k8?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$1,840",
      freeSpins: "288",
      wagering: "25x, 25x",
      rating: 4.5,
      tagline: "日本で人気の実機をプレイするなら、K8のパチンコで決まり！昔懐かしい台を打ちまくりましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/k8:k8?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Yuugado",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "「和」をテーマにしたオンラインカジノ｜パチンコからスポーツベットまで幅広く楽しめます！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Konibet",
      logo: "/images/konibet_375x375.png",
      href: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "パチンコ・パチスロもプレイできるオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x, 20x",
      rating: 4,
      tagline: "独自のシステムによるお得なキャッシュバックをご用意しています！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: "10x, 10x",
      rating: 4,
      tagline: "ボーナスが充実！スポーツベットにも最適なカジノです。♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "日本人プレイヤーの心を掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を謳うオンカジはここです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$0",
      freeSpins: "-",
      wagering: "N/A",
      rating: 3.5,
      tagline: "カジノとスポーツベットを両方楽しめるハイブリッド型カジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "オンラインカジノといえば、やはりベラジョンです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "ライブカジノをはじめ、多種多様なゲームが楽しめるお馴染みのカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Casino-X",
      logo: "/images/casino-x_375x375-1.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      rating: 4.5,
      tagline: "太っ腹なボーナスが盛りだくさんのカジノエックスで、お得にプレイしましょう♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x, 20x",
      rating: 4.5,
      tagline: "RPG型カジノで、旅をしながらボスを倒してお得にプレイしましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fthe-dog-house-dog-or-alive",
    },
  ],
  gameInfo: {
    intro: "Pragmatic Play社の最新作『ザ・ドッグ・ハウス・ドッグ・オア・アライブ』は、初代の魅力を引き継ぎつつ、最大10,000倍というハイボラティリティスロットとして登場しました。 CasinoTsu は、このエキサイティングなスロットを詳しくご紹介します。",
    basicInfo: {
      rtp: "96.52%",
      volatility: "High",
      reels: "5",
      paylines: "20",
      minBet: "$0.20",
      maxBet: "$240",
      provider: "Pragmatic Play",
      releaseDate: "2024年3月28日",
    },
  },
  payoutTable: {
    title: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのシンボルとペイアウト",
    symbols: [
      {
        name: "ドーベルマン",
        payout5: "$40.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "パグ",
        payout5: "$30.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "シーズー",
        payout5: "$20.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "ダックスフンド",
        payout5: "$16.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "首輪",
        payout5: "$12.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "骨",
        payout5: "$10.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "トランプのA, K",
        payout5: "$8.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "トランプのQ, J, 10",
        payout5: "$6.00",
        payout4: "",
        payout3: "",
      },
      {
        name: "ワイルドシンボル (保安官バッジ)",
        description: "リール2, 3, 4に出現。2倍または3倍のマルチプライヤーが付与されます。",
        isSpecial: true,
      },
      {
        name: "スキャッターシンボル (金庫/犬の足跡)",
        description: "リール1, 3, 5に出現。3つ以上揃うとフリースピンラウンドに突入します。",
        isSpecial: true,
      },
    ],
    maxPayout: "$10,000",
    notes: [
      "ベット額2ドルの場合の配当額です。",
      "ワイルドシンボルはペイライン上の勝利金を増加させます。",
    ],
  },
  features: {
    title: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのゲーム機能と特別なフィーチャー",
    items: [
      {
        name: "マルチプライヤーワイルド",
        description: "リール2, 3, 4に出現し、必ず2倍または3倍のマルチプライヤーが付与されます。複数のワイルドが出現した場合、マルチプライヤーは合算されます。",
        icon: "/images/the-dog-house-dog-or-alive-wild.jpg",
      },
      {
        name: "スキャッターシンボル",
        description: "3つ以上停止すると、9回から27回のフリースピンを獲得できます。",
        icon: "/images/the-dog-house-dog-or-alive-fs1.jpg",
      },
      {
        name: "フリースピン中のスティッキーワイルド",
        description: "フリースピン中に一度出現したマルチプライヤーワイルドは、スピン終了まで場に留まり続けます。これにより、ワイルドシンボルが増える可能性が高まります。",
        icon: "/images/the-dog-house-dog-or-alive-fs3.jpg",
      },
      {
        name: "追加フリースピン",
        description: "フリースピン中にワイルドシンボル3つ出現で、それぞれのマルチプライヤーが2倍になり、さらに追加で3スピンを獲得できます。",
        icon: "/images/the-dog-house-dog-or-alive-fs5.jpg",
      },
      {
        name: "ボーナスフィーチャー購入機能",
        description: "ベット額の100倍を支払うことで、フリースピンラウンドを直接購入できます。",
        icon: "/images/the-dog-house-dog-or-alive-bonusbuy.jpg",
      },
      {
        name: "オートプレイ機能",
        description: "ベット額とスピン回数を設定すれば、自動でスピンが進行します。特定の条件で停止させることも可能です。",
      },
    ],
  },
  sections: [
    {
      heading: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのレビュー",
      paragraphs: [
        "犬好きにはたまらない、魅力的なスロットが登場しました！🐶",
        "Pragmatic Play社がお届けするワンちゃんスロットの最新作、『 **ザ・ドッグ・ハウス・ドッグ・オア・アライブ（The Dog House Dog or Alive）**』がついにリリースされました。👏",
        "「デッド・オア・アライブ」をもじった「ドッグ・オア・アライブ（犬か生か問わず）」という、ユニークなスロット名が特徴的です。🤣",
        "この愛らしいスロットがどのようなゲームプレイを提供するのか、CasinoTsu が徹底的にレビューいたします。🐕",
      ],
    },
    {
      heading: "グラフィック・サウンド",
      table: {
        title: "グラフィック・サウンド",
        columns: ["項目", "詳細"],
        rows: [
          [
            "グラフィック",
            "グラフィックは非常に美しく、2024年に登場した最新スロットにふさわしいクオリティです。✨ テーマに沿った可愛らしいキャラクターデザインと、西部劇風の背景が絶妙にマッチしています。",
          ],
          [
            "モバイル対応",
            "👍 (下記参照)",
          ],
          [
            "サウンド・音響効果",
            "のどかな田舎の雰囲気に調和したBGMで、リラックスしてプレイできます。フリースピン中は一気にアップテンポな音楽に変わり、ゲームの興奮を高めます。効果音も適切で、プレイ体験を豊かにします。",
          ],
          [
            "特別フィーチャー",
            "・マルチプライヤー<br>・ワイルド<br>・スティッキーワイルド<br>・フリースピン購入機能",
          ],
        ],
      },
      paragraphs: [
        "🌟 **リリースされたばかりの最新スロットを、ぜひお楽しみください！**",
        "今が旬！最新スロットをまとめてチェックできます。",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "『ザ・ドッグ・ハウス・ドッグ・オア・アライブ』は、HTML5技術を用いて開発されており、**スマートフォンやタブレットなどのモバイルデバイスに完全に最適化**されています。",
        "**プラットフォーム:** iOS、Android",
        "**デバイス:** スマートフォン、タブレット",
        "**操作性:** 小さな画面でも直感的に操作でき、ストレスなくプレイできます。グラフィックやサウンドも、モバイル環境で最高の体験を提供できるよう調整されています。",
        "いつでもどこでも、お気に入りのデバイスでこの楽しいスロットをプレイすることができます。",
      ],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "CasinoTsu は、プレイヤーの皆様がより戦略的にプレイできるよう、以下のヒントを提供いたします。正確さが第一。興奮はその次。",
      ],
      bullets: [
        "ハイボラティリティを理解する",
        "'『ザ・ドッグ・ハウス・ドッグ・オア・アライブ』はハイボラティリティスロットです。これは、**勝利の頻度は低いかもしれませんが、一度勝利した際には大きな配当が期待できる**ことを意味します。",
        "   * **資金管理:** プレイする際は、十分な資金を用意し、一度のベット額を慎重に設定することが重要です。損失を取り戻そうと焦ってベット額を上げるのは避けましょう。",
        "   * **忍耐力:** 長時間プレイする覚悟を持ち、フリースピンなどのボーナスフィーチャーに到達するまで根気強く待ちましょう。",
        "**フリースピンの活用**",
        "フリースピンラウンドは、このスロットで最も大きな配当を得られるチャンスです。",
        "   * **スティッキーワイルドの重要性:** フリースピン中にワイルドシンボルが出現すると、そのシンボルはスピン終了まで場に留まります（スティッキーワイルド）。これにより、スピンが進むにつれてワイルドの数が増え、連鎖的な勝利の可能性が高まります。",
        "   * **ワイルドマルチプライヤーの活用:** ワイルドシンボルに付いているマルチプライヤーは、勝利金をさらに増加させます。複数のワイルドが出現した場合、それらのマルチプライヤーは合算されるため、爆発的な配当につながることもあります。",
        "   * **追加スピンの獲得:** フリースピン中に特定の条件（ワイルドシンボル3つ出現）を満たすと、マルチプライヤーが2倍になり、さらに3回の追加スピンを獲得できます。これを狙うことで、さらに勝利のチャンスを広げられます。",
        "**ベースゲームのフィーチャー**",
        "ベースゲーム中にもワイルドシンボルが出現し、マルチプライヤーが付与されるため、地道に配当を積み重ねることも可能です。複数のワイルドが出現すれば、それだけで大きな勝利につながることもあります。",
        "**ボーナス購入機能の利用**",
        "すぐにフリースピンを楽しみたい場合は、ボーナス購入機能を利用するのも一つの手です。ただし、購入したからといって必ずしも元が取れるとは限らないため、リスクを理解した上で活用しましょう。",
      ],
    },
    {
      heading: "まとめ",
      bullets: [
        "ターゲットプレイヤー層",
        "* **犬好き・動物テーマ好き:** 可愛らしい犬のキャラクターやテーマに魅力を感じるプレイヤー。",
        "* **ハイボラティリティ好き:** 大きな勝利の可能性を求めて、リスクを取ってでもプレイしたいプレイヤー。",
        "* **Western/Wild Westファン:** 保安官バッジなどの西部劇風モチーフに惹かれるプレイヤー。",
        "* **Pragmatic Playファン:** 同社のスロットをよくプレイする、または最新作を試したいプレイヤー。",
      ],
      paragraphs: [
        "『ザ・ドッグ・ハウス・ドッグ・オア・アライブ』は、**ゆったりとした雰囲気ながらも、アクション満載のゲーム体験を提供するスロット**です。チャーミングなテーマと革新的なメカニクスが組み合わさっており、プレイヤーを飽きさせません。",
        "初代『ザ・ドッグ・ハウス』からゲームフィーチャーを継承しつつ、グラフィックを大幅に向上させ、最大配当倍率も10,000倍に引き上げられています。 CasinoTsu は、完成度の高い、魅力的なスロットであると結論付けます。",
      ],
    },
  ],
  similarGames: [
    {
      name: "ラッキーネコ・ギガブロックス",
      href: "https://casinotsu.com/slots/lucky-neko-gigablox",
      provider: "Yggdrasil",
      description: "招き猫をテーマにしたスロット。3Dグラフィックのクオリティが高く、Gigabloxメカニクスによるユニークなゲーム展開が楽しめます。",
    },
    {
      name: "テッド",
      href: "https://casinotsu.com/slots/ted",
      provider: "Blueprint Gaming",
      description: "人気のアメリカンコメディー映画「テッド」をモチーフにしたスロット。可愛らしい（？）テディベアが登場し、ユーモアあふれる演出が特徴です。",
    },
    {
      name: "The Dog House Megaways",
      provider: "Pragmatic Play",
      description: "Megawaysメカニクスを導入し、ペイライン数が大幅に増加した人気作。よりダイナミックなゲームプレイが楽しめます。",
    },
    {
      name: "The Dog House Multihold",
      provider: "Pragmatic Play",
      description: "複数のリールセットでフリースピンが展開され、最大4つのリールセットでプレイできるユニークなゲーム性を持つスロットです。",
    },
  ],
  prosCons: {
    pros: [
      "最大10,000倍のハイボラティリティ",
      "可愛らしい犬のテーマと西部劇風のデザイン",
      "マルチプライヤーワイルドとスティッキーワイルドによる高い勝利ポテンシャル",
      "ボーナス購入機能で直接フリースピンを楽しめる",
      "モバイルデバイスに完全対応",
      "Pragmatic Play社の高品質なゲーム",
    ],
    cons: [
      "ハイボラティリティのため、勝利頻度が低い場合がある",
      "カジノによってRTPが異なる可能性がある",
      "初代『The Dog House』からの大きな変更点は少ないと感じるプレイヤーもいるかもしれない",
    ],
  },
  faq: [
    {
      q: "ザ・ドッグ・ハウス・ドッグ・オア・アライブの還元率は？",
      a: "RTPは96.52%、95.54%、94.54%のいずれかです。カジノによって設定が異なる場合がありますので、プレイ前に確認することをおすすめします。96.52%は業界平均を上回る高い数値です。",
    },
    {
      q: "ザ・ドッグ・ハウス・ドッグ・オア・アライブの最大配当倍率は？",
      a: "最大配当倍率は10,000倍です。これは、ハイボラティリティスロットとして非常に魅力的なポテンシャルです。",
    },
    {
      q: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのボラティリティは、どのくらい？",
      a: "ボラティリティは「High」（高）です。これは、勝利頻度は低いものの、一度の勝利で得られる配当が大きくなる可能性があることを意味します。",
    },
    {
      q: "ゲーム中に問題が発生した場合の対処法は？",
      a: "Pragmatic Playのゲームでは、通常、誤作動が発生した場合、そのベットは無効となり、ベット額は返還されるとされています。詳細については、プレイしているカジノの利用規約をご確認ください。 CasinoTsu では、常に正確な情報を提供するよう努めております。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "ザ・ドッグ・ハウス・ドッグ・オア・アライブ", href: "/slots/the-dog-house-dog-or-alive" },
  ],
  tableOfContents: [
    { label: "ザ・ドッグ・ハウス・ドッグ・オア・アライブ", href: "#header" },
    { label: "CasinoTsu 推薦カジノ", href: "#casinos" },
    { label: "ゲーム基本情報", href: "#game-info" },
    { label: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのレビュー", href: "#review" },
    { label: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのシンボルとペイアウト", href: "#payout-table" },
    { label: "ザ・ドッグ・ハウス・ドッグ・オア・アライブのゲーム機能と特別なフィーチャー", href: "#features" },
    { label: "プロバイダー情報", href: "#provider-info" },
    { label: "グラフィック・サウンド", href: "#visual-audio" },
    { label: "ペイアウト・配当表", href: "#payout-details" },
    { label: "モバイル対応", href: "#mobile" },
    { label: "戦略・攻略法", href: "#strategy" },
    { label: "類似ゲーム", href: "#similar-games" },
    { label: "まとめ", href: "#summary" },
    { label: "よくある質問", href: "#faq" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/the-dog-house-dog-or-alive" />;
}
