import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Mahjong Ways 2",
  hero: {
    title: "Mahjong Ways 2",
    subheading: "麻雀ウェイズ2",
    description: "麻雀のルールを知らなくても、まったく問題ございません！ PG Soft（ポケットゲームズソフト）社が提供する人気のスロット「麻雀ウェイズ2（Mahjong Ways 2）」について、CasinoTsu が徹底的に調査いたしました。",
    score: 3.4,
    scoreMax: 5,
    rtp: "96.95%",
    maxMultiplier: "x1,708",
    provider: "PG SOFT",
    releaseDate: "2020年7月1日",
    volatility: "中程度（Medium）",
    reels: "4-5-5-5-4",
    paylines: "最大2000通り",
    minBet: "$0.2",
    maxBet: "$50",
    slotImageSrc: "/slots/mahjong-ways-2.jpg",
    highlights: [
      "麻雀が分からなくても大丈夫✌️",
      "牌がシンボルですが、麻雀のルールを知らなくても全く問題ありません。直感的に楽しめる落下式スロットです。",
    ],
    watchouts: [],
  },
  featuredCasino: {
    name: "2アップカジノ 2up",
    logo: "/assets/casino/2up.png",
    href: "/reviews/2up",
    ctaText: "今すぐプレイ！",
    ctaHref: "/reviews/2up",
    tagline: "責任あるプレイ",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "30x",
      freeSpins: "30x",
      wagering: "¥850,000",
      rating: 4,
      tagline: "出金は基本的に即時反映で、ストレスフリーなプレイをお楽しみいただけます。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/golden-panda",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://casinotsu.com/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノでエンジョイしましょう。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/betgoat",
    },
    {
      name: "2up",
      logo: "/images/casino/2up_375x375.png",
      href: "https://casinotsu.com/reviews/2up",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/2up",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "https://casinotsu.com/reviews/cybet",
      bonus: "35x",
      freeSpins: "35x",
      wagering: "$500",
      rating: 3.5,
      tagline: "可愛いマスコットキャラクターが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/cybet",
    },
    {
      name: "1win",
      logo: "/images/casino/1win_375x375-2.png",
      href: "https://casinotsu.com/reviews/1win",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！ 今注目の仮想通貨対応オンラインカジノです★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/1win",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://casinotsu.com/reviews/miki",
      bonus: "30x",
      freeSpins: "20x",
      wagering: "$4,000",
      rating: 4,
      tagline: "充実したゲームラインナップ！ 盛りだくさんのボーナスでお得にプレイしましょう。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/miki",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/wsm-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wsm-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」を体験してみませんか？",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "29x",
      freeSpins: "-",
      wagering: "$1,000",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitz",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://casinotsu.com/reviews/katsuwin",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/katsuwin",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "35x",
      freeSpins: "40x",
      wagering: "¥200,000",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/sushi-casino",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://casinotsu.com/reviews/parimatch",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/parimatch",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io_375x375.png",
      href: "https://casinotsu.com/reviews/bets-io",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bets-io",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://casinotsu.com/reviews/duelbits",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "",
      rating: 4.5,
      tagline: "スポーツベットだけではありません！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/sportsbet-io",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "40x",
      freeSpins: "-",
      wagering: "$2,020",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノです★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/shuffle",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: "",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/winz-io",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "20x",
      freeSpins: "-",
      wagering: "$500",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノです。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/dafabet",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "35x",
      wagering: "50",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノです♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/lucky-block",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "30x",
      freeSpins: "20x",
      wagering: "1,800USDT",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/queen-casino",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "35x",
      freeSpins: "40x",
      wagering: "1BTC",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/mega-dice",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "45x",
      freeSpins: "60x",
      wagering: "$1,600",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bc-game",
    },
    {
      name: "Empire.io",
      logo: "/assets/casino/empireio.jpg",
      href: "https://casinotsu.com/reviews/empire-io",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "賭け条件ナシのキャシュバック＆VIP特典が素晴らしいカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/empire-io",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wonder-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナスが魅力です。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/wonder-casino",
    },
    {
      name: "K8",
      logo: "/assets/casino/k8.jpg",
      href: "https://casinotsu.com/reviews/k8",
      bonus: "25x",
      freeSpins: "25x",
      wagering: "$1,840",
      rating: 4.5,
      tagline: "日本で人気の実機を打つならK8のパチンコで決まりです！昔懐かしの台を打ちまくりましょう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/k8",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "35x",
      freeSpins: "40x",
      wagering: "¥65,000",
      rating: 4,
      tagline: "マニアックなプロバイダーも、OhMySpins なら見つかるかもしれません！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/ohmyspins",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "20x",
      freeSpins: "20x",
      wagering: "$777",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックがあります！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-me",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://casinotsu.com/reviews/mystino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "日本人プレイヤーの心を掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/mystino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "20x",
      freeSpins: "-",
      wagering: "$1,600",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここにあります！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/empire777",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino_375x375.png",
      href: "https://casinotsu.com/reviews/joycasino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスをぜひゲットしてください！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/joycasino",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://casinotsu.com/reviews/live-casino-house",
      bonus: "20x",
      freeSpins: "-",
      wagering: "¥50,000",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるお馴染みのカジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/live-casino-house",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "40x",
      freeSpins: "-",
      wagering: "¥200,000",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノです！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://casinotsu.com/reviews/casino-x",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイしましょう♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "20x",
      freeSpins: "20x",
      wagering: "$500",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/reviews/casitabi",
    },
    {
      name: "Lilibet",
      logo: "",
      href: "https://casinotsu.com/reviews/lilibet",
      bonus: "入金ボーナス最大¥50,000",
      freeSpins: "",
      wagering: "",
      rating: null,
      tagline: "",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/lilibet",
    },
    {
      name: "Casumo",
      logo: "",
      href: "https://casinotsu.com/reviews/casumo",
      bonus: "入金ボーナス合計最大$1,000＋300フリースピン",
      freeSpins: "",
      wagering: "",
      rating: null,
      tagline: "",
      ctaText: "詳細を見る",
      ctaHref: "https://casinotsu.com/reviews/casumo",
    },
  ],
  gameInfo: {
    intro: "「Mahjong Ways 2」は、人気ゲームプロバイダー [**PG SOFT（ポケットゲームズソフト）**](https://casinotsu.com/providers/pg-soft) が贈る、中国の伝統的なゲーム「麻雀」をテーマにした人気の [**スロット**](https://casinotsu.com/slots)「Mahjong Ways」の待望の続編です。\n\n**麻雀のルールを知らなくても、全く問題ありません！** このスロットは、麻雀の牌をモチーフにしたシンボルが登場しますが、ゲームシステムは現代的な落下式スロット（カスケードスロット）を採用しており、直感的に楽しむことができます。\n\nRTP（還元率）は96.95%と、オンラインスロットの平均を上回る高めの設定✨です。\n\n前作「Mahjong Ways」から、ゲームシステムがさらに洗練され、よりスムーズで没入感のあるゲーム体験を提供するように「ファインチューニング」されています。特にモバイルデバイスでのプレイ体験は、デスクトップよりも最適化されていると感じられるでしょう。\n\nCasinoTsu では、「Mahjong Ways 2」の魅力、ゲーム機能、そしてどこで遊べるのかを詳しく解説いたします。",
    basicInfo: {
      rtp: "96.95%",
      volatility: "中程度（Medium）",
      reels: "4-5-5-5-4",
      paylines: "最大2000通り",
      minBet: "$0.2",
      maxBet: "$50",
      provider: "PG SOFT",
      releaseDate: "2020年7月1日",
    },
  },
  payoutTable: {
    title: "Mahjong Ways 2 のルール、シンボル、ペイアウトについて",
    symbols: [
      {
        name: "發（ハツ）",
        description: "通常シンボルの中で最も配当が高い",
        payout5: "50倍",
        payout4: "",
        payout3: "",
      },
      {
        name: "通常シンボル",
        description: "9種類の通常シンボルが登場。麻雀の牌をモチーフにしたデザイン。",
        payout5: "",
        payout4: "",
        payout3: "",
      },
    ],
    maxPayout: "50倍",
    notes: [
      "「Mahjong Ways 2」は、メガウェイズスロットのようにシンボルがリール上に現れるたびに配当の可能性が変化する「カスケード（落下式）リール」を採用しています。",
      "左端のリールから順に3つ以上の同じシンボルが出現すると配当獲得となります。",
      "このカスケードシステムにより、1回のスピンで複数回の配当獲得のチャンスがあり、配当パターンは最大2,000通りにも及びます。",
    ],
  },
  features: {
    title: "Mahjong Ways 2｜ゲーム機能",
    items: [
      {
        name: "ワイルドシンボル",
        description: "ゲーム中、2、3、4列目に金色のシンボルが出現することがあります。これらの金色のシンボルが配当獲得の一部となった場合、そのシンボルがワイルドシンボルに変化します。ワイルドシンボルは、他のほとんどのシンボルの代わりとなるため、配当成立の可能性を高める重要な役割を果たします。",
        icon: "",
      },
      {
        name: "マルチプライヤー",
        description: "1回のスピン中に配当を獲得するたびに、マルチプライヤー（倍率）が増加していきます。このマルチプライヤーは、ワイルドシンボルとの相性が抜群で、高配当獲得のチャンスを大きく広げます。",
        icon: "",
      },
      {
        name: "フリースピンフィーチャー",
        description: "「胡」と書かれたシンボル（スキャッターシンボル）が3つ以上出現すると、フリースピンフィーチャーが発動します。初期状態では10回のフリースピンが獲得できます。フリースピンフィーチャー中は、ワイルドシンボルとマルチプライヤーの効果がさらに強化されます。特に、リール3列目（中央のリール）が全て金メッキシンボルに変化すること、マルチプライヤーが通常時よりも大幅に上昇することが特徴です。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "Mahjong Ways 2 とは？【導入・概要】",
      paragraphs: [
        "「Mahjong Ways 2」は、人気ゲームプロバイダー [**PG SOFT（ポケットゲームズソフト）**](https://casinotsu.com/providers/pg-soft) が贈る、中国の伝統的なゲーム「麻雀」をテーマにした人気の [**スロット**](https://casinotsu.com/slots)「Mahjong Ways」の待望の続編です。",
        "**麻雀のルールを知らなくても、全く問題ありません！** このスロットは、麻雀の牌をモチーフにしたシンボルが登場しますが、ゲームシステムは現代的な落下式スロット（カスケードスロット）を採用しており、直感的に楽しむことができます。",
        "RTP（還元率）は96.95%と、オンラインスロットの平均を上回る高めの設定✨です。",
        "前作「Mahjong Ways」から、ゲームシステムがさらに洗練され、よりスムーズで没入感のあるゲーム体験を提供するように「ファインチューニング」されています。特にモバイルデバイスでのプレイ体験は、デスクトップよりも最適化されていると感じられるでしょう。",
        "CasinoTsu では、「Mahjong Ways 2」の魅力、ゲーム機能、そしてどこで遊べるのかを詳しく解説いたします。",
      ],
    },
    {
      heading: "この記事で分かること",
      bullets: [
        "ゲームの遊び方、シンボル、ペイアウト",
        "最小・最大ベット額、オートプレイ機能",
        "RTP（還元率）、ボラティリティ（変動率）、最大配当倍率",
        "マルチプライヤー、ワイルド、フリースピンなどのゲームフィーチャー",
        "グラフィックやサウンドの質",
        "ゲームプレイ中のエラー対応",
        "前作からの改善点や、類似のおすすめスロット",
      ],
    },
    {
      heading: "Mahjong Ways 2 で利用できるボーナス",
      paragraphs: [
        "お得に「Mahjong Ways 2」をプレイしたい方のために、CasinoTsu がおすすめのカジノとボーナス情報をご紹介します。",
      ],
      table: {
        title: "カジノ名",
        columns: ["カジノ名", "ウェルカムボーナス"],
        rows: [
          ["[**Lilibet（リリベット）**](https://casinotsu.com/reviews/lilibet)", "入金ボーナス最大¥50,000"],
          ["[**Casumo（カスモ）**](https://casinotsu.com/reviews/casumo)", "入金ボーナス合計最大$1,000＋300フリースピン"],
        ],
      },
      notes: [
        "※上記以外にも、当サイト限定のボーナスが提供されている場合もあります。詳細は各カジノのレビューページをご確認ください。",
        "**💰新規登録時には初回入金ボーナスが狙い目です！** [オンラインカジノの初回入金ボーナス](https://casinotsu.com/bonuses/welcome-bonus) 特集では、ボーナスの種類や受け取り方、出金条件についても詳しく解説しています。",
      ],
    },
    {
      heading: "Mahjong Ways 2 のルール、シンボル、ペイアウトについて",
      paragraphs: [
        "「Mahjong Ways 2」の基本的なゲームシステムとシンボルについて、CasinoTsu が解説いたします。",
      ],
    },
    {
      heading: "【絵柄・シンボル】",
      paragraphs: [
        "ゲームには、 **9種類の通常シンボル** が登場します。これらのシンボルは、すべて麻雀の牌をモチーフにしたデザインです。",
        "通常シンボルの中で最も配当が高いのは「發（ハツ）」で、5つ揃った場合の最大配当倍率は **50倍** となっています。",
      ],
      table: {
        columns: ["シンボル", "説明", "5つ揃った時の配当"],
        rows: [
          ["發（ハツ）", "通常シンボルの中で最も配当が高い", "50倍"],
          ["通常シンボル", "9種類。麻雀の牌をモチーフ。", ""],
        ],
      },
    },
    {
      heading: "【配当について】",
      paragraphs: [
        "「Mahjong Ways 2」は、 [**メガウェイズスロット**](https://casinotsu.com/slots/megaways) のようにシンボルがリール上に現れるたびに配当の可能性が変化する「 **カスケード（落下式）リール** 」を採用しています。",
        "**左端のリールから順に3つ以上の同じシンボルが出現すると配当獲得** となります。このカスケードシステムにより、1回のスピンで複数回の配当獲得のチャンスがあり、 **配当パターンは最大2,000通り** にも及びます。",
      ],
      notes: [
        "🔥神出鬼没な当たりと読めないラインが病みつきになります💝",
        "[今イチ推しのメガウェイズスロットが気になる方はこちら♪](https://casinotsu.com/slots/megaways)",
      ],
    },
    {
      heading: "【ベットオプションとオートプレイ】",
      paragraphs: [
        "「Mahjong Ways 2」の **最小ベット額は$0.2**、 **最大ベット額は$50** です。",
        "プレイヤーは「 **ベットサイズ** 」と「 **ベットレベル** 」の2つの要素を設定して、1スピンあたりのベット額を調整します。",
        "ベット額 ＝ ベットサイズ × ベットレベル × 20",
        "勝利金 ＝ ベットサイズ × ベットレベル × 配当倍率",
        "**オートスピン機能も充実** しており、回数やロスリミットを設定できます。「その他」オプションからは、さらに残高増加額や1回あたりの賞金額によってオートスピンを停止させる細かな設定も可能です。",
      ],
    },
    {
      heading: "【RTP（還元率）】",
      paragraphs: [
        "**CasinoTsu が確認した「Mahjong Ways 2」のRTP（Return To Player：プレイヤーへの還元率）は96.95%** です。これは、オンラインスロットの平均的なRTP（約96%）と比較しても高い数値であり、プレイヤーにとって有利なゲームと言えるでしょう。",
      ],
    },
    {
      heading: "【変動率（ボラティリティ）】",
      paragraphs: [
        "**ボラティリティは「中程度（Medium）」** です。これは、ハイボラティリティのスロットに比べて爆発力はやや劣るものの、比較的頻繁に当たりが出やすく、リスクとリターンのバランスが良いことを意味します。初心者から経験者まで、幅広いプレイヤーが楽しめるでしょう。",
      ],
    },
    {
      heading: "【最大配当倍率について】",
      paragraphs: [
        "「Mahjong Ways 2」の最大配当倍率については、いくつかの情報源で異なる記載が見られます。",
        "ゲーム内表記: 最大配当倍率として **1,708倍** が提示されています。",
        "理論上の最大配当: 一方で、理論上の最大配当倍率は **100,000倍** にも達するとされています。また、一部の市場では€18,000,000.00（約27億円 ※1ユーロ150円換算）という途方もない勝利金の可能性も示唆されています。",
        "この大きな差は、ゲームの特性や計算方法によるものと考えられます。ゲームプレイ中は1,708倍の配当が現実的な目標となりますが、フリースピンなどのフィーチャーが重なることで、理論上の最大配当に近づく可能性も秘めています。",
      ],
      notes: [
        "💰一撃必殺！爆発力が自慢のスロット！",
        "[今一押しの高配当倍率スロットを発表します🎉](https://casinotsu.com/slots/best-payout)",
      ],
    },
    {
      heading: "Mahjong Ways 2｜ゲーム機能",
      paragraphs: [
        "「Mahjong Ways 2」の魅力は、その多彩なゲーム機能にあります。ここでは、ワイルドシンボル、マルチプライヤー、そしてフリースピンフィーチャーについて詳しく見ていきましょう。",
      ],
    },
    {
      heading: "・ワイルドシンボル",
      paragraphs: [
        "ゲーム中、 **2、3、4列目（リール）に金色のシンボル** が出現することがあります。これらの金色のシンボルが配当獲得の一部となった場合、そのシンボルが **ワイルドシンボルに変化** します。",
        "ワイルドシンボルは、他のほとんどのシンボルの代わりとなるため、配当成立の可能性を高める重要な役割を果たします。特に、カスケード（落下式）リールと組み合わせることで、連鎖的な配当獲得をサポートします。",
      ],
    },
    {
      heading: "・マルチプライヤー",
      paragraphs: [
        "「Mahjong Ways 2」では、 **1回のスピン中に配当を獲得するたびに、マルチプライヤー（倍率）が増加** していきます。このマルチプライヤーは、ワイルドシンボルとの相性が抜群で、高配当獲得のチャンスを大きく広げます。",
      ],
    },
    {
      heading: "・フリースピンフィーチャー",
      paragraphs: [
        "**「胡」と書かれたシンボル（スキャッターシンボル）が3つ以上** 出現すると、フリースピンフィーチャーが発動します。初期状態では **10回のフリースピン** が獲得できます。",
        "フリースピンフィーチャー中は、 **ワイルドシンボルとマルチプライヤーの効果がさらに強化** されます。",
        "特に注目すべきは、 **リール3列目（中央のリール）が全て金メッキシンボルに変化** することです。これにより、3列目までシンボルが揃えば配当獲得となるため、非常に有利な状況が生まれます。",
        "さらに、フリースピン中のマルチプライヤーは通常時よりも **大幅に上昇** し、高額配当獲得の絶好のチャンスとなります。",
      ],
      table: {
        columns: ["ラウンド", "フリースピン時マルチプライヤー", "通常時マルチプライヤー"],
        rows: [
          ["1", "×2", "×1"],
          ["2", "×4", "×2"],
          ["3", "×6", "×3"],
          ["4", "×10", "×5"],
        ],
      },
      notes: [
        "フリースピン中にさらにスキャッターシンボルが出現した場合、追加のフリースピンを獲得できる可能性があります。",
        "🐲ドラゴンが大活躍の中国がテーマのハイボラスロット！",
        "[『ドラゴン・ヒーロー（Dragon Hero）』もぜひチェックしてください♪](https://casinotsu.com/slots/dragon-hero)",
      ],
    },
    {
      heading: "【ボーナス購入機能について】",
      paragraphs: [
        "「Mahjong Ways 2」には、「ボーナスバイ（Bonus Buy）」機能は搭載されておりません。フリースピンフィーチャーを楽しむには、通常スピン中にスキャッターシンボルを引き当てる必要があります。",
      ],
    },
    {
      heading: "Mahjong Ways 2 のグラフィックとサウンド",
      paragraphs: [
        "「Mahjong Ways 2」のビジュアルは、赤と金色を基調とした、 **クリーンでスタイリッシュなデザイン** が特徴です。中華風のテーマが巧みに表現されており、洗練された印象を与えます。一方で、一部のプレイヤーからは、他のPG Soft社のゲームと比較して「やや地味」と感じられる可能性も指摘されています。",
        "このスロットは **モバイルデバイスでのプレイに最適化** されています。縦長のゲーム画面は、スマートフォンやタブレットでの操作性を重視して設計されており、パソコンよりも快適にプレイできるでしょう。",
        "BGMや効果音には、 **中国語のボイス** が取り入れられています。ゲームの雰囲気を盛り上げる効果音は魅力的ですが、何を言っているかはプレイヤーの語学力次第となります（笑）。",
      ],
    },
    {
      heading: "ゲーム中にエラーが発生したときは？",
      paragraphs: [
        "万が一、ゲームプレイ中にエラーが発生して中断してしまった場合でも、ご安心ください。 CasinoTsu が確認した対応策は以下の通りです。",
        "結果の確認: ゲーム結果は通常、サーバーに記録されております。プレイ履歴を確認することで、中断前の結果が確定しているかをご確認いただけます。",
        "再開方法: ブラウザを更新することで、ゲームが中断したところから再開できる場合があります。",
        "カスタマーサポート: 再開できない場合は、プレイしているオンラインカジノのカスタマーサポートに連絡し、状況を説明して指示を仰ぎましょう。",
      ],
    },
    {
      heading: "Mahjong Ways 2｜総評・レビューまとめ",
      paragraphs: [
        "「Mahjong Ways 2」は、麻雀をテーマにしながらも、 **麻雀を知らないプレイヤーでも安心して楽しめる** 、非常に完成度の高いスロットゲームです。前作「Mahjong Ways」からさらに洗練されたゲームシステムは、スムーズで没入感のあるプレイ体験を提供します。",
        "**RTP 96.95%** という高い還元率、 **中程度のボラティリティ** によるバランスの取れたゲーム性、そして **最大100,000倍** （理論値）という潜在的な爆発力は、多くのプレイヤーを魅了するでしょう。特に、カスケードリール、マルチプライヤー、そして強化されたフリースピンフィーチャーの組み合わせは、何度でもプレイしたくなる中毒性を持っています。",
        "**モバイルデバイスでのプレイ体験も非常に優れており** 、いつでもどこでも手軽に楽しめます。",
        "**ぜひ、カジノサイトで提供されているボーナスを活用して、「Mahjong Ways 2」の奥深いゲーム性を CasinoTsu と一緒に体験してみてください！**",
      ],
      notes: [
        "👑 **プレイヤーに最高のおもてなしを提供するカジノ**",
        "[初心者にも優しいデイリーキャッシュバックがあるリリベットをチェック！](https://casinotsu.com/reviews/lilibet)",
      ],
    },
    {
      heading: "Mahjong Ways 2 が好きな人におすすめのスロット！",
      paragraphs: [
        "「Mahjong Ways 2」がお好きなプレイヤーの皆様には、以下のスロットもきっと気に入っていただけることでしょう。",
      ],
      bullets: [
        "**麻雀ウェイズ（Mahjong Ways）**: 「Mahjong Ways 2」の前作であり、人気の基礎を築いた作品です。こちらもぜひプレイしてみてください。",
        "**麻雀88（Mahjong 88）**: 人気プロバイダー [**Play’n Go**](https://casinotsu.com/providers/play-n-go) 社による麻雀テーマのスロットです。高品質なグラフィックとサウンドが楽しめます。",
        "**[麻雀ウィンズ（Mahjong Wins）](https://casinotsu.com/slots/mahjong-wins)**: マルチプライヤーや落下式システムなど、「Mahjong Ways 2」と似たゲーム性を持つスロットです。[**Pragmatic Play**](https://casinotsu.com/providers/pragmatic-play) 社が開発しており、そのクオリティはお墨付きです。",
      ],
      notes: [
        "🀄 **オンラインカジノで麻雀ができる？**",
        "[麻雀をプレイしたい人は是非こちらをチェックしてください！](https://casinotsu.com/guides/mahjong)",
      ],
    },
    {
      heading: "Mahjong Ways 2｜戦略・攻略法",
      paragraphs: [
        "「Mahjong Ways 2」は運の要素が大きいスロットですが、CasinoTsu が見出したいくつかの戦略やポイントを意識することで、より長く、そして有利にプレイすることができます。",
      ],
      bullets: [
        "**中程度のボラティリティを理解する**\nこのゲームのボラティリティは「中程度」です。これは、ハイボラティリティのスロットのように一撃で巨額の賞金を狙うのは難しいかもしれませんが、比較的頻繁に配当が得られるため、資金を大きく減らすリスクを抑えながらプレイできることを意味します。",
        "【攻略のポイント】\n*   **頻繁な勝利を楽しむ:** 当たりやすいという特性を活かし、小さな勝利を積み重ねていくことを楽しみましょう。\n*   **資金管理:** 中程度のボラティリティでも、連敗が続く可能性はあります。事前にプレイ時間や予算の上限を決めて、それを守ることが重要です。\n*   **フリースピンの活用:** フリースピンフィーチャーは、マルチプライヤーが強化されるため、最も大きな配当が期待できる場面です。このフィーチャーを最大限に活かすことを目指しましょう。",
        "【ベット戦略】\n*   **ベットレベルの調整:** 「ベットサイズ」と「ベットレベル」を調整して、1スピンあたりのベット額を自分の資金に合わせて設定しましょう。最初は最小ベット額から始め、ゲームの感触を掴むのがおすすめです。\n*   **オートスピンの活用:** オートスピン機能を使えば、一定時間ゲームに集中できます。ただし、設定したロスリミットや賞金獲得額で自動停止するようにしておくと、無謀なプレイを防ぐことができます。",
        "【フィーチャー活用法】\n*   **ワイルドシンボルの重要性:** ワイルドシンボルは配当成立の鍵となります。常にリールに注目し、ワイルドシンボルの出現による連鎖に期待しましょう。\n*   **マルチプライヤーの連鎖:** 配当を獲得するたびにマルチプライヤーが増加する仕組みを理解し、連続して配当を獲得することで、賞金額を大きく伸ばすことを目指しましょう。",
        "【注意点】\n*   **「ボーナスバイ」機能はない:** このスロットには、直接フリースピンを購入できる機能はございません。フリースピンを得るには、通常のスピンでスキャッターシンボルを揃える必要があります。\n*   **過度な期待は禁物:** 最大配当倍率は理論上非常に大きいですが、現実的にはその上限に到達することは稀です。ゲームを楽しみつつ、堅実なプレイを心がけましょう。",
        "【モバイル最適化を活かす】\nこのスロットはモバイルでのプレイに最適化されています。スマートフォンやタブレットを使用することで、より直感的で快適な操作感を得られるでしょう。外出先でも手軽にプレイできるのが魅力です。",
        "【デモプレイの活用】\n「Mahjong Ways 2」は、多くのオンラインカジノで無料のデモモードが提供されています。実際のお金を使わずにゲームのルールやフィーチャーを試せるため、 **リアルマネーでプレイする前にデモプレイで十分に練習することをおすすめ** します。これにより、ゲームの理解を深め、 CasinoTsu と共に自分に合った戦略を見つけることができるでしょう。",
      ],
    },
    {
      heading: "よくある質問",
      faq: [
        {
          q: "「Mahjong Ways 2」のプロバイダーはどこですか？",
          a: "Pocket Games Soft（PG Soft）社です。 CasinoTsu が確認しております。",
        },
        {
          q: "麻雀のルールを知らなくても楽しめますか？",
          a: "はい、麻雀がテーマですが中身はスロットゲームです。麻雀のルールが分からなくても、直感的に楽しくプレイできます。",
        },
        {
          q: "「Mahjong Ways 2」のRTPはどれくらいですか？",
          a: "96.95%です。 CasinoTsu の情報に基づいております。",
        },
      ],
    },
  ],
  similarGames: [
    {
      name: "麻雀ウェイズ（Mahjong Ways）",
      href: "",
      provider: "PG SOFT",
      description: "「Mahjong Ways 2」の前作であり、人気の基礎を築いた作品です。こちらもぜひプレイしてみてください。",
    },
    {
      name: "麻雀88（Mahjong 88）",
      href: "",
      provider: "Play’n Go",
      description: "人気プロバイダー Play’n Go 社による麻雀テーマのスロットです。高品質なグラフィックとサウンドが楽しめます。",
    },
    {
      name: "麻雀ウィンズ（Mahjong Wins）",
      href: "/slots/mahjong-wins",
      provider: "Pragmatic Play",
      description: "マルチプライヤーや落下式システムなど、「Mahjong Ways 2」と似たゲーム性を持つスロットです。Pragmatic Play 社が開発しており、そのクオリティはお墨付きです。",
    },
  ],
  prosCons: {
    pros: [
      "麻雀のルールを知らなくても楽しめる",
      "RTP（還元率）が96.95%と高め",
      "中程度のボラティリティでバランスが良い",
      "カスケードリールとマルチプライヤーで連鎖的な配当獲得が期待できる",
      "強化されたフリースピンフィーチャー",
      "モバイルデバイスでのプレイに最適化されている",
    ],
    cons: [
      "最大配当倍率（ゲーム内表記）がやや低いと感じるプレイヤーもいるかもしれない",
      "ボーナスバイ機能がない",
      "グラフィックがやや地味と感じる可能性",
    ],
  },
  faq: [
    {
      q: "「Mahjong Ways 2」のプロバイダーはどこですか？",
      a: "Pocket Games Soft（PG Soft）社です。 CasinoTsu が確認しております。",
    },
    {
      q: "麻雀のルールを知らなくても楽しめますか？",
      a: "はい、麻雀がテーマですが中身はスロットゲームです。麻雀のルールが分からなくても、直感的に楽しくプレイできます。",
    },
    {
      q: "「Mahjong Ways 2」のRTPはどれくらいですか？",
      a: "96.95%です。 CasinoTsu の情報に基づいております。",
    },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "/reviews/2up",
  },
  breadcrumbs: [
    { label: "ホーム", href: "https://casinotsu.com/" },
    { label: "スロット", href: "https://casinotsu.com/slots" },
    { label: "Mahjong ways 2", href: "https://casinotsu.com/slots/mahjong-ways-2" },
  ],
  tableOfContents: [
    { label: "Mahjong Ways 2", href: "#" },
    { label: "Mahjong Ways 2 をプレイできるカジノ", href: "#" },
    { label: "Mahjong Ways 2 基本情報", href: "#" },
    { label: "Mahjong Ways 2 とは？【導入・概要】", href: "#" },
    { label: "この記事で分かること", href: "#" },
    { label: "Mahjong Ways 2 で利用できるボーナス", href: "#" },
    { label: "Mahjong Ways 2 のルール、シンボル、ペイアウトについて", href: "#" },
    { label: "【絵柄・シンボル】", href: "#" },
    { label: "【配当について】", href: "#" },
    { label: "【ベットオプションとオートプレイ】", href: "#" },
    { label: "【RTP（還元率）】", href: "#" },
    { label: "【変動率（ボラティリティ）】", href: "#" },
    { label: "【最大配当倍率について】", href: "#" },
    { label: "Mahjong Ways 2｜ゲーム機能", href: "#" },
    { label: "・ワイルドシンボル", href: "#" },
    { label: "・マルチプライヤー", href: "#" },
    { label: "・フリースピンフィーチャー", href: "#" },
    { label: "【ボーナス購入機能について】", href: "#" },
    { label: "Mahjong Ways 2 のグラフィックとサウンド", href: "#" },
    { label: "ゲーム中にエラーが発生したときは？", href: "#" },
    { label: "Mahjong Ways 2｜総評・レビューまとめ", href: "#" },
    { label: "Mahjong Ways 2 が好きな人におすすめのスロット！", href: "#" },
    { label: "Mahjong Ways 2｜戦略・攻略法", href: "#" },
    { label: "よくある質問", href: "#" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/mahjong-ways-2" />;
}
