import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "ゲーツ・オブ・ハデス (Gates of Hades)",
  hero: {
    title: "ゲーツ・オブ・ハデス (Gates of Hades)",
    subheading: "Pragmatic Play社より冥界からの挑戦状！",
    description: "Pragmatic Play社が2025年5月22日にリリースした最新スロット「ゲーツ・オブ・ハデス（Gates of Hades）」は、神々の世界を描いた「ゲーツ・オブ・オリンパス」シリーズとは対照的に、冥界を舞台としたスリリングな世界観を提供します。",
    score: 4.4,
    scoreMax: 5,
    rtp: "96.52%",
    maxMultiplier: "10,000x",
    provider: "Pragmatic Play",
    releaseDate: "2025年5月22日",
    volatility: "High",
    reels: "6x6",
    paylines: "Cluster Pays",
    minBet: "$0.20",
    maxBet: "$240",
    slotImageSrc: "/slots/gates-of-hades-2025.jpg",
    highlights: [
      "最大10,000倍という高い配当ポテンシャル。",
      "ワイルドマルチプライヤー機能による爆発力。",
      "マルチプライヤーが蓄積されていくフリースピン（特にスーパーフリースピン）。",
      "冥界をテーマにしたダークで魅力的なビジュアルとサウンド。",
      "アンティベット機能によるフリースピン突入率の向上。",
    ],
    watchouts: [
      "ボラティリティが高い分、勝利までに時間を要したり、大きな損失を被るリスクがあります。",
      "スーパーフリースピンのボーナス購入額が非常に高額（ベット額の500倍）です。",
      "ベースゲームの展開が単調に感じられることがあります。",
      "カジノによってRTPが異なる場合があるため、プレイ前に必ず確認が必要です。",
    ],
  },
  featuredCasino: {
    name: "2アップカジノ",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-hades",
    ctaText: "2アップカジノ で今すぐプレイ！",
    tagline: "CasinoTsu 推薦",
  },
  casinos: [
    {
      name: "ReSpin",
      logo: "/assets/casino/respin.jpg",
      href: "https://casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fgates-of-hades",
      bonus: "35x 賭け条件",
      freeSpins: "5x 賭け条件",
      wagering: "10種類の主要仮想通貨が利用可能なクリプトカジノ！",
      rating: 4,
      tagline: "10種類の主要仮想通貨が利用可能なクリプトカジノ！",
      ctaText: "ReSpinで今すぐプレイ！",
      ctaHref: "https://casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fgates-of-hades",
    },
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fgates-of-hades",
      bonus: "30x 賭け条件",
      freeSpins: "30x 賭け条件",
      wagering: "出金は基本的に即時反映でストレスフリー！",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー！",
      ctaText: "Golden Pandaで今すぐプレイ！",
      ctaHref: "https://casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fgates-of-hades",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fgates-of-hades",
      wagering: "独自コインも利用可能！最新クリプトカジノ。",
      rating: 4,
      tagline: "独自コインも利用可能！最新クリプトカジノ。",
      ctaText: "Betgoatで今すぐプレイ！",
      ctaHref: "https://casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fgates-of-hades",
    },
    {
      name: "2up",
      logo: "/images/casino/2up_375x375.png",
      href: "https://casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-hades",
      wagering: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
      ctaText: "2upで今すぐプレイ！",
      ctaHref: "https://casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-hades",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fgates-of-hades",
      wagering: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "Roobetで今すぐプレイ！",
      ctaHref: "https://casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fgates-of-hades",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fgates-of-hades",
      rating: 4,
      tagline: "",
      ctaText: "Mystinoで今すぐプレイ！",
      ctaHref: "https://casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fgates-of-hades",
    },
  ],
  gameInfo: {
    intro: "Pragmatic Play社がお届けする新作「ゲーツ・オブ・ハデス（Gates of Hades）」は、冥界の深淵へとプレイヤーを誘います👿「Gates of Olympos」や「Gates of Olympus 1000」のファンであれば、このダークな世界観は必見です👀🔥最大500倍のワイルドマルチプライヤー と 最大10,000倍 を誇るこのハイボラスロットについて、CasinoTsuが詳しくレビューいたします🤭このゲームは、ダークでスリリングなテーマが特徴であり、リスクを恐れず大金を動かすプレイヤーや、大胆なゲームプレイを求めるプレイヤーに最適です。しかし、その高いボラティリティゆえに、カジュアルなプレイヤーや少額でプレイするプレイヤーには、勝利までに時間を要する可能性があることをご留意ください。",
    basicInfo: {
      rtp: "96.52%",
      volatility: "High",
      reels: "6x6",
      paylines: "Cluster Pays",
      minBet: "$0.20",
      maxBet: "$240",
      provider: "Pragmatic Play",
      releaseDate: "2025年5月22日",
    },
  },
  payoutTable: {
    title: "ゲーツ・オブ・ハデスのシンボルとペイアウト",
    symbols: [
      {
        name: "王冠",
        payout5: "150x",
        payout4: "50x",
        payout3: "20x",
        payout2: "5x",
        payout1: "2x",
      },
      {
        name: "指輪",
        payout5: "100x",
        payout4: "30x",
        payout3: "15x",
        payout2: "4x",
        payout1: "1.5x",
      },
      {
        name: "兜",
        payout5: "75x",
        payout4: "25x",
        payout3: "12x",
        payout2: "3x",
        payout1: "1x",
      },
      {
        name: "剣",
        payout5: "60x",
        payout4: "20x",
        payout3: "10x",
        payout2: "2x",
        payout1: "0.8x",
      },
      {
        name: "宝石（赤）",
        payout5: "50x",
        payout4: "15x",
        payout3: "8x",
        payout2: "2x",
        payout1: "0.6x",
      },
      {
        name: "宝石（青）",
        payout5: "40x",
        payout4: "12x",
        payout3: "6x",
        payout2: "1.5x",
        payout1: "0.5x",
      },
      {
        name: "宝石（緑）",
        payout5: "30x",
        payout4: "10x",
        payout3: "5x",
        payout2: "1x",
        payout1: "0.4x",
      },
      {
        name: "宝石（紫）",
        payout5: "25x",
        payout4: "8x",
        payout3: "4x",
        payout2: "1x",
        payout1: "0.3x",
      },
      {
        name: "宝石（黄）",
        payout5: "20x",
        payout4: "6x",
        payout3: "3x",
        payout2: "0.8x",
        payout1: "0.2x",
      },
      {
        name: "スキャッター（ハデス）",
        description: "3つ以上でフリースピン突入",
        isSpecial: true,
      },
      {
        name: "ワイルド（火の輪）",
        description: "マルチプライヤー付き",
        isSpecial: true,
      },
    ],
    maxPayout: "10,000x",
    notes: [
      "8個以上のシンボルがクラスターを形成すると配当が発生します。",
      "シンボルが消えると上から新しいシンボルが降ってくるカスケード式スロットです。",
    ],
  },
  features: {
    title: "ゲーツ・オブ・ハデスのゲーム機能と特別なフィーチャー",
    items: [
      {
        name: "ワイルド（マルチプライヤー）",
        description: "「火の輪」ワイルドシンボルは、ベースゲーム中は2倍から最大100倍、フリースピン中は最大500倍のマルチプライヤーを伴って出現します。出現したマルチプライヤーはリール上部に蓄積され、カスケード終了ごとにリセットされますが、同じスピン中に複数のワイルドシンボルが停止した場合、それらのマルチプライヤーは加算されます。",
        icon: "/images/icons/wild.svg",
      },
      {
        name: "フリースピン",
        description: "スキャッターシンボル（ハデス様）3つ以上で発動します。3個で10回、4個で12回、5個で15回、6個以上で20回（スーパーフリースピン）のフリースピンを獲得できます。フリースピン中は、ベースゲームとは異なり、停止したワイルドマルチプライヤーがリセットされずに蓄積されていきます。",
        icon: "/images/icons/free-spins.svg",
      },
      {
        name: "スーパーフリースピン",
        description: "ハデス様（スキャッター）が6個以上出現して発動する、より強力なフリースピンです。最低でも10倍以上のマルチプライヤーが保証され、フリースピンの回数も20回獲得できます。リール上の倍率も素早く加算され、爆発的な配当が期待できます。",
        icon: "/images/icons/super-free-spins.svg",
      },
      {
        name: "ボーナス購入機能",
        description: "ベット額の100倍で通常フリースピンを、500倍でスーパーフリースピンを購入できます。一部の国や地域では利用できない場合があります。",
        icon: "/images/icons/bonus-buy.svg",
      },
      {
        name: "アンティベット機能",
        description: "ベット額が25%増加しますが、フリースピンがトリガーされる確率が大幅にアップします。",
        icon: "/images/icons/ante-bet.svg",
      },
    ],
  },
  sections: [
    {
      heading: "ゲーツ・オブ・ハデスのレビュー",
      paragraphs: [
        "Pragmatic Play社がお届けする新作「ゲーツ・オブ・ハデス（Gates of Hades）」は、冥界の深淵へとプレイヤーを誘います👿",
        "「Gates of Olympos」や「Gates of Olympus 1000」のファンであれば、このダークな世界観は必見です👀🔥",
        "最大500倍のワイルドマルチプライヤー と 最大10,000倍 を誇るこのハイボラスロットについて、CasinoTsuが詳しくレビューいたします🤭",
        "このゲームは、ダークでスリリングなテーマが特徴であり、リスクを恐れず大金を動かすプレイヤーや、大胆なゲームプレイを求めるプレイヤーに最適です。しかし、その高いボラティリティゆえに、カジュアルなプレイヤーや少額でプレイするプレイヤーには、勝利までに時間を要する可能性があることをご留意ください。",
      ],
    },
    {
      heading: "ゲーツ・オブ・ハデスのグラフィック＆サウンド",
      paragraphs: [
        "冥界の深淵を思わせる、赤・オレンジ・紫を基調としたダークな色使い。燃え盛る炎、溶岩流、ギザギザした岩などが描かれ、ハデス（冥界の神）の威厳ある姿が印象的です。全体的に重厚でスリリングな雰囲気を醸し出しています。",
        "緊張感を高める、重厚でダークなBGM。雷鳴、炎の燃える音、キャラクターの効果音などが絶妙に組み合わさり、プレイヤーを冥界の世界観へと深く引き込みます。プレイ中の緊迫感をさらに高めるサウンドデザインです。",
      ],
    },
    {
      heading: "ゲーツ・オブ・ハデスのモバイル体験",
      paragraphs: [
        "ゲーツ・オブ・ハデスは、モバイル環境に完全対応しています！外出先でも、PC版と変わらない高品質なグラフィックとスムーズな操作性をお楽しみいただけます📱 快適なモバイルカジノやカジノアプリを通じて、いつでもハデス様に挑戦することが可能です💪✨",
      ],
    },
    {
      heading: "ゲーツ・オブ・ハデスのおすすめ・残念ポイント",
      paragraphs: [
        "おすすめポイント: 最大10,000倍という高い配当ポテンシャル。ワイルドマルチプライヤー機能による爆発力。マルチプライヤーが蓄積されていくフリースピン（特にスーパーフリースピン）。冥界をテーマにしたダークで魅力的なビジュアルとサウンド。アンティベット機能によるフリースピン突入率の向上。",
        "残念ポイント: ボラティリティが高い分、勝利までに時間を要したり、大きな損失を被るリスクがあります。スーパーフリースピンのボーナス購入額が非常に高額（ベット額の500倍）です。ベースゲームの展開が単調に感じられることがあります。カジノによってRTPが異なる場合があるため、プレイ前に必ず確認が必要です。",
      ],
    },
    {
      heading: "最大10,000倍を目指して、いざ冥界へ😱",
      paragraphs: [
        "Pragmatic Play社の新作「ゲーツ・オブ・ハデス」は、単なる前作の焼き直しではなく、さらに深みと魅力を増したオンラインスロットです👿🔥",
        "クラスターペイとタンブル機能の連鎖に、高倍率のワイルドマルチプライヤーが絡んだ時の爆発力はまさに驚異的！",
        "特に、フリースピン中にマルチプライヤーが徐々に育っていく様子は、心臓が高鳴る体験です💓",
        "高いボラティリティは覚悟が必要ですが、その先に待つ最大10,000倍の配当は、挑戦する価値が大いにあります！",
        "ハイボラティリティスロットは、勝利までに時間がかかることがありますが、一度大きな勝利を掴めばそのリターンは非常に大きいです。十分なバンクロール管理と、焦らずゲームを楽しむ姿勢が重要です。",
        "ぜひ、冥府の王ハデスに挑戦してみてください😆🔥",
      ],
    },
    {
      heading: "ゲーツ・オブ・ハデスがお好きなあなたへのおすすめスロット",
      table: {
        columns: ["スロット名", "詳細"],
        rows: [
          ["ゲーツ・オブ・オリンパス", "やっぱり外せません！フリースピン獲得確率を2倍にする アンティベット で初期作を攻略しましょう♪"],
          ["ゲーツ・オブ・オリンパス1000", "ゼウス様のシリーズ作で、マルチプライヤー最大1,000倍に挑戦してみませんか？😆🎰"],
          ["ゲーツ・オブ・オリンパス・スーパースキャッター", "ゲーツ・オブ・オリンパスシリーズの最新作！ 最大配当倍率50,000倍 の激アツスロット🔥"],
        ],
      },
    },
    {
      heading: "よくある質問",
      faq: [
        {
          q: "ゲーツ・オブ・ハデスの最小ベット額と最大ベット額は？",
          a: "カジノによって若干の違いはありますが、基本的には0.20ドルから最大240ドルとなっております。",
        },
        {
          q: "ゲーツ・オブ・ハデスはどこでプレイできますか？",
          a: "Pragmatic Play社は人気のプロバイダーですので、多くのオンラインカジノでプレイ可能です。CasinoTsuでご紹介しているカジノでは、ReSpin、Golden Panda、Betgoat、2up、Roobet、Mystinoなどで遊ぶことができますよ♪",
        },
        {
          q: "ゲーツ・オブ・ハデスでフリースピンは購入できますか？",
          a: "はい、購入可能です。ベット額の100倍から通常フリースピンを、500倍でスーパーフリースピンを購入できます。",
        },
      ],
    },
  ],
  similarGames: [
    {
      name: "ゲーツ・オブ・オリンパス",
      href: "https://casinotsu.com/slots/gates-of-olympus",
      provider: "Pragmatic Play",
      description: "やっぱり外せません！フリースピン獲得確率を2倍にする アンティベット で初期作を攻略しましょう♪",
    },
    {
      name: "ゲーツ・オブ・オリンパス1000",
      href: "https://casinotsu.com/slots/gates-of-olympus-1000",
      provider: "Pragmatic Play",
      description: "ゼウス様のシリーズ作で、マルチプライヤー最大1,000倍に挑戦してみませんか？😆🎰",
    },
    {
      name: "ゲーツ・オブ・オリンパス・スーパースキャッター",
      href: "https://casinotsu.com/slots/gates-of-olympus-super-scatter",
      provider: "Pragmatic Play",
      description: "ゲーツ・オブ・オリンパスシリーズの最新作！ 最大配当倍率50,000倍 の激アツスロット🔥",
    },
  ],
  prosCons: {
    pros: [
      "最大10,000倍という高い配当ポテンシャル。",
      "ワイルドマルチプライヤー機能による爆発力。",
      "マルチプライヤーが蓄積されていくフリースピン（特にスーパーフリースピン）。",
      "冥界をテーマにしたダークで魅力的なビジュアルとサウンド。",
      "アンティベット機能によるフリースピン突入率の向上。",
    ],
    cons: [
      "ボラティリティが高い分、勝利までに時間を要したり、大きな損失を被るリスクがあります。",
      "スーパーフリースピンのボーナス購入額が非常に高額（ベット額の500倍）です。",
      "ベースゲームの展開が単調に感じられることがあります。",
      "カジノによってRTPが異なる場合があるため、プレイ前に必ず確認が必要です。",
    ],
  },
  faq: [
    {
      q: "ゲーツ・オブ・ハデスの最小ベット額と最大ベット額は？",
      a: "カジノによって若干の違いはありますが、基本的には0.20ドルから最大240ドルとなっております。",
    },
    {
      q: "ゲーツ・オブ・ハデスはどこでプレイできますか？",
      a: "Pragmatic Play社は人気のプロバイダーですので、多くのオンラインカジノでプレイ可能です。CasinoTsuでご紹介しているカジノでは、ReSpin、Golden Panda、Betgoat、2up、Roobet、Mystinoなどで遊ぶことができますよ♪",
    },
    {
      q: "ゲーツ・オブ・ハデスでフリースピンは購入できますか？",
      a: "はい、購入可能です。ベット額の100倍から通常フリースピンを、500倍でスーパーフリースピンを購入できます。",
    },
  ],
  cta: {
    text: "CasinoTsu 推薦カジノで今すぐプレイ！",
    href: "https://casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-hades",
  },
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "ゲーツ・オブ・ハデス", href: "/slots/gates-of-hades" },
  ],
  tableOfContents: [
    { label: "ゲーツ・オブ・ハデスのレビュー", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%AE%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC" },
    { label: "ゲーツ・オブ・ハデスのシンボルとペイアウト", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%AE%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AB%E3%81%A8%E3%83%9A%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88" },
    { label: "ゲーツ・オブ・ハデスのゲーム機能と特別なフィーチャー", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%AE%E3%82%B2%E3%83%BC%E3%83%A0%E6%A9%9F%E8%83%BD%E3%81%A8%E7%89%B9%E5%88%A5%E3%81%AA%E3%83%95%E3%82%A3%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC" },
    { label: "ゲーツ・オブ・オリンパスとゲーツ・オブ・ハデスを徹底比較！", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%82%AA%E3%83%AA%E3%83%B3%E3%83%91%E3%82%B9%E3%81%A8%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%82%92%E5%BE%B9%E5%BA%95%E6%AF%94%E8%BC%83%EF%BC%81" },
    { label: "ゲーツ・オブ・ハデスのグラフィック＆サウンド", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%AE%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%83%E3%82%AF%EF%BC%86%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89" },
    { label: "ゲーツ・オブ・ハデスのモバイル体験", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%AE%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E4%BD%93%E9%A8%93" },
    { label: "ゲーツ・オブ・ハデスのおすすめ・残念ポイント", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%AE%E3%81%8A%E3%81%99%E3%81%99%E3%81%B1%E3%83%BB%E6%AE%8B%E5%BF%83%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88" },
    { label: "最大10,000倍を目指して、いざ冥界へ😱", href: "https://casinotsu.com/slots/gates-of-hades#%E6%9C%80%E5%A4%A710,000%E5%80%8D%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%97%E3%81%A6%E3%80%81%E3%81%84%E3%81%96%E5%86%A5%E7%95%8C%E3%81%B8%F0%9F%98%B1" },
    { label: "ゲーツ・オブ・ハデスがお気に入りのあなたにオススメのスロット", href: "https://casinotsu.com/slots/gates-of-hades#%E3%82%B2%E3%83%BC%E3%83%84%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%83%8F%E3%83%87%E3%82%B9%E3%81%8C%E3%81%8A%E6%B0%97%E3%81%AB%E5%85%A5%E3%82%8A%E3%81%AE%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AB%E3%82%AA%E3%82%B9%E3%82%B9%E3%83%A1%E3%81%AE%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/gates-of-hades" />;
}
