import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Sweet Rush Megaways（スイートラッシュ・メガウェイズ）徹底レビュー 🍭",
  hero: {
    title: "Sweet Rush Megaways",
    subheading: "BGAMING社による、最大117,649通りのペイラインを持つカラフルなメガウェイズスロット！",
    description: "可愛らしいお菓子の世界観とは裏腹に、最大12,960倍のポテンシャルを秘めたハイボラティリティスロット。チャンス×2機能や固定ワイルドによるマルチプライヤーが勝利を後押しします。",
    score: 4.5,
    scoreMax: 5,
    rtp: "96.96%",
    maxMultiplier: "x12,960",
    provider: "BGAMING",
    releaseDate: "2023年2月16日",
    volatility: "Very High",
    reels: "6",
    paylines: "最大117,649通り",
    minBet: "$0.1",
    maxBet: "$100",
    slotImageSrc: "/slots/sweet-rush-megaways.jpg",
    highlights: [
      "メガウェイズエンジン搭載で最大117,649通りのペイライン",
      "最大12,960倍の驚異的な配当ポテンシャル",
      "チャンス×2機能でフリースピン突入率アップ",
      "フリースピン中は固定ワイルドとマルチプライヤーで高配当を狙える",
      "ボーナス購入機能で即フリースピンへ",
    ],
    watchouts: [
      "ハイボラティリティのため、勝利頻度は低い傾向",
      "チャンス×2機能有効時はベット額が上昇",
      "フリースピン中にスキャッターを追加してもフリースピンは増えない",
    ],
  },
  featuredCasino: {
    name: "Golden Panda",
    logo: "/assets/casino/golden-panda.png",
    href: "https://casinotsu.com/reviews/golden-panda",
    ctaText: "今すぐプレイ",
    ctaHref: "https://casinotsu.com/reviews/golden-panda",
    tagline: "ボーナス: 30倍賭け条件、フリースピン: 30倍賭け条件",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.png",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "30倍賭け条件",
      freeSpins: "30倍賭け条件",
      wagering: "30x",
      rating: 4.5,
      tagline: "ボーナス: 30倍賭け条件、フリースピン: 30倍賭け条件",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/golden-panda",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.png",
      href: "https://casinotsu.com/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4.2,
      tagline: "ボーナス: $0、フリースピン: -",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/betgoat",
    },
    {
      name: "2up Casino",
      logo: "/images/casino/2up-casino.png",
      href: "https://casinotsu.com/reviews/2up-casino",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/2up-casino",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.png",
      href: "https://casinotsu.com/reviews/cybet",
      bonus: "35倍賭け条件、$500",
      freeSpins: "35倍賭け条件、50",
      wagering: "35x",
      rating: 4.3,
      tagline: "ボーナス: 35倍賭け条件、$500、フリースピン: 35倍賭け条件、50",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/cybet",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      href: "https://casinotsu.com/reviews/1win",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.1,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/1win",
    },
    {
      name: "WSM Casino",
      logo: "/assets/casino/wsm-casino.png",
      href: "https://casinotsu.com/reviews/wsm-casino",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.4,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/wsm-casino",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.png",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "29倍賭け条件、$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4.3,
      tagline: "ボーナス: 29倍賭け条件、$1,000、フリースピン: -",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/bitz",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.png",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "35倍賭け条件、¥200,000",
      freeSpins: "40倍賭け条件、50",
      wagering: "35x",
      rating: 4.6,
      tagline: "ボーナス: 35倍賭け条件、¥200,000、フリースピン: 40倍賭け条件、50",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/sushi-casino",
    },
    {
      name: "Betpanda",
      logo: "/assets/casino/betpanda.png",
      href: "https://casinotsu.com/reviews/betpanda",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/betpanda",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io.png",
      href: "https://casinotsu.com/reviews/bets-io",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.2,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/bets-io",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "https://casinotsu.com/reviews/duelbits",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.3,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/images/casino/sportsbet-io.png",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ボーナス: 1,000USDT",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/sportsbet-io",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.png",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "40倍賭け条件、$2,020",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.4,
      tagline: "ボーナス: 40倍賭け条件、$2,020",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/shuffle",
    },
    {
      name: "Winz",
      logo: "/images/casino/winz-io.png",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: "-",
      rating: 4.6,
      tagline: "ボーナス: $10,000、フリースピン: 800",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/winz-io",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.png",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "35倍賭け条件、50",
      wagering: "35x",
      rating: 4.7,
      tagline: "ボーナス: €25,000、フリースピン: 35倍賭け条件、50",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/lucky-block",
    },
    {
      name: "Ramenbet",
      logo: "/assets/casino/ramenbet.png",
      href: "https://casinotsu.com/reviews/ramenbet",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.1,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/ramenbet",
    },
    {
      name: "Flush Casino",
      logo: "/assets/casino/flush-casino.png",
      href: "https://casinotsu.com/reviews/flush-casino",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.2,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/flush-casino",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/queen-casino.png",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "30倍賭け条件、1,800USDT",
      freeSpins: "20倍賭け条件、288",
      wagering: "30x",
      rating: 4.5,
      tagline: "ボーナス: 30倍賭け条件、1,800USDT、フリースピン: 20倍賭け条件、288",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/queen-casino",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.png",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4.4,
      tagline: "ボーナス: $0、フリースピン: -",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/roobet",
    },
    {
      name: "Fresh Casino",
      logo: "/assets/casino/fresh-casino.png",
      href: "https://casinotsu.com/reviews/fresh-casino",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.3,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/fresh-casino",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      href: "https://casinotsu.com/reviews/stake",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.6,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/stake",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      href: "https://casinotsu.com/reviews/yuugado",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/yuugado",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.png",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "20倍賭け条件、$777",
      freeSpins: "20倍賭け条件、77",
      wagering: "20x",
      rating: 4.4,
      tagline: "ボーナス: 20倍賭け条件、$777、フリースピン: 20倍賭け条件、77",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/casino-me",
    },
    {
      name: "Vera&John",
      logo: "/assets/casino/vera-john.png",
      href: "https://casinotsu.com/reviews/vera-john",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.3,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/vera-john",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/jp/bitcasino-io.png",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "40倍賭け条件、¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "ボーナス: 40倍賭け条件、¥200,000",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      href: "https://casinotsu.com/reviews/casino-x",
      bonus: "なし",
      freeSpins: "-",
      wagering: "-",
      rating: 4.2,
      tagline: "ボーナス: なし",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.png",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "20倍賭け条件、$500",
      freeSpins: "20倍賭け条件、250",
      wagering: "20x",
      rating: 4.4,
      tagline: "ボーナス: 20倍賭け条件、$500、フリースピン: 20倍賭け条件、250",
      ctaText: "今すぐプレイ",
      ctaHref: "https://casinotsu.com/reviews/casitabi",
    },
  ],
  gameInfo: {
    intro: "Sweet Rush Megaways（スイートラッシュ・メガウェイズ）は、BGaming社によって2023年2月16日にリリースされたメガウェイズエンジン搭載のスロットゲームです。カラフルなお菓子の世界観と、最大117,649通りのペイライン、そして最大12,960倍の配当ポテンシャルが魅力です。ハイボラティリティのスロットとして、大きな勝利の可能性を秘めています。",
    basicInfo: {
      rtp: "96.96%",
      volatility: "Very High",
      reels: "6",
      paylines: "最大117,649通り",
      minBet: "$0.1",
      maxBet: "$100",
      provider: "BGAMING",
      releaseDate: "2023年2月16日",
    },
  },
  payoutTable: {
    title: "ペイアウト・配当表",
    symbols: [
      {
        name: "お菓子のモンスター (最高配当シンボル)",
        payout5: "x5",
        payout4: "x4",
        payout3: "x3",
        description: "最高配当シンボル",
      },
      {
        name: "キャンディー (赤)",
        payout5: "x4",
        payout4: "x3",
        payout3: "x1.5",
      },
      {
        name: "キャンディー (青)",
        payout5: "x3",
        payout4: "x2",
        payout3: "x1",
      },
      {
        name: "キャンディー (緑)",
        payout5: "x2.5",
        payout4: "x1.5",
        payout3: "x0.8",
      },
      {
        name: "キャンディー (紫)",
        payout5: "x2",
        payout4: "x1.2",
        payout3: "x0.5",
      },
      {
        name: "A",
        payout5: "x1.5",
        payout4: "x1",
        payout3: "x0.4",
      },
      {
        name: "K",
        payout5: "x1.2",
        payout4: "x0.9",
        payout3: "x0.3",
      },
      {
        name: "Q",
        payout5: "x1",
        payout4: "x0.8",
        payout3: "x0.2",
      },
      {
        name: "J",
        payout5: "x0.9",
        payout4: "x0.7",
        payout3: "x0.1",
      },
      {
        name: "10",
        payout5: "x0.8",
        payout4: "x0.6",
        payout3: "x0.1",
      },
      {
        name: "ワイルドシンボル",
        description: "キャンディーボックス。スキャッターを除く全てのシンボルの代わりとなります。リール2, 3, 4, 5に出現し、最大3倍のマルチプライヤーが付与されます。",
        isSpecial: true,
      },
      {
        name: "スキャッターシンボル",
        description: "プレゼントの箱。3つ以上でフリースピンが発動します。",
        isSpecial: true,
      },
    ],
    maxPayout: "x12,960",
    notes: [
      "上記はベット額$1あたりの配当です。",
      "ワイルドシンボルはリール2, 3, 4, 5に出現し、最大3倍のマルチプライヤーが付与されます。",
      "スキャッターシンボルは3つ以上でフリースピンが発動します。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "マルチプライヤー付きワイルド",
        description: "ワイルドシンボルは、スキャッターシンボルを除く全てのシンボルの代わりとなり、配当成立をサポートします。ベースゲーム中に現れるワイルドには、最大3倍のマルチプライヤーが付与されることがございます。複数のワイルドが絡むと、それらのマルチプライヤーは合算されて効果を発揮いたします。",
        icon: "/icons/wild.svg",
      },
      {
        name: "チャンス×2機能",
        description: "ベット額を約50%増加させることで、フリースピン（ボーナスゲーム）への突入確率を2倍に高めます。この機能が有効な間は、ボーナス購入機能のご利用はいただけません。",
        icon: "/icons/feature.svg",
      },
      {
        name: "フリースピン",
        description: "スキャッターシンボル（プレゼントの箱）を3つ以上揃えることで、フリースピンが発動いたします。フリースピン中は、ベースゲームとは異なり、ワイルドシンボルが特定のリール（2, 3, 4, 5）に固定（リスピン）されます。さらに、これらの固定ワイルドにはマルチプライヤーが付与されており、連続して出現することで配当が大きく増加する可能性がございます。フリースピン中にスキャッターを追加で揃えても、追加のフリースピンは付与されません。",
        icon: "/icons/free-spins.svg",
      },
      {
        name: "ボーナス購入機能",
        description: "ベット額の100倍で直接フリースピンラウンドを購入することが可能です。これは、すぐにボーナスゲームを楽しみたいプレイヤーにとって、大変便利な機能と言えるでしょう。ただし、「チャンス×2」機能が有効な場合は、この機能はご利用いただけません。",
        icon: "/icons/bonus-buy.svg",
      },
    ],
  },
  sections: [
    {
      heading: "ベースゲーム",
      paragraphs: [
        "Sweet Rush Megawaysのベースゲームでは、可愛らしいシンボルがリールを彩ります。ワイルドシンボルは配当成立を助けるだけでなく、最大3倍のマルチプライヤーを付与する可能性があり、勝利への期待を高めます。また、「チャンス×2」機能を利用することで、より頻繁にフリースピンへの道が開かれます。",
      ],
    },
    {
      heading: "グラフィック・サウンド",
      paragraphs: [
        "「Sweet Rush Megaways」は、その名の通り、キャンディーやチョコレートで彩られた、甘くカラフルな世界観が魅力です。BGAMING社ならではの、鮮やかでポップなデザインは、プレイヤーを楽しい気分にさせてくれます。お菓子のモンスターたちのデザインも愛らしく、ゲームのテーマ性を一層高めています。",
        "バックグラウンドミュージックは、ファンタジーの世界を思わせるような、軽快でキャッチーなメロディーが流れます。スピン時や勝利時の効果音も、ゲームの興奮を高めるように巧みに作られています。",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "「Sweet Rush Megaways」は、HTML5技術を基盤に開発されておりますので、PCはもちろん、スマートフォンやタブレットといったモバイルデバイスでも快適にお楽しみいただけます。特別なアプリのダウンロードは不要で、お使いのブラウザから直接アクセスしてプレイを開始できます。レスポンシブデザインにより、画面サイズに合わせてレイアウトが自動調整されるため、どのデバイスからでもストレスなくゲームを操作いただけます。",
      ],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "「Sweet Rush Megaways」はハイボラティリティのスロットであるため、以下の点を意識してプレイされることをお勧めします。",
        "チャンス×2機能の活用: フリースピン突入のチャンスを倍増させる「チャンス×2」機能は、積極的に利用を検討しましょう。ただし、ベット額が上昇するため、資金管理には十分な注意が必要です。",
        "ボーナス購入機能の検討: 短時間でフリースピンの興奮を味わいたい場合には、ボーナス購入機能が有効です。ただし、100倍のベット額が必要となるため、資金に余裕がある場合や、ここぞという局面での利用が賢明です。",
        "徹底した資金管理: ハイボラティリティのスロットにおいては、勝利が続くこともあれば、負けが続くこともございます。事前にプレイ時間を設定したり、1回のベット額を調整したりするなど、常に冷静な資金管理を心がけましょう。",
        "高配当シンボルを狙う: 基本的に、お菓子のモンスターやキャンディーといった高配当シンボルが揃うことで、大きな勝利へと繋がります。ワイルドのマルチプライヤーをうまく活用し、これらのシンボルでの配当獲得を目指しましょう。",
        "UKプレイヤーへのご注意: 一部の地域（例：イギリス）では、規制によりボーナス購入機能が利用できない場合があります。プレイされるオンラインカジノの利用規約を事前にご確認ください。",
      ],
    },
  ],
  similarGames: [
    {
      name: "シュガーラッシュ",
      href: "https://casinotsu.com/slots/sugar-rush",
      provider: "Pragmatic Play",
      description: "Pragmatic Playの人気スロットであり、受賞歴もあるハイボラ機です。",
    },
    {
      name: "スィートボナンザ",
      href: "https://casinotsu.com/slots/sweet-bonanza",
      provider: "Pragmatic Play",
      description: "こちらもPragmatic Playの人気スロットで、ゲームショー化もされている作品です。",
    },
    ],
  prosCons: {
    pros: [
      "メガウェイズエンジン搭載で最大117,649通りのペイライン",
      "最大12,960倍の驚異的な配当ポテンシャル",
      "チャンス×2機能でフリースピン突入率アップ",
      "フリースピン中は固定ワイルドとマルチプライヤーで高配当を狙える",
      "ボーナス購入機能で即フリースピンへ",
      "ポップで魅力的なグラフィックとサウンド",
      "モバイルデバイスでの快適なプレイ体験",
    ],
    cons: [
      "ハイボラティリティのため、勝利頻度は低い傾向",
      "チャンス×2機能有効時はベット額が上昇",
      "フリースピン中にスキャッターを追加してもフリースピンは増えない",
      "一部地域ではボーナス購入機能が利用できない場合がある",
    ],
  },
  faq: [
    {
      q: "チャンス×2機能を使った場合のベット額はどれくらい上がりますか？",
      a: "チャンス×2機能は、通常のベット額に加えて、そのベット額の約50%に相当する追加ベットが発生します。そのため、例えば$1のベット額の場合、チャンス×2を有効にすると合計$1.5のベット額となります。",
    },
    {
      q: "フリースピンの購入額はいくらですか？",
      a: "フリースピンの購入額は、現在のベット額の100倍です。例えば、ベット額が$1の場合、フリースピンの購入には$100が必要となります。",
    },
    {
      q: "このスロットはモバイルでプレイできますか？",
      a: "はい、HTML5技術で開発されているため、スマートフォンやタブレットなどのモバイルデバイスで快適にプレイできます。",
    },
    {
      q: "最大配当はいくらですか？",
      a: "最大配当はベット額の12,960倍です。",
    },
    {
      q: "フリースピン中に再スピンはありますか？",
      a: "いいえ、フリースピン中にスキャッターシンボルを追加で揃えても、追加のフリースピンは付与されません。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "Sweet Rush Megaways", href: "/slots/sweet-rush-megaways" },
  ],
  tableOfContents: [
    { label: "導入・概要", href: "#introduction" },
    { label: "ゲーム基本情報", href: "#game-info" },
    { label: "どこで遊べるか", href: "#where-to-play" },
    { label: "ゲーム特徴・フィーチャー", href: "#features" },
    { label: "プロバイダー情報", href: "#provider-info" },
    { label: "グラフィック・サウンド", href: "#graphics-sound" },
    { label: "ペイアウト・配当表", href: "#payout-table" },
    { label: "モバイル対応", href: "#mobile" },
    { label: "戦略・攻略法", href: "#strategy" },
    { label: "類似ゲーム", href: "#similar-games" },
    { label: "まとめ", href: "#summary" },
    { label: "よくある質問", href: "#faq" },
  ],
  cta: {
    text: "今すぐSweet Rush Megawaysをプレイ！",
    href: "/go/sweet-rush-megaways",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/sweet-rush-megaways" />;
}
