import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Sweet Bonanza／スウィート・ボナンザ｜オンラインスロット攻略",
  hero: {
    title: "Sweet Bonanza／スウィート・ボナンザ",
    subheading: "Pragmatic Play",
    description: "キャンディーとフルーツがテーマの落ち物（クラスターペイ）型ビデオスロット。最大21,175倍の配当倍率と強力なマルチプライヤー機能で爆発的な勝利の可能性を秘めています。",
    score: 4.3,
    scoreMax: 5,
    rtp: "96.49%",
    maxMultiplier: "x21,175",
    provider: "Pragmatic Play",
    releaseDate: "2019年6月25日",
    volatility: "中～高",
    reels: "6",
    paylines: "クラスターペイ",
    minBet: "$0.20",
    maxBet: "$100",
    slotImageSrc: "/slots/sweet-bonanza.png",
    highlights: [
      "クラスターペイシステム",
      "強力なマルチプライヤー機能",
      "フリースピン購入機能",
      "アンテベット機能"
    ],
    watchouts: [
      "ボラティリティが高めなので、資金管理に注意が必要です。"
    ]
  },
  featuredCasino: {
    name: "Golden Panda",
    logo: "/assets/casino/golden-panda.png",
    ctaText: "今すぐプレイ！",
    tagline: "出金は基本的に即時反映でストレスフリー♪"
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.png",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30x",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.png",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "2up",
      logo: "/assets/casino/2up.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.png",
      bonus: "$500",
      freeSpins: "50",
      wagering: "35x",
      rating: 3.5,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.png",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30x",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "WSM Casino",
      logo: "/assets/casino/wsm-casino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.png",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29x",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.png",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20x",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casino/katsuwin.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.png",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Betpanda",
      logo: "/assets/casino/betpanda.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.png",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.png",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40x",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.png",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: "-",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.png",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.png",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35x",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Ramenbet",
      logo: "/assets/casino/ramenbet.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Flush Casino",
      logo: "/assets/casino/flush-casino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/queen-casino.png",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30x",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.png",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Casino Sky",
      logo: "/assets/casino/casino-sky.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.png",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35x",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.png",
      bonus: "キャッシュバック 最大$10,000",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "BC.Game",
      logo: "/images/casino/bc-game.png",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45x",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Empire.io",
      logo: "/assets/casino/empireio.png",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "賭け条件ナシのキャシュバック＆VIP特典がスゴイ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casino/wonder-casino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.png",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35x",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Tedbet",
      logo: "/assets/casino/tedbet.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "BetRebels",
      logo: "/assets/casino/betrebels.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Conquestador",
      logo: "/assets/casino/conquestador.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Lilibet",
      logo: "/assets/casino/lilibet.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Livecasino.io",
      logo: "/images/casino/livecasinoio.png",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.png",
      bonus: "$917",
      freeSpins: "-",
      wagering: "30x",
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.png",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Energy Casino",
      logo: "/assets/casino/energy-casino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Konibet",
      logo: "/assets/casino/konibet.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Vulkan Vegas",
      logo: "/assets/casino/vulkan-vegas.png",
      bonus: "¥100,000",
      freeSpins: "125",
      wagering: "40x",
      rating: 4,
      tagline: "アメコミの世界観に入り込んじゃえ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.png",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20x",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.png",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: "10x",
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Bons.com",
      logo: "/images/casino/bons.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "マインクラフトチックでも中身はモダン",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Trustdice",
      logo: "/assets/casino/trustdice.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "InterCasino",
      logo: "/images/casino/inter-casino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.png",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.png",
      bonus: "$0",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Justspin",
      logo: "/images/casino/just-spin.png",
      bonus: "$500",
      freeSpins: "600",
      wagering: "50x",
      rating: 4,
      tagline: "シンプルなデザインで見やすいプラットフォーム",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.png",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30x",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "21.com",
      logo: "/assets/jp/21-com.png",
      bonus: "$1,000",
      freeSpins: "1000",
      wagering: "50x",
      rating: 4,
      tagline: "構造もシンプルで検索機能も使いやすい",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "BitStarz",
      logo: "/assets/casino/bitstarz.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casino/casino-secret.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Vera&John",
      logo: "/assets/casino/vera-john.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.png",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20x",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/jp/bitcasino-io.png",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40x",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.png",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20x",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "William Hill",
      logo: "/assets/casino/william-hill.png",
      bonus: "$300",
      freeSpins: "-",
      wagering: "25x",
      rating: 3.5,
      tagline: "世界三大の超老舗ブックメーカー！",
      ctaText: "今すぐプレイ！",
    },
    {
      name: "Eldoah Casino",
      logo: "/images/casino/eldoah.png",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
    }
  ],
  gameInfo: {
    intro: "Pragmatic Play社が開発したスウィート・ボナンザは、その魅力的なゲーム性から多くのカジノで人気を集めています。CasinoTsu では、正確な情報をお伝えするため、このスロットの基本的な情報を詳細にまとめました。",
    basicInfo: {
      rtp: "96.48% (通常時) / 96.51% (アンテベット有効時)",
      volatility: "中～高（High）",
      reels: "6リール",
      paylines: "クラスターペイ（キャッシュ・アラウンド）方式。画面上のどこかに同じシンボルが8個以上出現すると配当成立。",
      minBet: "$0.20 / €0.20",
      maxBet: "$100 / €125",
      provider: "Pragmatic Play",
      releaseDate: "2019年6月25日"
    }
  },
  payoutTable: {
    title: "スウィート・ボナンザのシンボルとペイアウト",
    symbols: [
      {
        name: "赤いハートのキャンディー",
        description: "高配当シンボル",
        payout5: "12個以上でベット額の40倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "紫の四角キャンディー",
        description: "高配当シンボル",
        payout5: "12個以上でベット額の25倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "緑の六角形キャンディー",
        description: "高配当シンボル",
        payout5: "12個以上でベット額の20倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "青い丸キャンディー",
        description: "高配当シンボル",
        payout5: "12個以上でベット額の15倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "リンゴ",
        description: "低配当シンボル",
        payout5: "12個以上でベット額の10倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "プラム",
        description: "低配当シンボル",
        payout5: "12個以上でベット額の8倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "スイカ",
        description: "低配当シンボル",
        payout5: "12個以上でベット額の5倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "バナナ",
        description: "低配当シンボル",
        payout5: "12個以上でベット額の2倍",
        payout4: "-",
        payout3: "-",
        isSpecial: false
      },
      {
        name: "ペロペロキャンディー",
        description: "スキャッターシンボル",
        payout5: "4つ以上で10回のフリースピン獲得",
        payout4: "-",
        payout3: "-",
        isSpecial: true
      },
      {
        name: "マルチプライヤーシンボル（チョコボール風）",
        description: "フリースピンラウンド中のみ出現。2倍〜100倍（または1000倍）の倍率を適用。",
        payout5: "-",
        payout4: "-",
        payout3: "-",
        isSpecial: true
      }
    ],
    maxPayout: "ベット額の21,175倍",
    notes: [
      "ワイルドシンボルとジャックポットシンボルはありません。",
      "クラスターペイシステムのため、ペイラインはありません。"
    ]
  },
  features: {
    title: "スウィート・ボナンザのゲームフィーチャー",
    items: [
      {
        name: "フリースピン",
        description: "スキャッターシンボル（ペロペロキャンディー）が4つ以上出現すると10回のフリースピンを獲得。フリースピン中にスキャッターが3つ以上出現すると追加スピン獲得可能。",
        icon: "/images/icon/free-spins.png"
      },
      {
        name: "マルチプライヤー",
        description: "フリースピンラウンド中にマルチプライヤーシンボル（ボム）が出現し、勝利時に倍率が適用される。倍率は2倍から最大100倍（または1000倍）。",
        icon: "/images/icon/multiplier.png"
      },
      {
        name: "機能倍増チャンス（アンテベット機能）",
        description: "ベット額が25%増加する代わりに、フリースピンの出現確率が2倍になる。RTPもわずかに上昇。",
        icon: "/images/icon/ante-bet.png"
      },
      {
        name: "フリースピン購入機能",
        description: "ベット額の100倍を支払うことで、直接フリースピンラウンドに突入できる。",
        icon: "/images/icon/bonus-buy.png"
      },
      {
        name: "タンブル（落下）機能",
        description: "配当成立後、勝利シンボルが消滅し、新しいシンボルが落下してくる。連続して配当が発生する可能性がある。",
        icon: "/images/icon/tumble.png"
      },
      {
        name: "クラスターペイ",
        description: "ペイラインがなく、画面上のどこかに同じシンボルが8個以上出現すると配当成立。",
        icon: "/images/icon/cluster-pay.png"
      }
    ]
  },
  sections: [
    {
      heading: "スウィート・ボナンザのバリアント：スウィート・ボナンザ1000",
      paragraphs: [
        "2024年には、スウィート・ボナンザの続編とも言える「スウィート・ボナンザ1000」が登場しました。こちらは、オリジナルのゲーム性を踏襲しつつ、いくつかの点が強化されています。",
        "最大配当倍率: オリジナルの21,175倍から 25,000倍へとアップグレード。",
        "マルチプライヤー: マルチプライヤーシンボルの最大倍率が 1,000倍 まで引き上げられました。",
        "ボラティリティ: より高いボラティリティを持つように調整されており、より大きなリスクとリターンの可能性を秘めています。",
        "オリジナルのスウィート・ボナンザを楽しんだプレイヤーや、さらに高い爆発力を求めるプレイヤーには、「スウィート・ボナンザ1000」もおすすめです。"
      ]
    },
    {
      heading: "スウィート・ボナンザのグラフィックとサウンド",
      paragraphs: [
        "グラフィック: スウィート・ボナンザは、その名の通り「甘い」世界観を表現した、鮮やかでポップなグラフィックが特徴です。キラキラとしたキャンディーやみずみずしいフルーツのシンボルは、見ているだけで楽しくなります。背景には、お菓子でできたお城や丘が描かれており、ファンタジックな雰囲気を醸し出しています。アニメーションも滑らかで、勝利時のエフェクトはプレイヤーをさらに盛り上げます。",
        "サウンド: ゲームのサウンドトラックは、明るく軽快なポップチューンで、ゲームのテーマと見事に調和しています。スピンボタンを押した時の効果音や、シンボルが揃った時のサウンドも軽快で、プレイ中の楽しさを増幅させます。フリースピンラウンドでは、BGMが少し変化し、より興奮を高めるようなアレンジが加えられることもあります。全体として、ポジティブでハッピーな気分にさせてくれるサウンドデザインと言えるでしょう。"
      ]
    },
    {
      heading: "スウィート・ボナンザのモバイル対応",
      paragraphs: [
        "スウィート・ボナンザは、Pragmatic Play社が開発したスロットであるため、最新のHTML5技術を採用しており、モバイルデバイスでのプレイに最適化されています。CasinoTsu は、いつでもどこでも快適にプレイできる環境を提供することが重要だと考えております。",
        "スマートフォン・タブレット対応: iOS、Androidなどの主要なモバイルOSに対応しており、スマートフォンやタブレットから直接ブラウザ経由でプレイできます。アプリのダウンロードは不要です。",
        "優れたユーザーエクスペリエンス: モバイル画面でも、PC版と同様にリール、ベットボタン、各種設定へのアクセスが直感的で分かりやすく設計されています。グラフィックやサウンドもモバイル環境で最適に表示・再生されるため、場所を選ばずに快適なゲームプレイを楽しむことができます。"
      ]
    },
    {
      heading: "スウィート・ボナンザの戦略と攻略法",
      paragraphs: [
        "スウィート・ボナンザは運の要素が大きいスロットですが、CasinoTsu では、いくつかの戦略やヒントを意識することで、より長く、そして有利にプレイを進めることを推奨しています。正確さが第一。興奮はその次。",
        "ボラティリティの理解とバンクロール管理: スウィート・ボナンザは「中～高」のボラティリティを持つスロットです。これは、配当の頻度はそれほど高くないものの、一度当たると大きな配当が得られる可能性があることを意味します。そのため、十分な資金（バンクロール）を確保する、ベット額を慎重に設定する、損切りラインを決める、といった点に注意しましょう。",
        "アンテベット機能の活用: 「機能倍増チャンス」をオンにすることで、フリースピンの出現確率が上がり、RTPもわずかに上昇します。ベット額が25%増加しますが、フリースピンを狙いたい場合には有効な選択肢となります。",
        "フリースピン購入機能の利用: フリースピンがなかなか自力で引けない場合、フリースピン購入機能は有効な手段です。ベット額の100倍というコストはかかりますが、すぐにボーナスラウンドを体験できるため、時間短縮や、ボーナスラウンドでの高配当を狙いたい場合に活用できます。",
        "フィーチャー出現頻度への期待値: スウィート・ボナンザのフリースピンは、強力なマルチプライヤーシンボルが出現するため非常に魅力的ですが、自力での出現確率はそれほど高くありません。そのため、フリースピン購入機能やアンテベット機能がない場合は、気長にプレイを続ける覚悟が必要です。",
        "デモプレイの活用: リアルマネーでプレイする前に、無料のデモバージョンでゲームの感触を掴むことを強くお勧めします。これにより、ゲームのルール、フィーチャーの仕組み、そしてご自身のプレイスタイルに合っているかを確認できます。"
      ]
    },
    {
      heading: "スウィート・ボナンザ勝手に採点してみた！",
      bullets: [
        "グラフィック: ★★★★☆- みずみずしいキャンディーの表現は見ているだけで笑顔になる。",
        "サウンド: ★★★★☆- ハッピーな気分にさせてくれるポップなサウンド。",
        "面白さ: ★★★★☆- ユニークな機能で落ちゲーとしては、なかなかのエキサイティング感。",
        "RTPとボラティリティ: ★★★★★- RTPは平均96.48%％、ボラティリティは程々に高い。",
        "総合評価: ★★★★☆- 5段階評価の4.3"
      ]
    },
    {
      heading: "ボナンザシリーズのスロットをチェック",
      paragraphs: [
        "スウィート・ボナンザ以外にも、Pragmatic Play社や他のプロバイダーからは、「ボナンザ」の名を冠する、または類似したゲーム性のスロットが多数リリースされています。CasinoTsu では、これらの人気スロットもご紹介しております。",
        "ボナンザ (Bonanza)： Big Time Gaming社が開発した、メガウェイズ™️（Megaways™️）システムを搭載した元祖とも言える人気スロット。",
        "ビッグ・バス・ボナンザ（Big Bass Bonanza）： Reel Kingdom社（Pragmatic Play傘下）の人気シリーズで、釣りテーマのスロット。",
        "ハロウィン・ボナンザ（Halloween Bonanza）： BGaming社からリリースされた、季節感あふれるスロット。",
        "これらのスロットも、スウィート・ボナンザと同様に高い人気を誇っています。"
      ]
    }
  ],
  similarGames: [
    {
      name: "Bonanza",
      href: "/slots/bonanza",
      provider: "Big Time Gaming",
      description: "メガウェイズ™️システム搭載の元祖人気スロット。"
    },
    {
      name: "Big Bass Bonanza",
      href: "/slots/big-bass-bonanza",
      provider: "Reel Kingdom",
      description: "釣りテーマの人気シリーズ。"
    },
    {
      name: "Halloween Bonanza",
      href: "/slots/halloween-bonanza",
      provider: "BGaming",
      description: "季節感あふれるスロット。"
    }
  ],
  prosCons: {
    pros: [
      "最大21,175倍という高い配当倍率",
      "クラスターペイシステムとタンブル機能による連続勝利の可能性",
      "強力なマルチプライヤー機能（ボム）",
      "フリースピン購入機能とアンテベット機能による戦略の幅",
      "ポップでカラフルな魅力的なグラフィックとサウンド"
    ],
    cons: [
      "ボラティリティが高いため、資金管理に注意が必要",
      "フリースピンの自力出現確率が低い場合がある"
    ]
  },
  faq: [
    {
      q: "スウィート・ボナンザのマルチプライヤーシンボルはベースゲームでも獲得できますか？",
      a: "マルチプライヤーシンボル（ボム）は、フリースピンラウンド中のみに出現する特別なフィーチャーです。ベースゲーム中には出現しません。"
    },
    {
      q: "フリースピン中にスキャッターを獲得したら、追加スピンはもらえますか？",
      a: "はい、フリースピン中にスキャッターシンボル（ペロペロキャンディー）が3つ以上出現すると、追加で5回のフリースピンを獲得できます。これは、ゲームをより長く楽しむための重要な要素です。"
    }
  ],
  cta: {
    text: "今すぐプレイ！",
  },
  breadcrumbs: [
    { label: "ホーム", href: "https://casinotsu.com/" },
    { label: "スロット", href: "https://casinotsu.com/slots" },
    { label: "Sweet Bonanza", href: "https://casinotsu.com/slots/sweet-bonanza" }
  ],
  tableOfContents: [
    { label: "スウィート・ボナンザ：概要", href: "#スウィート・ボナンザ概要" },
    { label: "スウィート・ボナンザをプレイできるカジノ", href: "#スウィート・ボナンザをプレイできるカジノ" },
    { label: "スウィート・ボナンザの基本情報", href: "#スウィート・ボナンザの基本情報" },
    { label: "スウィート・ボナンザのシンボルとペイアウト", href: "#スウィート・ボナンザのシンボルとペイアウト" },
    { label: "スウィート・ボナンザのゲームフィーチャー", href: "#スウィート・ボナンザのゲームフィーチャー" },
    { label: "スウィート・ボナンザのバリアント：スウィート・ボナンザ1000", href: "#スウィート・ボナンザのバリアントスウィート・ボナンザ1000" },
    { label: "スウィート・ボナンザを遊ぶならこのカジノ！", href: "#スウィート・ボナンザを遊ぶならこのカジノ" },
    { label: "スウィート・ボナンザのグラフィックとサウンド", href: "#スウィート・ボナンザのグラフィックとサウンド" },
    { label: "スウィート・ボナンザのモバイル対応", href: "#スウィート・ボナンザのモバイル対応" },
    { label: "スウィート・ボナンザの戦略と攻略法", href: "#スウィート・ボナンザの戦略と攻略法" },
    { label: "スウィート・ボナンザ勝手に採点してみた！", href: "#スウィート・ボナンザ勝手に採点してみた" },
    { label: "ボナンザシリーズのスロットをチェック", href: "#ボナンザシリーズのスロットをチェック" },
    { label: "よくある質問", href: "#よくある質問" }
  ]
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/sweet-bonanza" />;
}
