import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Rage to Riches (レイジ・トゥ・リッチーズ) スロットレビュー | CasinoTsu",
  hero: {
    title: "Rage to Riches",
    subheading: "巨大怪獣が街を襲う！アメコミ風パニック・スロット",
    description: "Play’n GO社が贈る、迫力満点のビジュアルとスリリングなゲーム体験が魅力のスロット。",
    score: 3.2,
    scoreMax: 5,
    rtp: "97.12%",
    maxMultiplier: "10,000x",
    provider: "Play’n GO",
    releaseDate: "2014年7月",
    volatility: "低",
    reels: "5",
    paylines: "20",
    minBet: "$0.20",
    maxBet: "$100",
    slotImageSrc: "/slots/rage-to-riches.png",
    highlights: [
      "巨大怪獣が街を襲うユニークなテーマ",
      "カスケードリールとマルチプライヤー機能",
      "再フリースピン可能なフリースピン",
      "ビル破壊で賞金を獲得するボーナスゲーム",
      "高いRTP (97.12%) と低ボラティリティ",
    ],
    watchouts: [
      "グラフィックはやや古めかしいと感じる可能性あり",
      "低ボラティリティのため、一撃の最大配当は限定的",
    ],
  },
  featuredCasino: {
    name: "2up",
    logo: "/assets/casino/2up.png",
    href: "/reviews/2up",
    ctaText: "今すぐプレイ！",
    ctaHref: "/go/2up:2up?referrer_path=%2Fslots%2Frage-to-riches",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.png",
      href: "/reviews/golden-panda",
      bonus: "30x 賭け条件",
      freeSpins: "30x 賭け条件",
      wagering: "",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "2up",
      logo: "/assets/casino/2up.png",
      href: "/reviews/2up",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/2up:2up?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.png",
      href: "/reviews/miki",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/miki:miki?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "WSM Casino",
      logo: "/assets/casino/wsm-casino.png",
      href: "/reviews/wsm-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.png",
      href: "/reviews/bitz",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/bitz:bitz?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.png",
      href: "/reviews/wikibet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/wikibet:wikibet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casino/katsuwin.png",
      href: "/reviews/katsuwin",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.png",
      href: "/reviews/sushi-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.png",
      href: "/reviews/parimatch",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/parimatch:parimatch?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "/reviews/duelbits",
      bonus: "500フリースピン",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/duelbits:duelbits?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Sportsbet.io",
      logo: "/images/casino/sportsbet-io.png",
      href: "/reviews/sportsbet-io",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.png",
      href: "/reviews/shuffle",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/shuffle:shuffle?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Winz",
      logo: "/images/casino/winz-io.png",
      href: "/reviews/winz-io",
      bonus: "賭け条件なし",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/winz-io:winz-io?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.png",
      href: "/reviews/dafabet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/dafabet:dafabet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.png",
      href: "/reviews/lucky-block",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Ramenbet",
      logo: "/assets/casino/ramenbet.png",
      href: "/reviews/ramenbet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/flush.png",
      href: "/reviews/flush",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/flush-casino:flush?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/queen-casino.png",
      href: "/reviews/queen-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.png",
      href: "/reviews/roobet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/roobet:roobet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Casino Sky",
      logo: "/assets/casino/casino-sky.png",
      href: "/reviews/casino-sky",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.png",
      href: "/reviews/mega-dice",
      bonus: "最大1BTC",
      freeSpins: "",
      wagering: "",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.png",
      href: "/reviews/cosmoswin",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/cosmoswin:cosmoswin?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "BC.Game",
      logo: "/images/casino/bc-game.png",
      href: "/reviews/bc-game",
      bonus: "最大1,600ドルの初回入金ボーナス",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/bc-game:bc-game?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      href: "/reviews/stake",
      bonus: "ハウスエッジ5%レーキバック＆VIP特典",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/stake:stake?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casino/wonder-casino.png",
      href: "/reviews/wonder-casino",
      bonus: "賭け条件なし",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.png",
      href: "/reviews/ohmyspins",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/ohmyspins:ohmyspins?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      href: "/reviews/yuugado",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/yuugado:yuugado?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Tedbet",
      logo: "/assets/casino/tedbet.png",
      href: "/reviews/tedbet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/tedbet:tedbet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "BetRebels",
      logo: "/assets/casino/betrebels.png",
      href: "/reviews/betrebels",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/betrebels:betrebels?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Conquestador",
      logo: "/assets/casino/conquestador.png",
      href: "/reviews/conquestador",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/conquestador:conquestador?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.png",
      href: "/reviews/cloudbet",
      bonus: "入出金額上限なし",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/cloudbet:cloudbet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Lilibet",
      logo: "/assets/casino/lilibet.png",
      href: "/reviews/lilibet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/lilibet:lilibet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Livecasino.io",
      logo: "/assets/jp/livecasino-io.png",
      href: "/reviews/livecasino-io",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ライブカジノ×仮想通貨。そんなモダンな世界はいかが？",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/livecasino-io:livecasino-io?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Lucky Bull",
      logo: "/assets/casino/lucky-bull.png",
      href: "/reviews/lucky-bull",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "キャラと一緒にラッキーブルの世界でクエスト攻略！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/lucky-bull:lucky-bull?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Gamdom",
      logo: "/assets/casino/gamdom.png",
      href: "/reviews/gamdom",
      bonus: "最強レーキバック",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ハイローラープレイヤーにもってこいの最強レーキバックカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/gamdom:gamdom?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Energy Casino",
      logo: "/assets/casino/energy-casino.png",
      href: "/reviews/energy-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ウェブサイトの見やすさと操作性は抜群なカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/energy-casino:energy-casino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Konibet",
      logo: "/assets/casino/konibet.png",
      href: "/reviews/konibet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/konibet:konibet?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Vulkan Vegas",
      logo: "/assets/casino/vulkan-vegas.png",
      href: "/reviews/vulkanvegas",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "アメコミの世界観に入り込んじゃえ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/vulkan-vegas:vulkanvegas?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.png",
      href: "/reviews/casino-me",
      bonus: "独自システムのお得なキャッシュバック",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/casino-me:casino-me?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      href: "/reviews/mystino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/mystino:mystino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Trustdice",
      logo: "/assets/casino/trustdice.png",
      href: "/reviews/trustdice",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/trustdice:trustdice?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "InterCasino",
      logo: "/images/casino/inter-casino.png",
      href: "/reviews/inter-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/inter-casino-japan:inter-casino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.png",
      href: "/reviews/empire777",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/empire777:empire777?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.png",
      href: "/reviews/pinnacle",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Justspin",
      logo: "/images/casino/just-spin.png",
      href: "/reviews/just-spin",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "シンプルなデザインで見やすいプラットフォーム",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/justspin:just-spin?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.png",
      href: "/reviews/winunique",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/winunique:winunique?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "21.com",
      logo: "/assets/jp/21-com.png",
      href: "/reviews/21-com",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "構造もシンプルで検索機能も使いやすい",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/21-com:21-com?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "BitStarz",
      logo: "/assets/casino/bitstarz.png",
      href: "/reviews/bitstarz",
      bonus: "複数通貨のマルチウォレット対応",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "複数通貨のマルチウォレット対応カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/bitstarz:bitstarz?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino.png",
      href: "/reviews/joycasino",
      bonus: "てんこ盛りボーナス",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/joy-casino:joycasino?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Casino Secret",
      logo: "/assets/casino/casino-secret.png",
      href: "/reviews/casino-secret",
      bonus: "キャッシュバック",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "キャッシュバックと言えばこのカジノで間違いなし",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/casino-secret:casino-secret?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Vera&John",
      logo: "/assets/casino/vera-john.png",
      href: "/reviews/vera-john",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/vera-john:vera-john?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.png",
      href: "/reviews/live-casino-house",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/jp/bitcasino-io.png",
      href: "/reviews/bitcasino-io",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      href: "/reviews/casino-x",
      bonus: "太っ腹ボーナス盛りだくさん",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/casino-x:casino-x?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.png",
      href: "/reviews/casitabi",
      bonus: "RPG型カジノ",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/casitabi:casitabi?referrer_path=%2Fslots%2Frage-to-riches",
    },
    {
      name: "Eldoah Casino",
      logo: "/images/casino/eldoah.png",
      href: "/reviews/eldoah",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Frage-to-riches",
    },
  ],
  gameInfo: {
    intro: "「Rage to Riches」は、Play’n GO社が「カミカゼアタック」やアーケードゲーム「Rampage」からインスピレーションを受けて開発したスロットです。映画「キングコング」や「ゴジラ」のように、巨大な怪獣が都市を破壊するスリリングなテーマが特徴で、プレイヤーは高層ビルが崩壊する街並みを背景に、興奮に満ちたゲーム体験を味わえます。",
    basicInfo: {
      rtp: "97.12%",
      volatility: "低（Low）",
      reels: "5",
      paylines: "20",
      minBet: "$0.20",
      maxBet: "$100",
      provider: "Play’n GO",
      releaseDate: "2014年7月",
    },
  },
  payoutTable: {
    title: "Rage to Richesの配当表",
    symbols: [
      {
        name: "巨大ゴリラ（キングコング風）",
        payout5: "1,000x",
        payout4: "200x",
        payout3: "50x",
      },
      {
        name: "爬虫類系怪獣（ゴジラ風）",
        payout5: "500x",
        payout4: "150x",
        payout3: "40x",
      },
      {
        name: "狼男風怪獣",
        payout5: "300x",
        payout4: "100x",
        payout3: "30x",
      },
      {
        name: "A",
        payout5: "150x",
        payout4: "50x",
        payout3: "20x",
      },
      {
        name: "K",
        payout5: "120x",
        payout4: "40x",
        payout3: "15x",
      },
      {
        name: "Q",
        payout5: "100x",
        payout4: "30x",
        payout3: "10x",
      },
      {
        name: "J",
        payout5: "80x",
        payout4: "25x",
        payout3: "8x",
      },
      {
        name: "10",
        payout5: "50x",
        payout4: "20x",
        payout3: "5x",
      },
    ],
    maxPayout: "10,000x",
    notes: ["※上記はベット額1ドルあたりの配当です。"],
  },
  features: {
    title: "Rage to Richesのゲーム特徴・フィーチャー",
    items: [
      {
        name: "ワイルドシンボル",
        description: "「Rage to Riches」のロゴがワイルドシンボルとして登場。スキャッターシンボルとボーナススターシンボルを除く全てのシンボルと代用可能で、配当成立のチャンスを広げます。",
        icon: "/images/Rage-to-Riches-wild.jpg",
      },
      {
        name: "マルチプライヤー機能",
        description: "ペイアウトが発生するとシンボルが消滅し、新しいシンボルが落ちてくるカスケードリールシステム。連続ペイアウトごとにマルチプライヤーが上昇（最大x5）。フリースピン中はさらに上昇する可能性あり。",
        icon: "",
      },
      {
        name: "フリースピン",
        description: "女の子のシンボル（スキャッター）が3つ以上で10回のフリースピン獲得。フリースピン中はマルチプライヤーがより高くなり、最大50回まで再フリースピン可能。3スピンごとに保証ウィンあり。",
        icon: "/images/Rage-to-Riches-free-spins.jpg",
      },
      {
        name: "ボーナスゲーム",
        description: "リール上の「10」→「J」→「Q」→「K」→「A」シンボル出現で星が貯まり、5つ貯まると発動。怪獣を選び、破壊するビルを選択して賞金を獲得。最大ベット額の100倍の配当。",
        icon: "/images/Rage-to-Riches-bonus-stars.jpg",
      },
      {
        name: "オートプレイ機能",
        description: "連続してスピンを行うオートプレイ機能が搭載されており、効率的にゲームを進めることができます。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "Rage to Richesの基本情報",
      paragraphs: [
        "「Rage to Riches」は、Play’n GO社が「カミカゼアタック」やアーケードゲーム「Rampage」からインスピレーションを受けて開発したスロットです。映画「キングコング」や「ゴジラ」のように、巨大な怪獣が都市を破壊するスリリングなテーマが特徴で、プレイヤーは高層ビルが崩壊する街並みを背景に、興奮に満ちたゲーム体験を味わえます。",
      ],
      table: {
        title: "基本情報",
        columns: ["項目", "詳細"],
        rows: [
          ["リール", "5"],
          ["ペイライン", "20"],
          ["ベットレンジ", "$0.20 〜 $100"],
          ["コインバリュー", "$0.01 〜 $1.00"],
          ["コイン", "1〜5枚"],
          ["RTP", "97.12％"],
          ["ボラティリティ", "低（Low）"],
          ["リリース日", "2014年7月（または2013年10月、情報源により異なる）"],
          ["最大配当倍率", "10,000x"],
          ["最大ライン配当", "シンボル「巨大ゴリラ」：1,000x"],
        ],
      },
    },
    {
      heading: "【RTPとボラティリティについて】",
      paragraphs: [
        "**RTP (Return To Player)**: 97.12%という高い還元率は、プレイヤーにとって非常に有利な設定と言えます。これは、長期間プレイした場合に、ベットした金額の平均97.12%がプレイヤーに払い戻されることを意味します。正確さが第一。興奮はその次。",
        "**ボラティリティ**: 低ボラティリティは、比較的頻繁に小役が当たりやすく、資金が安定しやすい傾向があります。そのため、少額ベットで長く楽しみたいプレイヤーや、ボーナス消化に向いています。ただし、一撃の大きな配当が出にくいという側面もあります。",
      ],
    },
    {
      heading: "Rage to Richesのシンボル＆配当表",
      paragraphs: [
        "Rage to Richesのシンボルは、高額シンボルとして3種類の怪獣、低額シンボルとしてトランプカードの絵柄が採用されています。",
      ],
      bullets: [
        "**高額シンボル（怪獣）**: 巨大ゴリラ（キングコング風）、爬虫類系怪獣（ゴジラ風）、狼男風怪獣",
        "**低額シンボル（トランプカード）**: A、K、Q、J、10。これらのシンボルは、ボーナスゲームのトリガーにも関わってきます。",
        "**ペイライン**: ペイラインは全部で20通りあり、左から右へのシンボルの組み合わせで配当が発生します。",
      ],
    },
    {
      heading: "プロバイダー情報",
      paragraphs: [
        "「Rage to Riches」は、モバイルゲーム開発で有名な**Play’n GO（プレインゴー）** によって開発されました。Play’n GOは、革新的なゲーム性と魅力的なテーマで、世界中のプレイヤーから高い評価を得ています。",
      ],
      table: {
        title: "Play’n GO",
        columns: ["項目", "詳細"],
        rows: [
          ["開発会社", "Play’n GO"],
          ["ライセンス", "マルタ、イギリス、ジブラルタルなど多数"],
          ["リリース日", "2014年7月 (一部情報源では2013年10月)"],
          ["他の人気作品", "Book of Dead, Moon Princess, Fire Joker"],
        ],
      },
      bullets: [
        "Play’n GOは、HTML5技術を駆使した高品質なゲームを提供しており、PCだけでなくスマートフォンやタブレットでも快適にプレイできるのが特徴です。",
      ],
    },
    {
      heading: "グラフィック・サウンド",
      bullets: [
        "**デザイン品質**: 最初は少し古めかしいグラフィックに感じるかもしれませんが、これは演出の一環であり、コミック調のタッチが独特の世界観を醸し出しています。グロテスクすぎず、かといって可愛すぎもしない、絶妙なバランスのデザインです。",
        "**サウンド**: サウンドは比較的シンプルで、パニック映画にありがちな過剰なBGMや効果音は控えめです。これにより、ゲームプレイに集中しやすく、怪獣の咆哮やビルの崩壊音が効果的に響きます。",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "「Rage to Riches」は、Play’n GOの得意とするHTML5技術で開発されているため、PCはもちろん、スマートフォンやタブレットなどのモバイルデバイスにも完全対応しています。外出先でも、自宅と同じように快適なスロット体験を楽しむことができます。",
      ],
    },
    {
      heading: "戦略・攻略法",
      bullets: [
        "**低ボラティリティを活かす**: 比較的頻繁に勝利が発生しやすい反面、一撃で高額配当を獲得する可能性はやや低いことを意味します。少額ベットで長くプレイするのに向いています。",
        "**フィーチャー活用法**: カスケードリールによるマルチプライヤー上昇、フリースピン（高配当チャンス）、ボーナスゲーム（最大100倍）を狙いましょう。",
        "**初心者から経験者まで**: 高いRTPと安定しやすいゲーム性は初心者にも、多彩なフィーチャーは経験者にもおすすめです。",
      ],
    },
    {
      heading: "類似ゲーム",
      sections: [
        {
          heading: "同テーマのゲーム",
          bullets: [
            "King Kong Cash (Blueprint Gaming)",
            "Godzilla (Rival Gaming)",
          ],
        },
        {
          heading: "同プロバイダー（Play’n GO）のゲーム",
          bullets: [
            "Book of Dead",
            "Moon Princess",
            "Fire Joker",
          ],
        },
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "「Rage to Riches」は、ユニークな怪獣テーマ、高いRTP（97.12%）、そして低ボラティリティが特徴のスロットです。カスケードリールによるマルチプライヤー上昇、再フリースピン可能なフリースピン、そしてビルを破壊するボーナスゲームなど、多彩なフィーチャーがプレイヤーを飽きさせません。",
        "特に、資金が安定しやすい低ボラティリティと高いRTPは、長時間プレイしたいプレイヤーや、カジノのボーナス条件をクリアしたいプレイヤーにとって大きな魅力となるでしょう。CasinoTsu 推薦の、スリリングでやりがいのあるスロット体験をお楽しみください！✨",
      ],
      bullets: [
        "怪獣やパニック映画のテーマが好きなプレイヤー",
        "高いRTPの$スロット$を探しているプレイヤー",
        "資金を安定させながら長くスロットを楽しみたいプレイヤー",
        "カジノのボーナスを消化したいプレイヤー",
        "シンプルながらも奥深いゲーム性を求めるプレイヤー",
      ],
    },
  ],
  prosCons: {
    pros: [
      "ユニークな怪獣テーマとアメコミ風グラフィック",
      "高いRTP (97.12%)",
      "低ボラティリティで資金が安定しやすい",
      "カスケードリールとマルチプライヤー機能",
      "再フリースピン可能なフリースピン",
      "ビル破壊で賞金を獲得するボーナスゲーム",
      "モバイルデバイスに完全対応",
    ],
    cons: [
      "グラフィックはやや古めかしいと感じる可能性あり",
      "低ボラティリティのため、一撃の最大配当は限定的",
    ],
  },
  faq: [
    {
      q: "Rage to RichesのRTPは？",
      a: "Rage to RichesのRTP（Return To Player）は97.12%です。これは、プレイヤーにとって比較的有利な還元率と言えます。",
    },
    {
      q: "Rage to Richesはどのようなゲームですか？",
      a: "Rage to Richesは、怪獣が都市で大暴れするテーマのスロットゲームです。Play’n GO社によって開発され、カスケードリール、マルチプライヤー、フリースピン、ボーナスゲームといったフィーチャーが搭載されています。",
    },
    {
      q: "ボラティリティはどのくらいですか？",
      a: "Rage to Richesのボラティリティは「低（Low）」です。これは、勝利が頻繁に発生しやすい傾向がありますが、一撃の最大配当はやや抑えめであることを意味します。",
    },
    {
      q: "最大配当はいくらですか？",
      a: "Rage to Richesの最大配当は、ベット額の10,000倍です。フリースピン中にマルチプライヤーが上昇することで、この最大配当に到達する可能性があります。",
    },
    {
      q: "Rage to Richesは無料でプレイできますか？",
      a: "はい、多くのオンラインカジノでは、デモモード（無料プレイモード）でRage to Richesを試すことができます。実際のお金を使わずにゲームのルールやフィーチャーを学ぶのに最適です。",
    },
    {
      q: "モバイルデバイスでプレイできますか？",
      a: "はい、Rage to RichesはHTML5技術で開発されているため、スマートフォンやタブレットなどのモバイルデバイスで快適にプレイできます。",
    },
    {
      q: "ボーナスゲームでは何が起こりますか？",
      a: "ボーナスゲームでは、プレイヤーが怪獣を選び、ビルを破壊することで賞金を獲得します。破壊するビルや怪獣の選択によって、獲得できる賞金が変わります。最大でベット額の100倍の賞金が期待できます。",
    },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "/go/2up:2up?referrer_path=%2Fslots%2Frage-to-riches",
  },
  breadcrumbs: [
    { label: "CasinoTsu", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "Rage to Riches", href: "/slots/rage-to-riches" },
  ],
  tableOfContents: [
    { label: "Rage to Riches がプレイできるカジノ", href: "#casinos" },
    { label: "Rage to Richesの基本情報", href: "#game-info" },
    { label: "RTPとボラティリティについて", href: "#rtp-volatility" },
    { label: "Rage to Richesのゲーム特徴・フィーチャー", href: "#features" },
    { label: "ワイルドシンボル", href: "#wild-symbol" },
    { label: "マルチプライヤー機能", href: "#multiplier" },
    { label: "フリースピン", href: "#free-spins" },
    { label: "ボーナスゲーム", href: "#bonus-game" },
    { label: "その他の機能", href: "#other-features" },
    { label: "Rage to Richesのシンボル＆配当表", href: "#payout-table" },
    { label: "プロバイダー情報", href: "#provider-info" },
    { label: "グラフィック・サウンド", href: "#graphics-sound" },
    { label: "モバイル対応", href: "#mobile" },
    { label: "戦略・攻略法", href: "#strategy" },
    { label: "類似ゲーム", href: "#similar-games" },
    { label: "まとめ", href: "#summary" },
    { label: "よくある質問", href: "#faq" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/rage-to-riches" />;
}
