import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Moon Princess 100",
  hero: {
    title: "Moon Princess 100",
    subheading: "ムーンプリンセス100",
    description: "パワーアップした超ヒット作の続編、月に代わってカスケードよ♡ Playn’ GOから2022年4月7日にリリースされた、あの大ヒット作「ムンプリ」ことムーンプリンセスの続編が、賞金ポテンシャルをアップさせて堂々の再登場！このスロットは、アニメ、魔法、ファンタジーといったテーマが融合し、プレイヤーを魅惑的な世界へと誘います。✨",
    score: 4.7,
    scoreMax: 5,
    rtp: "96.2%",
    maxMultiplier: "x15,000",
    provider: "Play’n GO",
    releaseDate: "2021-12-20",
    volatility: "High",
    reels: "5",
    paylines: "Cluster Pays",
    minBet: "$0.2",
    maxBet: "$60",
    slotImageSrc: "/slots/moon-princess-100.png",
    highlights: [
      "アニメ、魔法、ファンタジーをテーマにした魅力的な世界観",
      "カスケードアクションと連鎖によるマルチプライヤー増加",
      "3人のプリンセスが発動する多彩なモディファイヤー",
      "最大100倍まで伸びるフリースピンモード",
      "最大15,000倍の高ポテンシャル",
    ],
    watchouts: [
      "高ボラティリティのため、大きな配当を得られる可能性がある反面、当たりが出る頻度は低くなる傾向があります。",
      "フリースピン突入には、プログレスメーターを貯めてグリッド全消しを達成する必要があります。",
    ],
  },
  featuredCasino: {
    name: "2アップカジノ 2up",
    logo: "/assets/casino/2up.png",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fmoon-princess-100",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fmoon-princess-100",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
  },
  casinos: [
    {
      name: "ReSpin",
      logo: "/assets/casino/respin.jpg",
      href: "https://go.casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "35x 賭け条件",
      freeSpins: "5x 賭け条件",
      wagering: "300USDT",
      rating: 4,
      tagline: "10種類のメジャーな仮想通貨が使えるクリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/respin:respin?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "30x 賭け条件",
      freeSpins: "30x 賭け条件",
      wagering: "¥850,000",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "2up",
      logo: "/images/casino/2up_375x375.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "30x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "$4,000",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "WSM Casino",
      logo: "/images/casino/wsm-casino_375x375.png",
      href: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "29x 賭け条件",
      wagering: "$1,000",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "20x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "¥50,000",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "35x 賭け条件",
      freeSpins: "40x 賭け条件",
      wagering: "¥200,000",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "1,000USDT",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "40x 賭け条件",
      wagering: "$2,020",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "$10,000",
      freeSpins: "800",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "20x 賭け条件",
      wagering: "$500",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "€25,000",
      freeSpins: "35x 賭け条件",
      wagering: "50",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Ramenbet",
      logo: "/images/casino/ramenbet_375x375-1.png",
      href: "https://go.casinotsu.com/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/Flush_375x375-1.png",
      href: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "30x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "1,800USDT",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "$0",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Casino Sky",
      logo: "/images/casino/casinosky_375x375.png",
      href: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "35x 賭け条件",
      freeSpins: "40x 賭け条件",
      wagering: "1BTC",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "https://go.casinotsu.com/go/cosmoswin:cosmoswin?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "$10,000",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cosmoswin:cosmoswin?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "45x 賭け条件",
      freeSpins: "60x 賭け条件",
      wagering: "$1,600",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Stake",
      logo: "/images/casino/stake_375x375-1.png",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "K8",
      logo: "/assets/casino/k8.jpg",
      href: "https://go.casinotsu.com/go/k8:k8?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "25x 賭け条件",
      freeSpins: "25x 賭け条件",
      wagering: "$1,840",
      rating: 4.5,
      tagline: "日本で人気の実機を打つならK8のパチンコで決まりっ！昔懐かしの台を打ちまくろう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/k8:k8?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://go.casinotsu.com/go/ohmyspins:ohmyspins?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "35x 賭け条件",
      freeSpins: "40x 賭け条件",
      wagering: "¥65,000",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ohmyspins:ohmyspins?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Yuugado",
      logo: "/assets/casinos/yuugado_375x375-1-1.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Tedbet",
      logo: "/images/casino/tedbet_375x375.png",
      href: "https://go.casinotsu.com/go/tedbet:tedbet?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/tedbet:tedbet?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Konibet",
      logo: "/images/casino/konibet_375x375.png",
      href: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "20x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "$777",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Trustdice",
      logo: "/images/casino/Trustdice_375x375.png",
      href: "https://go.casinotsu.com/go/trustdice:trustdice?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/trustdice:trustdice?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "20x 賭け条件",
      wagering: "$1,600",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "$0",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino_375x375.png",
      href: "https://go.casinotsu.com/go/joy-casino:joycasino?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/joy-casino:joycasino?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "20x 賭け条件",
      wagering: "¥50,000",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "40x 賭け条件",
      wagering: "¥200,000",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fmoon-princess-100",
      bonus: "20x 賭け条件",
      freeSpins: "20x 賭け条件",
      wagering: "$500",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fmoon-princess-100",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fmoon-princess-100",
    },
  ],
  gameInfo: {
    intro: "CasinoTsu は、Play’n GO 社の人気スロット「Moon Princess 100（ムーンプリンセス100）」を実際にプレイし、その魅力を深掘りいたしました。このスロットは、オリジナル版「ムーンプリンセス」の続編として、その魅力を引き継ぎつつ、いくつかの点で進化を遂げています。「ライズ・オブ・オリンパス100」のような「Olympus」シリーズの要素も取り入れられており、CasinoTsu でも注目しております。今回のレビューでは、以下のポイントに注目し、このスロットの奥深さを解き明かしていきます。 CasinoTsu は、正確さが第一。興奮はその次。をモットーに、詳細な情報をお届けします。",
    basicInfo: {
      rtp: "96.2%",
      volatility: "High",
      reels: "5",
      paylines: "Cluster Pays",
      minBet: "$0.2",
      maxBet: "$60",
      provider: "Play’n GO",
      releaseDate: "2021-12-20",
    },
  },
  payoutTable: {
    title: "Moon Princess 100 シンボルとペイアウト",
    symbols: [
      {
        name: "ラブ（高配当）",
        payout3: "x3",
        payout4: "x5",
        payout5: "x10",
      },
      {
        name: "スター（高配当）",
        payout3: "x3",
        payout4: "x5",
        payout5: "x10",
      },
      {
        name: "ストーム（高配当）",
        payout3: "x3",
        payout4: "x5",
        payout5: "x10",
      },
      {
        name: "プリンセスアクセ1",
        payout3: "x1",
        payout4: "x2",
        payout5: "x3",
      },
      {
        name: "プリンセスアクセ2",
        payout3: "x1",
        payout4: "x2",
        payout5: "x3",
      },
      {
        name: "プリンセスアクセ3",
        payout3: "x1",
        payout4: "x2",
        payout5: "x3",
      },
      {
        name: "プリンセスアクセ4",
        payout3: "x1",
        payout4: "x2",
        payout5: "x3",
      },
    ],
    maxPayout: "x15,000",
    notes: [
      "ペイラインとクラスターペイ：縦または横に3つ以上同じシンボルが隣接して揃うことで配当が発生します。",
      "配当を形成したシンボルは消滅し、上のシンボルが落下してきます（カスケード/アバランチ機能）。画面外からの新しいシンボルの補充はありません。",
      "プリンセスシンボルは、たとえ種類が異なっていても、いずれか3つ以上が隣接していれば配当が払い出されます。",
      "ワイルドシンボルは新月シンボルで、他のすべてのシンボルの代わりとなります。",
      "スキャッターやボーナスシンボルは存在しません。",
    ],
  },
  features: {
    title: "ゲームフィーチャー",
    items: [
      {
        name: "ワイルドシンボル",
        description: "新月シンボル。他のすべてのシンボルの代わりとなり、配当成立に貢献します。",
        icon: "/images/icons/wild.svg",
      },
      {
        name: "カスケードマルチプライヤー",
        description: "配当が発生すると、カスケードが連鎖するたびに賞金に適用されるマルチプライヤーが増加します。",
        icon: "/images/icons/multiplier.svg",
      },
      {
        name: "プログレスメーター",
        description: "高配当シンボルであるプリンセスシンボルが配当成立すると溜まり、3段階に分かれたプリンセスモディファイヤーが発動します。",
        icon: "/images/icons/meter.svg",
      },
      {
        name: "プリンセスモディファイヤー (ラブ)",
        description: "特定のシンボル1種類を別のシンボルに変換します。",
        icon: "/images/icons/love.svg",
      },
      {
        name: "プリンセスモディファイヤー (スター)",
        description: "ワイルドシンボルを1～2つグリッド上に追加します。",
        icon: "/images/icons/star.svg",
      },
      {
        name: "プリンセスモディファイヤー (ストーム)",
        description: "雷を呼び出し、ランダムな種類のシンボルを画面から消去します。",
        icon: "/images/icons/storm.svg",
      },
      {
        name: "ランダムモディファイヤー",
        description: "ベースゲーム中のハズレスピンでも、プリンセスモディファイヤーがランダムに発動することがあります。",
        icon: "/images/icons/random.svg",
      },
      {
        name: "グリッド全消し",
        description: "すべてのシンボルがグリッドから消える、またはワイルドシンボルだけになるまでシンボルが消滅すると達成され、50倍のマルチプライヤーが適用されます。",
        icon: "/images/icons/grid-clear.svg",
      },
      {
        name: "フリースピン",
        description: "プログレスメーターが満タンになり、グリッド全消しを達成すると突入します。毎スピン発動するモディファイヤーを選択でき、マルチプライヤーはリセットされず増加します。最大100回まで可能です。",
        icon: "/images/icons/free-spins.svg",
      },
    ],
  },
  sections: [
    {
      heading: "Moon Princess 100を徹底レビュー！",
      paragraphs: [
        "CasinoTsu は、Play’n GO 社の人気スロット「Moon Princess 100（ムーンプリンセス100）」を実際にプレイし、その魅力を深掘りいたしました。",
        "このスロットは、オリジナル版「ムーンプリンセス」の続編として、その魅力を引き継ぎつつ、いくつかの点で進化を遂げています。「ライズ・オブ・オリンパス100」のような「Olympus」シリーズの要素も取り入れられており、CasinoTsu でも注目しております。",
        "今回のレビューでは、以下のポイントに注目し、このスロットの奥深さを解き明かしていきます。 CasinoTsu は、正確さが第一。興奮はその次。をモットーに、詳細な情報をお届けします。",
      ],
      bullets: [
        "スロットシンボル： 登場シンボルとそれぞれの配当を詳細に解説",
        "ベット額： 最小ベットから最大ベット額まで、カジュアルプレイヤーからハイローラーまで幅広く対応",
        "RTP（払い出しレート）： プレイヤーへの還元率を正確に記載",
        "ボラティリティ： 当たりヒット時の払い出し頻度と賞金発生の間隔を分析",
        "ヒット率： 当たり発生の頻度、規模、およびそのインターバルを検証",
        "最大賞金： 獲得可能な賞金ポテンシャルを明記",
        "ワイルド、リスピン、その他のフィーチャー： ワイルドシンボルの役割や、停止した時のモディファイヤー、特殊フィーチャーを徹底解剖",
        "ボーナス購入： ボーナス購入機能の有無と、そのプレイ感をレビュー",
        "ボーナスゲーム： ボーナスゲーム（フリースピン）の詳細を解説",
        "グラフィックとサウンド： ビジュアルデザイン、テーマの表現、BGM、効果音などの感覚的な要素を評価",
      ],
    },
    {
      heading: "ボーナスもらってMoon Princess 100をプレイ！",
      paragraphs: [
        "ボーナスを賢く活用することは、リスクを抑えつつ、より多くのプレイチャンスを得るための重要な戦略です。 CasinoTsu は、皆様がよりお得に Moon Princess 100 をお楽しみいただけるよう、厳選したボーナス情報をご紹介いたします。当たりが出なくても損はなく、当たれば現金化のチャンスもございます。 CasinoTsu 推薦 のカジノで、ぜひこの機会をご活用ください。",
      ],
      table: {
        title: "Moon Princess 100 を楽しめるオンラインカジノボーナス",
        columns: ["オンラインカジノ名", "入金不要ボーナス内容"],
        rows: [
          [
            "[リリベット](https://casinotsu.com/reviews/lilibet)",
            "CasinoTsu限定！登録だけでもらえるジャパカジ限定 **入金不要ボーナス2000円**！（賭け条件1倍）<br>さらに、スロットで利用できる、最大 **7万円分** の **100％入金ボーナス** 💰（賭け条件 **30倍**）<br>＋元祖「ムーンプリンセス」の **50回分のフリースピン**。<br>CasinoTsu 推薦 のリリベットに登録して、Let’sムンプリ三昧！！",
          ],
          [
            "[遊雅堂](https://casinotsu.com/reviews/yuugado)",
            "遊雅堂では、 CasinoTsu 推薦 の **入金不要ボーナス** がございます🎁✨<br>**なんと！ その額3,000円** 😍💴<br>遊雅堂の **出金条件（賭け条件）は20倍** と低く、現金化のチャンスも十分にございます。",
          ],
        ],
      },
      paragraphs: [
        "さっそく、 CasinoTsu 推薦 のカジノに登録して、Moon Princess 100 の無料プレイやリアルマネープレイをお楽しみください。",
      ],
    },
    {
      heading: "Moon Princess 100 シンボルとペイアウト",
      paragraphs: [
        "ゲームのルールと配当を正確に理解することは、プレイをより深く楽しむために不可欠です。 CasinoTsu は、皆様が安心してゲームに臨めるよう、詳細な情報を提供いたします。",
      ],
      bullets: [
        "低配当シンボル： プリンセスのアクセサリーをモチーフにした4種類。",
        "高配当シンボル： 主人公のプリンセス3人（ラブ、スター、ストーム）の3種類。",
        "ワイルドシンボル： 新月シンボル。他のすべてのシンボルの代わりとなり、配当成立に貢献します。",
        "スキャッターやボーナスシンボルは存在しません。",
      ],
    },
    {
      heading: "ペイラインとクラスターペイ",
      paragraphs: [
        "Moon Princess 100 では、 **クラスターペイシステム** を採用しております。これは、 **縦または横に3つ以上同じシンボルが隣接して揃う** ことで配当が発生する仕組みです。最大5つまで連鎖させることが可能です。",
        "プリンセスシンボルは、たとえ種類が異なっていても、いずれか3つ以上が隣接していれば配当が払い出される点が特徴です。",
        "配当を形成したシンボルは消滅し、その上にあったシンボルが落下してきます（カスケード/アバランチ機能）。画面外からの新しいシンボルの補充はありません。 CasinoTsu は、このダイナミックなシステムがゲームの興奮を高めると考えております。",
      ],
    },
    {
      heading: "最小・最大ベット、オートプレイ",
      paragraphs: [
        "**ベット幅は$0.2（約30円）から$60（約9,000円）** までと幅広く、カジュアルプレイヤーからハイローラーまで、様々なプレイスタイルに対応しております。 CasinoTsu は、プレイヤーの皆様のニーズに合わせたゲーム選択が重要だと考えております。",
        "**ターボモード** や **オートプレイ機能** も完備されており、快適なプレイをサポートします。フリースピンに突入すると、オートプレイは自動的に停止します。",
      ],
    },
    {
      heading: "RTP（払い出しレート）",
      paragraphs: [
        "このスロットの **RTP（Return To Player）は96.2%** と公表されており、 CasinoTsu の基準においても標準的で良好な値です。",
      ],
    },
    {
      heading: "ボラティリティ",
      paragraphs: [
        "**ボラティリティは「High」**（高）に設定されています。これは、大きな配当を得られる可能性がある一方で、当たりが出る頻度は低くなる傾向があることを意味します。ただし、実際にはアクションが多いため、 CasinoTsu では中～高ボラティリティといった体感になるプレイヤーもいると推測しております。",
        "**ヒット率は未公表** ですが、 CasinoTsu による体感では20%を超えており、約5回に1度の割合で何らかの当たりが発生しているように感じられます。高ボラティリティスロットにありがちな「とにかく賞金が出るまで待つ」という苦行感は少なく、ベースゲーム中も飽きさせない工夫がされています。 CasinoTsu は、このようなバランスの取れたゲーム性を高く評価しております。",
      ],
    },
    {
      heading: "ジャックポット & 最大賞金ポテンシャル",
      paragraphs: [
        "Moon Princess 100 には、 **プログレッシブジャックポットは搭載されていません**。しかし、その代わりに **最大15,000倍** という非常に高い最大賞金ポテンシャルを秘めています。 CasinoTsu は、ジャックポットがない場合でも、このような高いポテンシャルを持つスロットは魅力的であると考えております。",
        "実質、中～高ボラティリティでありながら、ヒット率も体感20％超え。ベースゲームからワクワクするスピンが楽しめるのが、Moon Princess 100 の魅力です。カスケードアクションが頻繁に発生するため、フリースピン突入を待つ間も退屈しません！ CasinoTsu は、このゲームの持つエンターテイメント性を高く評価しております。",
      ],
    },
    {
      heading: "ワイルド、リスピン、その他のフィーチャー",
      paragraphs: [
        "Moon Princess 100 は、シンボル構成は比較的シンプルですが、 **モディファイヤー（停止したリール上のシンボルを変化させる効果）の多彩さ** がゲームの鍵となります。 CasinoTsu は、これらのフィーチャーがゲームに深みを与えていると分析しております。",
        "プレイ前に、どのようなフィーチャーが搭載されているかチェックしておきましょう。",
      ],
    },
    {
      heading: "カスケードマルチプライヤー",
      paragraphs: [
        "配当が発生すると、その当たりを形成したシンボルが爆発して消え、上のシンボルが落下してきます（カスケード）。このカスケードが連鎖するたびに、 **賞金に適用されるマルチプライヤーが増加** していきます。 CasinoTsu は、この連鎖によるマルチプライヤー増加が、大きな賞金獲得の鍵となると見ております。",
      ],
    },
    {
      heading: "プログレスメーター",
      paragraphs: [
        "高配当シンボルであるプリンセスシンボルが配当成立すると、画面左下に配置された **プログレスメーター** が溜まっていきます。",
        "メーターは3段階に分かれており、1段階分溜まるごとに **プリンセスモディファイヤー** が発動します。 CasinoTsu は、このメーターシステムがプレイヤーの期待感を高めると評価しております。",
      ],
    },
    {
      heading: "ランダムモディファイヤー",
      paragraphs: [
        "プログレスメーターが満タンになり発動するモディファイヤーですが、ベースゲーム中のハズレスピンでも、これらのモディファイヤーがランダムに発動することがあります。画面右側に表示されているプリンセスのモディファイヤーが、順次ランダムに発動します。 CasinoTsu は、このランダム性がゲームに予測不能な興奮をもたらすと考えております。",
      ],
    },
    {
      heading: "グリッド全消し",
      paragraphs: [
        "すべてのシンボルがグリッドから消える、またはワイルドシンボルだけになるまでシンボルが消滅すると、**グリッド全消し** が達成されます。",
        "グリッド全消しを達成すると、 **50倍のマルチプライヤー** が適用されます。 CasinoTsu は、このグリッド全消しがフリースピン突入への重要なステップとなると分析しております。",
      ],
    },
    {
      heading: "フリースピン",
      paragraphs: [
        "**フリースピンモード** は、プログレスメーターが満タンになった状態（ **プリンセストリニティ** と呼ばれます）で、 **グリッド全消しを達成する** ことで突入します。",
        "フリースピンモードでは、毎スピン発動するモディファイヤーを、 **3人のプリンセス（ラブ、スター、ストーム）から選択** できます。このモードでは、マルチプライヤーはリセットされず、ベースゲームで蓄積されたものが引き継がれ、さらに増加していきます。 CasinoTsu は、この選択肢の多さが戦略的なプレイを可能にすると評価しております。",
        "**フリースピンモードでの最大フリースピン回数は100回** に達する可能性があります。",
      ],
    },
    {
      heading: "BGMとグラフィック",
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["グラフィック", "2Dアニメーション"],
          ["モバイル対応", "👍 (Android, iOS)"],
          ["BGM", "80年代ヘビーロック調、アクションに合わせて変化"],
          ["スペシャルフィーチャー", "シンボル変換、シンボル消去、ワイルド追加、フリースピン、カスケードマルチプライヤー"],
        ],
      },
      paragraphs: [
        "Moon Princess 100 は、 **高ボラティリティスロットでありながら、アクションの多さ、フィーチャーの頻発度、カスケードアクションのスリル** により、ベースゲームからでも十分に盛り上がれるのが魅力です。 CasinoTsu は、このゲームの持つ没入感の高い体験を高く評価しております。",
        "特にフリースピンモードに突入した際は、マルチプライヤーが最高100倍まで伸びる可能性があり、一気に残高が伸びるチャンスがあります。ここはまさに「勝ち時」と言えるでしょう。",
      ],
    },
    {
      heading: "ムーンプリンセス100を遊ぶならこのカジノ！",
      table: {
        columns: ["カジノ名", "登録ボーナス"],
        rows: [
          [
            "[ラーメンベット](https://casinotsu.com/reviews/ramenbet)",
            "賭け条件5倍🔥 3,000円入金不要ボーナス【ジャパカジ限定】<br>👉 **[ラーメンベットのオファー](https://casinotsu.com/offers/ramenbet-exclusive)** へ",
          ],
          [
            "[コンクエスタドール](https://casinotsu.com/reviews/conquestador)",
            "コンクエスタドールに登録だけでもらえる無料の登録ボーナス40ドル＆登録スピン25回！<br>👉 [**コンクエスタドールのオファー**](https://casinotsu.com/offers/conquestador-exclusive) へ",
          ],
          [
            "[コニベット](https://casinotsu.com/reviews/konibet)",
            "ジャパカジ経由でコニベットに登録すると、登録ボーナスの$20に加えて、Lucky Neko – Gigablox（ラッキーネコ・ギガブロックス）のフリースピン50回がもらえちゃいます！<br>👉 **[コニベットのオファー](https://casinotsu.com/offers/konibet-exclusive)** へ",
          ],
          [
            "[**ジョイカジノ**](https://casinotsu.com/reviews/joycasino)",
            "入金不要でジョイカジノに登録するだけなのに、4,500円！<br>👉 **[**ジョイカジノ** のオファー](https://casinotsu.com/offers/joycasino-exclusive)** へ",
          ],
          [
            "[**ステークカジノ**](https://casinotsu.com/reviews/stake)",
            "ジャパカジから登録&カスタマーサポートに連絡するともらえる、入金不要ボーナス2,500円を進呈中～ヾ(≧▽≦\*)o<br>👉 **[ステークのオファー](https://casinotsu.com/offers/stake-exclusive)** へ",
          ],
        ],
      },
      paragraphs: [
        "このスロットはカナダ、フィンランド、ニュージーランド、ノルウェーなどの56カ国でプレイ可能ですが、アメリカのニュージャージー州のオンラインカジノでは提供されていません。 CasinoTsu は、プレイヤーの皆様がプレイできる環境で、安全にゲームを楽しんでいただくことを推奨いたします。",
      ],
    },
    {
      heading: "ゲームプレイ中に問題が発生したら",
      paragraphs: [
        "ゲームプレイ中に万が一、接続が切れたり、問題が発生したりした場合でもご安心ください。 CasinoTsu は、プレイヤーの皆様が安心してプレイできる環境作りをサポートいたします。ゲームは通常、プロバイダーのサーバー側で進行しており、プレイヤーのデバイス（パソコンやスマートフォン）にはその結果が表示されています。",
        "多くの場合、**ログインし直すことで、中断した時点からプレイを再開できます**。賞金やフィーチャーの状況、プログレスメーターの進行状況などがリセットされることはありませんので、ご安心ください。 CasinoTsu は、このような信頼性の高いゲームシステムを推奨いたします。",
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "Moon Princess 100 は、 **「アウト・オブ・ディス・ワールド」と評されるほどの高品質なプロダクションバリュー** を持ち、まさに「非の打ち所がない」と言えるような、完成されたスロットゲームです。 CasinoTsu は、このゲームの完成度を高く評価しております。",
        "ハイボラティリティスロットの中には、ひたすら耐えるようなゲームもありますが、この Moon Princess 100 は **アクション満載** で、ベースゲーム中も飽きさせない工夫が凝らされています。 CasinoTsu は、プレイヤーが最後まで楽しめるゲーム性を重視しております。",
        "ゲームプレイ中は、マットで落ち着いたトーンのBGMが流れますが、プリンセスモディファイヤーが発動する際には、リズミカルなビートとヘビーロック調のギターサウンドが加わり、ゲームを一層盛り上げます。 CasinoTsu は、このようなサウンドデザインがゲーム体験を豊かにすると考えております。",
        "まさに「 **傑出したリメイク** 」であり、オリジナル版の良さを「 **ほぼ全ての点で改善** 」していると言えるでしょう。 CasinoTsu は、この進化を高く評価し、皆様にもぜひ体験していただきたいと考えております。",
        "今後、「ムンプリ」シリーズで、エジプトやギリシャ、アステカなどをテーマにしたスピンオフ作品が登場するのも楽しみですね！",
      ],
    },
    {
      heading: "Moon Princess 100が気に入ったら、こちらもチェック！",
      bullets: [
        "[Moon Princess Christmas Kingdom](https://casinotsu.com/slots/moon-princess-christmas-kingdom) – Playn’ GO / RTP 94.2%",
        "[Moon Princess Trinity](https://casinotsu.com/slots/moon-princess-trinity) – Playn’ GO / RTP 96.2%",
        "Koi Princess – [NetEnt](https://casinotsu.com/providers/netent) / 96.23%",
        "Candy Land Princess – Playn’ GO / RTP 94.2%",
      ],
    },
  ],
  faq: [
    {
      q: "ムーンプリンセス100にボーナス購入機能はありますか？",
      a: "いいえ、Moon Princess 100 にはボーナス購入機能はございません。フリースピンは、ゲームプレイ中にプログレスメーターを貯めてグリッド全消しを達成することで突入します。 CasinoTsu では、このようなゲーム本来の楽しみ方を尊重しております。",
    },
    {
      q: "ムーンプリンセス100の最大配当は？",
      a: "Moon Princess 100 の最大配当は、ベット額の **15,000倍** です。 CasinoTsu は、この高いポテンシャルを魅力の一つとしております。",
    },
    {
      q: "新旧ムーンプリンセス・シリーズの違いは何ですか？",
      a: "Moon Princess シリーズには、これまで5作品がリリースされております。それぞれの作品では、フィーチャー機能や、フリースピンをトリガーする仕組みなどに若干の違いがありますが、基本的なテーマやゲーム性は共通しています。Moon Princess 100 は、特に賞金ポテンシャルを大幅に向上させている点が特徴です。 CasinoTsu は、シリーズの進化を追うことも楽しみの一つと考えております。",
    },
    {
      q: "ムーンプリンセス100はどのデバイスでプレイできますか？",
      a: "Moon Princess 100 は、**Android および iOS デバイス** で最適に動作するように設計されており、スマートフォンやタブレットで快適にプレイできます。 CasinoTsu は、モバイルフレンドリーなゲーム体験を推奨いたします。",
    },
    {
      q: "ムーンプリンセス100のユーザー評価は？",
      a: "プレイヤーからの評価は、**平均7.0/10** となっています。多くのプレイヤーが、その「アウト・オブ・ディス・ワールド」なプロダクションバリューと、完成度の高さを評価しています。 CasinoTsu も、この評価に同意いたします。",
    },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fmoon-princess-100",
  },
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Moon princess 100", href: "https://casinotsu.com/slots/moon-princess-100" },
  ],
  tableOfContents: [
    { label: "Moon Princess 100を徹底レビュー！", href: "#Moon%20Princess%20100%E3%82%92%E5%BE%B9%E5%BA%95%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%EF%BC%81" },
    { label: "ボーナスもらってMoon Princess 100をプレイ！", href: "#%E3%83%9C%E3%83%BC%E3%83%8A%E3%82%B9%E3%82%82%E3%82%89%E3%81%A3%E3%81%A6Moon%20Princess%20100%E3%82%92%E3%83%97%E3%83%AC%E3%82%A4%EF%BC%81" },
    { label: "Moon Princess 100 シンボルとペイアウト", href: "#Moon%20Princess%20100%20%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AB%E3%81%A8%E3%83%9A%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88" },
    { label: "ゲームフィーチャー", href: "#%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%95%E3%82%A3%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC" },
    { label: "Moon Princess 100 BGMとグラフィック", href: "#Moon%20Princess%20100%20BGM%E3%81%A8%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%83%E3%82%AF" },
    { label: "ムーンプリンセス100を遊ぶならこのカジノ！", href: "#%E3%83%A0%E3%83%BC%E3%83%B3%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9100%E3%82%92%E9%81%AB%E3%81%A3%E3%81%9F%E3%82%89%E3%81%93%E3%81%AE%E3%82%AB%E3%82%B8%E3%83%8E%EF%BC%81" },
    { label: "ゲームプレイ中に問題が発生したら", href: "#%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%97%E3%83%AC%E3%82%A4%E4%B8%AD%E3%81%AB%E5%95%8F%E9%A1%8C%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E3%81%9F%E3%82%89" },
    { label: "まとめ", href: "#%E3%81%BE%E3%81%A8%E3%82%81" },
    { label: "Moon Princess 100が気に入ったら、こちらもチェック！", href: "#Moon%20Princess%20100%E3%81%8C%E6%B0%97%E3%81%AB%E5%85%A5%E3%81%A3%E3%81%9F%E3%82%89%E3%80%81%E3%81%93%E3%81%A1%E3%82%89%E3%82%82%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%EF%BC%81" },
    { label: "よくある質問", href: "#%E3%82%88%E3%81%8F%E3%81%82%E3%82%8B%E8%B3%AA%E5%95%8F" },
  ],
  prosCons: {
    pros: [
      "アニメ、魔法、ファンタジーをテーマにした魅力的な世界観",
      "カスケードアクションと連鎖によるマルチプライヤー増加",
      "3人のプリンセスが発動する多彩なモディファイヤー",
      "最大100倍まで伸びるフリースピンモード",
      "最大15,000倍の高ポテンシャル",
      "ベースゲーム中も飽きさせないアクションの多さ",
      "モバイル対応でどこでもプレイ可能",
    ],
    cons: [
      "高ボラティリティのため、大きな配当を得られる可能性がある反面、当たりが出る頻度は低くなる傾向がある",
      "ボーナス購入機能がない",
    ],
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/moon-princess-100" />;
}
