import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Starburst XXXtreme：伝説がさらに過激に進化！",
  hero: {
    title: "Starburst XXXtreme",
    subheading: "伝説がさらに過激に進化！",
    description: "全世界で熱狂的な支持を得る、NetEnt社の象徴的なスロット『Starburst』が、さらにパワフルになって帰ってきました！それが 【Starburst XXXtreme】 です。",
    score: 4.7,
    scoreMax: 5,
    rtp: "96.26% (XXXtremeスピン有効時: 96.45%)",
    maxMultiplier: "200,000",
    provider: "NetEnt",
    releaseDate: "2021年7月15日",
    volatility: "High",
    reels: "5",
    paylines: "9",
    minBet: "$0.1",
    maxBet: "$50",
    slotImageSrc: "/slots/starburst-xxxtreme.png",
    highlights: [
      "最大配当200,000倍！",
      "マルチプライヤー付きワイルドシンボル",
      "エクストリームスピン機能",
      "ハイボラティリティで高額配当の可能性",
    ],
    watchouts: [
      "ハイボラティリティのため、勝利頻度が低い場合がある",
      "エクストリームスピン機能は高額なコストがかかる",
    ],
  },
  featuredCasino: {
    name: "2up",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/casinos/2up",
    ctaText: "今すぐプレイ！",
    ctaHref: "https://casinotsu.com/casinos/2up",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
  },
  casinos: [
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://casinotsu.com/casinos/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/betgoat",
    },
    {
      name: "2up",
      logo: "/assets/casino/2up.png",
      href: "https://casinotsu.com/casinos/2up",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/2up",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "https://casinotsu.com/casinos/cybet",
      bonus: "$500",
      freeSpins: "50",
      wagering: "35倍賭け条件",
      rating: 3,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/cybet",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      href: "https://casinotsu.com/casinos/1win",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/1win",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://casinotsu.com/casinos/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30倍賭け条件",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/miki",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/casinos/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29倍賭け条件",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/bitz",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://casinotsu.com/casinos/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20倍賭け条件",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/wikibet",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/casinos/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35倍賭け条件",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/sushi-casino",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.png",
      href: "https://casinotsu.com/casinos/parimatch",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/parimatch",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io.png",
      href: "https://casinotsu.com/casinos/bets-io",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/bets-io",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "https://casinotsu.com/casinos/duelbits",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/duelbits",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/casinos/sportsbet-io",
      bonus: "1,000 USDT",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/sportsbet-io",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/casinos/shuffle",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40倍賭け条件",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/shuffle",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/casinos/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: undefined,
      rating: 4,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/winz-io",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/casinos/dafabet",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20倍賭け条件",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/dafabet",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/casinos/lucky-block",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35倍賭け条件",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/lucky-block",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/flush.png",
      href: "https://casinotsu.com/casinos/flush",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "今年大注目のクリプトカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/flush",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/casinos/queen-casino",
      bonus: "1,800 USDT",
      freeSpins: "288",
      wagering: "30倍賭け条件",
      rating: 4,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/queen-casino",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/casinos/roobet",
      bonus: "$0",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/roobet",
    },
    {
      name: "Casino Sky",
      logo: "/assets/casino/casino-sky.png",
      href: "https://casinotsu.com/casinos/casino-sky",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/casino-sky",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/casinos/mega-dice",
      bonus: "1 BTC",
      freeSpins: "50",
      wagering: "35倍賭け条件",
      rating: 3,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/mega-dice",
    },
    {
      name: "Fresh Casino",
      logo: "/assets/casino/fresh-casino.png",
      href: "https://casinotsu.com/casinos/fresh-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/fresh-casino",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/casinos/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45倍賭け条件",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/bc-game",
    },
    {
      name: "Empire.io",
      logo: "/assets/casino/empireio.jpg",
      href: "https://casinotsu.com/casinos/empire-io",
      bonus: "$0",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "賭け条件ナシのキャシュバック＆VIP特典がスゴイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/empire-io",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      href: "https://casinotsu.com/casinos/stake",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/stake",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casino/wonder-casino.png",
      href: "https://casinotsu.com/casinos/wonder-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/wonder-casino",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/casinos/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35倍賭け条件",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/ohmyspins",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      href: "https://casinotsu.com/casinos/yuugado",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/yuugado",
    },
    {
      name: "Tedbet",
      logo: "/assets/casino/tedbet.png",
      href: "https://casinotsu.com/casinos/tedbet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/tedbet",
    },
    {
      name: "BetRebels",
      logo: "/assets/casino/betrebels.png",
      href: "https://casinotsu.com/casinos/betrebels",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "スポーツ好き必須！カジノもどんどん充実中。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/betrebels",
    },
    {
      name: "Conquestador",
      logo: "/assets/casino/conquestador.png",
      href: "https://casinotsu.com/casinos/conquestador",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "検索機能抜群！好みのゲームをサクサク検索できちゃう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/conquestador",
    },
    {
      name: "Cloudbet",
      logo: "/assets/casino/cloudbet.jpg",
      href: "https://casinotsu.com/casinos/cloudbet",
      bonus: "5 BTC",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "入出金額上限なし！仮想通貨好きハイローラー必見。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/cloudbet",
    },
    {
      name: "Lilibet",
      logo: "/assets/casino/lilibet.png",
      href: "https://casinotsu.com/casinos/lilibet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/lilibet",
    },
    {
      name: "Konibet",
      logo: "/assets/casino/konibet.png",
      href: "https://casinotsu.com/casinos/konibet",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/konibet",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/casinos/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20倍賭け条件",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/casino-me",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://casinotsu.com/casinos/kakeyo",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: "10倍賭け条件",
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/kakeyo",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      href: "https://casinotsu.com/casinos/mystino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/mystino",
    },
    {
      name: "InterCasino",
      logo: "/images/casino/Inter-Casino.png",
      href: "https://casinotsu.com/casinos/inter-casino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/inter-casino",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/casinos/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20倍賭け条件",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/empire777",
    },
    {
      name: "Joy Casino",
      logo: "/images/casino/joycasino.png",
      href: "https://casinotsu.com/casinos/joycasino",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/joycasino",
    },
    {
      name: "Vera&John",
      logo: "/images/casino/VeraJohn.png",
      href: "https://casinotsu.com/casinos/vera-john",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/vera-john",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/casinos/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40倍賭け条件",
      rating: 4,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/bitcasino-io",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      href: "https://casinotsu.com/casinos/casino-x",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/casino-x",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/casinos/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20倍賭け条件",
      rating: 4,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/casitabi",
    },
    {
      name: "Eldoah Casino",
      logo: "/images/casino/eldoah.png",
      href: "https://casinotsu.com/casinos/eldoah",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ。",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://casinotsu.com/casinos/eldoah",
    },
  ],
  gameInfo: {
    intro:
      "ついに、NetEnt社の人気スロット『Starburst』の続編 **【Starburst XXXtreme】** が登場いたしました！🚀✨\n\n最大配当はなんと200,000倍！その破壊力に驚きを隠せません。🔥🙀\n\n前作よりもボラティリティとRTPが引き上げられた本作が、どのようにスターバーストファンを魅了するのか、CasinoTsuが詳しくレビューしていきます！",
    basicInfo: {
      rtp: "96.26% (XXXtremeスピン有効時: 96.45%)",
      volatility: "High",
      reels: "5",
      paylines: "9",
      minBet: "$0.1",
      maxBet: "$50",
      provider: "NetEnt",
      releaseDate: "2021年7月15日",
    },
  },
  payoutTable: {
    title: "スターバースト・エクストリームのシンボルと配当",
    symbols: [
      {
        name: "ワイルド",
        description: "2、3、4リールに出現。リール全体に拡張し、マルチプライヤーが付与される。リスピン発生。",
        payout5: "-",
        payout4: "-",
        payout3: "-",
        isSpecial: true,
      },
      {
        name: "BAR",
        description: "最も高配当のシンボル。",
        payout5: "50x",
        payout4: "20x",
        payout3: "8x",
      },
      {
        name: "7",
        description: "高配当シンボル。",
        payout5: "25x",
        payout4: "15x",
        payout3: "5x",
      },
      {
        name: "ベル",
        description: "中配当シンボル。",
        payout5: "15x",
        payout4: "10x",
        payout3: "4x",
      },
      {
        name: "宝石（青）",
        description: "低配当シンボル。",
        payout5: "10x",
        payout4: "7x",
        payout3: "3x",
      },
      {
        name: "宝石（紫）",
        description: "低配当シンボル。",
        payout5: "8x",
        payout4: "6x",
        payout3: "3x",
      },
      {
        name: "宝石（緑）",
        description: "低配当シンボル。",
        payout5: "7x",
        payout4: "5x",
        payout3: "2x",
      },
      {
        name: "宝石（黄）",
        description: "低配当シンボル。",
        payout5: "6x",
        payout4: "4x",
        payout3: "2x",
      },
      {
        name: "宝石（赤）",
        description: "低配当シンボル。",
        payout5: "5x",
        payout4: "3x",
        payout3: "1x",
      },
    ],
    maxPayout: "200,000x",
    notes: [
      "ペイラインは左から右へのみ有効です。",
      "ワイルドシンボルは2、3、4リールにのみ出現します。",
      "ワイルドシンボルが出現すると、リール全体に拡張し、マルチプライヤーが付与され、リスピンが発生します。",
      "複数のワイルドシンボルが出現した場合、マルチプライヤーは掛け合わされます。",
    ],
  },
  features: {
    title: "スターバースト・エクストリームのゲーム機能と特別フィーチャー",
    items: [
      {
        name: "スターバースト・ワイルド機能",
        description: "2、3、4リールに出現するワイルドシンボルはリール全体に拡張し、マルチプライヤー（最大x150）が付与されます。その後、1回のリスピンが発生します。",
        icon: "/images/icons/wild.svg",
      },
      {
        name: "ランダムワイルド機能",
        description: "通常スピン中およびリスピン中に、1〜3個のスターバーストワイルドシンボルがランダムに出現する可能性があります。",
        icon: "/images/icons/random-wild.svg",
      },
      {
        name: "エクストリーム・スピン機能",
        description: "ベット額の10倍（ワイルド1個保証）または95倍（ワイルド2個保証）を支払うことで、スターバーストワイルドの出現が保証される機能です。",
        icon: "/images/icons/bonus-buy.svg",
      },
    ],
  },
  sections: [
    {
      heading: "スターバースト・エクストリームのレビュー",
      paragraphs: [
        "前作と比較しながら、ゲーム全体の雰囲気、リール構成、そしてRTPやボラティリティについて掘り下げていきます。さらに、注目のゲーム機能も詳しくご紹介。",
        "※RTPやボラティリティについてご不明な方は、[カジノ用語集](https://casinotsu.com/guides/glossary) をご参照ください。📚💕",
      ],
    },
    {
      heading: "【オリジナルStarburstとの比較】",
      table: {
        columns: ["仕様", "Starburst", "Starburst XXXtreme"],
        rows: [
          ["ペイライン", "10通り（左右両方有効）", "9通り（左からのみ有効）"],
          ["ボラティリティ", "ロー", "ハイ"],
          ["最大配当倍率", "500倍", "200,000倍"],
          ["特徴", "安定した小勝利", "低頻度だが超高額勝利の可能性"],
        ],
      },
    },
    {
      heading: "ベット額について",
      bullets: ["最小ベット額: $0.1", "最大ベット額: $50"],
    },
    {
      heading: "スターバースト・エクストリームのプレイにぴったりのボーナスをゲット！",
      paragraphs: [
        "リリース直後から多くのオンラインカジノで導入されたStarburst XXXtreme。その人気ぶりが伺えますね。🤩",
      ],
      table: {
        columns: ["カジノ", "ボーナス内容"],
        rows: [
          ["[Wonder Casino（ワンダーカジノ）](https://casinotsu.com/reviews/wonder-casino)", "登録だけで入金不要ボーナス$40ゲット★"],
          ["[デュエルビッツ](https://casinotsu.com/reviews/duelbits)", "最もお得度の高いレーキバックで、急成長中の仮想通貨特化型カジノ！"],
        ],
      },
      paragraphs: [
        "まだプレイするカジノを決めていない、または登録がお済みでない方は、ぜひこれらのカジノでボーナスも一緒にゲットしてくださいね！😋💕",
      ],
    },
    {
      heading: "スターバースト・エクストリームのシンボルと配当",
      paragraphs: [
        "前作の世界観を踏襲しつつ、さらなる宇宙の旅へと誘う本作。5×3のリール構成はそのままに、**配当倍率が大幅にアップしたハイボラティリティ**仕様となっています。🎉",
      ],
    },
    {
      heading: "シンボル",
      paragraphs: [
        "シンボルは、前作同様、宇宙に輝く宝石たち。しかし、本作では**シンボルの配当倍率が全体的に低下**しています。その代わりに、新しい**マルチプライヤー機能**が勝利の鍵となります。",
      ],
    },
    {
      heading: "ペイライン",
      paragraphs: [
        "ペイラインは前作の10通りから **9通り** へと減少しました。",
        "さらに、オリジナルStarburstでは左からでも右からでも配当が成立しましたが、本作では **左端からのシンボル揃いが配当の条件** となります。これは、ゲームプレイにおいて重要な変更点であり、勝利頻度に影響を与える可能性がありますが、その分、高額配当の可能性が秘められています。",
      ],
    },
    {
      heading: "RTP（還元率）",
      paragraphs: ["プレイヤーへの還元率（RTP）は、通常プレイ時とXXXtremeスピン有効時で異なります。"],
      table: {
        columns: ["ゲーム種類", "還元率"],
        rows: [
          ["通常プレイ", "96.26%"],
          ["XXXtremeスピン有効時", "96.45%"],
        ],
      },
      paragraphs: [
        "XXXtremeスピンを購入して有効にすると、RTPがわずかに上昇します。これは、ワイルドシンボルの出現が保証されることで、より多くの配当機会が期待できるためと考えられます。",
      ],
    },
    {
      heading: "ボラティリティ",
      paragraphs: [
        "オリジナルStarburstは、安定した小勝利が魅力の「ローボラティリティ」で、初心者の方にも人気でした。しかし、本作 **Starburst XXXtreme は「ハイボラティリティ」** へと進化しています。",
        "**ハイリスク・ハイリターンを求めるギャンブル精神旺盛なプレイヤー** には、まさにうってつけの仕様です。🤩😎",
        "ハイボラティリティゆえ、ベースゲームでの勝利頻度は低くなる傾向がありますが、一度大きな配当が発生した際のインパクトは絶大です。オリジナルのStarburstのような安定感を求める方には、少し物足りなく感じるかもしれません。",
      ],
    },
    {
      heading: "最大可能配当倍率",
      paragraphs: ["最大配当は驚異の200,000倍！"],
      paragraphs: [
        "前作の最大500倍と比較すると、その差は歴然です。ハイリスク・ハイリターンの名にふさわしい、爆発力のあるゲーム体験が期待できます。😍",
      ],
    },
    {
      heading: "オートプレイ（自動スピン）",
      paragraphs: [
        "スピンボタンの左側にはオートプレイ設定ボタンがあり、右側にはターボボタンも搭載されています。スピーディーなラウンド消化を望むプレイヤーにとって、非常に快適な環境が整っています。🎰",
        "シンボルや世界観は前作の魅力を引き継ぎつつ、配当やスペック面で大幅な進化を遂げたStarburst XXXtreme。プレイヤーの好みが分かれる可能性はありますが、エクストリームスピン機能を巧みに活用すれば、高いRTPを維持しつつ、非常に魅力的なスロットとなり得ます。",
      ],
    },
    {
      heading: "スターバースト・エクストリームのゲーム機能と特別フィーチャー",
      paragraphs: [
        "本作の目玉は、ワイルドシンボルの出現を保証する **エクストリームスピン**（XXXtreme Spin）機能です。この機能は購入することで発動可能です。🎰💰",
      ],
    },
    {
      heading: "スターバースト・ワイルド機能",
      paragraphs: [
        "前作から引き続き搭載されている機能です。2、3、4リールにワイルドが出現すると、**上下に拡張してリール全体をワイルドシンボルに変化**させ、次のスピンで **1回転のリスピン** が発生します。🙏",
        "本作で大きく進化した点は、このワイルド機能に **マルチプライヤーが搭載** されたことです！😻",
        "**マルチプライヤーは、x2、x3、x5、x10、x25、x50、x100、そして最大でx150まで、ワイルドシンボルごとにランダムに付与されます。**",
        "多くは1桁ですが、時折2桁、3桁のマルチプライヤーが出現すれば、興奮は最高潮に！🎉 CasinoTsuの担当者も、プレイ中に50倍と5倍のマルチプライヤーを同時に引く体験をしました。",
        "複数のワイルドシンボルが出現した場合、それぞれのマルチプライヤーは合算されるのではなく、掛け合わされます。これにより、一撃の配当が爆発的に増加する可能性があります。",
        "ワイルドリールによるリスピンは、前作同様に発生します。つまり、仮に一度目の着地で配当が発生しなくても、**もう1回転チャンスが残されている**ということです。🥺😇",
        "マルチプライヤーの重要性を実感できる瞬間です。",
      ],
    },
    {
      heading: "ランダムワイルド機能",
      paragraphs: [
        "本作から追加された新機能です。出現を願っていれば、**通常スピン中およびリスピン中に、1〜3個のスターバーストワイルドシンボルがランダムに出現する**可能性があります。これにより、予期せぬ勝利のチャンスが生まれます。",
      ],
    },
    {
      heading: "エクストリーム・スピン機能",
      paragraphs: [
        "本作の最も注目すべき機能です！これは単なるボーナス購入機能ではありません。",
        "1スピンあたりのベット額の10倍、または95倍を賭けてスピンすることで、**スターバーストワイルドの出現が保証される**という強力な機能です。🎰💰",
        "エクストリームスピンを有効にするボタンを押すと、以下の2つの選択肢が表示されます。",
      ],
      table: {
        columns: ["ベット額", "内容"],
        rows: [
          ["ベット額の **10倍**", "ワイルド1個保証／1スピン"],
          ["ベット額の **95倍**", "ワイルド2個保証／1スピン"],
        ],
      },
      paragraphs: [
        "どちらかを選択して確認を押すと、ゲーム画面に戻ります。",
      ],
    },
    {
      heading: "【エクストリームスピンの注意点】",
      paragraphs: [
        "この機能は、**非常に高額なコストがかかる**ことを理解しておく必要があります。特に95倍のオプションは、一般的なボーナス購入機能と比較しても高価です。したがって、資金管理には細心の注意が必要です。",
        "しかし、マルチプライヤーの破壊力でハイリターンを狙うプレイヤーにとっては、もはやベースゲームには戻れないほどの魅力があるでしょう。💜",
      ],
    },
    {
      heading: "【エクストリームスピンの必要性】",
      paragraphs: [
        "ハイボラティリティなゲーム性のため、**エクストリームスピン機能なしでは、ゲームプレイが単調に感じられたり、勝利が非常に少なくなる**ことがあります。この機能はゲームに興奮と大きな勝利の可能性をもたらしますが、その高額なコストから、全てのプレイヤーに適しているわけではありません。オリジナルのStarburstの安定したプレイフィールを好んでいたプレイヤーは、この機能の必要性やコストについて慎重に検討する必要があります。",
      ],
    },
    {
      heading: "スターバースト・エクストリームのグラフィックやサウンド",
      paragraphs: [
        "前作の宇宙空間をテーマにしたグラフィックは健在で、輝くネオンカラーの惑星シンボルが高画質のスクリーンを彩ります。サウンド演出もさらに洗練され、プレイ体験を一層盛り上げてくれるはずです。🤩🌟",
      ],
    },
    {
      heading: "スターバースト・エクストリームを遊ぶならこのカジノ！",
      paragraphs: [
        "CasinoTsuが厳選した、Starburst XXXtreme をプレイするのに最適なカジノをご紹介します。お得なボーナス情報もございますので、ぜひチェックしてください。",
      ],
      table: {
        columns: ["カジノ名", "登録ボーナス"],
        rows: [
          ["[**遊雅堂**](https://casinotsu.com/reviews/yuugado)", "ジャパカジ限定！ 遊雅堂の入金不要ボーナス3,000円🎁\n👉 [遊雅堂のオファー](https://casinotsu.com/offers/yuugado-exclusive) へ"],
          ["[**テッドベット**](https://casinotsu.com/reviews/tedbet)", "テッドベットの入金不要ボーナス4,500円【ジャパカジ限定】！\n👉 [テッドベットのオファー](https://casinotsu.com/offers/tedbet) へ"],
          ["[**インターカジノ**](https://casinotsu.com/reviews/inter-casino)", "ジャパカジからの登録で、今なら150回分（30ドル相当）の登録フリースピン！\n👉 [インターカジノのオファー](https://casinotsu.com/offers/intercasino-welcome-offer) へ"],
          ["[**ジョイカジノ**](https://casinotsu.com/reviews/joycasino)", "入金不要でジョイカジノに登録するだけ！4,500円プレゼント！\n👉 [ジョイカジノ のオファー](https://casinotsu.com/offers/joycasino-exclusive) へ"],
          ["[**ステークカジノ**](https://casinotsu.com/reviews/stake)", "ジャパカジから登録&カスタマーサポートに連絡で、入金不要ボーナス2,500円を進呈中～ヾ(≧▽≦\*)o\n👉 [ステークのオファー](https://casinotsu.com/offers/stake-exclusive) へ"],
        ],
      },
    },
    {
      heading: "プレイ中に問題が発生したら？",
      paragraphs: [
        "万が一、プレイ中に予期せぬ問題が発生した場合は、まずご利用のオンラインカジノのカスタマーサポートへお問い合わせください。",
        "問題が解決しない場合や、サポートの対応に不満がある場合は、他のカジノでのプレイを検討することも一つの方法です。",
      ],
    },
    {
      heading: "スターバースト・エクストリームのまとめ",
      paragraphs: [
        "シンプルで遊びやすいという、Starburstの大きな魅力はそのままに。\n配当やルールのシンプルさは引き継ぎつつ、新たなマルチプライヤー機能やエクストリームスピン機能によって、**一撃必殺の大当たりを狙うプレイヤーへの魅力が大幅に増した**のがStarburst XXXtreme です。",
        "ハイリスク・ハイリターンのボラティリティ設定と、高めのRTPは、新たなスターバーストシリーズのファンを獲得することは間違いないでしょう。",
        "各シンボルの配当が低くなったことや、右側からのペイラインが無くなったことには一瞬驚きましたが、それを補って余りある機能の数々に納得いたしました。😁",
        "エクストリームスピン機能を活用して、最大配当200,000倍をぜひ狙ってみてください！💪",
      ],
    },
    {
      heading: "【こんなプレイヤーにおすすめ】",
      bullets: [
        "オリジナルStarburstの宇宙テーマが好きで、より高い爆発力を求めているプレイヤー。",
        "ハイボラティリティスロットで一攫千金を狙いたいプレイヤー。",
        "高額ベットやボーナス購入に抵抗がなく、リスクを冒してでも大きな勝利を目指したいプレイヤー。",
      ],
    },
    {
      heading: "【CasinoTsuからの注意点】",
      bullets: [
        "ハイボラティリティのため、勝利頻度が低く、資金の減少が早まる可能性があります。",
        "エクストリームスピン機能は非常に高額であり、慎重な資金管理が不可欠です。",
        "オリジナルStarburstのような、頻繁に発生する小勝利による安定したゲームプレイを期待するプレイヤーには、合わない可能性があります。",
      ],
    },
    {
      heading: "スターバースト・エクストリームが好きならこのスロットも！",
      table: {
        columns: ["おすすめスロット", "詳細"],
        rows: [
          ["デッド オア アライブ2", "アメリカ西部開拓時代がテーマ！🏜 **最大配当倍率111,111倍**。ハイリスク・ハイリターンを狙うプレイヤーに最適。"],
          ["[マネートレイン 2](https://casinotsu.com/slots/money-train-2)", "Relax Gamingの人気スロット。**最大配当50,000倍**、**RTPは96.4%** (ボーナス購入時98%)。ハイボラティリティで一撃必殺を狙いましょう！😎"],
        ],
      },
    },
  ],
  similarGames: [
    {
      name: "Money Train 2",
      href: "/slots/money-train-2",
      provider: "Relax Gaming",
      description: "Relax Gamingの人気スロット。最大配当50,000倍、RTPは96.4% (ボーナス購入時98%)。ハイボラティリティで一撃必殺を狙いましょう！😎",
    },
  ],
  prosCons: {
    pros: [
      "最大配当200,000倍という驚異的なポテンシャル",
      "マルチプライヤー付きワイルドシンボルによる高額配当の可能性",
      "エクストリームスピン機能でワイルド出現を保証",
      "オリジナルStarburstの魅力的な世界観を継承",
      "ハイボラティリティで一攫千金を狙える",
    ],
    cons: [
      "ハイボラティリティのため、勝利頻度が低い場合がある",
      "エクストリームスピン機能は非常に高額",
      "ペイラインが左から右のみになり、オリジナルより減少",
      "ベースゲームでの配当が低い傾向",
    ],
  },
  faq: [
    {
      q: "スターバースト・エクストリームのRTPは？",
      a: "通常プレイ時は96.26%、XXXtremeスピン有効時は96.45%です。",
    },
    {
      q: "スターバースト・エクストリームのボラティリティは？",
      a: "本作Starburst XXXtremeは「ハイボラティリティ」です。一方、初期版のStarburstは「ローボラティリティ」で、初心者にも人気があります。",
    },
    {
      q: "エクストリームスピン機能の価格は？",
      a: "エクストリームスピン機能は、ベット額の10倍（ワイルド1個保証）または95倍（ワイルド2個保証）で購入できます。これは非常に高価な機能ですので、ご注意ください。",
    },
    {
      q: "最大マルチプライヤーはいくつですか？",
      a: "ワイルドシンボルに付与される最大マルチプライヤーはx150です。複数のワイルドが出現した場合、これらのマルチプライヤーは掛け合わされます。",
    },
    {
      q: "オリジナルのStarburstとどう違いますか？",
      a: "主な違いは、ペイライン（左から右のみ）、ボラティリティ（ハイ）、最大配当（200,000倍）、そしてマルチプライヤー付きワイルドとエクストリームスピン機能の追加です。オリジナルのStarburstは、両方向ペイライン、ローボラティリティ、最大500倍の配当で、より安定した勝利が期待できました。",
    },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "/casinos",
  },
  breadcrumbs: [
    { label: "ホーム", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "Starburst XXXtreme", href: "/slots/starburst-xxxtreme" },
  ],
  tableOfContents: [
    { label: "スターバースト・エクストリームのレビュー", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC" },
    { label: "スターバースト・エクストリームの基本情報", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E5%9F%BA%E6%9C%AC%E6%83%85%E5%A0%B1" },
    { label: "スターバースト・エクストリームのプレイにぴったりのボーナスをゲット！", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E3%83%97%E3%83%AC%E3%82%A4%E3%81%AB%E3%81%B4%E3%81%A3%E3%81%9F%E3%82%8A%E3%81%AE%E3%83%9C%E3%83%BC%E3%83%8A%E3%82%B9%E3%82%92%E3%82%B2%E3%83%83%E3%83%88%EF%BC%81" },
    { label: "スターバースト・エクストリームのシンボルと配当", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AB%E3%81%A8%E9%85%8D%E5%BD%91" },
    { label: "スターバースト・エクストリームのゲーム機能と特別フィーチャー", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E3%82%B2%E3%83%BC%E3%83%A0%E6%A9%9F%E8%83%BD%E3%81%A8%E7%89%B9%E5%88%A5%E3%83%95%E3%82%A3%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC" },
    { label: "スターバースト・エクストリームのグラフィックやサウンド", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%83%E3%82%AF%E3%82%84%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89" },
    { label: "スターバースト・エクストリームを遊ぶならこのカジノ！", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%82%92%E9%81%8A%E3%81%B6%E3%81%AA%E3%82%89%E3%81%93%E3%81%AE%E3%82%AB%E3%82%B8%E3%83%8E%EF%BC%81" },
    { label: "プレイ中に問題が発生したら？", href: "#%E3%83%97%E3%83%AC%E3%82%A4%E4%B8%AD%E3%81%AB%E5%95%8F%E9%A1%8C%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E3%81%9F%E3%82%89%EF%BC%9F" },
    { label: "スターバースト・エクストリームのまとめ", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%AE%E3%81%BE%E3%81%A8%E3%82%81" },
    { label: "スターバースト・エクストリームが好きならこのスロットも！", href: "#%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B9%E3%83%88%E3%83%BB%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%88%E3%83%AA%E3%83%BC%E3%83%A0%E3%81%8C%E5%A5%BD%E3%81%8D%E3%81%AA%E3%82%89%E3%81%93%E3%81%AE%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88%E3%82%82%EF%BC%81" },
    { label: "よくある質問", href: "#%E3%82%88%E3%81%8F%E3%81%82%E3%82%8B%E8%B3%AA%E5%95%8F" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/starburst-xxxtreme" />;
}
