import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Dead Canary (デッド・キャナリー) スロット攻略【2025年版】",
  hero: {
    title: "Dead Canary (デッド・キャナリー)",
    score: 4.3,
    scoreMax: 5,
    rtp: "96.02%",
    maxMultiplier: "x65,000",
    volatility: "High (Extreme)",
    releaseDate: "2022-12-20",
    provider: "Nolimit City",
    reels: "6",
    paylines: "1,728通り (最大展開時)",
    minBet: "$0.20",
    maxBet: "$100",
    slotImageSrc: "/slots/dead-canary.jpg",
    highlights: [
      "最大配当65,000倍という驚異的なポテンシャル",
      "ワイルドマイニングやXボムワイルドマルチプライヤーなどのユニークなフィーチャー",
      "炭鉱を舞台にしたダークで重厚な世界観",
      "フリースピン中の多彩な固定シンボルと金庫システム",
    ],
    watchouts: [
      "非常に高いボラティリティのため、資金管理が重要",
      "RTPはカジノやプレイ方法により変動する",
    ],
  },
  featuredCasino: {
    name: "Wonder Casino",
    logo: "/assets/casino/wonder-casino.png",
    href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdead-canary",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdead-canary",
    tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
  },
  casinos: [
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.png",
      href: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "2up Casino",
      logo: "/images/casino/2up-casino.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.png",
      href: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$500",
      freeSpins: "50回",
      wagering: "35倍",
      rating: 3.5,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "1win",
      logo: "/assets/casino/1win.png",
      href: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.png",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$4,000",
      freeSpins: "200回",
      wagering: "30倍 / 20倍",
      rating: 4.0,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.png",
      href: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29倍",
      rating: 4.0,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.png",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "¥200,000",
      freeSpins: "50回",
      wagering: "35倍 / 40倍",
      rating: 4.0,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Betpanda",
      logo: "/assets/casino/betpanda.png",
      href: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Parimatch",
      logo: "/assets/casino/parimatch.png",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io.png",
      href: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "最大1BTC",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4.0,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Duelbits",
      logo: "/assets/casino/duelbits.png",
      href: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "500回",
      wagering: "なし",
      rating: 4.0,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Sportsbet.io",
      logo: "/images/casino/sportsbet-io.png",
      href: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "なし",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.png",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4.0,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.png",
      href: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$10,000",
      freeSpins: "800回",
      wagering: "なし",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.png",
      href: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4.0,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.png",
      href: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "€25,000",
      freeSpins: "50回",
      wagering: "なし / 35倍",
      rating: 4.0,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Flush Casino",
      logo: "/assets/casino/flush-casino.png",
      href: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.png",
      href: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Stake",
      logo: "/assets/casino/stake.png",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.0,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casino/wonder-casino.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Yuugado",
      logo: "/assets/casino/yuugado.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Mystino",
      logo: "/assets/casino/mystino.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "InterCasino",
      logo: "/assets/casino/intercasino.png",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.png",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4.0,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.png",
      href: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Vera&John",
      logo: "/assets/casino/vera-john.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.png",
      href: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20倍",
      rating: 4.0,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/jp/bitcasino-io.png",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40倍",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Casino-X",
      logo: "/assets/casino/casino-x.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "-",
      freeSpins: "-",
      wagering: "-",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fdead-canary",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.png",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fdead-canary",
      bonus: "$500",
      freeSpins: "250回",
      wagering: "20倍",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fdead-canary",
    },
  ],
  gameInfo: {
    intro: "「Dead Canary（デッド・キャナリー）」は、Nolimit City 社が開発した、炭鉱を舞台にした高スペックなスロットゲームです。最大配当65,000倍という驚異的なポテンシャルを秘めており、リスピンやホールド＆ウィンといった、一撃必殺を狙えるフィーチャーが満載されています。カナリアやドワーフが爆発するユニークな演出も特徴的で、プレイヤーを飽きさせない魅力にあふれたゲームです。",
    basicInfo: {
      rtp: "92.11% - 96.02% (ベースゲーム) / 最大96.39% (フィーチャー購入時)",
      volatility: "High (Volatility Extreme - 10/10)",
      reels: "6",
      paylines: "1,728通り (最大展開時)",
      minBet: "$0.20",
      maxBet: "$100",
      provider: "Nolimit City",
      releaseDate: "2022-12-20",
    },
  },
  payoutTable: {
    title: "ペイアウト・配当表",
    symbols: [
      {
        name: "人相の悪いオジサン",
        payout5: "$20",
        payout4: "$12",
        payout3: "$8",
        payout6: "$40",
      },
      {
        name: "ドワーフ",
        payout5: "$16",
        payout4: "$10",
        payout3: "$6",
        payout6: "$32",
      },
      {
        name: "シルバーカナリア",
        payout5: "$12",
        payout4: "$8",
        payout3: "$4",
        payout6: "$24",
      },
      {
        name: "ゴールドカナリア",
        payout5: "$10",
        payout4: "$6",
        payout3: "$3",
        payout6: "$20",
      },
      {
        name: "A",
        payout5: "$6",
        payout4: "$4",
        payout3: "$2",
        payout6: "$10",
      },
      {
        name: "K",
        payout5: "$6",
        payout4: "$4",
        payout3: "$2",
        payout6: "$10",
      },
      {
        name: "Q",
        payout5: "$4.8",
        payout4: "$3.2",
        payout3: "$1.6",
        payout6: "$8",
      },
      {
        name: "J",
        payout5: "$4.8",
        payout4: "$3.2",
        payout3: "$1.6",
        payout6: "$8",
      },
      {
        name: "10",
        payout5: "$3.6",
        payout4: "$2.4",
        payout3: "$1.2",
        payout6: "$6",
      },
      {
        name: "9",
        payout5: "$3",
        payout4: "$2",
        payout3: "$1",
        payout6: "$5",
      },
    ],
    maxPayout: "x65,000",
    notes: [
      "上記はベット額$0.20時の配当例です。ベット額に応じて配当は変動します。",
      "クラスターペイ方式を採用しており、同一シンボルが3つ以上隣接して出現することで配当が成立します。",
    ],
  },
  features: {
    title: "ゲーム特徴・フィーチャー",
    items: [
      {
        name: "ワイルドマイニング (Wild Mining)",
        description: "同一シンボルが斜めに3〜5つ揃うと発動。揃ったシンボルがダイナマイトワイルドに変化し、周囲を爆発させて連鎖を誘発。5つ揃うとリール拡大とともに配当連鎖が期待できる。",
        icon: "/images/icons/wild.svg",
      },
      {
        name: "Xボム ワイルドマルチプライヤー (xBomb Wild Multiplier)",
        description: "スキャッター以外の全てのシンボルの代わりとなるダイナマイトシンボル。爆発すると周囲のシンボルを吹き飛ばし、マルチプライヤーを増加させる。各爆発ごとにリール上部の+1マルチプライヤーが追加される。",
        icon: "/images/icons/wild.svg",
      },
      {
        name: "スキャッター (Scatter)",
        description: "金または銀の鳥かごに入ったカナリア。3つ以上出現するとフリースピンが発動。",
        icon: "/images/icons/scatter.svg",
      },
      {
        name: "Xベット (XBet)",
        description: "ベット額に40%を追加することで、スキャッターシンボルの出現確率を高める機能。",
        icon: "/images/icons/bet.svg",
      },
      {
        name: "カスケード（連鎖）/ コラプス",
        description: "勝利したシンボルは爆発して消滅し、新しいシンボルが落下してくる。一度のスピンで複数回の配当成立が期待できる。",
        icon: "/images/icons/cascade.svg",
      },
      {
        name: "フリースピン (Free Spins)",
        description: "スキャッターシンボルを3つ揃えるか、ボーナス購入機能で開始。シルバーカナリア、ゴールドカナリア、または両方が固定され、リール構成が拡大する。",
        icon: "/images/icons/free-spins.svg",
      },
      {
        name: "固定シンボル (Collection Items)",
        description: "フリースピン中に登場する、カナリア、コイン、マルチプライヤー、爆弾、ガス、ネズミ、ドワーフ、アップグレードシンボルなど。賞金や配当に影響を与える。",
        icon: "/images/icons/feature.svg",
      },
      {
        name: "ボールトシステム (Vault System)",
        description: "フリースピン中にリールの四隅に出現する金庫。隣接するダイナマイト（xBomb）が爆発するとロックが解除され、賞金（コインやマルチプライヤー）を獲得できる。",
        icon: "/images/icons/feature.svg",
      },
    ],
  },
  sections: [
    {
      heading: "導入・概要",
      paragraphs: [
        "「Dead Canary（デッド・キャナリー）」は、[Nolimit City](https://casinotsu.com/providers) 社が開発した、炭鉱を舞台にした高スペックなスロットゲームです。最大配当65,000倍という驚異的なポテンシャルを秘めており、リスピンやホールド＆ウィンといった、一撃必殺を狙えるフィーチャーが満載されています。カナリアやドワーフが爆発するユニークな演出も特徴的で、プレイヤーを飽きさせない魅力にあふれたゲームです。",
        "Nolimit City社は、その独創的で過激なゲーム性から「ノーリミット」という名の通り、常に限界に挑戦するようなスロットをリリースしており、「Dead Canary」もその代表格と言えるでしょう。CasinoTsuは、その挑戦的なゲーム性に敬意を表し、詳細な分析をお届けいたします。",
      ],
    },
    {
      heading: "ゲーム基本情報",
      table: {
        title: "概要",
        columns: ["概要", "詳細"],
        rows: [
          ["名称", "Dead Canary"],
          ["リリース日", "2022-12-20"],
          ["プロバイダー", "Nolimit City"],
          ["最大配当倍率", "x65,000"],
          ["ボラティリティ", "High (Volatility Extreme - 10/10)"],
          ["最大ベット額", "$100"],
          ["最小ベット額", "$0.20"],
          ["リール数", "6"],
          ["行数", "ベースゲーム中は変動 (初期: 3-3-2-2-1-1、展開後: 3-4-3-4-3-4)"],
          ["ペイライン数", "1,728通り (最大展開時)"],
          ["RTP (還元率)", "92.11% - 96.02% (ベースゲーム) / 最大96.39% (フィーチャー購入時)"],
        ],
      },
      paragraphs: [
        "**注意**: RTP（還元率）はカジノやプレイしているフィーチャー（ベースゲーム、フリースピン、フィーチャー購入）によって変動します。正確な数値は、プレイするカジノのスロット内情報をご確認ください。CasinoTsuは、正確さが第一。興奮はその次。",
      ],
    },
    {
      heading: "どこで遊べるか：Dead Canary をプレイできるカジノ",
      paragraphs: [
        "「Dead Canary」は、多くの[オンラインカジノ](https://casinotsu.com/)でプレイ可能ですが、特におすすめのサイトをいくつかご紹介します。これらのカジノでは、[初回登録ボーナス](https://casinotsu.com/bonuses/welcome-bonus) や[フリースピン](https://casinotsu.com/free-spins) などの特典を利用できる場合もありますので、ぜひチェックしてみてください。CasinoTsu 推薦の優良カジノを厳選いたしました。",
      ],
      bullets: [
        "【ジャパカジ限定ボーナス情報】",
        "カジノシークレット: ジャパカジ登録で入金不要ボーナス$35！",
        "インターカジノ: ジャパカジ登録で登録フリースピン150回分（30ドル相当）！",
        "カジノエックス: ジャパカジ限定入金不要ボーナス4,500円！",
        "ベットレベルズ: Pragmatic Playの人気スロット「Fortune Hit ‘N’ Roll」の入金不要フリースピン20回分！",
        "→ [オンカジの入金ボーナス](https://casinotsu.com/bonuses) や登録ボーナスは他にもたくさん！[最新オンラインカジノ](https://casinotsu.com/new-casinos) をチェック！",
      ],
    },
    {
      heading: "ベースゲーム",
      paragraphs: [
        "**ワイルドマイニング (Wild Mining)**:\nベースゲーム中に、同一シンボルが斜め（ダイアゴナル）に3〜5つ揃った際に発動します。この揃ったシンボルがダイナマイトワイルドに変化し、周囲のシンボルを爆発させて連鎖を誘発します。シンボルが5つ揃うと、3つのダイナマイトが爆発し、リールが拡大されるとともに配当の連鎖が期待できます。この機能は、勝利の組み合わせを形成せずにシンボルが揃った場合でも発動し、連続したリスピン（collapse）によって追加の行がアンロックされることがあります。",
        "**Xボム ワイルドマルチプライヤー (xBomb Wild Multiplier)**:\nランダムに出現するダイナマイトシンボル（XBomb）は、スキャッター以外の全てのシンボルの代わりとなり、ワイルドとして機能します。配当成立時にXBombが爆発すると、周囲のシンボルをX字型に吹き飛ばし、マルチプライヤーを増加させます。さらに、各xBombの爆発ごとに、リール上部にある+1マルチプライヤーが追加されます。",
        "**スキャッター (Scatter)**:\n金または銀の鳥かごに入ったカナリアがスキャッターシンボルです。これらのスキャッターが3つ以上出現すると、フリースピン（ボーナスステージ）が発動します。",
        "**Xベット (XBet)**:\nNolimit City独自の機能で、通常ベット額に40%を追加することで、スキャッターシンボルの出現確率を高めることができます。これにより、ボーナスステージへの到達を早めることが期待できます。また、Xベットを有効にすると、配当成立時にリールに配置されたバリア（柵）が解除されやすくなります。",
        "**カスケード（連鎖）/ コラプス**:\n勝利したシンボルは爆発して消滅し、新しいシンボルが上から落ちてきます（カスケード/コラプス）。これにより、一度のスピンで複数回の配当成立が期待できます。ワイルドマイニング機能が連続して発動し、勝利コンボを形成せずにシンボルが揃うと、リールが徐々に拡大していくこともあります。",
      ],
    },
    {
      heading: "フリースピン（ボーナスステージ）",
      paragraphs: [
        "フリースピンは、スキャッターシンボルを3つ揃えるか、スロット左側の星型アイコン（🌟）から直接購入することで開始できます。購入時には3つのオプションがあります。CasinoTsuは、それぞれのオプションを詳細に解説いたします。",
      ],
      table: {
        columns: ["スピンフィーチャーと固定シンボル", "購入額", "詳細"],
        rows: [
          ["通常フリースピン（シルバーの鳥かご×3）", "ベット額の68倍", "シルバーのカナリア（マルチプライヤー）がリールに固定されます。リールは **4-3-4-3-4-3-4** の構成になり、配当獲得のチャンスが増加します。"],
          ["ゴールデンフリースピン（シルバーの鳥かご×2、ゴールドの鳥かご×1）", "ベット額の400倍", "ゴールドのカナリア（リール全体からマルチプライヤーを回収）とシルバーのカナリアが固定されます。リール構成は通常フリースピンと同様です。"],
          ["ラッキードロー（何が出てくるかはお楽しみ）", "ベット額の284倍", "通常フリースピンとゴールデンフリースピンのいずれかがランダムに発動します。"],
        ],
      },
      bullets: [
        "🔥 当たりシンボルがどんどん画面を埋め尽くす白熱フィーチャー！[ホールド＆ウィン機能完全ガイド👈](https://casinotsu.com/slots/hold-and-win)",
        "**☑️ 固定シンボル (Collection Items)**",
        "フリースピン中は、鳥かごに入ったカナリア（シルバー/ゴールド）、コイン、マルチプライヤー、爆弾（Bomb）、ガス（Gas）、ネズミ（Rat Enhancer）、ドワーフ（Dwarf Enhancer）、アップグレード（Upgrade）といった様々なシンボルが登場し、リールに固定されます。",
        "*   **シルバーカナリア**: 1マス離れた場所からマルチプライヤーを回収します。",
        "*   **ゴールドカナリア**: リール全体からマルチプライヤーを回収します。",
        "*   **ネズミ**: カナリアのマルチプライヤーを回収し、その一部を別のカナリアに分配します。",
        "*   **ドワーフ**: カナリアのマルチプライヤーを回収します。",
        "**☑️ ボールトシステム (Vault System)**",
        "フリースピン中は、リールの四隅にロックされた金庫（Vault）が出現します。これらの金庫は、隣接するダイナマイト（xBomb）が爆発することでロックが解除され、中に貯められた賞金（コインやマルチプライヤー）を獲得できます。xBombの爆発は、スピン回数を3回リセットする効果もあり、ボーナスラウンドの継続を助けます。",
        "**☑️ リスピン (Respin)**",
        "ダイナマイト（xBomb）や毒（Gas）シンボルが爆発すると、それに巻き込まれたカナリアが「死亡」し、そのマルチプライヤーが回収されます。この過激な演出もNolimit Cityならではの特徴です。CasinoTsuは、このダイナミックなゲーム展開を皆様にお伝えしたく存じます。",
      ],
    },
    {
      heading: "プロバイダー情報",
      paragraphs: [
        "**Dead Canary** は、革新的なスロットゲームで知られる **Nolimit City（ノーリミット・シティ）** によって開発されました。CasinoTsuは、この信頼できるプロバイダーの情報を詳細に解説いたします。",
      ],
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["開発会社", "Nolimit City"],
          ["ライセンス", "マルタ、ルーマニア、イタリア、デンマーク、スウェーデン、スペイン、イギリス、ギリシャ、エストニア、ラトビア、オランダ、オンタリオ（カナダ）など、多数の国でライセンスを取得。"],
          ["リリース日", "2022年12月20日"],
        ],
      },
      bullets: [
        "**他の人気作品**:",
        "*   **Fire in the Hole**: 炭鉱をテーマにした、Nolimit Cityの代表作の一つ。Dead Canaryはこのシリーズの後継機とも言われています。",
        "*   **San Quentin xWays**: 刑務所が舞台の、非常に高いボラティリティを持つ人気機種。",
        "*   **Mental**: ホラーテーマで、複雑なフィーチャーと高配当が魅力。",
        "*   **Tombstone R.I.P.**: ワイルドウエストが舞台の、こちらも高ボラティリティ機種。",
        "Nolimit Cityは、独自のxWays、xNudge、xBombといったメカニクスを駆使し、ユニークでエキサイティングなゲーム体験を提供しています。CasinoTsuは、常に最新の技術と独創性を追求する同社の姿勢を高く評価しております。",
      ],
    },
    {
      heading: "グラフィック・サウンド",
      bullets: [
        "*   **グラフィック**: Nolimit Cityらしい、ダークで重厚感のあるビジュアルデザインが特徴です。炭鉱の暗闇と、爆発やキャラクターの不気味な表情が、ゲームの緊張感を高めています。",
        "*   **モバイル対応**: PC、タブレット、スマートフォンなど、あらゆるデバイスで快適にプレイできるように最適化されています。[モバイルカジノ](https://casinotsu.com/mobile) でも問題なく楽しめます。",
        "*   **サウンド**: 陰鬱で緊迫感のあるBGMと、爆発音、キャラクターのボイスなどが融合し、ダークな世界観を巧みに表現しています。効果音も臨場感があり、ゲームへの没入感を深めます。CasinoTsuは、これらの要素が一体となり、プレイヤーを「Dead Canary」の世界へと深く引き込むと分析しております。",
      ],
    },
    {
      heading: "モバイル対応",
      paragraphs: [
        "「Dead Canary」は、最新のHTML5技術を使用して開発されているため、スマートフォンやタブレットなどのモバイルデバイスで、PCと同様に高品質なグラフィックとスムーズなゲームプレイを楽しむことができます。特別なアプリのダウンロードは不要で、お使いのデバイスのウェブブラウザから直接アクセスしてプレイできます。CasinoTsuは、いつでもどこでも手軽にプレイできる環境を高く評価しています。",
      ],
    },
    {
      heading: "戦略・攻略法",
      paragraphs: [
        "「Dead Canary」は非常に高いボラティリティを持つため、戦略的なプレイが重要になります。CasinoTsuは、皆様の健全なプレイを支援するため、以下の戦略と攻略法をご提案いたします。",
      ],
      bullets: [
        "**ベット戦略**:",
        "*   **資金管理**: 高ボラティリティ機種なので、一回のスピンで大きく変動する可能性があります。事前にプレイ資金の上限を決め、それに沿ったベット額を設定しましょう。 CasinoTsu は、常に[責任あるギャンブル](https://casinotsu.com/info/responsible-gambling) を推奨いたします。",
        "*   **ベット額の調整**: 大きな勝利を狙う場合は高めのベットも有効ですが、リスクも高まります。少額ベットで回転数を稼ぎ、フィーチャー突入を待つ戦略も考えられます。",
        "*   **Xベットの活用**: スキャッター出現確率を上げるXベットは、フリースピンへの到達を早めるのに役立ちます。ただし、追加コストがかかるため、資金状況と相談しながら利用しましょう。",
        "**フィーチャー活用法**:",
        "*   **ワイルドマイニングの活用**: ベースゲーム中にワイルドマイニングが連続して発動し、リールが拡大されると、配当成立のチャンスが大きく広がります。このフィーチャーは、デモプレイなどで感覚を掴んでおくと良いでしょう。",
        "*   **フリースピンの購入**: 高額ですが、直接フリースピンに突入できるボーナス購入機能は、時間がない場合や一刻も早くボーナスラウンドを体験したい場合に有効です。特に「ゴールデンフリースピン」は高配当に期待できますが、コストも高いため慎重に検討しましょう。",
        "*   **金庫（Vault）の解除**: フリースピン中にxBombをうまく利用し、金庫のロックを解除することが高配当への鍵となります。",
        "**注意点**:",
        "*   **高ボラティリティ**: 短時間で大きく勝つこともあれば、大きく負ける可能性もあります。一喜一憂せず、冷静にプレイを続けることが大切です。",
        "*   **RTPの変動**: カジノによってRTPが異なる場合があります。プレイ前に確認することをおすすめします。 CasinoTsu は、正確な情報提供に努めております。",
        "*   **デモプレイの活用**: 実際の資金を使う前に、無料デモプレイでゲームの仕組みやフィーチャーの感覚を掴んでおくことを強く推奨します。",
      ],
    },
    {
          name: "Money Trainシリーズ",
          provider: "Relax Gaming",
          description: "特殊なボーナスラウンド（Money Cart Bonus Round）で高配当を狙う人気シリーズ。",
          href: "/slots/money-train-3",
        },
        {
          name: "Jammin' Jarsシリーズ",
          provider: "Push Gaming",
          description: "クラスターペイ方式で、ワイルドシンボルが移動しながらマルチプライヤーを蓄積していくゲーム性。",
          href: "/slots/jammin-jars-2",
        },
      ],
    },
    {
      heading: "まとめ",
      paragraphs: [
        "「Dead Canary」は、Nolimit Cityらしい過激な演出と、最大65,000倍という圧倒的なポテンシャルを秘めたスロットです。ワイルドマイニング、XBomb、そしてフリースピン中の多彩なフィーチャーが、プレイヤーを飽きさせないエキサイティングな体験を提供します。CasinoTsuは、このゲームが提供する興奮と戦略性の融合を高く評価しております。",
        "**こんなプレイヤーにおすすめ！**",
        "*   **高ボラティリティ機種が好きなプレイヤー**: 一撃必殺の興奮を味わいたい方。",
        "*   **Nolimit City社のスロットが好きなプレイヤー**: 独特の世界観とゲーム性を楽しめる方。",
        "*   **戦略的なプレイを楽しみたいプレイヤー**: 資金管理やフィーチャー活用を駆使したい方。",
        "ただし、その高いボラティリティゆえに、初心者の方やリスクを避けたい方には少しハードルが高いかもしれません。プレイする際は、デモモードで十分にゲームを理解してから、自己責任のもとで楽しむことをお勧めします。CasinoTsuは、皆様の安全で楽しいカジノ体験を第一に考えております。",
        "**🎰バリエーション豊富なスロットはマストプレイ！[オンラインスロットの基礎知識から最新機種情報まで1ページで丸わかり！](https://casinotsu.com/slots)**",
      ],
    },
    {
      heading: "悪い顔選手権？悪そうなオジサンが登場するスロット",
      table: {
        columns: ["スロット名", "プロバイダー", "詳細"],
        rows: [
          ["ブラッド・サッカーズ", "NetEnt", "顔色の悪い吸血鬼が登場。ローボラティリティで遊びやすい。"],
          ["クラック・ダ・バンク", "Booming Games", "囚人と警察官が登場するホールド＆ウィン機種。演出が派手。"],
          ["マネー・トレイン", "Relax Gaming", "コレクト式ボーナスラウンドで高配当を狙える。シリーズ作品も人気。"],
        ],
      },
      paragraphs: [
        "CasinoTsuは、個性的なキャラクターが登場するスロットも積極的にご紹介いたします。",
      ],
    },
  ],
  prosCons: {
    pros: [
      "最大65,000倍のポテンシャルを秘めた高配当機種",
      "ワイルドマイニング、XBombなどユニークなフィーチャー",
      "フリースピン中の多様なフィーチャーと金庫システム",
      "Nolimit Cityらしいダークで重厚な世界観",
      "モバイルデバイスでのプレイに最適化",
    ],
    cons: [
      "非常に高いボラティリティのため、リスクが高い",
      "RTPはカジノやプレイ方法により変動する",
      "初心者にはやや複雑で難しいと感じる可能性がある",
    ],
  },
  faq: [
    {
      q: "デッド・キャナリーの最大配当は何倍ですか？",
      a: "デッド・キャナリーの最大配当は、ベット額の **65,000倍** です。 CasinoTsu は、この驚異的な数字に注目しています。",
    },
    {
      q: "デッド・キャナリーのRTP（還元率）はどれくらいですか？",
      a: "ベースゲーム中のRTPは、カジノによって **92.11%から96.02%** の範囲で変動します。フリースピン中やフィーチャー購入時には、さらに上昇することがあります（最大96.39%）。正確な数値は、プレイするカジノのスロット内情報をご確認ください。CasinoTsuは、正確さが第一。興奮はその次。",
    },
    {
      q: "デッド・キャナリーは無料でプレイできますか？",
      a: "はい、多くのオンラインカジノで[無料デモバージョン](https://casinotsu.com/slots/free)が提供されています。実際の資金を使う前に、ゲームのルールやフィーチャーを試すことができます。Bigwinboard.com、VegasSlotsOnline.com、Slots Templeなどのサイトでもプレイ可能です。CasinoTsuは、デモプレイの活用を推奨いたします。",
    },
    {
      q: "デッド・キャナリーはどのようなテーマのスロットですか？",
      a: "炭鉱を舞台にしたダークファンタジーなテーマのスロットです。カナリアが危険を知らせる役割を担いますが、このゲームでは爆発に巻き込まれてしまうことも…。CasinoTsuは、このダークな世界観がプレイヤーを魅了すると分析しています。",
    },
    {
      q: "フリースピン中にリール構成はどうなりますか？",
      a: "フリースピン中は、ベースゲームの **3-4-3-4-3-4** からさらに拡大し、 **4-3-4-3-4-3-4** の構成になります。これにより、ペイライン数が増加し、配当獲得のチャンスが広がります。 CasinoTsu は、このリール拡張がゲームをよりエキサイティングにすると評価しています。",
    },
    {
      q: "「Fire in the Hole」と比較してどうですか？",
      a: "「Dead Canary」は、「Fire in the Hole」の後継機として位置づけられることもありますが、一部のプレイヤーからは「Fire in the Hole」ほどのインパクトや完成度に達していないという意見もあります。しかし、「Dead Canary」独自のフィーチャーやゲーム性も魅力的であり、どちらが良いかはプレイヤーの好みによります。[Fire in the Hole](https://casinotsu.com/slots/fire-in-the-hole)のWild Mining機能は、ベースゲームを特に面白くしていると評価されることが多いです。CasinoTsuは、両作品ともNolimit City社の意欲作として、それぞれに異なる魅力があると認識しております。",
    },
  ],
  cta: {
    text: "今すぐ Dead Canary をプレイ！",
    href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fdead-canary",
  },
  breadcrumbs: [
    { label: "CasinoTsu", href: "/" },
    { label: "スロット", href: "/slots" },
    { label: "Dead Canary", href: "/slots/dead-canary" },
  ],
  tableOfContents: [
    { label: "Dead Canary (デッド・キャナリー) スロット攻略【2025年版】", href: "#" },
    { label: "導入・概要", href: "#導入・概要" },
    { label: "ゲーム基本情報", href: "#ゲーム基本情報" },
    { label: "どこで遊べるか：Dead Canary をプレイできるカジノ", href: "#どこで遊べるか：Dead Canary-をプレイできるカジノ" },
    { label: "ゲーム特徴・フィーチャー", href: "#ゲーム特徴・フィーチャー" },
    { label: "ベースゲーム", href: "#ベースゲーム" },
    { label: "フリースピン（ボーナスステージ）", href: "#フリースピン（ボーナスステージ）" },
    { label: "プロバイダー情報", href: "#プロバイダー情報" },
    { label: "グラフィック・サウンド", href: "#グラフィック・サウンド" },
    { label: "モバイル対応", href: "#モバイル対応" },
    { label: "戦略・攻略法", href: "#戦略・攻略法" },
    { label: "類似ゲーム", href: "#類似ゲーム" },
    { label: "まとめ", href: "#まとめ" },
    { label: "悪い顔選手権？悪そうなオジサンが登場するスロット", href: "#悪い顔選手権？悪そうなオジサンが登場するスロット" },
    { label: "よくある質問 (FAQ)", href: "#よくある質問-(FAQ)" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/dead-canary" />;
}
