import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Blobsters Clusterbuster",
  hero: {
    title: "Blobsters Clusterbuster",
    subheading: "ブロッブスターズ・クラスターバスター",
    description: "カスケードスロット「ブロッブスターズ・クラスターバスター」は、ユニークな「クラスターバスター」メカニズムと可愛らしいエイリアンたちが魅力のゲームです。 CasinoTsuが、その詳細を徹底レビューします！",
    score: 4.3,
    scoreMax: 5,
    rtp: "95.7%",
    maxMultiplier: "x7,517",
    provider: "Red Tiger",
    releaseDate: "2023年2月16日",
    volatility: "中〜高",
    reels: "9",
    paylines: "クラスターペイ",
    minBet: "$0.10",
    maxBet: "$60",
    slotImageSrc: "/slots/blobsters-clusterbuster.jpg",
    highlights: [
      "クラスターバスターメカニズム",
      "段階的にアンロックされる3つのフィーチャー",
      "フリースピン中のマルチプライヤー",
      "可愛いエイリアンキャラクター",
    ],
    watchouts: [
      "ベット額変更でフィーチャーアンロックがリセットされる可能性あり",
      "RTPが平均よりやや低め",
    ],
  },
  featuredCasino: {
    name: "2upカジノ",
    logo: "/assets/casino/2up.png",
    href: "/reviews/2up",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
  },
  casinos: [
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "独自コインも利用可能！ 最新クリプトカジノ",
      rating: 4,
      tagline: "ベットゴート",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "2up",
      logo: "/images/casino/2up_375x375.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      rating: 4,
      tagline: "2アップカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "1win",
      logo: "/images/casino/1win_375x375.png",
      href: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      rating: 4,
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      rating: 4,
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      rating: 4,
      tagline: "Bitz",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      rating: 4,
      tagline: "Wikibet",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      rating: 4.5,
      tagline: "Katsuwin",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      rating: 4,
      tagline: "Sushi Casino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "2024年11月オープンの最新オンカジを徹底レビュー！",
      rating: 4,
      tagline: "Parimatch",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Bets.io",
      logo: "/images/casino/bets-io_375x375-1.png",
      href: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      rating: 4,
      tagline: "Bets.io",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "500フリースピンが嬉しいクリプトカジノ♪",
      rating: 4,
      tagline: "Duelbits",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "スポーツベットだけじゃない！",
      rating: 4.5,
      tagline: "Sportsbet.io",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      rating: 4,
      tagline: "Shuffle",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "ウェルカムオファーやボーナスに賭け条件なし♪",
      rating: 4.5,
      tagline: "Winz",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "セルティックFCのスポンサーカジノ",
      rating: 4,
      tagline: "Dafabet",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "独自トークンもある仮想通貨カジノ♪",
      rating: 4,
      tagline: "Lucky Block",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Flush Casino",
      logo: "/images/casino/Flush_375x375-1.png",
      href: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "今年大注目のクリプトカジノ",
      rating: 4,
      tagline: "Flush Casino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      rating: 4.5,
      tagline: "Queen Casino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      rating: 4,
      tagline: "Roobet",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Casino Sky",
      logo: "/images/casino/casino-sky_375x375.png",
      href: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "日本のオンカジ業界プロが運営する期待のカジノ！",
      rating: 4,
      tagline: "Casino Sky",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "ボーナス最大1BTCの仮想通貨カジノ！",
      rating: 3.5,
      tagline: "Mega Dice",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Fresh Casino",
      logo: "/images/casino/fresh_375x375.png",
      href: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "6,000種類以上のゲームで遊びたい放題！",
      rating: 4,
      tagline: "Fresh Casino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      rating: 4,
      tagline: "BC.Game",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Stake",
      logo: "/images/casino/stake_375x375-1.png",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      rating: 4,
      tagline: "Stake",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      rating: 4.5,
      tagline: "Wonder Casino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Yuugado",
      logo: "/images/casino/yuugado_375x375-1.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      rating: 4.5,
      tagline: "Yuugado",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Lilibet",
      logo: "/images/casino/lilibet_375x375.png",
      href: "https://go.casinotsu.com/go/lilibet:lilibet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      rating: 4,
      tagline: "Lilibet",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lilibet:lilibet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Konibet",
      logo: "/images/casino/konibet_375x375.png",
      href: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "パチンコ・パチスロが遊べるオンラインカジノ！",
      rating: 4.5,
      tagline: "Konibet",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "独自システムのお得なキャッシュバックあり！",
      rating: 4,
      tagline: "Casino Me",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "ボーナス充実！スポーツベットにも最適カジノ♪",
      rating: 4,
      tagline: "Kakeyo",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      rating: 4.5,
      tagline: "Mystino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "実は20年以上歴史のあるカジノはココ！",
      rating: 4.5,
      tagline: "InterCasino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "アジアNo.1を豪語するオンカジはここだ！",
      rating: 4,
      tagline: "Empire777",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "https://go.casinotsu.com/go/winunique:winunique?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      rating: 4,
      tagline: "WinUnique",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winunique:winunique?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "オンカジといえば、やっぱりベラジョン！",
      rating: 4.5,
      tagline: "Vera&John",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "元祖仮想通貨カジノ！",
      rating: 4.5,
      tagline: "Bitcasino.io",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Casino-X",
      logo: "/images/casino/casino-x_375x375-1.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      rating: 4.5,
      tagline: "Casino-X",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      rating: 4.5,
      tagline: "Casitabi",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
      bonus: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      rating: 4.5,
      tagline: "Eldoah Casino",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
    },
  ],
  gameInfo: {
    intro: "ブロッブスターズ・クラスターバスター（Blobsters Clusterbuster）は、キュートなエイリアンたちが地球征服を企むユニークなテーマのカスケードスロットです！🎰\nこのスロットは、人気のゲームプロバイダーである Red Tiger社 が開発しました。🐯 トラのマークでおなじみですね！\n最大の特徴は、グリッド中央の3×3シンボルエリアを取り囲む「クラスターバスター」と呼ばれる仕組み。ここで配当が成立すると、特別なフィーチャーがアンロックされるんです。\n中〜高ボラティリティ に設定されており、特にボーナスステージでは 大爆発の可能性 を秘めています。そして何より、登場するエイリアンたちの愛らしいデザインがプレイヤーを惹きつけます。😍\nそれでは、この魅力的な ブロッブスターズ・クラスターバスター を詳しくレビューしていきましょう！🚀",
    basicInfo: {
      rtp: "95.70%",
      volatility: "中〜高",
      reels: "9",
      paylines: "クラスターペイ",
      minBet: "$0.10 〜 $0.20",
      maxBet: "$60 〜 $100",
      provider: "Red Tiger",
      releaseDate: "2023年2月16日",
    },
  },
  payoutTable: {
    title: "絵柄／シンボル",
    symbols: [
      {
        name: "エイリアン（大）",
        payout5: "$200",
      },
      {
        name: "エイリアン（中）",
        payout5: "$100",
      },
      {
        name: "エイリアン（小）",
        payout5: "$75",
      },
      {
        name: "トランプ A",
        payout5: "$40",
      },
      {
        name: "トランプ K",
        payout5: "$30",
      },
      {
        name: "トランプ Q",
        payout5: "$25",
      },
      {
        name: "トランプ J",
        payout5: "$20",
      },
    ],
    notes: [
      "賭け額1ドルあたりの配当は以下の通りです",
      "高配当シンボルは、個性豊かな エイリアン たちです。",
      "低配当シンボルは、おなじみのトランプの絵柄（A, K, Q, J）が採用されています。",
    ],
  },
  features: {
    title: "ゲーム機能",
    items: [
      {
        name: "クラスターバスター",
        description: "中央の3×3シンボルエリアを取り囲むシンボルを消去することで、3つのフィーチャー（アップグレーダー、フレンジー、スーパーサイズ）を段階的にアンロックします。",
        icon: "/images/blobsters-clusterbuster-features.png",
      },
      {
        name: "アップグレーダー",
        description: "8個から24個の低配当シンボルが、高配当シンボルへとアップグレードされます。",
      },
      {
        name: "フレンジー",
        description: "5個から20個の通常シンボルが、ワイルドシンボルに変換されます。フリースピン中は最大31個のワイルドシンボルに変換されることもあります。",
      },
      {
        name: "スーパーサイズ",
        description: "高配当シンボル、またはワイルドシンボルが3×3の大きなシンボルに拡大します。",
      },
      {
        name: "インベーダースピン（フリースピン）",
        description: "ベースゲームでフィーチャーが全てアンロックされた状態で、さらに周りのシンボルが全て消滅すると、10回のフリースピンを獲得できます。フリースピン中は、3つのフィーチャーがランダムに発動し、配当成立ごとに3回の追加スピンと3倍のマルチプライヤー（最大12倍まで上昇）を獲得できます。",
        icon: "/images/blobsters-clusterbuster-freespins.png",
      },
      {
        name: "カスケードシステム",
        description: "配当成立後、そのシンボルは消滅し、上から新しいシンボルが落ちてくる連鎖が発生します。",
      },
    ],
  },
  sections: [
    {
      heading: "ブロッブスターズ・クラスターバスターの比較情報",
      paragraphs: [
        "ブロッブスターズ・クラスターバスターは、同じRed Tiger社の「Clusterbuster」シリーズに属するゲームと比較すると、[Dragon Clusterbuster](https://casinotsu.com/slots/dragon-clusterbuster) よりも高い勝利ポテンシャルを持っています。しかし、シリーズ特有の「Clusterbuster」技術における劇的な進化というよりは、既存のシステムをベースに、より高い勝利を目指せるように調整されていると言えるでしょう。CasinoTsuは、このような進化を常に注目しています。",
      ],
    },
    {
      heading: "ブロッブスターズ・クラスターバスター  \| レビューの流れ",
      paragraphs: [
        "**ブロッブスターズ・クラスターバスター** の魅力を余すところなくお伝えします！ CasinoTsuが、一つ一つ丁寧にご説明いたします。😆",
      ],
      bullets: [
        "ゲームのテーマ、シンボル、配当について",
        "注目のゲームフィーチャーとボーナスラウンド",
        "[カスケードスロット](https://casinotsu.com/slots/cascade-slots) としての特徴",
        "グラフィックとサウンドデザイン",
      ],
    },
    {
      heading: "ブロッブスターズ・クラスターバスターで遊べるオンラインカジノ＆ボーナス",
      paragraphs: [
        "**ブロッブスターズ・クラスターバスター** は、以下のオンラインカジノでプレイ可能です！ CasinoTsuが厳選した、お得なボーナス情報もチェックしてくださいね。",
      ],
      table: {
        columns: ["カジノ名", "オファー"],
        rows: [
          ["ワンダーカジノ", "賭け条件1倍！ [ワンダーカジノの入金不要ボーナス](https://casinotsu.com/bonuses/no-deposit) $40"],
          ["バルカンベガス", "[バルカンベガスのボーナス](https://casinotsu.com/reviews/vulkanvegas) 最大100,000円+フリースピン最大125回分"],
          ["コニベット", "[コニベットの入金不要ボーナス](https://casinotsu.com/bonuses/no-deposit) $20＆キャッシュスピン50回"],
        ],
      },
      notes: [
        "[**入金不要ボーナス**](https://casinotsu.com/bonuses/no-deposit) はジャパカジ限定のものもあります！🎁 CasinoTsuでは、常に最新かつお得な情報を皆様にお届けできるよう努めております。",
        "他にもたくさんのボーナスが用意されていますので、お気に入りの [オンラインカジノ](https://casinotsu.com/) を見つけて、お得にプレイしてくださいね💝",
        "**🤩ジャパカジ限定ボーナスも盛りだくさん！** [全てのお得なオファーを今すぐチェック！](https://casinotsu.com/offers)！",
      ],
    },
    {
      heading: "ルール、シンボル、ペイアウトについて",
      paragraphs: [
        "ここでは、[**カジノ・デイズ**](https://casinotsu.com/reviews/casino-days) のPC版を参考に、スロットの詳細を解説します！ CasinoTsuは、正確な情報提供を心がけております。",
      ],
    },
    {
      heading: "配当成立の仕組み",
      paragraphs: [
        "このスロットは **9×9のグリッド** で展開されます。ペイラインは固定されておらず、**同一シンボルが5つ以上、縦または横に隣接** することで配当が成立する **クラスターペイシステム** を採用しています。配当成立後、そのシンボルは消滅し、上から新しいシンボルが落ちてくる **カスケード（連鎖）** が発生します。この連鎖によって、一度のスピンで複数回の配当獲得が期待できます。",
      ],
      image: { src: "/images/blobsters-clusterbuster-payline.png", alt: "ブロッブスターズ・クラスターバスター｜パイライン" },
    },
    {
      heading: "ベット額の設定",
      paragraphs: [
        "ベットサイズは **$0.10から$60** の範囲で調整可能です。ベット額の変更は、スロット画面の左下にあるボタンから行えます。",
        "**注意点:** 複数の情報源によると、**最小ベット額は$0.10または$0.20**、**最大ベット額は$10.00、$60.00、$100.00など、カジノによって異なる**場合があります。プレイする際は、お利用のカジノで正確なベット範囲をご確認ください。CasinoTsuは、正確な情報提供に努めます。",
        "**※重要な注意点:** **ベット額を変更すると、それまでにアンロックされていたフィーチャーがリセットされる可能性があります。** 連続してフィーチャーを解除したい場合は、ベット額の変更には十分ご注意ください。CasinoTsuは、プレイヤーの皆様が有利にゲームを進められるよう、これらの注意点を共有いたします。",
      ],
      image: { src: "/images/blobsters-clusterbuster-bet-amount.png", alt: "ブロッブスターズ・クラスターバスター｜ベット額" },
      notes: [
        "💴 **日本円でBlobsters Clusterbusterを遊ぶならここ👇 CasinoTsu 推薦！**",
        "[Vulkan Vegas（バルカンベガス）レビューページをチェック](https://casinotsu.com/reviews/vulkanvegas)",
      ],
    },
    {
      heading: "オートプレイオプション",
      paragraphs: [
        "オートプレイ機能は、画面左下の **『自動』** ボタンから設定できます。スピン回数に加えて、**ロスリミット（損失上限額）** も設定できるため、計画的なプレイを心がけましょう💡 CasinoTsuは、[責任あるギャンブル](https://casinotsu.com/info/responsible-gambling) を推奨しています。",
      ],
      image: { src: "/images/blobsters-clusterbuster-autoplay.png", alt: "ブロッブスターズ・クラスターバスター｜オートプレイ" },
    },
    {
      heading: "ブロッブスターズ・クラスターバスターのRTP（還元率）",
      paragraphs: [
        "[**還元率（RTP）**](https://casinotsu.com/slots/high-rtp) は **95.70%** です。これは一般的なオンラインスロットの平均値（約96%）と比較すると、やや低めですが、ゲームの持つユニークなフィーチャーや高いポテンシャルを考慮すると、 CasinoTsuとしては許容範囲と考えております。正確さが第一。興奮はその次。",
      ],
    },
    {
      heading: "変動率（ボラティリティ）",
      paragraphs: [
        "[**ボラティリティ**](https://casinotsu.com/slots/high-volatility) は **中〜高** とされています。これは、ベースゲームでも比較的小さな勝利が頻繁に発生する一方で、大きな勝利（ビッグウィン）を狙うには、特にフリースピン中のマルチプライヤーの恩恵が重要になることを意味します。",
      ],
    },
    {
      heading: "ジャックポット機能／最大賞金",
      paragraphs: [
        "ブロッブスターズ・クラスターバスターには、残念ながら [**ジャックポット機能**](https://casinotsu.com/slots/progressive-jackpot) は搭載されていません。しかし、**最大配当倍率はx7,517** と非常に高く、ジャックポットに匹敵するような大きな勝利を得られる可能性があります🎉。CasinoTsuは、このような高配当の可能性も注視しています。",
      ],
      notes: [
        "**💰一攫千金を夢見てプレイ！** [ジャックポットスロット好きはこちらをチェック🎉](https://casinotsu.com/slots/progressive-jackpot)",
      ],
    },
    {
      heading: "ベースゲームとフィーチャーのアンロック",
      paragraphs: [
        "このスロットの最大の特徴は、ベースゲーム中に **3つの特別なフィーチャー** が **段階的にアンロック** されていく点です💪。CasinoTsuは、この段階的な解除システムに注目しています。",
        "これらのフィーチャーは、ゲーム開始時には **ロック** された状態（画面右上、黄色枠で表示）です。",
        "グリッドの中央にある3×3の特殊シンボル（ポニョのような見た目、赤枠）の周囲にあるシンボルが、配当成立によって全て消滅すると、**1種類ずつ順番にフィーチャーがアンロック（解除）** されていきます。",
      ],
      image: { src: "/images/blobsters-clusterbuster-features.png", alt: "ブロッブスターズ・クラスターバスター｜フィーチャー" },
      bullets: [
        "アップグレーダー",
        "フレンジー",
        "スーパーサイズ",
      ],
      notes: [
        "可愛いエイリアンが、勝利のチャンスを広げてくれます！(\*‘ω‘ \*)",
        "😍 **CasinoTsu 推薦:** 対応速度No.1をうたうカジノでジャパカジ限定登録ボーナスをゲット！",
        "[ワンダーカジノのボーナス](https://casinotsu.com/reviews/wonder-casino) でお得にブロッブスターズ・クラスターバスターで遊ぼう！",
      ],
    },
    {
      heading: "フィーチャーのアンロックとリセットについて",
      paragraphs: [
        "重要な注意点:",
        "フィーチャーのアンロックは、そのゲームセッション中にのみ有効です。**ベット額を変更すると、それまでにアンロックされたフィーチャーがリセットされる場合があります。** 連続してフィーチャーを解除し、有利な状況を維持したい場合は、ベット額の変更を慎重に行うか、同じベット額でプレイを続けることをお勧めします。CasinoTsuは、プレイヤーの皆様に公平で安全なゲーム体験を提供するため、このような重要な情報を丁寧にお伝えいたします。",
        "**全てのフィーチャーがアンロックされた後:**",
        "3つのフィーチャー全てがアンロックされると、ベースゲーム中に **3種類のフィーチャーがランダムに発動** するようになります。CasinoTsuは、このランダム性の面白さにも注目しています。",
      ],
      image: { src: "/images/blobsters-clusterbuster-features-2.png", alt: "ブロッブスターズ・クラスターバスター｜フィーチャー2" },
    },
    {
      heading: "ボーナスステージ（インベーダースピン）",
      paragraphs: [
        "ブロッブスターズ・クラスターバスターには、残念ながら [**ボーナス購入機能**](https://casinotsu.com/slots/bonus-buy) は搭載されていません。ボーナスステージへの突入は、ゲームプレイを通じて狙う必要があります。CasinoTsuは、ボーナス購入機能がない場合でも、ゲーム本来の面白さを追求することが大切だと考えています。",
      ],
      image: { src: "/images/blobsters-clusterbuster-freespins.png", alt: "ブロッブスターズ・クラスターバスター｜フリースピン" },
      notes: [
        "インベーダースピン（フリースピン）への突入条件:",
        "ベースゲームで、3×3シンボルエリアの周りのフィーチャーが全てアンロックされた状態で、さらにその周りのシンボルが全て消滅すると、**10回のフリースピン** が獲得できます！ CasinoTsuは、この条件達成の瞬間が醍醐味だと考えます。",
      ],
    },
    {
      heading: "フリースピン中のゲームプレイ",
      paragraphs: [
        "フリースピン中も、ベースゲームと同様に、**3つのフィーチャー（アップグレーダー、フレンジー、スーパーサイズ）がランダムに発動** します🎯。CasinoTsuは、フリースピン中のフィーチャーの連鎖が、大きな勝利への鍵となると見ています。",
      ],
      image: { src: "/images/blobsters-clusterbuster-freespins-2.png", alt: "ブロッブスターズ・クラスターバスター｜フリースピン2" },
      notes: [
        "追加スピンとマルチプライヤーの獲得:",
        "フリースピン中に、中央の3×3シンボル周りで配当が成立し、シンボルが消滅すると、**3回の追加スピン** と **3倍のマルチプライヤー** が獲得できます🎁！",
        "このマルチプライヤーは、連鎖するたびに **7倍、そして最大12倍** まで段階的に上昇していきます。",
        "12倍のマルチプライヤーを獲得できた時の興奮は格別です！ CasinoTsuは、この興奮を皆様にも体験していただきたいと考えております。",
      ],
      image2: { src: "/images/blobsters-clusterbuster-freespins-3.png", alt: "ブロッブスターズ・クラスターバスター｜フリースピン3" },
      conclusion: [
        "ベースゲームでフィーチャーをアンロックしていく過程は、達成感があり、ゲームに深みを与えています。フリースピン中は、マルチプライヤーと追加スピンをうまく活用することで、**x7,517** という最大配当倍率の獲得を目指しましょう🥰！ CasinoTsuは、これらの要素が、このスロットの魅力を高めていると分析しています。",
        "🔑**フリースピン購入が勝利のカギ！？**",
        "[ボーナス購入機能スロットで勝率爆上がりを目指すならここからチェック！](https://casinotsu.com/slots/bonus-buy)",
      ],
    },
    {
      heading: "ブロッブスターズ・クラスターバスターのグラフィックとサウンド",
      paragraphs: [
        "CasinoTsuが、ゲームの細部にまでこだわって分析しました。",
      ],
      table: {
        columns: ["カテゴリ", "詳細"],
        rows: [
          ["グラフィック", "宇宙とエイリアンをテーマにした、ポップで可愛らしいデザイン。フィーチャー発動時のエイリアンのコミカルな動きや表情が魅力的です。"],
          ["モバイル対応", "デスクトップ、タブレット、**スマートフォン** など、あらゆるデバイスに完全対応しています。いつでもどこでも快適にプレイ可能です。 CasinoTsuは、モバイルでのプレイ体験も重視しています。"],
          ["サウンド・BGM", "🛸宇宙空間を思わせるような、近未来的で軽快なBGMがゲームの雰囲気を盛り上げます。効果音も、ペイアウト時などに心地よく響きます。"],
          ["特別フィーチャー", "**クラスターバスター** 🔥<br>中央の3×3エリアを囲むシンボルを消去することで、3つのフィーチャー（アップグレーダー、フレンジー、スーパーサイズ）を段階的にアンロック。全てのフィーチャーを解除し、強力な効果を発揮させましょう！"],
        ],
      },
    },
    {
      heading: "ゲーム中に問題が起こったら？",
      paragraphs: [
        "[**Red Tiger**](https://casinotsu.com/providers/red-tiger) 社のゲーム説明によると、万が一、ソフトウェアの不具合によってゲームプレイに問題が発生した場合、そのゲームにおけるベットおよびゲーム結果は無効とされるとのことです。常に最新のオペレーティングシステムやブラウザを使用することが推奨されています。CasinoTsuは、プレイヤーの皆様が安心してプレイできるよう、このような情報を共有いたします。",
      ],
    },
    {
      heading: "ブロッブスターズ・クラスターバスター｜総評・まとめ",
      paragraphs: [
        "**ブロッブスターズ・クラスターバスター** は、カスケードシステムによるスピーディーな配当成立が爽快なスロットです🤩。CasinoTsuは、このゲームの持つポテンシャルとユニークなゲームプレイを高く評価しています。",
        "**中〜高ボラティリティ** ながらも、フィーチャーアンロックの過程でベースゲーム中も安定して勝利を積み重ねやすく、飽きさせない工夫が凝らされています。",
        "何より、地球征服を企む（？）キュートなエイリアンたちのキャラクターデザインが個性的で、プレイヤーを和ませてくれます。ユニークなゲーム体験を求める方、可愛いエイリアンに癒されたい方には、ぜひ一度プレイしていただきたいスロットです😆💖 CasinoTsuが自信を持って推薦いたします。",
      ],
      notes: [
        "CasinoTsu 推薦:",
        "😍 **登録するだけで$20もらえちゃう！ ジャパカジ限定ボーナスも🎵**",
        "[コニベット（Konibet）のレビューページをチェック✅](https://casinotsu.com/reviews/konibet)",
      ],
    },
    {
      heading: "最近流行ってる？カスケード型スロット",
      paragraphs: [
        "カスケード（連鎖）システムを採用したスロットは、一度のリスピンで複数回の勝利のチャンスがあるため、非常に人気があります。CasinoTsuが、特におすすめのカスケードスロットをいくつかご紹介します。",
      ],
      table: {
        columns: ["スロット名", "詳細"],
        rows: [
          ["[**ギガントゥーンズ (Giga 7s)**](https://casinotsu.com/slots/gigantoonz)", "[**Play’nGO**](https://casinotsu.com/providers/play-n-go) が贈る、大人気「Moon Princess」シリーズの姉妹機。メガシンボルが特徴の **カスケードスロット**！"],
          ["[**スイート・アルケニー2 (Sweet Alchemy 2)**](https://casinotsu.com/slots/sweet-alchemy-2)", "お菓子と魔女が登場する、可愛らしい **カスケードスロット**。 **3段階スピン** 機能が特徴で、連鎖が期待できます (≧▽≦)。"],
          ["[**ムーンプリンセス・トリニティ (Moon Princess Trinity)**](https://casinotsu.com/slots/moon-princess-trinity)", "あの [**ムンプリシリーズ**](https://casinotsu.com/slots/moon-princess) の第4弾！ 爆発力よりも安定感を重視した、初心者にもおすすめの話題作です🌙。"],
        ],
      },
    },
    {
      heading: "よくある質問",
      faq: [
        {
          q: "ベースゲームでアンロックしたフィーチャーは、フリースピン中も有効ですか？",
          a: "はい、有効です。ベースゲームでアンロックされたフィーチャーは、フリースピン中も引き続き機能し、勝利に貢献します。CasinoTsuは、この連動性をゲームの面白さの一つと考えています。",
        },
        {
          q: "ボーナスステージ（インベーダースピン）で追加のスピンを獲得する条件は何ですか？",
          a: "フリースピン中に、スロット中央にある3×3の特殊シンボル（お魚のような見た目）の周りで配当が成立し、シンボルが消滅すると、フリースピンが3回追加されます。CasinoTsuは、この追加スピンの獲得が、さらなる勝利への期待を高めると分析しています。",
        },
      ],
    },
  ],
  similarGames: [
    {
      name: "Giga 7s",
      href: "/slots/gigantoonz",
      provider: "Play'n GO",
      description: "メガシンボルが特徴のカスケードスロット。",
    },
    {
      name: "Moon Princess Trinity",
      href: "/slots/moon-princess-trinity",
      provider: "Play'n GO",
      description: "安定感を重視した、初心者にもおすすめのカスケードスロット。",
    },
  ],
  prosCons: {
    pros: [
      "ユニークなクラスターバスターメカニズム",
      "段階的にアンロックされる3つのフィーチャー",
      "フリースピン中のマルチプライヤーと追加スピン",
      "可愛いエイリアンキャラクターとポップなグラフィック",
      "カスケードシステムによるスピーディーなゲームプレイ",
    ],
    cons: [
      "ベット額変更でフィーチャーアンロックがリセットされる可能性あり",
      "RTPが平均よりやや低め",
      "ボーナス購入機能なし",
    ],
  },
  faq: [
    {
      q: "ベースゲームでアンロックしたフィーチャーは、フリースピン中も有効ですか？",
      a: "はい、有効です。ベースゲームでアンロックされたフィーチャーは、フリースピン中も引き続き機能し、勝利に貢献します。CasinoTsuは、この連動性をゲームの面白さの一つと考えています。",
    },
    {
      q: "ボーナスステージ（インベーダースピン）で追加のスピンを獲得する条件は何ですか？",
      a: "フリースピン中に、スロット中央にある3×3の特殊シンボル（お魚のような見た目）の周りで配当が成立し、シンボルが消滅すると、フリースピンが3回追加されます。CasinoTsuは、この追加スピンの獲得が、さらなる勝利への期待を高めると分析しています。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Blobsters clusterbuster", href: "https://casinotsu.com/slots/blobsters-clusterbuster" },
  ],
  tableOfContents: [
    { label: "ブロッブスターズ・クラスターバスター  | レビューの流れ", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%83%96%E3%83%AD%E3%83%83%E3%83%96%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%BA%E3%83%BB%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%82%B9%E3%82%BF%E3%83%BC%C2%A0|%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%81%AE%E6%B5%81%E3%82%8C" },
    { label: "ブロッブスターズ・クラスターバスターで遊べるオンラインカジノ＆ボーナス", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%83%96%E3%83%AD%E3%83%83%E3%83%96%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%BA%E3%83%BB%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%82%B9%E3%82%BF%E3%83%BC%E3%81%A7%E9%81%8A%E3%81%B9%E3%82%8B%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E3%82%AB%E3%82%B8%E3%83%8E%EF%BC%86%E3%83%9C%E3%83%BC%E3%83%8A%E3%82%B9" },
    { label: "ルール、シンボル、ペイアウトについて", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%83%AB%E3%83%BC%E3%83%AB%E3%80%81%E3%82%B7%E3%83%B3%E3%83%9C%E3%83%AB%E3%80%81%E3%83%9A%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6" },
    { label: "ブロッブスターズ・クラスターバスター | ゲーム機能", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%83%96%E3%83%AD%E3%83%83%E3%83%96%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%BA%E3%83%BB%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%82%B9%E3%82%BF%E3%83%BC%20|%20%E3%82%B2%E3%83%BC%E3%83%A0%E6%A9%9F%E8%83%BD" },
    { label: "ブロッブスターズ・クラスターバスターのグラフィックとサウンド", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%83%96%E3%83%AD%E3%83%83%E3%83%96%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%BA%E3%83%BB%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%82%B9%E3%82%BF%E3%83%BC%E3%81%AE%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%83%E3%82%AF%E3%81%A8%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%C2%A0" },
    { label: "ゲーム中に問題が起こったら？", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%82%B2%E3%83%BC%E3%83%A0%E4%B8%AD%E3%81%AB%E5%95%8F%E9%A1%8C%E3%81%8C%E8%B5%B7%E3%81%93%E3%81%A3%E3%81%9F%E3%82%89%EF%BC%9F" },
    { label: "ブロッブスターズ・クラスターバスター｜総評・まとめ", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E3%83%96%E3%83%AD%E3%83%83%E3%83%96%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%BA%E3%83%BB%E3%82%AF%E3%83%A9%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%90%E3%82%B9%E3%82%BF%E3%83%BC%EF%BD%9C%E7%B7%8F%E8%A9%95%E3%83%BB%E3%81%BE%E3%81%A8%E3%82%81" },
    { label: "最近流行ってる？カスケード型スロット", href: "https://casinotsu.com/slots/blobsters-clusterbuster#%E6%9C%80%E8%BF%91%E6%B5%81%E8%A1%8C%E3%81%A3%E3%81%A6%E3%82%8B%EF%BC%9F%E3%82%AB%E3%82%B9%E3%82%B1%E3%83%BC%E3%83%89%E5%9E%8B%E3%82%B9%E3%83%AD%E3%83%83%E3%83%88" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fblobsters-clusterbuster",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/blobsters-clusterbuster" />;
}
