import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "Happy Apples",
  hero: {
    title: "Happy Apples",
    subheading: "ハッピー・アップル",
    description: "最大100倍のマルチプライヤーや追加スピンで高配当を狙っちゃおう！カワイイお菓子のクラスタースロット徹底レビュー！🍬✨",
    score: 4.6,
    scoreMax: 5,
    rtp: "95.7%",
    maxMultiplier: "x6,186",
    provider: "Red Tiger",
    releaseDate: "2023-03-16",
    volatility: "High",
    reels: "6",
    paylines: "クラスターペイス（ペイラインなし）",
    minBet: "$0.10 - $0.20",
    maxBet: "$50 - $100",
    slotImageSrc: "/slots/happy-apples.jpg",
    highlights: [
      "最大100倍のマルチプライヤー",
      "追加スピンで高配当を狙える",
      "カワイイお菓子のクラスタースロット",
      "クラスターペイスシステム",
      "連鎖（カスケード）機能",
      "フォーチュントゥリー機能",
      "ボーナス購入機能あり",
    ],
    watchouts: [
      "ボラティリティが高めなので、頻繁な小当たりは少なめかもしれません。",
      "RTPはカジノによって異なる場合があるため、プレイ前に確認することをおすすめします。",
      "ジャックポット機能はありません。",
    ],
  },
  featuredCasino: {
    name: "2アップカジノ",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/reviews/2up",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fhappy-apples",
  },
  casinos: [
    {
      name: "ステークカジノ",
      href: "https://casinotsu.com/reviews/stake",
      bonus: "5%レーキバックボーナス",
      freeSpins: undefined,
      wagering: undefined,
      rating: undefined,
      tagline: undefined,
      ctaText: undefined,
      ctaHref: undefined,
    },
    {
      name: "カジノ・エックス",
      href: "https://casinotsu.com/reviews/casino-x#main-content",
      bonus: "入金不要ボーナス¥4,500",
      freeSpins: undefined,
      wagering: undefined,
      rating: undefined,
      tagline: undefined,
      ctaText: undefined,
      ctaHref: undefined,
    },
    {
      name: "ワンダーカジノ",
      href: "https://casinotsu.com/reviews/wonder-casino#main-content",
      bonus: "賭け条件1倍のお得な40ドル入金不要ボーナス",
      freeSpins: undefined,
      wagering: undefined,
      rating: undefined,
      tagline: undefined,
      ctaText: undefined,
      ctaHref: undefined,
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "2up",
      logo: "/wp-content/uploads/2up_375x375.png",
      href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "1win",
      logo: "/wp-content/uploads/1win_375x375.png",
      href: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 30x 賭け条件",
      freeSpins: "200",
      wagering: "フリースピン 20x 賭け条件",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 29x 賭け条件",
      freeSpins: "-",
      wagering: "フリースピン -",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 20x 賭け条件",
      freeSpins: "200",
      wagering: "フリースピン 20x 賭け条件",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Katsuwin",
      logo: "/wp-content/uploads/katsuwin_375x375.png",
      href: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 35x 賭け条件",
      freeSpins: "50",
      wagering: "フリースピン 40x 賭け条件",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Parimatch",
      logo: "/wp-content/uploads/parimatch_375x375-2.png",
      href: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Bets.io",
      logo: "/wp-content/uploads/bets-io_375x375.png",
      href: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Duelbits",
      logo: "/wp-content/uploads/duelbits_375x375-1.png",
      href: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 1,000USDT",
      freeSpins: "-",
      wagering: undefined,
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 40x 賭け条件",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス $10,000",
      freeSpins: "800",
      wagering: undefined,
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 20x 賭け条件",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス €25,000",
      freeSpins: "50",
      wagering: "フリースピン 35x 賭け条件",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Flush Casino",
      logo: "/wp-content/uploads/Flush_375x375-1.png",
      href: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 30x 賭け条件",
      freeSpins: "288",
      wagering: "フリースピン 20x 賭け条件",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス $0",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Casino Sky",
      logo: "/wp-content/uploads/casinosky_375x375.png",
      href: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 35x 賭け条件",
      freeSpins: "50",
      wagering: "フリースピン 40x 賭け条件",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Fresh Casino",
      logo: "/wp-content/uploads/fresh_375x375.png",
      href: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "6,000種類以上のゲームで遊びたい放題！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/fresh-casino:fresh-casino?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Stake",
      logo: "/wp-content/uploads/stake_375x375-1.png",
      href: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Wonder Casino",
      logo: "/wp-content/uploads/wonder-casino_375x375.png",
      href: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Yuugado",
      logo: "/wp-content/uploads/yuugado_375x375-1.png",
      href: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Lilibet",
      logo: "/wp-content/uploads/lilibet_375x375.png",
      href: "https://go.casinotsu.com/go/lilibet:lilibet?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lilibet:lilibet?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Konibet",
      logo: "/wp-content/uploads/konibet_375x375.png",
      href: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 20x 賭け条件",
      freeSpins: "77",
      wagering: "フリースピン 20x 賭け条件",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 10x 賭け条件",
      freeSpins: "50",
      wagering: "フリースピン 10x 賭け条件",
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Mystino",
      logo: "/wp-content/uploads/mystino_375x375.png",
      href: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "InterCasino",
      logo: "/wp-content/uploads/Inter-Casino_375x375-1.png",
      href: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 20x 賭け条件",
      freeSpins: "-",
      wagering: undefined,
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "https://go.casinotsu.com/go/winunique:winunique?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 30x 賭け条件",
      freeSpins: "20",
      wagering: "フリースピン 30x 賭け条件",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winunique:winunique?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Vera&John",
      logo: "/wp-content/uploads/VeraJohn_375x375-1.png",
      href: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 40x 賭け条件",
      freeSpins: "-",
      wagering: undefined,
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Casino-X",
      logo: "/wp-content/uploads/casino-x_375x375-1.png",
      href: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: "ボーナス 20x 賭け条件",
      freeSpins: "250",
      wagering: "フリースピン 20x 賭け条件",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fhappy-apples",
    },
    {
      name: "Eldoah Casino",
      logo: "/wp-content/uploads/eldoah_375x375-3.png",
      href: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fhappy-apples",
      bonus: undefined,
      freeSpins: undefined,
      wagering: undefined,
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fhappy-apples",
    },
  ],
  gameInfo: {
    intro:
      "Happy Apples（ハッピー・アップル）は、その可愛らしい外見とは裏腹に、プレイヤーの皆様を熱くさせる様々なゲームフィーチャーを搭載しております。",
    basicInfo: {
      rtp: "95.7% (一部カジノでは96.13%の場合あり)",
      volatility: "High",
      reels: "6",
      paylines: "クラスターペイス（ペイラインなし）",
      minBet: "$0.10 - $0.20",
      maxBet: "$50 - $100",
      provider: "Red Tiger",
      releaseDate: "2023-03-16",
    },
  },
  payoutTable: {
    title: "Happy Apples のペイアウト・配当表",
    symbols: [
      {
        name: "トラ",
        description: "最高配当シンボル",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "パンダ",
        description: "高配当シンボル",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "ブタ",
        description: "高配当シンボル",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "イヌ",
        description: "高配当シンボル",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "和菓子（フライドアイスクリーム、ドーナツ、団子など）",
        description: "低配当シンボル",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: false,
      },
      {
        name: "フリースピンシンボル",
        description: "3つ以上出現でフリースピンラウンドに突入",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: true,
      },
      {
        name: "ダイヤモンドアップル",
        description: "マルチプライヤー（2倍〜100倍）が付与",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: true,
      },
      {
        name: "ゴールデンアップル",
        description: "他のシンボルに置き換わり、配当成立を助ける",
        payout5: undefined,
        payout4: undefined,
        payout3: undefined,
        isSpecial: true,
      },
    ],
    maxPayout: "6,186x",
    notes: [
      "ベット額1ドルあたりの配当例です。",
      "15個以上のシンボルが揃った場合の配当を示しています。",
    ],
  },
  features: {
    title: "Happy Apples のゲーム特徴・フィーチャー",
    items: [
      {
        name: "クラスターペイスと連鎖（カスケード）",
        description: "10個以上の同一シンボルが隣接して出現すると配当が成立。配当成立シンボルは消え、新しいシンボルがカスケード（連鎖）して落ちてくる。",
        icon: undefined,
      },
      {
        name: "ダイヤモンドアップル（マルチプライヤー）",
        description: "出現するとマルチプライヤーとして機能し、配当に掛け合わされる。複数出現し、最大100倍まで上昇する可能性がある。",
        icon: undefined,
      },
      {
        name: "ゴールデンアップル（シンボル置換）",
        description: "他のシンボルにランダムに置き換わり、配当成立を助ける。",
        icon: undefined,
      },
      {
        name: "フォーチュントゥリー（ Fortune Tree）機能",
        description: "ゲーム画面上部の木から、ランダムにゴールデンアップルやダイヤモンドアップルがリールに振りまかれる。",
        icon: undefined,
      },
      {
        name: "フリースピン",
        description: "フリースピンシンボルが3つ以上出現すると10回のフリースピンが開始。フリースピン中はダイヤモンドアップルとゴールデンアップルの出現率が大幅にアップする。",
        icon: undefined,
      },
      {
        name: "追加スピン",
        description: "フリースピン中にフリースピンシンボルが3つ以上出現すると、追加で5回のフリースピンが付与される。",
        icon: undefined,
      },
      {
        name: "ボーナス購入機能",
        description: "ベット額の70倍で、直接フリースピンを購入できる機能。",
        icon: undefined,
      },
    ],
  },
  sections: [
    {
      heading: "Happy Apples のグラフィック・サウンド",
      paragraphs: [
        "アジア風の要素を取り入れつつ、全体的にユルフワで可愛らしいデザイン。リンゴや和菓子、動物のシンボルが愛らしく、見ているだけで癒されます。",
        "穏やかで癒し系のBGMが流れ、プレイにリラックスした雰囲気をもたらします。シンボルの出現や配当成立時には、軽快な効果音が鳴り、ゲームを盛り上げます。",
      ],
      bullets: [
        "グラフィック: アジア風、ユルフワで可愛らしいデザイン",
        "サウンド: 穏やかで癒し系のBGM、軽快な効果音",
        "モバイル仕様: PCはもちろん、スマートフォンやタブレットでも最適化されたゲーム体験が可能。iOS、AndroidどちらのOSにも対応。",
        "特別フィーチャー: ゴールデンアップルとダイヤモンドアップルのコンビネーションは、連続配当とマルチプライヤーのチャンスを生み出し、ゲームに戦略的な深みを与えます。",
      ],
    },
    {
      heading: "ゲーム中に問題が起こったら？",
      paragraphs: [
        "Red Tiger 社は、スムーズなゲームプレイのために、最新のソフトウェアを使用することを推奨しております。",
        "万が一、ソフトウェアの不具合やゲームの故障が発生した場合、その時点での賭けやゲーム結果が無効となる可能性があります。問題が発生した場合は、速やかにご利用のオンラインカジノのサポートへご連絡ください。",
      ],
    },
    {
      heading: "Happy Apples のモバイル対応",
      paragraphs: [
        "Happy Applesは、現代のプレイヤーの皆様のニーズに応えるべく、モバイルデバイスに完全最適化されております。",
        "スマートフォン・タブレット対応: iOS、Androidのどちらのデバイスからでも、ブラウザを通じてシームレスにプレイ可能です。",
        "優れたUX: モバイル画面でも、リール操作や機能へのアクセスが直感的で、ストレスなく楽しめます。グラフィックやサウンドも、デバイスの性能に合わせて最適化されており、どこでも本格的なカジノ体験ができます。",
      ],
    },
    {
      heading: "Happy Apples の戦略・攻略法",
      paragraphs: [
        "Happy Applesで勝利のチャンスを最大限に引き出すための戦略とヒントをCasinoTsuがご紹介いたします。",
      ],
      bullets: [
        "ベット戦略:\n- 低〜中ベットで回数を重ねる: ボラティリティが高めなので、一度の大きな勝利を狙うより、低〜中程度のベット額でスピン回数を増やすことで、フリースピン突入の機会を増やし、クラスター発生の可能性を高めることができます。\n- マネーマネジメントの徹底: 損失許容額と目標勝利額を事前に設定し、それに従ってプレイすることが重要です。感情的にならず、計画的にベットを行いましょう。",
        "フィーチャー活用法:\n- フォーチュントゥリーと連鎖の活用: ベースゲーム中にフォーチュントゥリーからゴールデンアップルやダイヤモンドアップルが出現したら、連鎖（カスケード）を狙いましょう。連鎖が続けば、配当とマルチプライヤーがどんどん増加します。\n- フリースピンの重要性: フリースピン中は、ダイヤモンドアップルとゴールデンアップルの出現率が大幅にアップします。このラウンドでマルチプライヤーを最大限に活かし、高配当を狙うのが最も効果的です。\n- ボーナス購入機能の検討: 資金に余裕があり、すぐにフリースピンを楽しみたい場合は、ボーナス購入機能の利用も検討できます。ただし、購入額に見合うリターンが得られるとは限らないため、リスクを理解した上でご利用ください。",
        "注意点:\n- RTPの確認: プレイするカジノによってRTPが異なる場合があるため、事前に確認しておくと良いでしょう。チェック、ダブルチェック、そして CasinoTsu チェックで正確な情報を掴みましょう。\n- ジャックポット機能なし: このスロットにはジャックポット機能はありません。最大配当は6,186倍ですが、プログレッシブジャックポットのような無限の賞金は期待できません。",
      ],
    },
    {
      heading: "Happy Apples｜まとめ",
      paragraphs: [
        "Happy Apples は、その愛らしい見た目とは裏腹に、クラスターペイス、連鎖（カスケード）、マルチプライヤー、そしてボーナス購入機能といった、プレイヤーの皆様を飽きさせない多彩なフィーチャーを搭載したスロットです。",
        "特にフリースピン中は、マルチプライヤーが最大100倍まで到達する可能性があり、最大6,186倍 の高配当を狙えるチャンスが広がります。アジア風のテーマと癒し系のサウンドも魅力で、リラックスしながらもエキサイティングなゲームプレイを楽しみたいプレイヤーに最適です。",
      ],
      bullets: [
        "どんなプレイヤーにおすすめ？\n- 可愛らしいキャラクターやテーマのスロットが好きな方\n- クラスターペイスや連鎖（カスケード）機能のスロットが好きな方\n- 高配当を狙える、ボラティリティ高めのスロットを探している方\n- フリースピンやマルチプライヤーで一攫千金を狙いたい方",
      ],
    },
  ],
  similarGames: [
    {
      name: "ソジュ・ボム",
      href: "https://casinotsu.com/slots/soju-bomb",
      provider: undefined,
      description: "韓国のお酒「ソジュ」と韓国美女がテーマの新作スロット 🍷💕",
    },
    {
      name: "ドラゴン・ヒーロー",
      href: "https://casinotsu.com/slots/dragon-hero",
      provider: "Pragmatic Play",
      description: "Pragmatic Play の中華スロット！ フリースピン中の スーパーワイルド でビッグウィンが狙えちゃう！",
    },
    {
      name: "ゲイシャ",
      href: "https://casinotsu.com/slots/geisha",
      provider: "Endorphina",
      description: "日本の芸者が登場する Endorphina のスロット👘 ギャンブルなどの独自フィーチャーが面白いっ！",
    },
    ],
  prosCons: {
    pros: [
      "可愛らしいアジア風のデザインと癒し系のサウンド",
      "クラスターペイスと連鎖（カスケード）機能で高配当のチャンス",
      "最大100倍のマルチプライヤー搭載",
      "フリースピン中にマルチプライヤーとシンボル置換が強化",
      "フォーチュントゥリー機能によるランダムボーナス",
      "ボーナス購入機能で直接フリースピンへ",
      "最大配当6,186倍と高いポテンシャル",
      "モバイルデバイスに完全最適化",
    ],
    cons: [
      "ボラティリティが高めで、頻繁な小当たりは少なめ",
      "RTPはカジノによって変動する可能性あり",
      "ジャックポット機能なし",
    ],
  },
  faq: [
    {
      q: "追加のフリースピンはどれくらいもらえますか？",
      a: "フリースピン中にスキャッター（フリースピンシンボル）が3つ以上出現すると、フリースピン5回が追加されます。",
    },
    {
      q: "ダイヤモンドアップルのマルチプライヤーは最大どれくらいですか？",
      a: "ダイヤモンドアップルは、2倍から最大100倍までのマルチプライヤーが付与されるチャンスがあります。",
    },
    {
      q: "Happy Apples はジャックポット搭載ですか？",
      a: "いいえ、Happy Applesにはジャックポット機能は搭載されておりません。ただし、最大配当倍率は6,186倍と非常に高いため、ジャックポットに匹敵するような大きな勝利が期待できます。",
    },
    {
      q: "demo（無料プレイ）はできますか？",
      a: "はい、多くのオンラインカジノやスロットレビューサイトで、Happy Applesのデモプレイ（無料プレイ）が提供されております。実際のお金を使わずに、ゲームのフィーチャーやプレイ感を試すことができます。",
    },
  ],
  breadcrumbs: [
    { label: "Home", href: "https://casinotsu.com/" },
    { label: "Slots", href: "https://casinotsu.com/slots" },
    { label: "Happy apples", href: "https://casinotsu.com/slots/happy-apples" },
  ],
  tableOfContents: [
    { label: "Happy Apples をプレイできるカジノ", href: "#happy-apples-をプレイできるカジノ" },
    { label: "Happy Apples の基本情報", href: "#happy-apples-の基本情報" },
    { label: "Happy Apples のゲーム特徴・フィーチャー", href: "#happy-apples-のゲーム特徴・フィーチャー" },
    { label: "Happy Apples のグラフィック・サウンド", href: "#happy-apples-のグラフィック・サウンド" },
    { label: "ゲーム中に問題が起こったら？", href: "#ゲーム中に問題が起こったら" },
    { label: "Happy Apples のペイアウト・配当表", href: "#happy-apples-のペイアウト・配当表" },
    { label: "Happy Apples のモバイル対応", href: "#happy-apples-のモバイル対応" },
    { label: "Happy Apples の戦略・攻略法", href: "#happy-apples-の戦略・攻略法" },
    { label: "Happy Apples の類似ゲーム", href: "#happy-apples-の類似ゲーム" },
    { label: "Happy Apples｜まとめ", href: "#happy-apples-まとめ" },
    { label: "よくある質問", href: "#よくある質問" },
  ],
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/happy-apples" />;
}
