import SlotTemplate, { SlotPageData } from "@/components/templates/SlotTemplate";

const data: SlotPageData = {
  title: "ゲーツ・オブ・オリンパス (Gates of Olympus) スロットレビュー！",
  hero: {
    title: "ゲーツ・オブ・オリンパス (Gates of Olympus)",
    subheading: "「ゼウス様、我にマルチプライヤーを！」 CasinoTsu 推薦、神々しいスロット「ゲーツ・オブ・オリンパス（Gates of Olympus）」を徹底解説いたします！",
    description: "「ゼウス様、我にマルチプライヤーを！」 CasinoTsu 推薦、神々しいスロット「ゲーツ・オブ・オリンパス（Gates of Olympus）」を徹底解説いたします！",
    score: 4.7,
    scoreMax: 5,
    rtp: "96.5%",
    maxMultiplier: "x5,000",
    provider: "Pragmatic Play",
    releaseDate: "2021年2月25日",
    volatility: "High",
    reels: "6",
    paylines: "なし (Pay Anywhereシステム)",
    minBet: "$0.2",
    maxBet: "$100",
    slotImageSrc: "/slots/gates-of-olympus.png",
    highlights: [
      "カスケード機能（タンブル機能）",
      "マルチプライヤーオーブ（2倍〜500倍）",
      "スキャッターシンボルでフリースピン突入",
      "フリースピン中のマルチプライヤー合計機能",
      "アンティベット機能でフリースピン当選確率アップ",
      "フリースピン購入機能搭載",
    ],
    watchouts: [
      "ハイボラティリティのため、勝利が続かない場合がある",
      "一部カジノではRTPが異なる場合がある",
    ],
  },
  featuredCasino: {
    name: "2upカジノ",
    logo: "/assets/casino/2up.png",
    href: "https://casinotsu.com/reviews/2up",
    ctaText: "今すぐプレイ",
    ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-olympus",
  },
  casinos: [
    {
      name: "Golden Panda",
      logo: "/assets/casino/golden-panda.jpg",
      href: "https://casinotsu.com/reviews/golden-panda",
      bonus: "¥850,000",
      freeSpins: "50",
      wagering: "30倍 賭け条件",
      rating: 4,
      tagline: "出金は基本的に即時反映でストレスフリー♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/golden-panda:golden-panda?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Betgoat",
      logo: "/assets/casino/betgoat.jpg",
      href: "https://casinotsu.com/reviews/betgoat",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "独自コインも利用可能！ 最新クリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betgoat:betgoat?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "2up",
      logo: "/images/2up_375x375.png",
      href: "https://casinotsu.com/reviews/2up",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "仮想通貨でも日本円でも遊べる、最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Cybet",
      logo: "/assets/casino/cybet.jpg",
      href: "https://casinotsu.com/reviews/cybet",
      bonus: "$500",
      freeSpins: "50",
      wagering: "35倍 賭け条件",
      rating: 3.5,
      tagline: "可愛いマスコットキャラが魅力の最新クリプトカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cybet:cybet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "1win",
      logo: "/images/1win_375x375.png",
      href: "https://casinotsu.com/reviews/1win",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "幅広いゲームラインナップが魅力！今注目の仮想通貨対応オンラインカジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/1win:1win?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Miki",
      logo: "/assets/casino/miki.jpg",
      href: "https://casinotsu.com/reviews/miki",
      bonus: "$4,000",
      freeSpins: "200",
      wagering: "30倍 賭け条件",
      rating: 4,
      tagline: "充実したゲームラインナップ！盛りだくさんのボーナスでお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/miki:miki?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "WSM Casino",
      logo: "/images/WSM_375x375.png",
      href: "https://casinotsu.com/reviews/wsm-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "時代の最先端？！「ミームコイン」×「オンラインカジノ」",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wsm-casino:wsm-casino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Bitz",
      logo: "/assets/casino/bitz.jpg",
      href: "https://casinotsu.com/reviews/bitz",
      bonus: "$1,000",
      freeSpins: "-",
      wagering: "29倍 賭け条件",
      rating: 4,
      tagline: "本人確認書類不要！？ 匿名性もバッチリの最新仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitz:bitz?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Wikibet",
      logo: "/assets/casino/wikibet.jpg",
      href: "https://casinotsu.com/reviews/wikibet",
      bonus: "¥50,000",
      freeSpins: "200",
      wagering: "20倍 賭け条件",
      rating: 4,
      tagline: "シンプルな操作性と可愛いデザインが特徴！厳選されたゲームをプレイしよう★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wikibet:wikibet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Katsuwin",
      logo: "/assets/casinos/katsuwin_375x375.png",
      href: "https://casinotsu.com/reviews/katsuwin",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界トップクラスのパチンコ・パチスロ台数を誇る新星カジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/katsuwin:katsuwin?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Sushi Casino",
      logo: "/assets/casino/sushi-casino.jpg",
      href: "https://casinotsu.com/reviews/sushi-casino",
      bonus: "¥200,000",
      freeSpins: "50",
      wagering: "35倍 賭け条件",
      rating: 4,
      tagline: "てんこ盛りのオファーやVIPプログラムが魅力的な最新オンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sushi-casino:sushi-casino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Betpanda",
      logo: "/images/Betpanda_375x375.png",
      href: "https://casinotsu.com/reviews/betpanda",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 3.5,
      tagline: "匿名で安全に遊べるクリプトオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betpanda:betpanda?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Parimatch",
      logo: "/assets/casinos/parimatch_375x375-2.png",
      href: "https://casinotsu.com/reviews/parimatch",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "2024年11月オープンの最新オンカジを徹底レビュー！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/parimatch:parimatch?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Bets.io",
      logo: "/images/bets-io_375x375.png",
      href: "https://casinotsu.com/reviews/bets-io",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "最大1BTCの豪華入金ボーナスが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/betsio:bets-io?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Duelbits",
      logo: "/assets/casinos/duelbits_375x375-1.png",
      href: "https://casinotsu.com/reviews/duelbits",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "500フリースピンが嬉しいクリプトカジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/duelbits:duelbits?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Sportsbet.io",
      logo: "/assets/casino/sportsbetio.jpg",
      href: "https://casinotsu.com/reviews/sportsbet-io",
      bonus: "1,000USDT",
      freeSpins: "-",
      wagering: "",
      rating: 4.5,
      tagline: "スポーツベットだけじゃない！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/sportsbet-io:sportsbet-io?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Shuffle",
      logo: "/assets/casino/shuffle.jpg",
      href: "https://casinotsu.com/reviews/shuffle",
      bonus: "$2,020",
      freeSpins: "-",
      wagering: "40倍 賭け条件",
      rating: 4,
      tagline: "独自のトークンで資産運用もできる仮想通貨カジノ★",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/shuffle:shuffle?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Winz",
      logo: "/assets/casino/winz.jpg",
      href: "https://casinotsu.com/reviews/winz-io",
      bonus: "$10,000",
      freeSpins: "800",
      wagering: "",
      rating: 4.5,
      tagline: "ウェルカムオファーやボーナスに賭け条件なし♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winz:winz-io?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Dafabet",
      logo: "/assets/casino/dafabet.jpg",
      href: "https://casinotsu.com/reviews/dafabet",
      bonus: "$500",
      freeSpins: "-",
      wagering: "20倍 賭け条件",
      rating: 4,
      tagline: "セルティックFCのスポンサーカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/dafabet:dafabet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Lucky Block",
      logo: "/assets/casino/lucky-block.jpg",
      href: "https://casinotsu.com/reviews/lucky-block",
      bonus: "€25,000",
      freeSpins: "50",
      wagering: "35倍 賭け条件",
      rating: 4,
      tagline: "独自トークンもある仮想通貨カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lucky-block:lucky-block?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Ramenbet",
      logo: "/images/ramenbet_375x375-1.png",
      href: "https://casinotsu.com/reviews/ramenbet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "スロットもライブカジノもスポーツも充実！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ramenbet:ramenbet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Flush Casino",
      logo: "/images/Flush_375x375-1.png",
      href: "https://casinotsu.com/reviews/flush",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "今年大注目のクリプトカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/flush-casino:flush?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Queen Casino",
      logo: "/assets/casino/shinqueen.jpg",
      href: "https://casinotsu.com/reviews/queen-casino",
      bonus: "1,800USDT",
      freeSpins: "288",
      wagering: "30倍 賭け条件",
      rating: 4.5,
      tagline: "アジア市場知名度ナンバーワンに君臨するオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/queen-casino:queen-casino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Roobet",
      logo: "/assets/casino/roobet.jpg",
      href: "https://casinotsu.com/reviews/roobet",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "世界的有名人がアンバサダーを務めるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/roobet:roobet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Casino Sky",
      logo: "/images/casinosky_375x375.png",
      href: "https://casinotsu.com/reviews/casino-sky",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "日本のオンカジ業界プロが運営する期待のカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-sky:casino-sky?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Mega Dice",
      logo: "/assets/casino/mega-dice.jpg",
      href: "https://casinotsu.com/reviews/mega-dice",
      bonus: "1BTC",
      freeSpins: "50",
      wagering: "35倍 賭け条件",
      rating: 3.5,
      tagline: "ボーナス最大1BTCの仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mega-dice:mega-dice?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Cosmoswin",
      logo: "/assets/casino/cosmoswin.jpg",
      href: "https://casinotsu.com/reviews/cosmoswin",
      bonus: "キャッシュバック 最大$10,000",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "可愛い女の子のキャラが案内役♪ ユニークなボーナスショップも必見です！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/cosmoswin:cosmoswin?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "BC.Game",
      logo: "/assets/casino/bcgame.jpg",
      href: "https://casinotsu.com/reviews/bc-game",
      bonus: "$1,600",
      freeSpins: "460",
      wagering: "45倍 賭け条件",
      rating: 4,
      tagline: "圧巻のゲーム数＆最大1,600ドルの初回入金ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bc-game:bc-game?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Empire.io",
      logo: "/assets/casino/empireio.jpg",
      href: "https://casinotsu.com/reviews/empire-io",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 4,
      tagline: "賭け条件ナシのキャシュバック＆VIP特典がスゴイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire-io:empire-io?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Stake",
      logo: "/images/stake_375x375-1.png",
      href: "https://casinotsu.com/reviews/stake",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "ハウスエッジ5%レーキバック＆VIP特典が超おトク！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/stake:stake?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Wonder Casino",
      logo: "/assets/casinos/wonder-casino_375x375.png",
      href: "https://casinotsu.com/reviews/wonder-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "業界最速の出金スピードと仮想通貨特化ボーナス！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/wonder-casino:wonder-casino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "OhMySpins",
      logo: "/assets/casino/ohmyspins.jpg",
      href: "https://casinotsu.com/reviews/ohmyspins",
      bonus: "¥65,000",
      freeSpins: "200",
      wagering: "35倍 賭け条件",
      rating: 4,
      tagline: "マニアックなプロバイダーもココなら見つかる！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/ohmyspins:ohmyspins?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Yuugado",
      logo: "/images/yuugado_375x375-1.png",
      href: "https://casinotsu.com/reviews/yuugado",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "「和」がテーマのオンラインカジノ \| パチンコからスポーツベットまで！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/yuugado:yuugado?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Tedbet",
      logo: "/images/tedbet_375x375.png",
      href: "https://casinotsu.com/reviews/tedbet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "豊富な決済方法が嬉しいっ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/tedbet:tedbet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Lilibet",
      logo: "/images/lilibet_375x375.png",
      href: "https://casinotsu.com/reviews/lilibet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "勝ったらラッキー、負けても安心！初心者さんいらっしゃい！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/lilibet:lilibet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Konibet",
      logo: "/images/konibet_375x375.png",
      href: "https://casinotsu.com/reviews/konibet",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "パチンコ・パチスロが遊べるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/konibet:konibet?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Casino Me",
      logo: "/assets/casino/casino-me.jpg",
      href: "https://casinotsu.com/reviews/casino-me",
      bonus: "$777",
      freeSpins: "77",
      wagering: "20倍 賭け条件",
      rating: 4,
      tagline: "独自システムのお得なキャッシュバックあり！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-me:casino-me?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Kakeyo",
      logo: "/assets/casino/kakeyo.jpg",
      href: "https://casinotsu.com/reviews/kakeyo",
      bonus: "¥100,000",
      freeSpins: "50",
      wagering: "10倍 賭け条件",
      rating: 4,
      tagline: "ボーナス充実！スポーツベットにも最適カジノ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/kakeyo:kakeyo?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Mystino",
      logo: "/assets/casinos/mystino_375x375.png",
      href: "https://casinotsu.com/reviews/mystino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "日本人プレイヤーの心をグッと掴むカジノといえば…！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/mystino:mystino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Trustdice",
      logo: "/images/Trustdice_375x375.png",
      href: "https://casinotsu.com/reviews/trustdice",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4,
      tagline: "賭けて遊んで資産運用もできるオンラインカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/trustdice:trustdice?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "InterCasino",
      logo: "/assets/casinos/Inter-Casino_375x375-1.png",
      href: "https://casinotsu.com/reviews/inter-casino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "実は20年以上歴史のあるカジノはココ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/intercasino-japan:inter-casino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Empire777",
      logo: "/assets/casino/empire777.jpg",
      href: "https://casinotsu.com/reviews/empire777",
      bonus: "$1,600",
      freeSpins: "-",
      wagering: "20倍 賭け条件",
      rating: 4,
      tagline: "アジアNo.1を豪語するオンカジはここだ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/empire777:empire777?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Pinnacle",
      logo: "/assets/casino/pinnacle.jpg",
      href: "https://casinotsu.com/reviews/pinnacle",
      bonus: "$0",
      freeSpins: "-",
      wagering: "",
      rating: 3.5,
      tagline: "カジノもスポーツベットも楽しめるハイブリッド！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/pinnacle:pinnacle?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "WinUnique",
      logo: "/assets/casino/winunique.jpg",
      href: "https://casinotsu.com/reviews/winunique",
      bonus: "$330",
      freeSpins: "20",
      wagering: "30倍 賭け条件",
      rating: 4,
      tagline: "ピカピカ金色招き猫が勝利を運んでくれる？！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/winunique:winunique?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Joy Casino",
      logo: "/images/joycasino_375x375.png",
      href: "https://casinotsu.com/reviews/joycasino",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ジョイカジノのてんこ盛りボーナスを貰っちゃおう！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/joy-casino:joycasino?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Vera&John",
      logo: "/assets/casinos/VeraJohn_375x375-1.png",
      href: "https://casinotsu.com/reviews/vera-john",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "オンカジといえば、やっぱりベラジョン！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/vera-john:vera-john?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Live Casino House",
      logo: "/assets/casino/live-casino-house.jpg",
      href: "https://casinotsu.com/reviews/live-casino-house",
      bonus: "¥50,000",
      freeSpins: "-",
      wagering: "20倍 賭け条件",
      rating: 4,
      tagline: "ライブカジノを始め、多種多様なゲームが遊べるおなじみのカジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/live-casino-house:live-casino-house?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Bitcasino.io",
      logo: "/assets/casino/bitcasinoio.jpg",
      href: "https://casinotsu.com/reviews/bitcasino-io",
      bonus: "¥200,000",
      freeSpins: "-",
      wagering: "40倍 賭け条件",
      rating: 4.5,
      tagline: "元祖仮想通貨カジノ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/bitcasino-io:bitcasino-io?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Casino-X",
      logo: "/images/casino-x_375x375-1.png",
      href: "https://casinotsu.com/reviews/casino-x",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "太っ腹ボーナス盛りだくさんのカジノエックスで、お得にプレイ♪",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casino-x:casino-x?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Casitabi",
      logo: "/assets/casino/casitabi.jpg",
      href: "https://casinotsu.com/reviews/casitabi",
      bonus: "$500",
      freeSpins: "250",
      wagering: "20倍 賭け条件",
      rating: 4.5,
      tagline: "RPG型カジノで旅をしながらボスを倒してお得にプレイ！",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/casitabi:casitabi?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
    {
      name: "Eldoah Casino",
      logo: "/assets/casinos/eldoah_375x375-3.png",
      href: "https://casinotsu.com/reviews/eldoah",
      bonus: "",
      freeSpins: "",
      wagering: "",
      rating: 4.5,
      tagline: "ライブカジノ利用満足度6年連続ナンバー1のオンラインカジノ",
      ctaText: "今すぐプレイ！",
      ctaHref: "https://go.casinotsu.com/go/eldoah-casino:eldoah?referrer_path=%2Fslots%2Fgates-of-olympus",
    },
  ],
  gameInfo: {
    intro: "日本でも絶大な人気を誇るオンラインスロットプロバイダー、Pragmatic Play（プラグマティック・プレイ） 社より、今回 CasinoTsu がご紹介するのは、ゲーツ・オブ・オリンパス（Gates of Olympus） です！このスロットは、あらゆる面でまさに神々しい存在と言えるでしょう。🔥😇✨ゲームには、ギリシャ神話の最高神であるゼウスが登場します。ゼウスが雷⚡︎ を手に「ハーッ！」と一撃を放つと、マルチプライヤーが発動！他にもどのような魅力的なフィーチャーがあるのか、以下のポイントに注目しながら、ゲーツ・オブ・オリンパス の奥深さを探っていきましょう！🎉",
    basicInfo: {
      rtp: "96.5% (一部カジノでは95.51%, 94.51%の場合もあります)",
      volatility: "High",
      reels: "6",
      paylines: "なし (Pay Anywhereシステム)",
      minBet: "$0.2",
      maxBet: "$100 (アンティベット有効時は$125)",
      provider: "Pragmatic Play",
      releaseDate: "2021年2月25日",
    },
  },
  payoutTable: {
    title: "ゲーツ・オブ・オリンパス｜シンボル＆配当",
    symbols: [
      {
        name: "王冠",
        description: "最高配当シンボル",
        payout5: "",
        payout4: "",
        payout3: "",
        payout8_or_more: "x100",
      },
      {
        name: "指輪",
        payout8_or_more: "x60",
      },
      {
        name: "砂時計",
        payout8_or_more: "x50",
      },
      {
        name: "杯",
        payout8_or_more: "x40",
      },
      {
        name: "宝石（赤）",
        payout8_or_more: "x30",
      },
      {
        name: "宝石（緑）",
        payout8_or_more: "x20",
      },
      {
        name: "宝石（青）",
        payout8_or_more: "x15",
      },
      {
        name: "宝石（紫）",
        payout8_or_more: "x12",
      },
      {
        name: "宝石（黄）",
        payout8_or_more: "x10",
      },
      {
        name: "ゼウス（スキャッター）",
        description: "4つ以上でフリースピン突入",
        payout5: "",
        payout4: "",
        payout3: "",
        isSpecial: true,
      },
      {
        name: "マルチプライヤーオーブ",
        description: "2倍〜500倍のランダム倍率",
        isSpecial: true,
      },
    ],
    maxPayout: "x5,000",
    notes: [
      "ペイラインシステムではなく、「Pay Anywhere」システムを採用。",
      "リール上のどこに同じシンボルが8つ以上出現すれば配当。",
      "ワイルドシンボルは搭載されていない。",
    ],
  },
  features: {
    title: "ゲーツ・オブ・オリンパス｜ゲーム機能",
    items: [
      {
        name: "タンブル機能 (Tumble Feature)",
        description: "勝利が発生すると、その勝利に貢献したシンボルは消滅し、代わりに上から新しいシンボルが落下してきます。これにより、1回のスピンで連続して配当が発生し、複数回の勝利を狙うことが可能です。この機能は、フリースピン中にも継続して発動します。",
        icon: "",
      },
      {
        name: "マルチプライヤーオーブ (Multiplier Orbs)",
        description: "右側に浮遊するゼウスが、時折、雷を手に「ハーッ！」と力強く叫びます。✊⚡︎この時、「マルチプライヤーオーブ」シンボルが出現することがあります。これらのシンボルは、2倍から500倍（ベースゲーム時）までのランダムな倍率を持ち、そのラウンドで発生した配当を増加させます。",
        icon: "",
      },
      {
        name: "スキャッター (Scatter)",
        description: "ゼウスの顔が描かれたシンボル。リールの横にも浮遊していますが、シンボルとしても出現します。4つ以上のスキャッターシンボルがリールに出現すると、ボーナスラウンド（フリースピン）に突入します。",
        icon: "",
      },
      {
        name: "ボーナスラウンド（フリースピン）",
        description: "スキャッター（ゼウスのシンボル）が4個以上出現すると、ボーナスラウンドに突入し、フリースピン15回分を獲得できます。フリースピン中は、2倍〜500倍のマルチプライヤーシンボル（マルチプライヤーオーブ）がランダムに出現します。さらに、フリースピン中は、獲得したマルチプライヤーシンボルの倍率が合計され、画面左側のメーターに蓄積されます。配当が発生した際には、この蓄積されたマルチプライヤーが適用され、配当がさらに大きく増加します。フリースピン中にスキャッターが3つ以上出現すると、追加で5回のフリースピンを獲得できます。",
        icon: "",
      },
      {
        name: "アンティベット (Ante Bet)",
        description: "アンティベット機能を利用すると、通常のベット額に追加で25%（カジノにより異なる場合があります）を支払うことで、フリースピンの当選確率が2倍になります。",
        icon: "",
      },
      {
        name: "フリースピン購入機能",
        description: "ベット額の100倍で購入することで、すぐにボーナスラウンドを開始できる機能です。ただし、この機能は全てのオンラインカジノで提供されているわけではありません。",
        icon: "",
      },
    ],
  },
  sections: [
    {
      heading: "ゲーツ・オブ・オリンパスをプレイできるオンラインカジノ",
      paragraphs: [
        "CasinoTsu が、自信を持っておすすめする「ゲーツ・オブ・オリンパス」をプレイできるオンラインカジノを、お得なボーナス情報と併せてご紹介いたします。ご自身のプレイスタイルに合ったカジノを見つけ、ぜひ最大限にお楽しみください。😊",
      ],
    },
    {
      heading: "ゲーツ・オブ・オリンパスのシンボル、ペイアウト",
      paragraphs: [
        "ゲーツ・オブ・オリンパスは、6リール x 5行 (6x5) のグリッドレイアウト を採用したカスケード型 スロットです。リールの右側には、ギリシャ神話の神々の王、ゼウスが堂々と浮遊しています。まさに神の風格です。😇",
        "ゼウスをはじめ、シンボルや背景のデザインは、全体的に荘厳で神話の世界観を忠実に再現しています。",
      ],
      bullets: [
        "通常シンボルは、宝石や王冠、指輪など9種類、スキャッターが1種類、そしてマルチプライヤーシンボル（マルチプライヤーオーブ）が4種類、合計14種類のシンボルで構成されています。残念ながら、ワイルドシンボルは搭載されていません。😭",
        "通常シンボルは、出現数に応じて配当が変動しますが、シンボルごとにその比率には大きな違いが見られます。",
      ],
      table: {
        title: "最小／最大ベット額、オートプレイ機能",
        columns: ["項目", "詳細"],
        rows: [
          ["最小ベット額", "$0.2"],
          ["最大ベット額", "$100"],
          ["アンティベット有効時", "$125"],
          ["オートプレイ", "10〜1,000回"],
        ],
      },
    },
    {
      heading: "RTP（還元率）",
      paragraphs: [
        "オンラインスロットの平均RTPは一般的に96%前後とされています。ゲーツ・オブ・オリンパスの標準RTPは96.50% と、平均よりもやや高めです。",
        "ただし、一部のカジノでは95.51%、94.51%といった異なるRTP設定が提供されている場合があるため、プレイ前には必ず確認することをおすすめします。",
        "アンティベット機能やフリースピン購入機能を利用した場合でも、RTPは基本的に96.50%のまま です。",
        "これらの機能を使用するとRTPが変動するスロットが多い中、常に一定であることは、プレイヤーがその時の気分や資金状況に合わせて柔軟に賭け方を変えられるという点で、非常に魅力的です。",
        "もし資金に余裕があり、攻めのプレイをしたい気分であれば、フリースピン購入機能でボーナスラウンドに突入してみるのも良いでしょう💪。",
      ],
    },
    {
      heading: "ボラティリティ",
      paragraphs: [
        "ゲーツ・オブ・オリンパスは、ハイリスク・ハイリターンのハイボラティリティスロット に分類されます。",
        "カスケード機能（タンブル機能） が搭載されているため、連鎖がうまく続けば通常時でも大きな勝利の可能性がありますが、一方で、フリースピンがなかなか獲得できないといった場面も少なくありません。🙀",
        "ヒット頻度は約28.82% (約20%) とされており、これは平均的なスロットと比較して勝利が発生する頻度がやや低いことを意味しますが、その分、一度の勝利で得られる配当は大きくなる傾向があります。",
      ],
    },
    {
      heading: "最大可能配当倍率",
      paragraphs: [
        "最大配当は、ベット額の5,000倍 です。",
        "この数値は、ハイボラティリティスロットとしては標準的ですが、破壊力のあるマルチプライヤー機能との組み合わせにより、一撃で高額賞金を獲得できるポテンシャルを秘めています。",
        "ゲーツ・オブ・オリンパスはハイボラティリティであるため、忍耐が求められる場面も多いかもしれません。",
        "しかし、勝利によって消えたシンボルの代わりに新しいシンボルが落下してくるタンブル機能（カスケード型）は、連鎖が続いた際の爽快感が格別です！🤩 🎉",
      ],
    },
    {
      heading: "ゲーツ・オブ・オリンパス｜サウンド＆グラフィック",
      table: {
        columns: ["項目", "詳細"],
        rows: [
          ["グラフィック", "2D。高品質で神々しいデザイン。モダンかつ鮮やかなグラフィックと、細部までこだわったアートワーク、アニメーションが特徴です。"],
          ["サウンド", "荘厳なBGMと効果音。ゲームの雰囲気を盛り上げます。"],
        ],
      },
    },
    {
      heading: "ゲーツ・オブ・オリンパスをボーナスでお得にプレイ！",
      paragraphs: [
        "ゲーツ・オブ・オリンパスは、世界的に有名なプロバイダー、Pragmatic Play 社の人気ゲームです。",
        "そのため、日本語対応の多くのオンラインカジノでプレイすることが可能です。🤩",
        "どのカジノでゲーツ・オブ・オリンパスをプレイするか迷ってしまう方もいらっしゃるかもしれませんね。",
        "せっかくプレイするなら、お得に楽しみたいものです。",
        "そこで、CasinoTsu では、ゲーツ・オブ・オリンパスで利用できる、特別なボーナスと、それを提供しているカジノをご紹介します。",
        "ぜひ、これらのボーナスを活用して、思う存分プレイをお楽しみください！😆",
        "ここで紹介するボーナスは、当サイト限定の特別なオファーが多数ございます。ご登録の際は、必ず当サイト経由でアクセスしてくださいませ。🥺",
      ],
      table: {
        columns: ["カジノ名", "ボーナスの内容"],
        rows: [
          ["EMPIRE777/エンパイア777", "日本市場ではまだ馴染みが薄いかもしれませんが、このカジノはタイ、マレーシア、中国をはじめとするアジア諸国で高い人気を誇っています。"],
          ["ボンズカジノ（Bons）", "マインクラフトやレゴブロックのようなユニークなキャラクターが特徴のボンズカジノでは、ブックメーカーも楽しめます。当サイト経由で登録後、ボーナスコードを入力すると、入金不要ボーナス4,500円＋フリースピン20回分 を獲得できます。さらに、最大200%の入金ボーナスもご用意しております★"],
        ],
      },
    },
  ],
  similarGames: [
    {
      name: "Pragmatic Play",
      href: "https://casinotsu.com/providers/pragmatic-play",
      provider: "Pragmatic Play",
      description: "日本でも絶大な人気を誇るオンラインスロットプロバイダー、Pragmatic Play（プラグマティック・プレイ） 社より、今回 CasinoTsu がご紹介するのは、ゲーツ・オブ・オリンパス（Gates of Olympus） です！",
    },
  ],
  prosCons: {
    pros: [
      "神々しいグラフィックとサウンド",
      "Pay Anywhereシステムで高配当を狙いやすい",
      "マルチプライヤー機能で配当が大きく増加する可能性",
      "フリースピン中のマルチプライヤー合計機能が強力",
      "アンティベット機能とフリースピン購入機能で戦略の幅が広がる",
      "RTPが平均よりやや高め",
    ],
    cons: [
      "ハイボラティリティのため、勝利が続かない場合がある",
      "ワイルドシンボルがない",
      "一部カジノではRTPが異なる場合がある",
      "フリースピン購入機能は高額",
    ],
  },
  faq: [
    {
      q: "ゲーツ・オブ・オリンパスのRTPは？",
      a: "標準RTPは96.50%ですが、一部カジノでは95.51%、94.51%の場合もあります。プレイ前に確認することをおすすめします。",
    },
    {
      q: "ゲーツ・オブ・オリンパスはどこでプレイできますか？",
      a: "多くのオンラインカジノでプレイ可能です。当サイトでは、おすすめのカジノとボーナス情報も紹介しています。",
    },
    {
      q: "ゲーツ・オブ・オリンパスにジャックポットはありますか？",
      a: "プログレッシブジャックポットはありません。最大配当はベット額の5,000倍です。",
    },
    {
      q: "ゲーツ・オブ・オリンパスはスマホでプレイできますか？",
      a: "はい、モバイルデバイスに対応しており、スマートフォンやタブレットで快適にプレイできます。",
    },
  ],
  breadcrumbs: [
    { label: "ホーム", href: "https://casinotsu.com/" },
    { label: "スロット", href: "https://casinotsu.com/slots" },
    { label: "ゲーツ・オブ・オリンパス", href: "https://casinotsu.com/slots/gates-of-olympus" },
  ],
  tableOfContents: [
    { label: "ゲーツ・オブ・オリンパスをプレイできるオンラインカジノ", href: "#" },
    { label: "ゲーツ・オブ・オリンパスのシンボル、ペイアウト", href: "#" },
    { label: "RTP（還元率）", href: "#" },
    { label: "ボラティリティ", href: "#" },
    { label: "最大可能配当倍率", href: "#" },
    { label: "ゲーツ・オブ・オリンパス｜サウンド＆グラフィック", href: "#" },
    { label: "ゲーツ・オブ・オリンパス｜ゲーム機能", href: "#" },
    { label: "ゲーツ・オブ・オリンパスをボーナスでお得にプレイ！", href: "#" },
  ],
  cta: {
    text: "今すぐプレイ！",
    href: "https://go.casinotsu.com/go/2up:2up?referrer_path=%2Fslots%2Fgates-of-olympus",
  },
};

export default function Page() {
  return <SlotTemplate data={data} canonicalPath="/slots/gates-of-olympus" />;
}
